utils/servicioSintys.ts
- servicioSintys paso url a traves del config private
=> agrego cositas de servicioSintys  al config private

config.ts, core/mpi/routes/paciente.ts
- Agrego lo return next error faltantes.
- Algunos linteos.
=> agrego return next error y linteo

core/log/routes/logPaciente.ts
Corrijo next error de log Paciente
=> Bug Fix log Paciente

modules/mobileApp/routes/vacunas.ts
Listado de vacunas ordenado por fecha en forma descendiente
=> Ordenamiento de listado de vacunas en por fecha descendente

modules/turnos/routes/agenda.ts
corrige error de la fecha de bloques y turnos
=> Fix Clonar 

modules/mobileApp/routes/vacunas.ts, modules/mobileApp/schemas/vacunas.ts
Agregar validación de vacunas por paciente que devuelvan un porcentaje de matching de 90% o más
Cambiar schema de vacunas y estandarizar con el mismo nombre y tipo de datos que los pacientes
=> Validacion vacunas paciente

modules/turnos/routes/agenda.ts
Saco código de moment del lado de la api pq pinchaba...lo resuelvo en la app
=> Correcion moment

fhir/patient/controller/parser.ts, fhir/patient/controller/validator.ts, fhir/patient/routes/patient.ts, modules/turnos/routes/espacioFisico.ts, modules/turnos/schemas/espacioFisico.ts
* agrega organizacion al espacio fisico (se habia quitado en versiones anteriores)
* lint de código de fhir
=> Agrega organizacion en espacio fisico

modules/turnos/controller/agenda.ts
me había faltado sumar a los restantes del tipo de turno correspondiente cuando quitaba el turno doble
=> corrijo quitar turno doble  para que sume a los restantes

auth/routes/routes.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.registro.ts
Agrego diagnostico principal al schema de registros y se modifico el patch para guardar el registro luego de actualizar en la validación.
=> Diagnostico principal

core/mpi/controller/paciente.ts, core/mpi/schemas/paciente.ts, modules/mobileApp/routes/paciente.ts
Agregado de campo fotoMobile al esquema.
Agregado método PATCH en la ruta de la API para appMobile.
=> Foto mobile

modules/mobileApp/routes/paciente.ts
Patch de dirección para cuando el usuario de la app mobile modifica los datos de donde vive y donde trabaja.
=> Patch de la direccion del usuario desde la app mobile

config.ts, modules/mobileApp/controller/AuthController.ts, modules/mobileApp/routes/turnos.ts, utils/scriptsMongo/correccionUsuariosApp.ts, utils/sendMail.ts
--Cambios en matcheo para vincular paciente con el usuario de la app mobile
--Configuración para envío de mails y sms
=> Control pacientes app

modules/turnos/routes/agenda.ts
- filtramos las agendas candidatas por organización
=> agregamos chequeo de organizacion para las agendas candidatas

core/term/controller/mapping.spec.ts, core/term/controller/mapping.ts, core/term/routes/snomed.ts, core/term/schemas/mapping.ts, package-lock.json, package.json
- Incorporamos función y método en la API para transformar un código SNOMED a CIE10.
- Repositorio para trasformar el mapeo a una colección de mongo: https://github.com/andes/snomed-cie10
- Agregamos algunos test  unitarios para probar: 
```
npm install --dev
npm test
```
=> Mapeo SNOMED to CIE10

auth/permisos.ts, modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts, modules/turnos/schemas/agenda.ts
- se agrega funcionalidad necesarias para cambiar estado de una agenda a "borrada"
- Se altera el esquema de agenda: Actualizamos el enumerado "estado" para incluir "borrada"
- Se agrega un nuevo permiso para borrar agenda
=> Feature Borrar agenda

modules/mobileApp/auth_routes/autenticacionApp.ts, modules/mobileApp/schemas/pacienteApp.ts, templates/emails/reset-password.html
- Incorporamos metodos en la API para recuperar contraseña.
- Eliminamos rutas de registros en desuso.
- Incorporamos templates de emails.
=> Mobile App: Reset Password

modules/turnos/controller/agenda.ts
- modificamos el job actualizarAgenda
=> modificaciones job actualizarAgenda

core/log/schemas/log.ts, modules/mobileApp/routes/turnos.ts, modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts, modules/turnos/routes/listaEspera.ts, modules/turnos/routes/turno.ts, utils/logService.ts
- Agregamos comentarios al log
- actualizamos los enumerados del log schema
- logueamos los cambios realizados por el job actualizarAgenda
=> Actualizar agenda

core/tm/routes/organizacionCache.ts, core/tm/schemas/organizacionCache.ts
- Aregamos el metodo GET de organizacionesCache y una projección para no envíar todos los datos a la app mobile.
=> Se agregan las consultas a los centros de salud desde Lanin

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts, utils/logService.ts
=> fix loggger

core/tm/routes/organizacionCache.ts
- Bug en el post de organizacionesCache que no estaba en uso
=> se comenta el post de orgnaizacionesCache que no se usaba y pinchaba

core/term/routes/snomed.ts, core/term/schemas/snomed.ts, modules/rup/schemas/snomed-concept.ts
Se agregó refsetId schemas snomed
=> evolución 

core/mpi/controller/mpiUpdater.ts, core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, package-lock.json, utils/elasticSync.ts
=> Fix varios

modules/usuarios/routes/usuario.ts
- mejora en get usuario por dni
=> fix Usuarios

core/mpi/controller/mpiController.ts
- Modificamos la condición para que sólo busque los denunciados con error.
=> modifico la condicion solo los reportados

modules/mobileApp/routes/vacunas.ts
Fix en el GET de vacunas en la app mobile
=> Vacunas fix in domuyo

modules/turnos/routes/agenda.ts
- Mejoramos condiciones de agendas candidatas
- luego de testear hay que mergear a domuyo
=> Fix reasignación

modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/turnoCacheController.ts
=> Integracion sips

modules/legacy/controller/operations.ts, modules/legacy/schemas/constantes.ts, modules/turnos/controller/agendasCacheController.ts, modules/turnos/routes/turno.ts
=> Linteo de codigo de integración

config.ts
- Quitamos el ruteo legacy en el archivo config.ts
=> quitamos ruteo de legacy

config.ts, core/term/controller/mapping.spec.ts, package-lock.json
- Quito middleware en la parte de ruteo de autentificación. Fue agregado erroneamente en este commit: 
https://github.com/andes/api/commit/a8578613752f493fd3c92582e2a0c8bb182eb854#diff-0bd249cf9ac7fc14e26c46da701972c3
- Agrego 'declare const before' para enmendar error de linteo.
=> MobileApp: auth middleware

fhir/patient/controller/parser.ts, fhir/patient/routes/patient.ts, package-lock.json
- Verificación de algunos campos.
- Agregamos permisos.
=> algunso fix de fhir

fhir/patient/controller/parser.ts, fhir/patient/controller/validator.ts, fhir/patient/routes/patient.ts
- Faltaba verificación de tag NAME.
- Verificación de tags mínimos.
=> some fixes

jobs/integracionSipsJob.ts
* agrega jobs para integración de agendas con sips
* agregar a la lista de jobs dentro del config.private
=> Jobs para integración  con sips

jobs/integracionSipsJob.ts, modules/legacy/schemas/constantes.ts, modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/turnoCacheController.ts
=> Integración con especialidades CIE10

core/tm/routes/organizacion.ts
- Se agrega la posibilidad de buscar por tipo de establecimiento.
=> se agrega la posibilidad de filtrar por tipo de organizacion

core/mpi/controller/paciente.ts, modules/turnos/controller/agenda.ts, modules/turnos/controller/turnosController.ts, modules/turnos/routes/turno.ts, modules/turnos/schemas/turno.ts
- Después de actualizar un paciente, buscamos si existen turnos futuros asignados al paciente y actualizamos los datos de cada turno.
- Modificamos el esquema embebido de paciente en turno, para incluir la fechaNacimiento.
=> Mejora paciente turno

core/mpi/controller/mpiUpdater.ts, core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, core/mpi/schemas/paciente.ts, mongoose/audit.ts
- Se modifica el audit de mongoose para asegurar que la información de actualización y creación se realice sólo por los usuarios y omitiendo lo que hace el scheduler.
- Se mejora la funcionalidad del updater.
- Se verifica que actualice la información correctamente
=> fix updater - CreatedAt - updatedAt and users

modules/rup/routes/prestacion.ts
=> Fix get estado

fhir/interfaces/IPacienteFHIR.ts, fhir/patient/controller/errorCodes.ts, fhir/patient/controller/parser.ts, fhir/patient/controller/validator.ts, fhir/patient/routes/patient.ts, utils/checkPatientExist.ts
- Verificación de la url: family e identifier.
- Creamos los codidos de error.
=> fix error codes

modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/operationsCacheController.ts, modules/turnos/controller/turnoCacheController.ts, modules/turnos/routes/agenda.ts
- Mejoras para la integración.
- Linteo.
=> Refactor integration

core/mpi/controller/mpiController.ts
- Fix repetía las entidades validadoras al momento de actualizar los datos en sisa.
=> fix control de entidades validadoras

modules/mobileApp/routes/accounts.ts
Fix de este error:
https://trello.com/c/yi10TUKp/2-c%C3%B3digo-de-activaci%C3%B3n-app-mobile
Hice el pull request a develop, pero debería ser a domuyo o domuyo2 así podemos publicarlo en la inmediates.  Cual sería la rama?
=> Regenerar código de verificación antes de reenviar

core/tm/schemas/barrio.ts, core/tm/schemas/direccion.ts, core/tm/schemas/localidad.ts, core/tm/schemas/organizacion.ts, core/tm/schemas/provincia.ts, core/tm/schemas/ubicacion.ts, modules/auditorias/schemas/auditoriaPrestacionPaciente.ts, modules/llaves/schemas/llaveTipoPrestacion.ts, modules/turnos/schemas/listaEspera.ts
Se realizan cambios en los esquemas por actualización de la versión de typescript
=> Cambios en los esquemas por actualización de versión de typescript

core/term/routes/snomed.ts
Pasar LowerCase los términos de búsqueda para filtros de snomed
=> Pasar LowerCase los terminos de busqueda para snomed

auth/permisos.ts
Se agregan permisos correspondientes a operaciones sobre turnos
=> Permisos turnos

modules/turnos/schemas/agenda.ts
- Modifico condicion en el virtual schema de agenda "turnosDisponibles" 
:tada:
=> Modifico condicion en el virtual 

core/mpi/controller/mpiUpdater.ts
- Se quita promesa sobrante en updatingMpi()
- modificaciones menores en el resto del código
=> modificaciones updater

core/log/schemas/log.ts, modules/mobileApp/controller/VacunasController.ts, modules/mobileApp/routes/vacunas.ts, modules/rup/routes/frecuentesProfesional.ts, modules/rup/routes/hudsExtras.ts
Agrego nuevas acciones en el logger para llevar cuenta de lo que ven los profesionales.
Refactor de vacunas y rutas para que los profesionales puedan ver las vacunas del paciente.
=> Rup: Logger y Vacunas

modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/operationsCacheController/operationsPaciente.ts, modules/turnos/controller/operationsCacheController/operationsTurno.ts
- Modificaciones en la transacción y uso del pool de conexión mssql.
=> Refactor integracion

modules/rup/controllers/rup.ts, modules/rup/routes/prestacion.ts
Nueva ruta para buscar en la HUDS de un paciente. 
Se agregó método recursivo que filtra los resultados en base a un conjunto de conceptId.
=> Buscar en huds

modules/rup/routes/elementosRUP.ts
Cambiar orden en rutas para elementosRUP
=> Cambiar orden en rutas para elementosRUP

modules/legacy/controller/operations.ts, modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/operationsCacheController/operationsPaciente.ts, modules/turnos/controller/operationsCacheController/operationsTurno.ts, package-lock.json, package.json
- La ejecución de todas las consultas del job se vuelve a realizar de forma secuencial para evitar fallos con la librería mssql actualizada.
=> Fixes integracion

modules/legacy/controller/operations.ts
=> fix verificacion paciente

core/term/routes/snomedv2.ts, core/term/schemas/snomed.ts
Ajusto los nombre de los campos que devuelve la api de expresiones de SNOMED.
=> SNOMED: Renombre de campos

core/tm/schemas/organizacion.ts
- Se agrega un array de servicios con conceptos snomed en el schema de organizaciones
=> se agrega servicios al schema de organizacion

fhir/patient/controller/parser.ts
se agrega un elemento mas al array de identificadores del paciente
=> agregar identificador en get de paciente fhir

jobs/integracionAndes.ts, modules/legacy/controller/operations.ts, modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/turnoCacheController.ts, modules/turnos/schemas/turno.ts
- Se separan los jobs de la integración con SIPS. **Es necesario agregar a la configuración el nuevo job**
=> Vuelta integracion

core/tm/routes/ocupacion.ts, core/tm/schemas/ocupacion.ts
- Se agrega el schema y la ruta para ocupaciones en tablas maestras.
- Para los que usan la base de datos local abajo dejo el insert.. 
db.getCollection('ocupaciones').insertMany([ { "nombre": "Desocupado" }, { "nombre": "Abad" }, { "nombre": "Abastecedor de entradas a cines y teatros" }, { "nombre": "Abastecedor de líneas de producción" }, { "nombre": "Abastecedor recolector/fichas/tel/públ." }, { "nombre": "Abastecedor recolector/tarj/agenc/juego" }, { "nombre": "Abogado" }, { "nombre": "Abogado defensor" }, { "nombre": "Abogado" }, { "nombre": "Abogado" }, { "nombre": "Abonador en explotación agrícola ganadera" }, { "nombre": "Acabador de muebles de madera" }, { "nombre": "Acomodador de cine" }, { "nombre": "Acomodador de teatro" }, { "nombre": "Acompañante terapéutico" }, { "nombre": …
=> se agrega el schema de ocupacion y el get para las ocupaciones

config.ts, core/tm/models/camaEstado.ts, core/tm/routes/camaEstado.ts, core/tm/routes/organizacion.ts, core/tm/schemas/camaEstado.ts, core/tm/schemas/camas.ts, core/tm/schemas/organizacion.ts
- Se agrega el audit en camas, organización, estados y se guardan los estados en otra colección
- Se agrega models con el modelo para cama estado
=> Camas en organizacion

fhir/patient/controller/parser.ts
Permite buscar tanto pacientes temporales como validados
=> Modificar get de paciente Fhir 

modules/fuentesAutenticas/routes/sisa.ts
- Se agrega request al WS de SISA que brinda información de PUCO a partir de un DNI.
- Queda pendiente integrar la consulta a la BD en MONGO cuando esté lista.
=> Arancelamiento

utils/roboSender/sendEmail.ts
Agrego promise en función de enviar email. El try catch no estaba capturando la excepción.
=> Handler error email

modules/turnos/routes/turno.ts
- agrego la nota al dataset del patch
=> Cambio turnos

config.private.ts.example, core/log/schemas/log.ts, jobs/cdaSipsJob.ts, modules/cda/controller/CDAPatient.ts, modules/cda/controller/import-labs.ts, modules/cda/routes/cda.ts, modules/cda/routes/cdaLaboratory.ts, modules/legacy/controller/operations.ts, modules/mobileApp/auth_routes/autenticacionApp.ts, modules/mobileApp/routes/paciente.ts
- Importación de laboratorios de SIPS de pacientes Validados mediante un Jobs.
- Ruta de consulta de laboratorios mobile paginada y cofidencialidad.
- Nuevo valores en el Log.
=> Importación de laboratorios desde SIPS

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
- fix bug cuando suspendemos sobreturno
=> suspender sobreturno

modules/rup/controllers/frecuentesProfesional.ts, modules/rup/routes/prestacion.ts
Agregamos la carga y actualización de conceptos frecuentes del profesional en el patch de prestaciones, para cuando se valida la prestación.
=> Actulizar los conceptos frecuentes en el patch de prestaciones

modules/turnos/controller/operationsCacheController/operationsAgenda.ts
- Fix markAgendaAsProcessed: Intentaba procesar una agenda undefined.
=> fix de exec de undefined

modules/turnos/controller/operationsCacheController/operationsAgenda.ts
- Fix integración Sips. markAgendaAsProcessed solved
=> Fix integracion sips

core/tm/routes/cama.ts
- Nueva ruta para cambiar los estados y las validaciones
=> agrego nueva ruta para cambiar el estado con sus validaciones

modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/operationsCacheController/operationsPaciente.ts
=> fix codigo repetido

modules/turnos/schemas/turno.ts
- Modificamos schema turno para agregar alias en el paciente embebido
=> alias de paciente

config.private.ts.example, modules/legacy/controller/operations.ts, modules/legacy/schemas/constantes.ts, modules/turnos/controller/operationsCacheHPNController.ts
* Agrega nuevas constantes para las prestaciones y organizaciones que se integran a otros sistemas
* Modifica las operaciones para utilizarla
=> Modifica las condiciones de integración

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
- Patch de paciente Andes para actualizar a demanda.
=> Cuil patch

auth/routes/routes.ts, core/term/routes/snomedv2.ts, jobs/farmaciasJob.ts, modules/legacy/controller/operations.ts, modules/mobileApp/auth_routes/autenticacionApp.ts, modules/mobileApp/controller/AuthController.ts, modules/mobileApp/controller/FarmaciasTurnosDownloader.ts, modules/mobileApp/routes/accounts.ts, modules/mobileApp/schemas/farmacias.ts, modules/mobileApp/schemas/pacienteApp.ts, templates/emails/active-app-code.html
Si envía un email con una contraseña temporal. Desde la app mobile, se activa la cuenta desde  el login directamente.
=> Mobile: Simplificación del registro de la app mobile

core/mpi/routes/paciente.ts
- Add patch method Mpi, only for cuilification
=> patch mpi para cuil

modules/turnos/controller/agenda.ts
Al publicar la agenda, se agrega chequeo equivalente al del job de tipos de turnos
=> Se modifica Publicar Agenda

config.ts, core/tm/routes/cama.ts, package-lock.json, package.json
Saco el middleware en tm y lo agrego directamente en camas ya uqe hay modulos que necesitan estar desprotegidos.
=> Saco Middleware en tm.

core/term/routes/cie10.ts
Mejora búsqueda cie10:
- Búsqueda case insensitive
- Búsqueda por código, sinónimo, nombre y por array de words
=> mejora busqueda cie10

fhir/patient/controller/parser.ts, fhir/patient/routes/patient.ts
- Se estaba accediendo a un objeto que no tenía la información del paciente.
=> fix fhir parser

modules/mobileApp/auth_routes/farmacias.ts
Seteo el filtro de localidad como opcional para poder listar todas las farmacias de un día y mostrarlas en el mapa.
=> Mobile Farmacias

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
- Los diagnósticos hechos desde rup para sobreturnos se mapean a cie10 y se almacenan en turno correctamente
=> fix Mapeo Snomed CIE-10 / Sobreturnos

modules/turnos/controller/agenda.ts
**mejora en el job de actualizar tipos de turno**
- Detecta sábados y feriados
=> Jobs actualizarTiposDeTurno

Dockerfile, config.private.ts.example, modules/cda/controller/import-labs.ts, package-lock.json, package.json
Elimino las dependencias globales de npm para compilar la api.
=> Dockerfile Modificaciones

auth/permisos.ts
Agregamos permisos para punto de inicio
=> permisos pto inicio

modules/legacy/controller/operations.ts, modules/legacy/schemas/agendasCache.ts, modules/prestamosCarpetas/controller/prestamosController.ts, modules/turnos/controller/operationsCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/operationsCacheController/operationsTurno.ts, modules/turnos/controller/turnoCacheController.ts
* Pasa los sobreturnos de ordontología en la integración con Sips
* Fix varios para la codificación de los turnos y sobreturnos
=> Fix de codificación de sobretrunos

modules/prestamosCarpetas/controller/prestamosController.ts, modules/prestamosCarpetas/routes/prestamos.ts, package-lock.json
se guardan masivamente el prestamo de carpetas solicitadas
=> se agrega funcionalidad para prestamosCarpetas masivamente

fhir/patient/controller/parser.ts, fhir/patient/routes/patient.ts, jobs/farmaciasJob.ts, modules/cda/routes/cda.ts, modules/legacy/controller/operations.ts, modules/legacy/schemas/agendasCache.ts, modules/mobileApp/auth_routes/farmacias.ts, modules/mobileApp/routes/paciente.ts, modules/prestamosCarpetas/controller/prestamosController.ts, modules/prestamosCarpetas/routes/prestamos.ts, modules/prestamosCarpetas/schemas/prestamo.ts, modules/sugerencias/routes/sugerencias.ts, modules/turnos/controller/operationsCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/operationsCacheController/operationsTurno.ts, modules/turnos/controller/turnoCacheController.ts, package-lock.json, package.json
Actualización con el rama release 2.6.0
=> Update release 2.6.0

modules/turnos/controller/operationsCacheController/operationsAgenda.ts
* Modifica las codificaciones de odontología al nuevo esquema de turnos
=> fix codificacion de sobreturnos

modules/turnos/controller/operationsCacheController/operationsAgenda.ts
Agrega cambios en la codificación de los sobreturno para adaptarlo al esquema de turno
(Cambio ingresado a v2.6.0-release)
=> agrega cambios en codificación de sobreturnos

core/tm/controller/formularioTerapeutico.ts, core/tm/routes/especialidadesFT.ts, core/tm/routes/formularioTerapeutico.ts, core/tm/schemas/especialidadesFT.ts, core/tm/schemas/formularioTerapeutico.ts
Extraje los cambios del PR #249  y los movemos al release V2.6.2
=> Formulario Terapeutico

modules/turnos/controller/turnosController.ts, package-lock.json, package.json
Modificamos aggregate en controller de turno (getTurno)
=> Hot fix get turno

modules/turnos/controller/operationsCacheController/operationsAgenda.ts
fix condición repetidos para diagnósticos odonto
=> Fix integración job

modules/turnos/controller/operationsCacheController/operationsAgenda.ts
fix chequeo de repetidos en odonto.
=> Fix integracion job

modules/turnos/schemas/agenda.ts
- fix error $pushall schema agenda mongoose
**Falta testear sobre versión de mongoose 5.***, tal vez no sea necesario para esa versión
=> WORK IN PROGRESS: hotfix schema agenda mongoose 

core/term/routes/cie10.ts, package-lock.json
Se corrige bug en buscador de cie10
=> Fix revision

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
=> Consultas estadisticas agendas

utils/loggerPaciente.ts
fix error log paciente suspender turno sin paciente
=> bugfix logger paciente

core/log/schemas/log.ts, modules/turnos/routes/listaEspera.ts
agrego operacion lista espera al enumerado
=> agrego operacion lista espera al enumerado

auth/permisos.ts, modules/prestamosCarpetas/controller/prestamosController.ts, modules/prestamosCarpetas/routes/prestamos.ts, modules/prestamosCarpetas/schemas/constantes.ts, modules/prestamosCarpetas/schemas/prestamo.ts, modules/prestamosCarpetas/schemas/solicitudCarpetaManual.ts
* Modificaciones para habilitar la posibilidad de registrar los préstamos de las carpetas de los pacientes que son solicitadas en el archivo y no tienen una solicitud automática generada
=> Prestamos manuales

Dockerfile, core/mpi/controller/paciente.ts, core/tm/routes/cama.ts, modules/obraSocial/routes/obraSocial.ts, modules/rup/controllers/cama.ts, modules/rup/controllers/censo.ts, modules/rup/routes/internacion.ts, modules/turnos/controller/estadisticas.ts, modules/turnos/routes/agenda.ts, modules/turnos/routes/carpetaPaciente.ts, modules/turnos/schemas/turno.ts, package-lock.json, package.json, utils/loggerPaciente.ts
- Agregar el filtro por efector a las consultas por censo diario y mensual. [Task](https://openproject.hospitalneuquen.org.ar/projects/rup/work_packages/102/activity?query_id=14)
=> agregar filtro por organizacion para el censo diario y mensual

modules/legacy/schemas/constantes.ts, modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/operationsCacheController/operationsPaciente.ts, modules/turnos/controller/operationsCacheController/operationsTurno.ts, package-lock.json, package.json
- Permitimos el envío a sips de pacientes sin DNI.
- Permitimos la modificación del profesional en la agenda (Si no tenía o para actualización)
- Fixes varios
- Agregamos conexion de agendas como variable local
- Asistencia de sobreturnos
Obs: Aún queda mucho por hacer y mejorar....
=> Fix integracion

core/tm/routes/cama.ts, core/tm/schemas/camaEstado.ts, modules/rup/routes/prestacion.ts
Van los cambios de la api que me quedaron sin subir! :dancer:
=> se agrega es sugerido a

modules/turnos/controller/diagnosticosC2Controller.ts
Se modifica consulta de diagnosticos C2 para que se adapten a nuevos rangos etarios
=> Rangos etarios C2

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
** Agradecimientos @silviroa, sin ella esto no hubiera sido posible.  **
- fix codificacion turno.
=> Revision hotfix

modules/turnos/controller/operationsCacheController/operationsAgenda.ts, package-lock.json, package.json
- Fix que soluciona el update de agenda profesional, cuando cambian el profesional desde CITAS.
=> fixito AgendaProfesional

modules/rup/routes/internacion.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/elementoRUP.ts
Se agrega filtro por organización cuando trae las prestaciones que están en lista de espera de Internación
=> filtro por organizacion en la lista de espera

modules/prestamosCarpetas/controller/prestamosController.ts, modules/turnos/controller/turnosController.ts
* Se realiza control para los préstamos de carpetas automáticos
* Agregamos los distintos estados de la agenda para poder visualizar el historial de turnos del paciente
=> Fix prestamos automaticos

core/tm/routes/cama.ts, modules/rup/routes/prestacion.ts
[OP#88](https://openproject.hospitalneuquen.org.ar/projects/rup/work_packages/88/activity)
=> se agrega filtro a las camas por sector y se filtra la prestación sin cama

core/tm/routes/cama.ts, modules/rup/controllers/cama.ts
Se agrega consulta a la BD para traer las camas con su ultimo estado según fecha y hora.  [OP#118](https://openproject.hospitalneuquen.org.ar/projects/rup/work_packages/118/activity)
=> Internación: Ver el estado del mapa de cama en una fecha determinada.

core/mpi/controller/mpiCorrector.ts, core/mpi/controller/mpiUpdater.ts, jobs/actualizarAgendasJob.ts, jobs/actualizarTurnosDelDiaJob.ts, jobs/cdaSipsJob.ts, jobs/farmaciasJob.ts, jobs/integracionAndes.ts, jobs/integracionHPNJob.ts, jobs/integracionSipsJob.ts, jobs/manual.ts, jobs/mpiCorrectorJob.ts, jobs/mpiUpdaterJob.ts, jobs/roboSenderJob.ts, jobs/scheduler.ts, modules/mobileApp/controller/FarmaciasTurnosDownloader.ts, modules/turnos/controller/agenda.ts, modules/turnos/controller/agendasCacheController.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts, modules/turnos/controller/turnosController.ts, package-lock.json, package.json, utils/roboSender/roboSender.ts
Mejoras introducidas al scheduler:
- Cada ejecución se realiza en un proceso aparte.
- Se corrigen los Jobs que notifiquen cuando termina sus proceso.
- Control de los procesos hijos que se están corriendo.
- Prevención de solapamientos de jobs.
=> V3.2.0 Release 3.2.0 Scheduler 

modules/turnos/controller/diagnosticosC2Controller.ts
- Se mueven los controles únicamente al diagnostico principal marcado como primeraVez.
- Se corrigen bugs en bronquiolitis, poliomielitis y botulismo
=> Modificaciones en reporte C2

core/term/schemas/configuracionPrestacion.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts
* cambia esquema de configuración prestación
* modifican rutas de la integración de sips
=> Modifica esquema de configuración prestación

CHANGELOG.md, package-lock.json, package.json, utils/roboSender/sendSms.ts, utils/utils.ts
- aplicamos función removediacritics en send sms
=> fix acentos SMS

modules/prestamosCarpetas/controller/prestamosController.ts
se cambia el sort date para mostrar los prestamos recientes en el historial de carpeta
=> Prestamos carpetas v330

Dockerfile, modules/rup/controllers/estadisticas.ts, modules/rup/routes/estadisticas.ts, modules/rup/routes/frecuentesProfesional.ts, modules/rup/routes/hudsExtras.ts, package-lock.json, package.json
Se agregan queries para crear estadisticas para rup.
=> estadisticas: queries para rup

modules/cda/controller/builder/BaseBuilder.ts, swagger/swagger.class.ts
- Se corrige error al generar CDA, aparecian campos privados de mongoose.
- Se corrige la ruta de Swagger para que sea accesible con la Vapp.
=> cda: fix propiedades de mongoose

modules/cda/controller/CDAPatient.ts, package-lock.json, package.json
- Se corrige un bug en la ruta de acceso a los adjuntos del cda.
=> cda: cambio en path de archivos adjuntos para app mobile

core/mpi/controller/paciente.ts, modules/carpetas/routes/ultimaCarpeta.ts, modules/turnos/controller/agenda.ts
* mejoras en el update turnos paciente para incluir la actualización de los sobreturnos
=> fix cambio carpeta sobreturnos

modules/turnos/controller/pacienteHPNController.ts, modules/turnos/controller/turnoHPNCacheController.ts
- Seteamos el idHistoria clínica (ya que estabamos guardando el idPaciente en ese lugar).
- Faltaba controlar si el turno tiene estado disponible y existe en HPN para poder hacer el update, sino debe continuar buscando turnos.
PD: Mañana probar la integración sobre esta rama, si funciona todo hacemos el merge a master y lo dejamos corriendo en master.
=> fixeamos la historia clinica y el turno cuando existe

.github/pull_request_template.md
Agregamos template para los nuevos pull request, con una guía para el titulo y la descripción de los mismos.
=> Agregamos template para los pull request

auth/permisos.ts, modules/turnos/controller/carpetasController/carpetasController.ts
* Link a la user storie de open project, referencia al issue (#1111) o breve descripcion del requerimiento
* **https://github.com/andes/app/issues/663**
1. Nueva regla para editar carpeta desde punto inicio
2. Fix ruta schema carpetaPaciente
3.
=> CITAS - Punto de Inicio - Editar número de carpeta

modules/turnos/controller/carpetasController/carpetasController.ts, modules/turnos/controller/turnosController.ts, modules/turnos/routes/turno.ts
1. Fix ruta import carpetaPaciente
2. mejora aggregate getHistorial paciente
3. mejora patch avisosuspension/motivoconsulta
=> Get historial paciente - mejora

core/tm/routes/profesional.ts
* agregamos el skip and limit que faltaba en la query de profesionales
=> Request profesionales

core/tm/routes/profesional.ts, utils/utils.ts
* Optimizar la búsqueda de profesionales. Se corrige el issue https://github.com/andes/app/issues/695.
1. Busqueda de profesional por nombre y apellido. 
2. Se evita buscar subpalabras, solo el comienzo del nombre o apellido.
3. Se corrige un error en la función makePattern que consideraba a un espacio en blanco como una palabra.
=> Tabla maestras - optimizacion de busqueda de profesionales

modules/rup/controllers/prestacion.ts, modules/turnos/routes/agenda.ts
Se agrega método que limpia la referencia del turno en la solicitud al liberarlo. Issue #596
=> Referencia solicitud

modules/obraSocial/routes/obraSocial.ts
* Cuando el paciente no tiene obra social se cae la API, y cuando no tiene DNI devuelve un status 400 que muestra un error en pantalla. :fire: :fire: :fire: :fire: :fire: 
1. Agregamos chequeo de nulidad para pacientes que no figuran en el padron 
2. Para el request sin DNI, quitamos el status 400 del response para evitar el alerta. Se devuelve directamente un JSON que reza "Parámetros incorrectos"
=> Query obra social > Agregamos chequeo de nulidad 

modules/descargas/controller/descargas.ts, templates/rup/informes/html/informe.html
Se resuelven los issues #768 y #769 (en el proyecto app)
1. Cambiamos el cálculo de edad con moment
2. Controlamos los casos en que el paciente no tenga registrada la fecha de nacimiento
3. Cambiamos el texto en el footer del informe para que haga referencia al ministerio de salud.
=> Corregimos calculo de edad y agregamos al ministerio de salud en el footer de los informes

CHANGELOG.md
* Actualización de changelog v3.7.2
- [] Si
=> update changelog v3.7.2

modules/prestamosCarpetas/controller/prestamosController.ts, package-lock.json
* Ver listado de carpetas prestadas  https://github.com/andes/app/issues/815
1. Se agrego un cast a ObjectId faltante.
=> prestamos de carpeta: agrega cast a ObjectId

modules/turnos/controller/pacienteHPNController.ts, package-lock.json
* Error en la integración con HPN con documentos de pacientes validados de la forma 0456987, donde 0 es el primer caracter del documento.
Se creo una regex al momento de buscar al paciente para evitar que busque con ese número incorrecto.
```
paciente.documento.replace(/^0+/, '');
```
=> solucionamos el error del prefijo cero en los documentos de LC

core/tm/routes/cama.ts, core/tm/schemas/camaEstado.ts, modules/rup/controllers/internacion.ts, modules/rup/routes/internacion.ts
* Simplificar el workflow de internación
1. Permitir cambio de estado de camas de ocupada a disponible
2. Agregar campo al estado de la cama para identificar movimientos de cama
3.
=> Cambio workflow

modules/cda/routes/cda.ts
1.  Se agrega parámetro en la creación de CDA para setear la confidencialidad de la api.
=> cda: opcion de confidencialidad

core/tm/routes/cama.ts, modules/rup/controllers/cama.ts
*https://pm.andes.gob.ar/work_packages/530
Una tabla con todo lo que paso en una determinada cama con un filtro de fechas desde/hasta.  Con un limite de hasta 30 registros.
=> RUP - internación. - Historial de cama

modules/rup/controllers/cama.ts, modules/rup/controllers/censo.ts
* Filtrar para el censo diario los movimientos de cama dentro de una misma unidad organizativa
1. Se filtran del listado de camas ocupadas en una fecha los movimientos que son dentro de la misma unidad organizativa
=> RUP - Filtrar Movimientos intra unidad organizativa

core/tm/schemas/organizacion.ts, modules/mobileApp/routes/agendas.ts
CITAS: Filtramos los turnos por organización
* Se filtran las organizaciones que ofrecerán turnos para la app mobile
=> Agrega filtro de organizacion para los turnos de la app mobile

auth/permisos.ts
* Agregar un nuevo permiso para visualización de la HUDS (para no-profesionales)
1. Agregar un nuevo permiso al array de permisos
2. 
3.
=> RUP - Agregar un nuevo permiso para visualizacion de la HUDS

core/tm/controller/campaniasSalud.ts, core/tm/routes/campaniasSalud.ts, core/tm/schemas/campaniasSalud.ts, jobs/campaniasSaludJob.ts, modules/mobileApp/controller/AuthController.ts, modules/mobileApp/controller/NotificationService.ts, modules/version/routes/routes.ts, package-lock.json
MobileAPP: Notificaciones push masivas de campañas de Salud.
User Story:
https://pm.andes.gob.ar/projects/mobile-app/work_packages/509/activity
Obs: Se tuvieron que tener en cuenta otros factores para poder realizar esta US. Ver a continuación la funcionalidad desarrollada.
1. Se crea un JOB que recorre todas las campañas vigentes y por cada una envía una notificación PUSH a cada paciente que tenga su cuenta activada. A modo de prueba, el job es ejecutable de forma manual, esto es: node jobs/manual.js jobs/campaniasSaludJob
2. La campaña es visible desde el HOME de la aplicación, debido a que no necesariamente el usuario la aplicación corriendo en background. Permitiendole acceder a la información.
3. La campaña es full customizable cargando TODOS los fields de la colección.
Debe crearse …
=> Campanias mobile

core/tm/controller/campaniasSalud.ts
=> Se resuelve el bug del return

modules/matriculaciones/routes/turnoSolicitado.ts
1. tipo de turno en el pdf
2. generar sobreturno cuando llega un profesional nuevo desde el sistema
3. error de login
- [x ] No
=> Matriculaciones - issues app(pdf de turno,  sobreturno matricula nueva, login,..)

modules/prestamosCarpetas/controller/prestamosController.ts
Bugs y sugerencias en Prestamos de Carpetas
1. Actualizar listados de Solicitudes y Prestamos de carpeta cuando se prestan o devuelven.
2. Se visualizan datos del paciente en el historial de carpeta.
3. Se fixean los filtros de busqueda en Solicitud y Prestamos.
4. Se reacomodan las fechas en los filtros de busqueda.
=> Cambios prestamo carpeta

auth/permisos.ts
Sin User Story. Se requiere agregar una key en permisos > fuentes autenticas para controlar el uso del ws de ReNaPer en la validación de pacientes.
1. Se agrega la key 'renaper' en permisos.ts > fuentes autenticas.
=> MPI -> Se agrega key para ws renaper

core/tm/controller/campaniasSalud.ts, core/tm/routes/campaniasSalud.ts, core/tm/schemas/campaniasSalud.ts, jobs/campaniasSaludJob.ts, modules/matriculaciones/routes/turnoSolicitado.ts, modules/mobileApp/controller/AuthController.ts, modules/mobileApp/controller/NotificationService.ts, modules/turnos/controller/turnosController.ts, modules/version/routes/routes.ts, package-lock.json
=> TOP - fix #886

modules/turnos/controller/operationsCacheController/operationsAgenda.ts, package-lock.json, package.json
1. Se quita el cambio de estado en agendas integradas
2. Se agrega tag
=> Cambios en estados de agendas integradas

utils/servicioRenaper.ts
* Respuesta de renaper sin validar genera errores
1. Se agrega la verificación de la respuesta
=> verifica respuesta renaper

modules/fuentesAutenticas/routes/sisa.ts, utils/servicioSisa.ts
Se requiere nueva ruta que no precise matching con pacientes para validar mediante WS SISA, de manera que puedan registrarse nuevos pacientes.
1. Se crea nueva ruta en la cual mediante dni y sexo de un paciente, se obtienen sus datos mediante WS SISA.
- [] Si
=> MPI - Se implementa nueva ruta para servicio de SISA

modules/turnos/controller/agenda.ts
* fix #923 (app) 
1. Se modificó método codificarTurno para que agregue campos que faltaban
- [] Si
- [] No
- [] Si
=> se agregan campos de ficha y reporte en codificarTurno

modules/fuentesAutenticas/routes/sisa.ts, utils/servicioSisa.ts
1.  Cambia los request HTTP al paquete `request` para manejar el uso del proxy.
=> Actualiza los HTTP Request al paquete 'request'

package-lock.json, package.json, utils/servicioSisa.ts
* Debugging en servicio sisa para validación de pacientes.
1. Corrección.
- [] Si
=> MPI - Correccion función en servicioSisa

modules/turnos/controller/agenda.ts
1. Aumenta contador en condición while. Nunca terminaba y disparaba el procesador al máximo.
=> Agenda: corrige while never ending

core/tm/routes/profesional.ts
1.  solucionado el problema de timeout en guía de profesional
=> Guia profesional

auth/permisos.ts, modules/rup/routes/prestacion.ts
* https://pm.andes.gob.ar/projects/top/work_packages/582/activity
1. Se agregaron permisos en módulo TOP (solicitudes)
=> Filtros por permisos TOP

core/term/controller/grammar/parser.ts, core/term/routes/snomedv2.ts
1. Cambia el tipo de busqueda de relaciones en snomed. 
Nota: Es un para el modulo de estadísticas.
=> Snomed: Cambia el tipo de relaciones usadas por defualt.

modules/prestamosCarpetas/controller/prestamosController.ts
1. Controla si existe número de carpeta
=> controla si existe numero de carpeta

modules/fuentesAutenticas/routes/renaper.ts, utils/servicioRenaper.ts
* Renaper requiere identificar al operador que realiza la consulta, siempre que esté disponible la información.
1. Identificamos al usuario que realiza la consulta en la llamada al servicio de renaper
=> Agregamos operador a la llamada del WS Renaper

modules/descargas/controller/descargas.ts
resuelvo issue #969
se agrega una opción para que busque si en valor tenemos un concepto e imprima el term
=> RUP-issue 969 Impresión de Informe - Screening

config.ts, core/mpi/routes/paciente.ts, modules/mobileApp/controller/VacunasController.ts, modules/mobileApp/routes/vacunas.ts, modules/mobileApp/schemas/vacunas.ts, package-lock.json
NOMIVAC: 
- Refactor de pesos y codigos de error en el archivo de configuración.
- Se crean  2 métodos getVacuna y createVacuna para mantener (por un tiempo) la colección NOMIVAC que actualmente es utilizada para la app mobile.
- Se agrega idvacuna ya que NO estaba en el schema y en los datos de la base de datos sí!.
=> Se agrega funcionalidad a la api de nomivac

modules/prestamosCarpetas/controller/prestamosController.ts
1. en la funcion getRegistrosSolicitudCarpetas no estaba recibiendo la variable mostrarPrestamos
=> PRESTAMOS HC - Se actualiza la funcion getRegistrosSolicitudCarpetas

modules/cda/routes/cda.ts
* Se agregan controles en la asignación de la evolución en el cda.
=> CDA: cambios en evolución

modules/rup/schemas/elementoRUP.ts
Se modifica el Schema de elementoRUP.
Se agrega lo siguiente:
formulaImplementation: {
type: String,
required: false
}
=> RUP - formula base

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, modules/webhook/routes/webhook.ts
MPI - Se agregan los eventos para integración de pacientes FHIR con aplicaciones externas e internas.
Se debe agragar a la colección webhook lo siguiente:
{
"event" : "mpi:paciente:create",
"url" : "http://172.16.1.115/flebes/andesapi.php/Patient",
"method" : "POST"
}
{
"event" : "mpi:paciente:update",
"url" : "http://172.16.1.115/flebes/andesapi.php/Patient",
"method" : "POST"
}
=> Se agregan los eventos para integración de pacientes

modules/descargas/controller/descargas.ts, templates/puco/constancia.html, templates/puco/constancia.scss
* Que figure en el comprobante la fecha de impresión y validez del mismo.
=> PUCO - Se agrega leyenda y fecha de impresión

core/mpi/controller/paciente.ts
* Error al escanear DNI de paciente :fire: 
1. Se quita el filtro que genera problemas en el case simplequery
=> Búsqueda elastic simplequery

core/tm/routes/barrio.ts
* PR app: https://github.com/andes/app/pull/1018
1. Se ordena la colección obtenida antes de devolverla.
=> MPI - Barrio

core/tm/controller/profesional.ts
* Cambios requeridos en el proceso que realiza la verificación de vencimientos de posgrados
1. Se cambia la función de vencimiento de posgrado.
=> Vencimiento de matrículas de posgrado

modules/rup/routes/prestacion.ts
* Agregar filtro por tipo de prestación en el get de prestaciones
1. Agrega filtro por tipo de prestación (en la solicitud) en el get de prestaciones
2. Cambia el tipo de dato del filtro tieneTurno de string a boolean
=> RUP - Agrega filtros por tipo de prestación

modules/rup/routes/codificacion.ts
* HOTFIX: Se corrige Bug que ocurría en la revisión de prestaciones fuera de agenda
=> CITAS: Corrección en la revisión de prestaciones fuera de agenda

modules/turnos/routes/turno.ts
* Corregir bug para dar turnos por la app-mobile
1. Agrega un control al dar un turno por si el usuario logueado no tiene organización (para app mobile), para que no intente buscar y/o actualizar nro de carpeta.
2. 
3.
=> CITAS: Control de organización en dar el turno

core/term/controller/mapping.ts, modules/turnos/controller/agenda.ts
No aplica
1. Al método que devuelve el código CIE10 se le agregó que busque en la colección CIE10 si existe el término. Así se evitan muchos "Mapeos no disponibles" por devolver otro CIE10 del mismo término Snomed
- [x ] No
=> RUP - Mapeo Snomed - CIE10

config.private.ts.example, modules/estadistica/pecas/controller/agenda.ts
* Se corrige INSERT para que castee caracteres extraños
=> BI - Fix caracteres en insert

modules/rup/routes/codificacion.ts, package-lock.json
Mejorar filtros y performance de get de codificaciones fuera de agenda.
1. Agrega una query con lookup para el get de codificaciones de prestaciones fuera de agenda
2. 
3.
=> CITAS: lookup para el get de codificaciones de prestaciones fuera de agenda

modules/rup/controllers/frecuentesProfesional.ts, modules/rup/routes/frecuentesProfesional.ts, modules/rup/schemas/profesionalMeta.ts
https://pm.andes.gob.ar/projects/rup/work_packages/528/activity
Va junto con el pull request de la app: 
https://github.com/andes/app/pull/864
1. Registrar los conceptos de la prestación como frecuentes, agregando el campo esSolicitud.
=> RUP-Mejoras en conceptos frecuentes

modules/estadistica/pecas/controller/agenda.ts
* Se optimizan la cantidad de consultas realizadas previa a la exportación de datos: se agregan las agendas en todos los estados.
1. Se agregan agendas dinámicas sin pacientes
2. Se exportan agendas no nominalizadas
3. Se eliminan las agendas completas y se vuelven a insertar
=> BI:  agrega agendas no nominalizadas

modules/turnos/routes/agenda.ts
* Corrige error que ocurría al actualizar una agenda "Can't save() the same doc multiple times in parallel"
=> Save mulltiple

config.private.ts.example, config.ts, connections.ts, core/mpi/controller/mpiUpdater.ts, package-lock.json, package.json
* Reemplazar el Logger usado hasta ahora por libreria log de npm
1. Se reemplazó el logger actual sólo en mpiUpdater
- [] Si
=> MPI - Se implementa nuevo log en mpiUpdater

modules/turnos/controller/turnosController.ts
* Se agrega información de espacio físico en el punto de inicio de CITAS y en la confirmación del turno
=> CITAS - mostrar información de espacio fisico

modules/rup/routes/codificacion.ts, modules/rup/schemas/codificacion.ts, modules/turnos/controller/diagnosticosC2Controller.ts
* 
1. Se agregaron las prestaciones fuera de agenda al reporte C2.
2. 
3.
=> CITAS - Reporte C2

modules/turnos/controller/diagnosticosC2Controller.ts
* Se corrige aggregate para que se puedan visualizar sólo los diagnósticos C2 en el listado de los Reportes C2.
=> Reporte C2 - Correcciones 

modules/cda/routes/cda.ts
* Mejora en una condición de búsqueda del cie10 para crear un cda
=> Integración- Mejoras del cie10 para createCDA

templates/rup/informes/sass/main.scss
https://pm.andes.gob.ar/projects/rup/work_packages/639/activity
1. Modifico en scss el tamaño de las fotos a imprimir en los informes
=> RUP- Colonoscopia: Mejoras de estilos

modules/rup/controllers/frecuentesProfesional.ts, modules/rup/routes/frecuentesProfesional.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/profesionalMeta.ts
* Corrige bugs en conceptos frecuentes. No se estaba devolviendo el campo `refsetIds`.
1. Devuelve `refsetIds` en el get.
2. Actualiza el código al estilo async/await.
3. Implementa la interfaz para ProfesionalMeta. 
Nota: Deberíamos actualizar las prestaciones viejas que tienen cierto error en los datos.
=> Rup: Corrige error en frecuentes

core/log/schemas/logPaciente.ts, core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, core/tm/schemas/nombreApellido.ts, modules/prestamosCarpetas/schemas/prestamo.ts, modules/prestamosCarpetas/schemas/solicitudCarpetaManual.ts, modules/turnos/schemas/agenda.ts, utils/requestHandler.ts, utils/servicioGeonode.ts
Se corrigen distitntos errores detectados:
```
(node:10775) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
```
Cannot read property '0' of undefined
core/mpi/controller/paciente.ts in Object.<anonymous> at line 877
```
```
Error: AUDIT PLUGIN ERROR: Inicialice el plugin utilizando el método audit(). Ejemplo: myModel.audit(req.user)
at EmbeddedDocument.<anonymous> (/var/www/andes/api/packages/mongoose-plugin-audit/index.ts:26:25)
at callMiddlewareFunction (/var/www/andes/api/node_modules/kareem/index.js:427:23)
at EmbeddedDocument.next (/var/www/andes/api/node_modules/kareem/index.js:58:7)
at _next (/var/www/andes/api/node_modules/kareem/index.js:106:10)
at …
```
=> Correcciones de varios errores.

config.private.ts.example, jobs/fueraDeAgendaJob.ts, modules/estadistica/pecas/controller/agenda.ts, modules/estadistica/pecas/controller/fueraDeAgenda.ts
* Implementar Job para agregar al tablero de PECAS las prestaciones fuera de agenda.
Hay que modificar en el config.private el objeto **conSqlPecas** para configuración de la nueva tabla SQL **fuera_de_agenda**
=> BI - Agrega job para insertar en BI las prestaciones fuera de agenda

auth/routes/routes.ts, connect/fhir/routes/organization.ts, core/tm/routes/organizacion.ts, core/tm/schemas/contacto.ts, core/tm/schemas/organizacion.ts, modules/cda/routes/cda.ts, modules/descargas/controller/descargas.ts, modules/estadistica/pecas/controller/agenda.ts, modules/legacy/controller/operations.ts, modules/mobileApp/routes/agendas.ts, modules/mobileApp/routes/turnos.ts, modules/turnos/controller/carpetasController/carpetasController.ts
* Listado de configuraciones por cada efector. 
1. Se agrega un campo al schema de organizaciones.
=> organizacion: Opciones configurables por cada efector.

core/mpi/controller/mpiUpdater.ts
* Mpi Updater fallaba en algunos casos y eliminaba cambios hechos sobre pacientes
1. agrega check al response de servicio anses - quita awaits innecesarios
=> Corrección en MPI UPDATER

config.ts, core/mpi/jobs/elasticFix.ts, jobs/elasticFixJob.ts, package.json
* Re sincronizar pacientes y sus respectivos turnos y prestaciones asociadas
1. Para todos los paciente doblemente indexados en elastic, se analizan los datos del índice de elastic que no se corresponde con ningún documento en mongodb. Si ese id tiene prestaciones o turnos asociados se reemplazan por el id del paciente en mongodb (MPI) y se elimina el registro duplicado en elastic
=> Re-sincronización de pacientes elastic <-> mongodb

core/mpi/jobs/elasticFix.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts
* Modificación del job manual para re-sincronizar pacientes entre elastic y mongodb
=> Elastic fix

config.private.ts.example
1. Actualizar nombre de la variable de entorno de la coleccion LOGS
=> config: actualiza archivo de ejemplo

core/mpi/controller/paciente.ts
* Se quita resolve en mpi Updater
1. Evita que los pacientes se eliminen de Elastic por promises no resueltas
=> MPI: cambios en mpi Updater

modules/cda/routes/cda.ts
* Para un mejor seguimiento del log mostrar mensajes mas informativos.
1. Modificar el error del log agregando cual es el dato por el que falla.
2. Se agrega la condición que busque por cie10.8
=> CDA - logs

core/tm/routes/ocupacion.ts, core/tm/routes/procedimientoQuirurgico.ts, core/tm/schemas/ocupacion.ts, core/tm/schemas/procedimientoQuirurgico.ts, modules/descargas/controller/descargaCensoMensual.ts, modules/descargas/routes/descargas.ts, modules/rup/controllers/censo.ts, modules/rup/controllers/internacion.ts, modules/rup/routes/internacion.ts, modules/rup/schemas/censo.ts, templates/rup/informes/html/censoMensual.html, templates/rup/informes/sass/main.scss
* https://pm.andes.gob.ar/projects/rup-internacion/work_packages/690/activity
1. Implementación del html y ts para la impresión del censo
2. Ruta para la creación del pdf
3. Consulta en mongo para obtener los censos mensuales 
4. Consulta para obtener ocupaciones y procedimientos ya sea por código o por nombre
=> RUP: Internación - Censo mensual

jobs/censoMensualJob.ts, modules/rup/controllers/censo.ts, modules/rup/controllers/internacion.ts, modules/rup/routes/internacion.ts, modules/rup/schemas/censo.ts
https://pm.andes.gob.ar/projects/rup-internacion/work_packages/690/activity
1. censo mensual + job
2. fix a filtro de busqueda
=> INTERNACION - censo

core/mpi/routes/paciente.ts, modules/turnos/controller/agenda.ts, modules/turnos/controller/turnosController.ts
* Errores en Fn updateTurnosPaciente.
1. Hasta corregir los errores, se comentan todas las llamadas a la función.
=> Comenta llamadas a función updateTurnosPaciente

auth/permisos.ts, config.ts, modules/estadistica/controller/procesarAgendas.ts, modules/estadistica/controller/procesarFueraDeAgenda.ts, modules/estadistica/routes/turnos_prestaciones.ts
* https://pm.andes.gob.ar/projects/citas/work_packages/716/activity
1. Agrega opción en menu hamburguesa (requiere permisos)
2. Agrega componente buscador de turnos y prestaciones
=> Busqueda turnos prestaciones

core/log.v2/routes/log.ts, modules/descargas/controller/descargas.ts, package-lock.json, package.json
* Se cambia la versión @types/node
1. cambia el package-lock
=> Actualización de dependencias

modules/descargas/controller/descargas.ts, templates/rup/informes/html/includes/insumo.html, templates/rup/informes/html/informe.html, templates/rup/informes/sass/main.scss
Mejora en la vista de los insumos y se agrega la fecha ocupo una cama y la fecho que desocupo la cama
1. Se agrega fecha desde y hasta que estuvo internado en el documento a imprimir
2. Los insumos se muestran en columnas para ocupar menos espacio
3.
=> RUP- Imprimir epicrisis

auth/permisos.ts
Agregar permiso para el acceso al mapa de camas
=> Internacion - Permiso mapa de camas

modules/estadistica/routes/turnos_prestaciones.ts, modules/rup/schemas/prestacion.ts
=> Buscador Prestaciones: Se agrega verificación de permisos+indice solicitud.turno

config.ts, jobs/actualizarTurnosMobile.ts, modules/descargas/controller/descargas.ts, modules/estadistica/routes/turnos_prestaciones.ts, modules/mobileApp/routes/agendas.ts, modules/rup/schemas/prestacion.ts, modules/turnos/controller/agenda.ts, package-lock.json, package.json
JOB: Para la aplicación móvil. Consiste en quitar el cupo 24 hrs antes del día del turno. Se ejecuta a las 12 del mediodía.
Fixes georeferencia: Verificaciones en la colección de organizaciones por faltantes de información.
=> Version 4.4.5

core/term/controller/snomedCtr.ts, core/term/routes/snomed.ts, core/term/routes/snomedv2.ts, core/term/schemas/snomed.ts, modules/facturacionAutomatica/controllers/facturacionAutomatica.ts, modules/rup/controllers/estadisticas.ts, modules/rup/routes/elementosRUP.ts, modules/rup/routes/estadisticas.ts, modules/rup/routes/prestacion.ts
* Navegación de registros RUP según la jerarquía de Snomed
=> Dashboard: Navegación Snomed

config.ts, core/mpi/routes/paciente.ts
* Solucionar el hecho de que algunos pacientes inactivos no puedan volver a activarse desde auditoria mpi.
1. Se agrego endpoint para actualizar el estado de un paciente.
=> MPI - Refactor activar/desactivar pacientes por auditoria

modules/turnos/controller/estadisticas.ts, modules/turnos/controller/operationsCacheController/operationsAgenda.ts
* Se resuelve incidente en integración de Sips. Se agrega control de dirección en el controller de estadisticas
1. 
2. 
3.
=> Fix integración y estadísticas

modules/estadistica/controller/procesarAgendas.ts, modules/estadistica/controller/procesarFueraDeAgenda.ts
* Optimizar consulta utilizada por el buscador de turnos y prestaciones.
1. Se cambia la consulta por un aggregate.
=> Optimiza buscador

modules/rup/controllers/codificacionController.ts, modules/rup/routes/codificacion.ts, modules/rup/routes/prestacion.ts
Soluciona el problema de la duplicación en la auditoría cuando se rompe la validación y se vuelve a validar la prestación.
=> RUP/CITAS: Soluciona la duplicación de auditoría. Close #1110

modules/estadistica/controller/procesarAgendas.ts, modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts, modules/turnos/schemas/turno.ts
Quitamos los commit de hora de agenda, que aún no va a entrar
=> V4.4.7 repared

modules/estadistica/controller/procesarAgendas.ts
=> quitamos los imports no utilizados

auth/routes/routes.ts
Verifica que el servidor LDAP responda, sino llama a la función de logincache.
=> AUTH: Verifica problemas con ldap 

modules/estadistica/controller/procesarAgendas.ts
* Corregir condición que determina el estado que se muestra en el buscador (mostraba sin registro del profesional en casos que si había) 
* Corregir bug en lookup con prestaciones, no realizaba control sobre el estado de las prestaciones ahora controla que sean prestaciones validadas.
=> Correcciones en buscador 

core/mpi/routes/paciente.ts, modules/obraSocial/controller/obraSocial.ts
1. Se agrega un endpoint para obtener el paciente con su obra social
=> Endpoint de paciente para obtener paciente con su obra social o financiador

modules/turnos/controller/estadisticas.ts, modules/turnos/routes/agenda.ts
* Separar de la actual consulta de estadísticas la consulta de "turnos por localidad" en otra llamada a la API
1. En consulta de turnos por localidad verifico si el paciente tiene localidad, si no tiene se setea "sin localidad"
2. Separo consulta de turnos por localidad de la consulta estadísticas para dashboard de CITAS
=> DASHBOARD - Refactor de la consulta del dashboard en CITAS

auth/permisos.ts, core/tm/controller/campaniasSalud.ts
1. Se agregó los permisos para la campaña de salud
=> Agrega permisos a campaña de salud

package.json
=> V448: Tag version

core/tm/routes/tipoPrestacion.ts
Chequea tipo de parametro en tipoPrestacion.
=> RUP: Tipo prestación

jobs/pecasConsolidadoJob.ts, modules/estadistica/pecas/controller/agenda.ts, modules/estadistica/pecas/controller/aggregateQueryPecas.ts, modules/estadistica/pecas/controller/fueraDeAgenda.ts
* Verificar inconsistencias en los datos generados por el job que actualiza la tabla de pecas.
* Realizar las correcciones que se requieran luego de la verificación.
=> BI - Correcciones en el proceso

core/tm/routes/organizacion.ts, modules/mobileApp/routes/agendas.ts, modules/turnos/routes/agenda.ts
Se corrigieron los comentarios de la Caro sobre la rama v4.4.9 que está protegida.
https://github.com/andes/api/pull/677#pullrequestreview-232167374
1. 
2. 
3. 
- [x ] No
=> Corrigen anotaciones sobre v4.4.9

modules/estadistica/pecas/controller/aggregateQueryPecas.ts
* Elimina toArray() y cursor innecesarios
=> Elimina toArray() y cursor innecesarios

core/mpi/routes/paciente.ts
* ERROR: no se incluían los virtuals en la rta del get paciente by id de pacientes (edad, edadReal, ...)
1. Se agrega un flag para conservar los virtuals al hacer paciente.[toObject()](https://mongoosejs.com/docs/api.html#document_Document-toObject)
=> GetById paciente paciente responde incluyendo los virtuals

modules/estadistica/controller/procesarFueraDeAgenda.ts, modules/rup/schemas/codificacion.ts, modules/turnos/routes/turno.ts, modules/turnos/schemas/turno.ts
1.  Se corrige el filtro de prestaciones Sin Comprobante de Sumar en el buscador de prestaciones
=> Facturacion

modules/estadistica/pecas/controller/aggregateQueryPecas.ts, modules/estadistica/pecas/controller/fueraDeAgenda.ts
* Se inserta el nombre cie10 en lugar del sinónimo por acuerdo con Información Sanitaria
=> Se cambia sinónimo por nombre

modules/turnos/routes/espacioFisico.ts
* issue https://github.com/andes/app/issues/1075
1. Se modificó filtro de búsqueda de espacios físicos por edificio.
=> CITAS - Corrige issue #1075

config.private.ts.example, jobs/migracionPecas.ts, modules/estadistica/pecas/controller/agenda.ts, modules/estadistica/pecas/controller/aggregateQueryPecas.ts, modules/estadistica/pecas/controller/fueraDeAgenda.ts
* Permitir la migración a las tablas de PECAS de uno o mas meses de un período. 
1. Se implementó un proceso que va recorriendo los días de un período dado y ejecutando el proceso de agendas y fuera de agenda ya implementado.
=> BI - Migración de agendas y prestaciones fuera de agenda en período

modules/turnos/routes/espacioFisico.ts
Corregir nuevo bug generado a partir del fix de issue #1075
=> CITAS - Corrige nuevo bug en espacios físicos (issue#1075)

package.json
Solo cambia la versión del sistema en el `package.json`
1. 
2. 
3.
=> Cambia versión en package.json a 4.4.11

core/mpi/routes/paciente.ts
issue /andes/app/#1258
1. fix del bug mencionado
=> mejoras y issues v4.5.0 en test

modules/estadistica/controller/procesarFueraDeAgenda.ts
1. Se agrega el estado de facturación a las prestaciones fuera de agenda para poder mostrar el botón Comprobante en el buscador de prestaciones
=> Se muestra botón Comprobante en buscador de prestaciones

core/mpi/controller/paciente.ts
Requerimientos obtenidos en pruebas de MPI2 en ambiente de test
1. Se recupera la dirección de renaper (anteriormente PO's solicitaron no hacerlo, luego se reconsideró)
2. Se corrige error en llamada a fn log
=> Actualización v4.5.0

package.json
=> Actualiza versión v4.4.13 del package.json

modules/turnos/controller/agenda.ts, modules/turnos/controller/diagnosticosC2Controller.ts, package.json
Actualiza a la versión 4.4.13
Primero mergear la actualización de la versión
1. Se agrego a la consulta de diagnósticos un pipeline para incluir diagnósticos fuera de agenda (codificaciones).
=> Actualizar master a v4.4.13

core/tm/routes/profesional.ts, modules/matriculaciones/routes/turno.ts
1. se quita un exec
2. se agrega una comprobacion en el put de profesional
=> cambios sugeridos en quitar exec e if en la ruta put de profesional

package.json
Actualización versión v4.4.14 package.json.
=> V4.4.14: Tag versión

modules/rup/routes/prestacion.ts
1. Se llama al microservicio de facturación Sumar al romper vaidación.
=> Se emite evento para romper validación en sumar

core/tm/routes/profesional.ts
* Optimización de ancho de banda para los get de profesionales.
1. Agrega select de mongoose
=> refactor(profesional): agrega select en get

modules/descargas/controller/descargas.ts, package-lock.json, package.json, templates/rup/informes/html/informe.html
* Los títulos "Fecha de Ingreso" y "Fecha de egreso" para las Epicrisis se perdieron
* En el informe PDF aparecían datos de PDFs generados anteriormente, se sospecha problemas relacionados al cache de la librería
1. Se reestablecieron los títulos
2. Se cambió de paquete que genera PDF
=> Títulos en fechas de ingreso y egreso para epicrisis + update phanthomjs

modules/mobileApp/routes/gestion.ts
Acceso al microservicio de la app de gestión
1. Agrega ruta para el acceso al microservicio de la app de gestión
2. 
3.
=> Nueva ruta para acceso al MS

modules/rup/routes/prestacion.ts
Borré lo que se había agregado del webhook por los comentarios en el PR de la v4.4.15 a master. Además, el webhook que se iba a utilizar no está subiendo en esta versión así que no tiene sentido subir esto ahora
1. 
2. 
3.
=> Fix v4.4.15 - Webhook

auth/routes/routes.ts
1. Agrega control de los errores de LDAP
=> fix(auth): handler LADP error and invalid credentials

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
Control que valida si la agenda posee asistencia antes de ser suspendida
1. Control que valida si la agenda posee asistencia antes de ser suspendida
=> AGENDAS: Validar asistencia antes de suspender agenda

modules/rup/routes/prestacion.ts
Ordenar por fecha resultados de búsqueda de solicitudes.
1. Inclusión de condiciones de búsqueda ascendente y descendente en búsqueda de solicitudes.
=> TOP: Ordenar solicitudes por fecha

.github/pull_request_template.md, package.json
Nos olvidamos de subir el número de la nueva versión de la api. Aprovechamos el PR también para modificar el template de PR para agregar unos comentarios
1. 
2. 
3.
=> Actualiza versión del package y PR-template

.github/pull_request_template.md, auth/permisos.ts, auth/routes/routes.ts, config.private.ts.example, config.ts, core/mpi/controller/paciente.ts, core/tm/controller/permiso.ts, core/tm/routes/organizacion.ts, core/tm/routes/permisos.ts, core/tm/routes/profesional.ts, jobs/migracionPecas.ts, modules/descargas/controller/descargas.ts, modules/estadistica/controller/procesarFueraDeAgenda.ts, modules/estadistica/pecas/controller/agenda.ts, modules/estadistica/pecas/controller/aggregateQueryPecas.ts, modules/estadistica/pecas/controller/fueraDeAgenda.ts, modules/matriculaciones/routes/turno.ts, modules/matriculaciones/schemas/turno.ts, modules/rup/routes/prestacion.ts, modules/turnos/controller/agenda.ts, modules/turnos/controller/diagnosticosC2Controller.ts, package-lock.json, package.json, templates/rup/informes/html/informe.html, utils/servicioSisa.ts, utils/serviciosGeoreferencia.ts
Actualizar branch, eliminar conflictos y refactorizar según comentarios en PR.
1. Refactor y actualización a master
=> Update 4.5.0 - refactor y update from master

modules/facturacionAutomatica/routes/configFacturacionAutomatica.ts
1. En la colección de config automática se busca por prestación turneable y prestación ejecutable.
Se deben agregar los conceptos turneables para niño sano, en los grupos etareas de 0 a 1 Año, de 1 a 6 años y de 6 a 9 años.
Se debe sacar el concepto turneable "nombre" : "niño sano",   "conceptId" : "410620009" de "prestacionSnomed"
"conceptosTurneables" : [ 
{
"nombre" : "niño sano",
"conceptId" : "410620009"
}, 
{
"nombre" : "medicina general",
"conceptId" : "391000013108"
}, 
{
"nombre" : "pediatría",
"conceptId" : "511000013109"
}
],
=> Se agrega prestacion turneable al buscar prestación

modules/descargas/controller/descargas.ts
Productos con semantic tags "objeto físico" y "medicamento clínico" no se muestran en el informe PDF
1. Se agregó la detección de esos semantic tags, con el fin que se impriman correctamente
**Capturas que muestran el problema**
=> RUP ~ Informe semantic tags de productos

modules/turnos/controller/agenda.ts
Se corrige el comentario realizado en el PR de la versión `v4.5.1` https://github.com/andes/api/pull/737/files#r299093507
1. 
2. 
3.
=> CITAS: mejora función de agenda controlador

package.json
Cambia la versión en el `package.json`
1. 
2. 
3.
=> Actualiza versión a v4.5.1 en package

modules/mobileApp/auth_routes/autenticacionApp.ts, templates/emails/emailGenerico.html, utils/roboSender/sendEmail.ts
Enviar email con formato genérico
1. Se agrega una ruta para envío de Email genérico desde la app mobile
2. 
3.
=> AppMobile: agrega un envío de email genérico

modules/mobileApp/routes/turnos.ts, modules/rup/controllers/prestacion.ts, modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
La aplicación permitía liberar turnos sin verificar que se haya iniciado la prestación asociada
1. Se agrega una verificación para evitar la liberación de turnos con prestación iniciada
=> fix(CITAS): La aplicación permitía liberar turnos sin verificar que se haya iniciado la prestación asociada

modules/descargas/controller/descargas.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/elementoRUP.ts, modules/rup/schemas/prestacion.registro.ts, package-lock.json
* https://pm.andes.gob.ar/projects/rup/work_packages/618/activity
1. Se filtran los registros de las prestaciones que son privados. Si la consulta la ejecuta el mismo profesional que aplico el valor private no se filtra.
ElementosRUP a insertar
```
{
"_id" : ObjectId("5c50661713e0cba8b55c9a77"),
"componente" : "ObservacionesComponent",
"tipo" : "atomo",
"defaultFor" : [],
"style" : {
"columns" : 12.0,
"cssClass" : null
},
"conceptos" : [ 
{
"conceptId" : "4291000013101",
"term" : "nota privada",
"fsn" : "nota privada (elemento de registro)",
"semanticTag" : "elemento de registro"
}
],
"params" : {
"privacy" : "private"
},
"requeridos" : [],
"frecuentes" : []
}
```
```
{
"_id" : ObjectId("5cf6a26b5cd661b503731e66"),
"componente" : …
```
=> RUP - Privacidad de registros

modules/descargas/controller/descargas.ts
Resuelve incidente en la generación de Informes de Rup
1. Agrega await en la generación de informes de Rup
=> fix(rup): Generar Informes de Rup

modules/obraSocial/routes/obraSocial.ts
=> Mejora código devolución errores

modules/rup/controllers/codificacionController.ts
1. Cuando se trate de una epicrisis o colonoscopia va a buscar los conceptos asociados en cada sección
=> RUP - indicar la primera vez en los C2 en epicrisis y colonoscopia

config.private.ts.example, modules/mobileApp/routes/devices.ts, modules/mobileApp/routes/gestion.ts, modules/mobileApp/routes/registrosProblemas.ts, modules/mobileApp/schemas/registrosProblemas.ts
https://pm.andes.gob.ar/projects/mobile-app/work_packages/845/activity
1. Creación de rutas y esquema para reportes de problemas.
=> App Gestión - Agrega ruta para registrar y obtener problemas

modules/turnos/controller/diagnosticosC2Controller.ts
No se estaban mostrando las atenciones realizadas como sobreturnos porque la parte del aggregate de sobreturnos hacía un unwind del arreglo `codificaciones` y después un match con ese dato como si siguiera siendo un arreglo (`codificaciones.0`) lo que causaba que no trajera ningún resultado
1. 
2. 
3.
=> Reporte C2 - Corrige el filtro de sobreturnos

modules/obraSocial/routes/obraSocial.ts, modules/turnos/controller/diagnosticosC2Controller.ts
Ahora recibe el documento necesario para realizar la query de OS en los params
Actualizar en endpoint GET de obras sociales
1. Se reciben el dato necesario (documento) por param
=> OBRA SOCIAL - modifica endpoint get obras sociales

modules/obraSocial/routes/obraSocial.ts
1. FIX - modifica el endpoint de obrasSociales/:documento a obrasSociales/puco/:documento porque estaba ocultando el resto de los endpoints obrasSociales/...
=> OBRAS SOCIALES : modifica ruta obrasocial

core/mpi/routes/paciente.ts
issue #709 
1. Se quita la eliminación innecesaria en MPI para los pacientes modificados en endpoint POST identificadores
=> Quita delete de paciente en POST identificadores

auth/auth.controller.ts, auth/ldap.controller.ts, auth/routes/routes.ts, auth/schemas/permisos.ts
Se requiere tener usuarios de prueba genéricos para que varias pesonas que no tienen ONELOGIN puedan ver el sistema.  Entonces se crea un metodo de verificaicon por password y no por LDAP.
1. Se agrega campo opcional en el schema de Usuarios.
=> feat(login): agrega metodo de autentificacion por password

Dockerfile
Actualiza el archivo DockerFile
1. Copia el archivo package-lock
=> chore(docker): actualizar dockerfile

core/tm/routes/organizacion.ts
Agregar la posibilidad de seleccionar campos en el get de organizaciones para [ésta user](https://pm.andes.gob.ar/projects/rup/work_packages/821/activity)
1. Se agrega un select al find organizaciones en el endpoint GET
=> Organizaciones: Agrega campo fields

modules/estadistica/controller/procesarAgendas.ts, modules/estadistica/controller/procesarFueraDeAgenda.ts, modules/estadistica/routes/turnos_prestaciones.ts
Agrega filtro de DNI de paciente al buscador de turnos y prestaciones
https://pm.andes.gob.ar/projects/lab/work_packages/814/activity
1. Se incluye un filtro de DNI de paciente, y se agrega dicho parámetro al request de GET de prestaciones.
=> BUSCADOR: filtro DNI buscador

modules/estadistica/pecas/controller/agenda.ts
1. Se corrigió problema con asincronismo
2. Se quitó el envío de mail de los catch.
=> fix(BI): Corrige errores en proceso

modules/facturacionAutomatica/routes/configFacturacionAutomatica.ts
1. Se valida si la prestación turneable y la prestación ejecutable son válidas.
=> Se valida idPrestacionTurneable y idPrestacionEjecutada

modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts
- andes/app#1320 
- andes/app#1322
1. Validación para POST y PUT de agenda que chequea que la agenda no superponga profesionales y/o espacios físicos en un mismo rango horario.
=> CITAS: solapamiento de agendas

modules/descargas/controller/descargas.ts, package.json, templates/rup/informes/html/includes/adjunto.html, templates/rup/informes/html/includes/adjuntoNoSoportado.html, templates/rup/informes/html/informe.html, templates/rup/informes/sass/main.scss
https://pm.andes.gob.ar/projects/ui-ux/work_packages/925/activity
Resumen:
**COMO** profesional médico
**QUIERO** poder visualizar la descripción (term) y tipo de archivo (video, audio, documento word, etc) si el archivo no es compatible con PDF
**PARA** que el paciente pueda entender mejor los datos de su historia clínica
1. Se agregó una librería para detectar tipos de archivo, si el archivo no se puede visualizar en un PDF se muestra la descripción del archivo y un detalle del tipo (si es un video, audio, etc) y un mensaje que indica que no es visualizable
=> RUP Informe: Documentos adjuntos no compatibles

modules/mobileApp/routes/registrosProblemas.ts, modules/mobileApp/schemas/registrosProblemas.ts
Agrega campos para almacenar el id y cargo de quien cambia el estado de un problema a **resuelto**
=> feat:(AppGestion): Agrega campos para almacenar quien resuelve

core/term/controller/snomedCtr.ts, modules/rup/controllers/plantillasRUP.ts, modules/rup/routes/plantillasRUP.ts, modules/rup/schemas/plantillasRUP.ts
https://pm.andes.gob.ar/projects/rup/work_packages/847/activity
1. Se agrega una nueva collección con las plantillas necesarias.
=> feat(rup): plantillas para procedimientos

core/tm/routes/profesion.ts, core/tm/routes/profesional.ts, core/tm/schemas/profesion_model.ts
Armado de excel para exportar a Sisa los profesionales filtrando con fecha desde y hasta en el módulo de matriculaciones. **https://github.com/RedTICS/matriculaciones/pull/86**. 
1. Se agregaron todos los campos obligatorios que debería tener el excel
2. Se agregaron controles al traer los datos desde BD
=> feat(Matriculaciones): exportSisa Profesionales

modules/matriculaciones/routes/turno.ts
https://pm.andes.gob.ar/projects/matriculaciones/work_packages/931/activity
1. Endpoint turnos matriculaciones, se agrega query para obtener los turnos de matriculaciones filtrando por mes
=> feat (matriculaciones): se agrega funcionalidad a endpoint get turnos

core/log/schemas/log.ts, core/log/schemas/logPaciente.ts, core/term/schemas/cie10.ts, core/term/schemas/mapping.ts, core/term/schemas/staticmapping.ts, core/tm/schemas/profesional.ts, modules/auditorias/schemas/auditoriaPrestacionPaciente.ts, modules/carpetas/schemas/carpetaPaciente.ts, modules/legacy/schemas/agendasCache.ts, modules/mobileApp/schemas/vacunas.ts, modules/obraSocial/schemas/obraSocial.ts, modules/prestamosCarpetas/schemas/prestamo.ts, modules/rup/schemas/prestacion.ts, modules/turnos/schemas/agenda.ts
Agrego al código la creación de indices que fuimos agregando a demanda.
=> feat(index): Agrega creacion de indices necesarios

core/tm/routes/profesional.ts
Se realizaron cambios en el armado del archivo del excel. 
1. Se pasaron los campos del excel a mayúsculas
2. Se cambio el aggregate para que sea mas eficiente la búsqueda
3. Se cambio la consulta para el campo ID_PROFESION_REFERENCIA
=> fix(MATRICULACIONES): cambios en el archivo exportSisa

auth/permisos.ts, core/tm/routes/profesional.ts, core/tm/schemas/siisa.ts
Se reutiliza el endpoint utilizado para obtener profesionales para generar los reportes de los profesionales/matrículas. Se agregaron nuevos filtros que se utilizan en este reporte y si viene determinado parámetro, se devuelve el resultado como lo devuelve la BD o prepara para exportar un Excel
1. 
2. 
3.
=> TM - Reporte matrículas

modules/turnos/controller/estadisticas.ts, modules/turnos/routes/agenda.ts, package.json
* Descarga de csv, agregar tipo de turno 'App Mobile', fix de filtrado por estado de turno 'disponible', order by cantidad
1. Se agrega tipo de turno 'app mobile' en el aggregate para contabilizarlo
2. Se ordenan los resultados de mayor a menor tomando en cuenta la cantidad de turnos
3. Se arregla problema de filtrado por estado de turno 'disponible'
4. Creación y descarga de csv. Falta adaptarlo para los gráficos de Agendas
=> CITAS - Dashboard mejoras

core/tm/schemas/tipoPrestacion.ts, modules/turnos/controller/agenda.ts, modules/turnos/routes/agenda.ts, modules/turnos/schemas/turno.ts
Que las agendas no nominalizadas se auditen solo de forma manual.
1. Al momento de actualizar el estado de las agendas, si esta es no nominalizada se la ignora.
=> CITAS: Auditoria de agendas no nominalizadas

core/tm/schemas/profesional.ts
Se reporto error al cargar la especialidad de un profesional en la formación de posGrado. 
1. Se agregó en el schema de profesional un import EspecialidadSIISASchema 
2. Se modificó el type de la especialidad de la formación de posGrado
3. Se modificó el campo de notas para que se guarden correctamente
=> fix(MATRICULACIONES): corrige error código de especialidad y notas

core/mpi/controller/mpiCorrector.ts
Modificar el job MPI Corrector para que el proceso de corrección de errores reportados se realice para los pacientes que se encuentren en Andes, ya que no se están sincronizado actualmente a la base de MPI 
1. Se modifica la función mpiCorrector para utilizar el paciente de Andes y no de la base de MPI.
=> fix(mpi): Fix de Job mpiCorrector

modules/turnos/controller/agenda.ts, modules/turnos/schemas/turno.ts
https://pm.andes.gob.ar/projects/mobile-app/work_packages/891/activity
1. Se agregó el atributo "horaAsistencia" al schema de turnos
2. Se registra la hora de asistencia al turno al momento de "dar asistencia", en los casos que no exista previamente.
=> RUP: hora de asistencia en turno

modules/rup/routes/prestacion.ts
Al momento de iniciar una una nueva prestación con turno, chequear que no este siendo iniciada simultáneamente por otro profesional.
1. Antes de hacer efectivo el post de la nueva prestación, chequea que esta no haya sido iniciada por otro profesional (Que no exista una prestación con mismo id de turno) que esté viendo la agenda simultáneamente.
=> RUP - chequeo de prestación ya iniciada

modules/rup/routes/prestacion.ts
corrige error que se generó al agregar control al iniciar prestación
=> fix(rup) elimina condición con error

modules/turnos/routes/agenda.ts
Optimizar la visualización de agendas para búsquedas con resultados significantes.
1. Agrega skip y limit para evitar traer grandes cantidades de agendas de una sola vez.
=> CITAS: Optimizacion en busqueda de agendas

modules/webhook/routes/webhook.ts, modules/webhook/schemas/webhookSchema.ts
Mejoras en la clase webhook:
1- Nombre para cada funcionalidad del evento con el que se quiere interoperar.
2- Función transform para aplicar el encode de Fhir.
3- Algunos tocitos.
Scripts:
1) db.webhook.updateMany({active: {$exists: false}}, {$set: { "active" : true}});
2) db.webhook.updateMany({nombre: {$exists: false}}, {$set: { "nombre" : "add webhook name"}});
=> feat(webhook): dynamic tramformation layer

modules/facturacionAutomatica/routes/configFacturacionAutomatica.ts, modules/turnos/routes/turno.ts
1. Se agrega facturación automática desde sobreturnos 
2. Se agrega evento para facturar RF
Se deben agregar los siguientes webhook:
1-  "event" : "facturacion:factura:buscador",
"url" : "http://url/facturacion/facturar",
"method" : "POST"
2- "event" : "facturacion:factura:recupero_financiero",
"url" : "http://url/facturacion/facturar",
"method" : "POST"
=> CITAS: se agrega facturación automática desde sobreturnos

modules/descargas/controller/descargas.ts, package-lock.json, templates/rup/informes/html/informe.html, templates/rup/informes/sass/main.scss
https://pm.andes.gob.ar/projects/ui-ux/work_packages/1036/activity
1. Se reemplazan fechas de solicitud/ejecución/validación por ingreso/egreso
2. Se muestra la unidad organizativa (sector)
=> fix(informe pdf): se muestran datos de ingreso, egreso y servicio en epicrisis

modules/descargas/controller/descargas.ts, templates/rup/informes/html/includes/adjuntoNoSoportado.html
https://pm.andes.gob.ar/projects/ui-ux/work_packages/1037/activity
1. Se muestra un mensaje acotado indicando archivos adjuntos incompatibles
=> feat: Se comprimen los datos de adjuntos no compatibles en 1 renglón

modules/rup/routes/prestacion.ts
Filtrar solicitudes originadas en TOP
1. Agrega filtro para filtrar prestaciones de TOP (que no poseen prestación origen)
=> Prestaciones: agrega filtro para trear únicamente prestaciones TOP

auth/auth.class.ts, auth/routes/routes.ts
- Renovar el token cada vez que se actualizan los datos
- Funcion que refresca el token de aplicación.
=> feat(AppGestion):Actualizar Token

auth/routes/routes.ts
Corrige datos que faltaban al refrescar un token. Los datos del usuario se sacan del request y hay algunos cambios en cuanto a la generación del token al momento del login.
1. 
2. 
3.
=> fix(auth): Corrige datos que faltaban al refrescar un token de usuario

core/term/routes/cie10.ts, jobs/actualizarDatosInternacionJob.ts, modules/rup/schemas/camaEstado.ts, utils/scriptsMongo/actualizarDatosInternacion.ts
issues issue andes/app#1417 y andes/app#1418
1. Modifica esquema de estadoCama
2. Modifica filtro para busqueda de diagnosticos de egreso
3. Crea un script para actualizar los datos de las internaciones registradas segun el nuevo esquema
=> Internacion - Corrige varios issues

modules/webhook/routes/webhook.ts
Se modifica la variable de body para que no se sobreescriba el valor.
=> fix(webhook): Se soluciona que se estaba pisando una variable

core/tm/routes/organizacion.ts, modules/rup/controllers/cama.ts, modules/rup/routes/internacion.ts
Verificar las rutas que devuelven res.json(null) por actualización de @andes/shared.
1. Se modifican rutas que devuelven null y se cambia por [ ] si corresponde.
=> Fix: modifica rutas que devuelven null

core/log/routes/log.ts
La ruta del log devolvía null. Donde se ha visto eso.
1. Devuelve un json con estado ok. 
Queda pendiente actualizar a async/await. Pero esto es un fix rápido.
=> fix(log): ruta log return null

modules/carpetas/routes/ultimaCarpeta.ts
Cambia el valor devuelto por las rutas de carpetas
api/modules/carpetas/ultimaCarpeta
api/modules/carpetas/incrementarCuenta
1. Cambia el valor devuelto por las rutas
2. Refactoriza las dos rutas de carpetas
=> fix(carpetaPaciente): rutas return null

modules/turnero/routes/configuracionPantalla.ts, modules/turnero/schemas/turneroPantalla.ts, websockets.ts
Cambiar el path por defecto de la conexión socket 
1.  Modificar path por defecto websocket(reemplaza  socket.io por ws)
2. Agrega proyección a la consulta get de las rutas de pantallas
=> TURNERO: modifica path de websocket

modules/turnos/routes/agenda.ts
Fix en la codificación de un sobreturno
=> fix(agenda): modifica return en sobreturnos

core/tm/routes/profesional.ts
Quitar el mensaje de error al cargar la foto de un profesional seleccionado
1. Elimina setHeader ya que el Content-Type correspondiente es 'application/json' y no image/jpeg
=> fix(profesionales):   Modifica Content-Type

core/tm/routes/sms.ts, utils/roboSender/sendSms.ts
Fix en captura de error cuando no se puede enviar el mensaje
=> fix(turnos): captura error en SMS

modules/estadistica/controller/procesarFueraDeAgenda.ts
https://github.com/andes/app/issues/1408
1. Se corrigió bug en consulta de prestaciones fuera de agenda que reasignaba el match cuando se filtraba por prestación y paciente al mismo tiempo.
=> AGENDAS: Corrección en query de prestaciones fuera de agenda

core/tm/routes/profesional.ts
Modificar las respuestas de la ruta de la firma del profesional
1. Cambia Content-Type
=> fix(profesional): modifica get firmas del profesional

modules/descargas/controller/descargas.ts, templates/rup/informes/html/includes/adjunto.html, templates/rup/informes/html/includes/hallazgo.html, templates/rup/informes/html/includes/insumo.html, templates/rup/informes/html/includes/procedimiento.html, templates/rup/informes/html/includes/registro.html, templates/rup/informes/html/includes/solicitud.html, templates/rup/informes/sass/main.scss
Se filtran conceptos en la generación del informe.  Modificación menor en estilos.
arreglos varios
https://pm.andes.gob.ar/projects/rup/work_packages/816/activity
1. Se filtran los conceptos de interés y se ajustan algunos estilos.
=> RUP -  PDF registro de colonoscopía

auth/permisos.ts
… habilitar funcionalidad por niveles
Se comentan del listado de permisos el permiso para matriculaciones y auditoria de pacientes temporalmente, hasta que se agregue la funcionalidad de permisos por niveles
=> fix(GestorUsuarios): Se comentan permisos temporalmente

auth/ldap.controller.ts
Debido a que la librería es muy inestable así también el servicio de LDAP, se implemente un timeout casero por afuera de la librería ldap.js para que en el caso de no respuesta forzar al cache de password.
1. Utiliza función Promise.race con un sleep de 3 segundos.
=> fix(auth): implementa ldap timeout

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, modules/turnos/controller/turnosController.ts, modules/turnos/routes/turno.ts
* https://proyectos.andes.gob.ar/browse/TOT-3
1. Se modifica la función getHistorialPaciente para buscar turnosPróximos, filtrar por paciente y por prestación
2. Se suma una nueva ruta 'search' a turnos
=> TOTEM: traer próximos turnos del paciente

auth/permisos.ts, core/tm/schemas/localidad.ts, core/tm/schemas/mapeo.ts, jobs/exportarInternaciones.ts, modules/descargas/routes/descargas.ts
Dado un efector, poder descargar un listado de sus internaciones según filtros de búsqueda.
1. Se agregó un boton en '/internacion/listado' para poder descargar los resultados de la búsqueda en formato .csv
2. Se agregó la colección 'mapeo' para, dada una especialidad de snomed, obtener el servicio correspondiente prestado por el efector.
Nueva coleccion 'mapeo':
{
"_id" : ObjectId("5d8389a331972e9272139030"),
"identificador" : "especialidad",
"codigoOrigen" : "394802001",
"descripcionOrigen" : "medicina general",
"codigoDestino" : "200",
"descripcionDestino" : "servicio de medicina general"
}
=> Internacion - Descarga listado internaciones

core/tm/schemas/organizacion.ts
User Story: https://pm.andes.gob.ar/projects/tablas-maestras/work_packages/1066/activity
1. Se cambió el esquema de oferta prestacional
2. 
3. 
Se necesita borrar todas las ofertas prestacionales ya cargadas porque ahora cumplen con otro esquema. Colección: Organización, Atributo: OfertaPrestacional
Nulifica todas las ofertas prestacionales creadas ya que ahora cumplen con otro esquema y se debe usar el ABM para crear nuevas o crearlas de nuevo.
```
db.organizacion.updateMany({"ofertaPrestacional": {"$exists": true}}, {"$set": {"ofertaPrestacional": null}})
```
=> refactor(oferta-prestacional): cambio de esquema de Oferta Prestacional

core/mpi/controller/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-9
1. Log de validacion con datos de paciente temporal y mathing contra renaper.
=> MPI - Log de validación de un paciente temporal

modules/rup/routes/prestacion.ts
https://pm.andes.gob.ar/projects/mobile-app/work_packages/1058/activity
1. Patch de registros solicitud (prioridad)
2. Refactor de consulta de prestaciones de find a aggregate
3. Filtro y ordenamiento de búsquedas por prioridad
=> feat(PRESTACIONES): incluye prioridad a las solicitudes

modules/rup/routes/prestacion.ts
=> fix(solicitudes): Elimina filtro erroneo

core/tm/routes/profesional.ts
ISSUE #812
1. Suma al resultado de resumen de profesional el dato de formacionGrado.
=> MATRICULACIONES - Se suma el dato de formacionGrado al resumen de profesional

modules/prestamosCarpetas/controller/prestamosController.ts
Mejora performance de consulta de solicitudes de carpeta
1. Mejora performance de consulta de solicitudes de carpeta, al agrupar consultas a la base de datos en un Promise.all
=> Prestamo Carpetas: optimización de consultas

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
Arreglar errores al consultar los próximos turnos de los pacientes.
1. Cambio en el formateo de las fecha en getHistorialPaciente
=> fix(totem): arreglo de formateo de fechas en ruta de historial paciente

modules/estadistica/controller/procesarFueraDeAgenda.ts
issue https://github.com/andes/app/issues/1441
1. Se modifica la fecha asignada al objeto que se retorna a la app
=> Buscador de turnos y prestaciones -  Fecha de la prestación

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
Al momento de crear un paciente, si se ingresaba mismo documento y sexo que un paciente temporal, el sistema solicitaba que se seleccione ese en lugar de crear uno nuevo. Ahora esa validación omite a los pacientes temporales
1. Se agregó un parámetro para indicar si se desea excluir a los pacientes temporales en el controlador de pacientes. Esta función se usa también en la auditoría de pacientes que debe seguir comportándose como venía (sugerir pacientes temporales)
2. 
3.
=> MPI - Excluir pacientes temporales en pacientes candidatos

core/tm/routes/profesional.ts, core/tm/schemas/profesional.ts
Se pidió que se pudiera agregar desde la app, a los profesionales no matriculados desde matriculaciones, la profesión que tienen y la matrícula. 
1. Se reutilizó un commit del otro PR para corregir la colección del modfelo siisa porque no traía sino las profesiones al no existir la colección donde buscaba 
2. Agregar los campos nuevos al esquema y patch del profesional
3. No se agregó al post de profesional porque se agrega el profesional como llega por parámetro
4. Se sumó al esquema de profesional los atributos validadoRenaper y foto
=> TM - Profesión y matrícula externa

modules/rup/routes/prestacion.ts
Arreglar performance en aggregate de solicitudes
1. Cambia posición de addFields después del match principal.
=> TOP: Arregla error de performance en aggregate

modules/prestamosCarpetas/controller/prestamosController.ts
1.  Prestamos: agrega retorno a método savePrestamosCarpetas
=> Prestamos: agrega retorno a método savePrestamosCarpetas

auth/schemas/authUsers.ts
Agrega configuraciones generales para el usaurio. En este momento es para poder activar hotjar a ciertos usuarios.
1. Un campo en el Schema de usuarios
https://github.com/andes/app/pull/1507
=> feat(hotjar): add configuraciones para usuarios

modules/turnos/routes/agenda.ts
Corrige bug en clonación de cupo de agenda dinámica cuando turnos de la misma se consumieron
https://proyectos.andes.gob.ar/browse/CIT-10
1. Corrige bug en clonación de cupo de agenda dinámica cuando turnos de la misma se consumieron
=> AGENDAS: Corrige bug de clonación de cupo

modules/rup/schemas/prestacion.estado.ts
https://proyectos.andes.gob.ar/browse/TOP-2
1. Se incluyó el campo de observaciones en el schema de estado de prestación. Motivo rechazo permanece deprecado
=> TOP: cambia property motivoRechazo x observaciones

modules/turnos/routes/agenda.ts
Corregir bug al clonar agendas que no se dinámicas, con el control de cupo no dejaba clonar en estos casos
1. Agrega control de agenda dinámica al momento de cargar el cupo cuando se clona una agenda
2. 
3.
=> fix(CITAS): Agrega control de agenda dinamica al clonar

templates/rup/informes/sass/main.scss
Arregla issue #872
1. Se incrementó `line-height` de tag `p`
=> fix(informe PDF): se corrige interlineado de párrafos issue #872

modules/rup/routes/prestacion.ts
Se quita momentáneamente el control del token
1. 
2. 
3.
=> fix(huds): se quita control de token

modules/cda/routes/cda.ts, modules/rup/routes/prestacion.ts
Se quita verificación de la Huds
1. 
2. 
3.
=> fix(huds): quita verificación de token de Huds

jobs/exportarInternaciones.ts
Reporte de efector añelo sobre error en la generación del documento.
1. Se modificó control de obra social
=> Internación - documento de listado de internaciones

config.ts, core/mpi/controller/mpiCorrector.ts
https://proyectos.andes.gob.ar/browse/MPI-8?filter=-3
1. Se reemplazan viejos logs los de andesLogs en mpiCorrector.
=> MPi - Reemplaza logger por andesLog

modules/rup/controllers/prestacion.ts, modules/rup/schemas/prestacion.solicitud.historial.ts, modules/rup/schemas/prestacion.ts, modules/turnos/routes/agenda.ts
https://proyectos.andes.gob.ar/browse/TOP-20
1. Schema de historial de solicitud de prestación
2. Método para registrar el historial antes de liberar el turno
=> feat(TOP): Guarda historial de solicitud al liberarse turno

modules/mobileApp/controller/AuthController.ts, modules/mobileApp/routes/accounts.ts, modules/mobileApp/schemas/pacienteApp.ts
https://proyectos.andes.gob.ar/browse/AM-13
1. Se agrega al Schemma pacienteApp el campo _lastLogin_ de tipo _Date_ para poder registrar cada vez que un usuario se loguea o actualiza la app mobile de gestión
2. Se agrega una función _patch_ para realizar la actualización del campo _lastLogin_
=> APP-MOBILE: Registrar accesos de usuarios

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, core/tm/controller/localidad.ts
https://proyectos.andes.gob.ar/projects/MPI/issues/MPI-11?filter=allopenissues
https://proyectos.andes.gob.ar/projects/MPI/issues/MPI-12?filter=allopenissues
https://proyectos.andes.gob.ar/projects/MPI/issues/MPI-13?filter=allopenissues
1. Función que realiza matching de dos strings correspondientes a provincia y localidad contra colecciones de la DB con el mismo nombre.
2. Se guarda la dirección obtenida desde renaper como domicilio legal del paciente.
=> MPI - Dirección legal en pacientes

modules/rup/routes/prestacion.ts
Agrega skip y match de pacientes a aggregation de solicitudes
En GET de prestaciones:
1. Agrega skip y limit
2. Agrega match de organización
3. Agrega match de nombre completo de paciente y numero de documento de paciente.
=> TOP: Agrega skip y match de pacientes a aggregation de solicitudes

modules/rup/routes/prestacion.ts
Saca query de solicitudes que consulta todas las prestaciones
=> fix(TOP): Saca query de solicitudes que consulta todas las prestaciones

modules/mobileApp/auth_routes/rup-adjuntos.ts
Corregir error al momento de adjuntar archivos desde la app mobile, por acceso al id del profesional logeado.
1. Cambia el acceso al id del profesional desde el request para adjuntar archivos desde la app mobile
2. 
3.
=> fix(MOBILE): Cambia el acceso al id del profesional para adjuntar archivos

modules/rup/controllers/prestacion.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.estado.ts
Permitir que el profesional pueda dar respuesta a la solicitud sin necesidad de pasar por un turno
https://proyectos.andes.gob.ar/browse/TOP-15
NOTA: Se parte de la rama TOP-20 porque depende de los cambios desarrollados en el PR #895
=> TOP: Asignación de solicitudes

auth/permisos.ts, modules/rup/controllers/prestacion.ts, modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-16
https://proyectos.andes.gob.ar/browse/TOP-25
Se sumaron filtros a la ruta de búsqueda de solicitudes
=> TOP: Filtros en la búsqueda de prestaciones

core/mpi/routes/paciente.ts
Crear una ruta en la API que devuelva la foto decodificada.
https://github.com/andes/app/pull/1526
=> feat(mpi): ruta /foto de pacientes

modules/turnero/routes/configuracionPantalla.ts
Fix en la generación del token para el turnero
1. Se quita _id
2. 
3.
=> fix(turnero): agrega control en pantalla

modules/turnos/routes/turno.ts
https://proyectos.andes.gob.ar/browse/CIT-7
1. En el PUT de turnos, se remueve el atributo "asistencia" si su valor es falsy.
=> CITAS: Remueve el atributo asistencia si su valor es falsy

modules/turnos/controller/reportesDiariosController.ts
El ultimo dia de cada mes del reporte diario mensual no lo contaba.
1. Se sumo un dia mas a la fecha limite para que tome el ultimo dia del mes
2. 
3.
=> Reportes Diario Mensual - Ultimo dia

modules/descargas/controller/descargas.ts, modules/rup/schemas/semantic-tag.ts
https://proyectos.andes.gob.ar/browse/MIT-7
Agregar al buscar el semantic Tag: _fármaco de uso clínico_
=> feat(RUP): Agregar al buscador el semantic Tag: fármaco de uso clínico

auth/schemas/authUsers.ts, core/tm/routes/disclaimer.ts, core/tm/schemas/disclaimer.ts, modules/gestor-usuarios/usuarios.routes.ts
Cuando el usuario ingresa al sistema, deberá aceptar un disclaimer para continuar a la aplicación.
1. Se sumó el schema de disclaimer
2. Se crearon las rutas de disclaimer
1. Se modificó el schema de authUser para que guarde los disclaimers que aceptó
2. Sumadas rutas a usuarios para acceder a sus disclaimers, agregar nuevos y modificarlos.
Se crea una nueva colección llamada *authDisclaimers*
=> PRIVACIDAD: sumado schema/rutas de disclaimer 

modules/descargas/controller/descargas.ts, templates/rup/informes/sass/main.scss
Falla en la generación de pdf. La descarga del resumen en rup generaba un pdf con la palabra "false" cuando la prestacion no tenía una configuracion de informe propia. También se necesitaba arreglar el formato incorporando un salto de línea y los títulos en minuscula
1. Arregla la generación de pdf para aquellas prestaciones que no tienen una configuración de informe.
2. Arregla los titulos en minuscula y el salto de línea que faltaba en los mismos.
=> DESCARGAS - Corrección en la generación de informes

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
Refactor de código de la georeferencia de un paciente nuevo
1. Mueve la función de georeferenciar al evento de la creación del paciente
2. Loguea datos de las opciones seleccionadas (ignoreCheck)
=> fix(mpi): agrega logs en la creación del paciente

modules/descargas/controller/descargas.ts, templates/rup/informes/html/censoDiario.html, templates/rup/informes/html/informe.html, templates/rup/informes/sass/main.scss
https://proyectos.andes.gob.ar/browse/RUP-27?jql=key%20in%20(RUP-27)
1. Si el informe a generarse corresponde a una prestación no validada se muestra una marca de agua y se eliminan los datos de validación.
=> RUP - Previsualización de informe de prestación

modules/obraSocial/schemas/puco.ts
Se agrega índice para optimizar la query de versiones del Padron de Obras Sociales
1. Agregar índice al esquema de Puco
2. 
3.
=> feat(puco): agregar índice de versión a puco

modules/rup/routes/prestacion.ts
https://github.com/andes/app/issues/1588
1. Arregla bug de permiso para única prestación
=> TOP: Arregla bug de permiso para unica prestacion

modules/rup/internacion/camas.controller.ts
Al crear una cama, el equipamiento se guarda en la cama y no en el estado de la misma (donde deberia estar).
1. Corrige el bug del equipamiento de una cama, ahora se guarda en el estado de la misma
2. 
3.
=> fix(camas): guarda el equipamiento en el estado de cama, no en la cama

core/mpi/controller/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-43
1. Se reemplazó una descripción del log no significativa por el detalle de la ruta y método proveniente para poder hacer un seguimiento a partir de los logs
=> Mpi - Detalle en logs create/update pacientes

modules/rup/internacion/cama-estados.controller.ts
Agregar en la búsqueda de snapshotEstados el filtro por egreso
1. Agrega en los filtros de snapshot la búsqueda por idInternación en el egreso
=> fix(mapa-camas): egreso no encuentra cama

modules/rup/controllers/codificacionController.ts
https://github.com/andes/app/issues/1460
Corrige el tema de elegir primera vez y diagnostico principal en epicrisis y colonoscopia. 
Queda pendiente la visualizacion a cargo de UI/UX que van a hacer una propuesta. 
1. des-hardcodea los conceptos epicrisis y colonoscopia.
2. Utiliza las banderas genéricas. 
PR APP: https://github.com/andes/app/pull/1502
=> fix(huds): des-hardcodea epicrisis y colonoscopia

connections.ts, package.json
Agrega un comando que sobreescribe los HOST de las base de datos. Para cuando se esta desarrollando con andes-test-integracion.
=> feat(package): add testing command

auth/permisos.ts
https://proyectos.andes.gob.ar/browse/MISC-37
1. agrega permiso para emisión de comprobante
NOTA: Al implementar este nuevo permiso, correr este script de mongo para otorgar permiso de emisión de comprobante a todos los usuarios con permiso para acceder al buscador.
```
var usuarios = db.getCollection('authUsers').find({'organizaciones.permisos': 'turnosPrestaciones:buscar'}).toArray();
usuarios.map(u => u.organizaciones).map(o => o.forEach(e => e.permisos.forEach((p, index, array) => {
if(p === 'turnosPrestaciones:buscar') { 
array[index] = 'turnosPrestaciones:*';
}
})));
usuarios.forEach(u => db.getCollection('authUsers').update({ "_id":u._id }, u, { upsert:true }));
```
=> PERMISOS: agrega permiso para emisión de comprobante

core/term/routes/snomed.ts
https://proyectos.andes.gob.ar/browse/RUP-15
1. Se cambio la ruta de mapeo CIE10: metodo POST x GET, req.params x req.body
=> RUP: Corrige ruta mapeo CIE10

core/tm/routes/formularioTerapeutico.ts
https://proyectos.andes.gob.ar/browse/AM-16
1. Cuando el parámetro de búsqueda es por el nombre del medicamento(en el searchbar), se agrega la búsqueda del medicamento por la expresión regular ingresada.
2. Se solucionan errores de linteo
=> APP-MOBILE: Búsqueda en formulario terapeutico

auth/auth.class.ts
https://proyectos.andes.gob.ar/browse/RUP-50
1. En auth.class.ts, se cambió la referencia de req.user.profesional.id a req.user.profesional
=> HUDS: cambia referencia de req.user.profesional.id a req.user.profesional

modules/descargas/controller/descargas.ts, modules/descargas/routes/descargas.ts, templates/emails/email-informe.html, templates/rup/informes/html/includes/solicitud.html, templates/rup/informes/html/informe.html, templates/rup/informes/sass/main.scss, utils/roboSender/sendEmail.ts
https://proyectos.andes.gob.ar/browse/RUP-60
https://proyectos.andes.gob.ar/browse/RUP-62
https://proyectos.andes.gob.ar/browse/RUP-63
https://proyectos.andes.gob.ar/browse/RUP-64
https://proyectos.andes.gob.ar/browse/RUP-65
https://proyectos.andes.gob.ar/browse/RUP-66
https://proyectos.andes.gob.ar/browse/RUP-67
1. Nuevo endpoint para envío de informes por correo.
2. Mejoras visuales en el informe, corrección de títulos, agrega datos de prestación.
3. Mejora búsqueda de registros para incluir secciones.
4. Visualización de algunos labels faltantes.
Para que figure el listado de correos, la organización debe tener seteado:
"configuraciones" : {
"emails" : [
{
"nombre" : "",
"email" : ""
}
]
}
=> Informe PDF - Descarga, envío por correo y mejoras visuales

modules/rup/internacion/censo.controller.ts
Los censos diarios se duplican al almacenarse y no se ven correctamente en el censo mensual
1. Corrige fecha de inicio y fin de bucket al almacenar los censos diarios
2. 
3.
=> fix(Internacion): Corrige fechas de bucket en internacionCensos

modules/turnos/controller/reportesDiariosController.ts
División de reportes diarios en los turnos: mañana, tarde y noche.
=> Reportes diarios - Dividir por turnos

modules/cda/routes/cda.ts
Emite evento para generar todos los cda de un paciente
1. 
2. 
3.
=> feat(cda): emite evento para generar CDA

modules/mobileApp/pacienteApp.routes.ts
https://proyectos.andes.gob.ar/browse/MONIT-24
1. Se sumó a los searchFields de PacienteAppResource el email
=> MONITOREO: sumado filtro de email a las rutas de pacienteApp

initialize.ts, modules/turnos/controller/agenda.ts, modules/turnos/controller/turnosController.ts, modules/turnos/index.ts, modules/turnos/institucion.routes.ts, modules/turnos/institucion.schema.ts, modules/turnos/routes/agenda.ts, modules/turnos/schemas/agenda.ts
1. Se crea instituciones.routes (Resource Base) para poder realizar la búsqueda por nombre en la base de datos de las instituciones previamente cargadas.
2. Se crea InstitucionSchema.
3. En AgendaSchema se agrega el campo otroEspacioFisico para poder guardar la institucion seleccionada al crear una agenda
Se deben insertar en la Base de Datos las instituciones, dentro de la colección "Institucion".
=> CITAS: Se agrega esquema institucion para crear agendas fuera de una organizacion

modules/rup/internacion/camas.routes.ts
Fusión de camas que no sean estadistica. Mantenemos los estados en la app, pero en la api se rutea todo a la capa medica. No deberían cambiar los estados de las capas por ahora.
Quedo avisado
1. Se crea middleware que reescribe el nombre de la capa en los GET, y PATCH de camas.
=> feat(mapa-camas): fusion medico/enfermero

modules/turnos/institucion.routes.ts, modules/turnos/institucion.schema.ts, package-lock.json, package.json
Actualiza paquete @andes/api-tool: Ya no se setea limit = 50 por default.
1. Actualiza paquete
2.  Acomoda schema de instituciones
https://github.com/andes/app/pull/1677
=> chore: actualiza api-tool

modules/turnos/routes/agenda.ts
[https://proyectos.andes.gob.ar/browse/CIT-26](url)
1.  Se agregan los controles necesarios para evitar conflictos en los cambios de estados de las agendas
=> CITAS: Pasar control de estados de agendas para operaciones que estan en app a la api

modules/turnos/controller/agenda.ts
En la codificación del turno con los datos de la prestación validada se estaba omitiendo el control del diagnostico principal cuando no mapea a un cie10.
1. Que el diagnostico principal indicado por el profesional se muestre correctamente al momento de realizar la auditoria en CIE10
2. 
3.
=> fix(TURNOS): corrige la codificación del turno con el diagnostico principal

modules/turnos/routes/turno.ts
En patch de turno, arregla comparación de ids de carpetas, que al fallar fuerza a reescribir la carpeta de paciente con la del registro de colección carpetasEfectores, ignorando el cambio de numero de carpeta.
1.  arregla comparación de ids de carpetas
=> AGENDAS: arregla comparación de ids de carpetas

modules/descargas/controller/descargas.ts, modules/descargas/routes/descargas.ts, modules/rup/schemas/prestacion.ts, templates/emails/email-informe.html
Modificar la plantilla de email agregando nombre, apellido ,dni del paciente , ambito y tipo de prestación  
1.agregue una  consulta para obtener la prestacion actual
2. 
3.
=> fix(rup):modificación de plantilla de email

modules/rup/routes/elementosRUP.ts, modules/rup/schemas/elementoRUP.ts
https://proyectos.andes.gob.ar/browse/RUP-38
1. Eliminar código relacionado a búsquedas guiadas
=> RUP: remueve código de búsqueda guiada

auth/auth.controller.ts
Agregar control de profesional null antes de pasar a string
=> fix(auth): Agrega control de profesional null

core/mpi/routes/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-99
1. Agrega chequeo por campo de direccion del paciente antes de realizar una comparacion.
=> MPI - FIx en correccion manual de errores, auditoria

core/mpi/controller/mpiCorrector.ts
https://proyectos.andes.gob.ar/browse/MPI-54
1. Modificaciones relacionadas al contenido del log, para registro de corrección de datos de pacientes
=> MPI - Modificaciones en job mpiCorrector

auth/auth.class.ts, auth/auth.controller.ts
Envía configuraciones del usuarios en la sesion. 
1.  Enviar configuraciones del usuario bajo el nombre de features, para activar servicios o "componentes" en la app.
=> feat(auth): add feature flags 

modules/rup/controllers/codificacionController.ts
Poder codificar registros que se cargaron dentro de las secciones
1.  Se cambia el orden del filtro por elementos de registro (las secciones por lo general son elementos de registro)
2. Se corrige el control por diagnostico principal
=> fix(RUP): Acceso a registros en secciones al codificar una prestación

modules/rup/schemas/prestacion.ts
Resuleve error al buscar subregistros.
=> fix(rup): get sub registros

core/mpi/routes/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-62
1. Se elimina el atributo 'foto' antes de enviar el response a la app
=> MPI - Elimina la transferencia de foto del paciente

modules/rup/internacion/cama-estados.controller.ts
Se requiere obtener la fecha de creación del estado y no de la cama.
1. Modifica el metodo searchEstados para que no reemplace el atributo createdAt de la cama con el de su estado.
2. 
3.
=> INTERNACION - evita mergear el createdAt de cama con el de estado

modules/estadistica/pecas/controller/fueraDeAgenda.ts, modules/rup/routes/codificacion.ts, modules/rup/schemas/codificacion.ts
Agregar al esquema de codificación el ámbito de la prestación que se codifica. Y se filtra en el job que pasa estas codificaciones a pecas, para solo migrar las prestaciones ambulatorias
1. Agrega ámbito de la prestación al esquema
2. Copia el ámbito de la prestación al cargar una nueva codificación 
3. Agrega filtro por ámbito ambulatorio el en job de migración a pecas
=> feat(RUP-CITAS): Agrega ambito de la prestación a la codificación

auth/routes/routes.ts, modules/mobileApp/auth_routes/autenticacionApp.ts
https://proyectos.andes.gob.ar/browse/AM-9
1. Se llama a _updateAccount_ con el parametro _lastUpdate_ de _AuthController_ para actualizar dicho campo con la fecha y hora actual.
2. Boyscout: Se reemplaza funcion de callback por async/await
=> APP-MOBILE: Registro de accesos a la aplicación mobile

initialize.ts, modules/rup/elementos-rup.controller.ts, modules/rup/index.ts, modules/rup/schemas/elementoRUP.ts, modules/rup/schemas/semantic-tag.ts
=> Rupers alpha

modules/rup/internacion/censo.controller.ts
- Corregir entradas triplicadas en el censo diario cuando el paciente ingresa y egresa en el mismo día. 
- Ordenar salida de censo mensual por fecha
1. Agrega control en el conteo del censo diario por ingreso y egreso en el día
2. Agrega acento en constante defunción ya que no se estaba contando
3. Ordena listado de censo mensual por fecha
=> fix(Internacion-Censos): Control de ingreso-egreso en el mismo día

modules/rup/internacion/cama-estados.schema.ts
Guardar en el esquema de camaEstados el tipo de egreso, que para el caso de la capa medica o de enfermería, ese dato no se almacenaba en ningún lado.
1. Modifica el esquema de camaEstados para agregar el tipo de egreso
2. 
3.
=> Mapa-camas: agrega al esquema de estados el tipo de egreso

modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.ts
Actualizar seccion frecuentes en RUP  
1. se agrega for para recorrer y calcular los frecuentes 
2. 
3.
=> Fix(RUP):frecuentes en secciones

core/mpi/controller/paciente.ts, core/mpi/schemas/paciente.ts, modules/mobileApp/routes/paciente.ts, modules/mobileApp/routes/turnos.ts
https://proyectos.andes.gob.ar/browse/AM-20
1. Se agrega en el _pacienteController_ la función _buscarRelaciones_ donde ingresa el dni del usuario y se crea un objeto por cada relación de este para enviar solo los datos necesarios.
2. Se realizan las modificaciones necesaria para que un usuario de la app pueda sacar y/o cancelar turnos "personificado" en su hijo/a
=> MOBILE-APP: se agrega funcion mis familiares

modules/rup/controllers/prestacion.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.solicitud.historial.ts
https://proyectos.andes.gob.ar/browse/TOP-11
https://proyectos.andes.gob.ar/browse/TOP-12
1. Se incluye operación "Remitir" al PATCH de prestaciones
2. Modifica método de registros de historial para poder ser reutilizado.
3. En GET de solicitudes, evalua parametro flag `remitidas`, para agregar condición de búsqueda de registro de remisión (tiene que ser la organización de la solicitud o poseer algún registro de remisión de su organización).
4. En `prestacion.solicitud.historial.ts`, corrige tipo de atributo `organización` (que causaba que se registre otro id)
https://proyectos.andes.gob.ar/browse/TOP-12
=> TOP: agrega remisión de solicitudes

auth/permisos.ts, core/tm/modulos.routes.ts, core/tm/schemas/modulos.schema.ts
https://proyectos.andes.gob.ar/browse/MISC-69
1. Modifica el esquema de módulos para agregar si está activo
2. Modifica el esquema de módulos para agregar el orden
=> MÓDULOS: campos de activo y orden

modules/rup/schemas/prestacion.registro.ts
https://proyectos.andes.gob.ar/browse/RUP-96
Flag empty que determina si un registro esta vacío.
1. Agrega parámetro isEmpty la schema,
=> feat(rup): add isEmpty flag

modules/descargas/informe-rup/informe-header.ts, modules/descargas/informe-rup/informe-rup.ts, modules/rup/internacion/camas.controller.ts
Tener el nombre y sector de la cama en el informe pdf
=> feat(informe-pdf): agrega nombre y sector de la cama

modules/descargas/informe-rup/elementos-rup/solicitud-default.component.ts, modules/rup/controllers/plantillasRUP.ts, modules/rup/schemas/plantillasRUP.ts
RUP 114 ejecución: agregar plantillas a solicitudes y régimen/tratamiento
RUP 111 solicitudes: reaccionar al cambio de un concepto (plantillas)
1. se agrega variable esSolicitud al esquema de plantillas  
2. se agrega funcionalidad a la función find para diferenciar solicitud de procedimiento. 
3. 
- [] Si
=> feat(RUP):diferenciar solicitudes y procedimientos

core/mpi/controller/paciente.ts, package-lock.json, package.json
Se producía error de validacion en un caso particular, cambiando el sexo y genero del paciente.
1. Se modifican valores que asigna la respuesta de sisa al paciente.
REQUIERE APROBACION DE https://github.com/andes/api-tools/pull/25
=> MPI - Fixes en validacion de paciente

auth/permisos.ts
https://proyectos.andes.gob.ar/browse/PRIV-46
1. Agrega permiso impresión HUDS con visibilidad restringida.
=> PRIV: Agrega permiso impresión HUDS

modules/descargas/informe-rup/informe-body.ts
https://proyectos.andes.gob.ar/browse/RUP-129
1. Informe PDF de HUDS excluye notas privadas
=> RUP: informe excluye notas privadas de otro profesional

modules/turnos/routes/turno.ts
https://proyectos.andes.gob.ar/browse/AM-40
1. Se agrega la opción para obtener los turnos del historial de un paciente sin los que fueron liberados.
Cambio para que funcione correctamente PR https://github.com/andes/mobile-app/pull/107 de la app mobile
=> App Mobile: Visualizar Historial de turnos

modules/descargas/routes/descargas.ts
cambiar el subject del email
1. se modifica el subjet de email  ,"ambitoOrigen" - "procedimiento" - PACIENTE "nombre paciente" - PROFESIONAL "nombre profesional"
2. 
3.
=> fix(RUP) modificación de plantilla de email RUP-138

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-51
1. Incluye operacion citar al PATCH de preestaciones
=> TOP: incluye operacion citar al PATCH de preestaciones

utils/roboSender/index.ts, utils/roboSender/roboSchema.ts, utils/roboSender/roboSender.ts
https://proyectos.andes.gob.ar/browse/CORE-40
1. Se agrega al _roboschema_ el campo _device_id_ que es un _array_ que contiene los _id_ de los dispositivos registrados la colección _pacienteApp_ y el campo _notificationData_ que guardara los datos de la notificacion.
2. Se agrega al controller del _robosender_ la opción para enviar una notificación push.
3. Se agrega la función _sendNotification_ para generar el model de la notificación.
4. Se realizo la prueba de enviar una notificación push cuando un paciente pide restablecer la contraseña de la app mobile (Adjunto imagen)
=> CORE: Agregar el envío de push notifications a roboSender

core/mpi/routes/paciente.ts
Verifica si el campo de dirección cambió para georeferenciarlo.  Controla el caso que el paciente no posea dirección
1. Control del campo dirección para georeferenciarlo
2. 
3.
=> fix(mpi): check georeferencia

jobs/jobMapaDeCamasExport.ts, jobs/mapaDeCamasExport.ts
Job para exportar los datos del mapa de camas y de egresos cada 8 horas
1. Agrega job que ejecuta 2 queries para exportar mapa de camas y egresos. El job realiza el llamado al microservicio de bi-queries
**Requiere cambios realizados en el microservicio de Bi** [andes/andesMicroservices#87](url)
Agregar al config.private, en la constante jobs el siguiente object
```
{
when: '* 8,16,24 * * *',
action: './jobs/jobMapaDeCamasExport.js'
}
```
=> Feat(Internacion): Agrega job para exportar datos de mapa de camas y egresos usando Bi-queries

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-153
1. Se agrega campo 'numeroIdentificacion' del esquema de pacientes a los campos en los que realiza la búsqueda multimatch
=> MPI - Fix busqueda por documento extranjero

modules/rup/internacion/censo.controller.ts
Se necesitan censar solo las camas que son censables.
1. El censo controla que la cama sea censable antes de realizar el conteo.
2. 
3.
=> INTERNACION - Censo solo cuenta las camas censables

.circleci/config.yml, core/term/controller/mapping.spec.ts, jest.config.js, modules/descargas/model/html-component.test.ts, modules/rup/internacion/camas.controller.test.ts, modules/rup/internacion/censo.controller.test.ts
Se necesita actualizar los tests de API que estan fallando actualmente.
1. Actualiza los tests del controller de camas
2. Actualiza los tests del controller de censo
3.
=> INTERNACION - Actualizar tests de API

modules/top/routes/reglas.ts
https://proyectos.andes.gob.ar/browse/RUP-126
1. En GET de reglas, agrega parametro de query de autorización, para resolver en el GET mismo cuales son las prestaciones permitidas al usuario.
=> feat(RUP): consulta permisos de prestaciones en API

core/mpi/controller/paciente.ts, core/mpi/controller/updateFuzzy.ts, core/mpi/jobs/generateTokens.ts, core/mpi/schemas/paciente.ts
Dejar de utilizar la búsqueda 'multimatch' de elastic
1. refactor: implementa aggregate
Ejecutar el job:   node jobs/manual.js core/mpi/jobs/generateTokens.js
=> MPI - Reemplaza la busqueda multimatch de elastic

core/mpi/schemas/paciente.ts
Este cambio se realizará en el próximo refactor de las rutas de pacientes
1. 
2. 
3.
=> fix(mpi): cambia schema de mpi

core/tm/routes/organizacion.ts
https://proyectos.andes.gob.ar/browse/TM-8?
1. En el POST de organización, se le asigna la organización al usuario del request.
=> TM: asigna organización a usuario autor

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-54
1. GET de búsqueda de solicitudes filtra por `$in` de array de organizaciones origen en match de prestaciones
=> TOP: busca solicitudes por mas de una organización

auth/permisos.ts
https://proyectos.andes.gob.ar/browse/TOP-50
**IMPORTANTE:** Este PR depende de https://github.com/andes/app/pull/1759.
Se remueve el permiso `solicitudes:asignadas` dado que cae en desuso.
Despues de mergear:
**1.** Limpiar permisos de los registros de `authUsers` del mongo con
```
var permisoEliminar = 'solicitudes:asignadas';
var usuarios = db.getCollection('authUsers').find({'organizaciones.permisos': permisoEliminar}).toArray();
usuarios.map(u => u.organizaciones).forEach(o => o.forEach(e => e.permisos = e.permisos.filter(p => p !== permisoEliminar)));
usuarios.forEach(u => db.getCollection('authUsers').update({ "_id":u._id }, u, { upsert:true }));
```
**2.** Limpiar permisos de los registros de `authPerfiles`
```
var permisoEliminar = 'solicitudes:asignadas';
var perfiles = …
```
=> feat(GESTOR): Remueve permiso Mis Solicitudes

modules/rup/internacion/camas.controller.ts
Agregar ingreso: true en los extras del movimiento de ingreso
1. Al momento de guardar un estado de cama, se evalúa si el estado que se está modificando es un movimiento, entonces es necesario guardar los extras en el mismo. Si no lo es entonces no se asigna el extra.
2. 
3.
=> INTERNACION - Guarda los extras en los estados de las camas

modules/rup/internacion/camas.controller.test.ts, modules/rup/internacion/camas.controller.ts, modules/rup/internacion/camas.routes.ts
Crear funcionalidad en la API que haga un control de integridad de los estados de las camas.
1. Agrega funcion de chequeo de integridad de camas.
2. Agrega test de API para el chequeo de integridad.
3.
=> INTERNACION - Check integridad de estados de camas

modules/rup/internacion/censo.controller.test.ts, modules/rup/internacion/censo.controller.ts
En los censos para calcular los dias de estada de cada internacion se debe tomar desde la fecha de ingreso al servicio (que se esta consultando) y la fecha del censo. 
1. Se cambió la manera de calcular los dias de estada por internacion en un censo siendo: diasEstada = fechaCenso - fechaIngresoServicio.
2. También se agrega el total de dias de estada, siendo el total de dias de estada de las internaciones.
3.
=> INTERNACION - Censo modifica el calculo de dias estada

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-57
1.  match de organizaciones de solicitud por array
=> TOP: match de organizaciones de solicitud por array

modules/estadistica/pecas/controller/agenda.ts, modules/estadistica/pecas/controller/aggregateQueryPecas.ts, modules/estadistica/pecas/schemas/pecas.ts
Agregar en la tabla de agendas y fuera de agenda en SQL los campos
-    tipoAgenda (dinámica, no nominalizada)
-    domicilio del paciente
1. Se agregó el campo: tipoAgenda (dinámica, no nominalizada, programada)
2. domicilio del paciente, se actualizaron los campos:
- Provincia
- Localidad
- Barrio
- Calle
- Longitud (domicilio)
- Latitud (domicilio)
=> Se agregan y completan campos en tabla consolidado SQL

modules/obraSocial/controller/puco.ts
https://proyectos.andes.gob.ar/browse/MPI-114
1. Se verifica la conexion con la base de padrones antes de consultar por obra social para evitar solicitud pendiente.
=> MPI - Verifica conexion con PADRONES

auth/permisos.ts
Elimina permisos de MPI que ya no se utilizaban
https://proyectos.andes.gob.ar/browse/MPI-108
1. Se eliminaron permisos de MPI que ya no se utilizan
=> MPI - Elimina permisos en desuso 

modules/estadistica/pecas/controller/agenda.ts
Fix en proceso que carga consolidado de pecas. Se agrega control por si la calle tiene apostrofe.
=> fix(calle): agrega control de caracteres

jobs/perfilesJob.ts, utils/scriptsMongo/actualizarPerfiles.ts
https://proyectos.andes.gob.ar/browse/GDU-16
1. Se agrega job para actualizar los perfiles de un usuario según los permisos que tenga.
=> GDU: Script node para perfiles de usuario

modules/rup/internacion/censo.controller.ts
Corregir conteo en el censo diario al realizar pases de unidades organizativas. Se estaba visualizado un movimiento de pase en unidades organizativas que que no correspondían
1. Agrega control al calcular "pases de" y "pases a"
=> fix(Internacion): Controla la unidad organizativa al calcular pases

modules/rup/schemas/prestacion.estado.ts, modules/rup/schemas/prestacion.ts
https://proyectos.andes.gob.ar/browse/RUP-131
1. Agrega atributo `ultimoEstado` al schema de prestación.
2. En el pre save, setea automáticamente `ultimoEstado` con el último estado de la prestación. 
Script para setear automáticamente `estadoActual` a los registros de prestaciones preexistentes en el mongo 
```
var prestaciones = db.getCollection('prestaciones').find({}).toArray();
prestaciones.forEach(prestacion => {
prestacion.estadoActual = prestacion.estados[prestacion.estados.length - 1]
db.getCollection('prestaciones').update({ "_id":prestacion._id }, prestacion, { upsert:true });
});
```
=> RUP: Prestación nuevo campo ultimoEstado

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, core/mpi/schemas/constantes.ts, core/mpi/schemas/paciente.ts, modules/mobileApp/routes/accounts.ts
Este PR es requerido para el correcto funcionamiento del refactor visual de mpi en app (https://github.com/andes/app/pull/1781)
1. Se agrega endpoint que dado un email devuelve la cuenta a la que pertenece, en caso de existir
2. Se agrega 'numeroIdentificacion' en esquema de relaciones del paciente
3. Modifica constante 'identificacion' en esquema de paciente
=> MPI - Modificaciones varias para refactor visual de app

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
Cambios para realizar el fix de pacientes similares
1. 
2. 
3.
=> fix(mpi): fix pacientes similares

core/mpi/schemas/constantes.ts
Setea campo no requerido
1. 
2. 
3.
=> fix(mpi) campo no requerido

modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-76
1. Filtrado de solicitudes por fecha de creación
2. Nuevo indice por createdAt
=> TOP: filtrado de solicitudes por createdAt y nuevo indice

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-70
1. Busca por solicitudes por mas de una prestacion destino
=> feat(TOP): busca por mas de una prestacion destino

modules/prestamosCarpetas/controller/prestamosController.ts
1. Faltaba un control de fecha en las solicitudes manuales.
=> fix(prestamo): agrega control de fecha manual

modules/rup/controllers/prestacion.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.solicitud.historial.ts
https://proyectos.andes.gob.ar/browse/TOP-67
1. Nueva operacion devolver en patch dde prestaciones
2. Registro de historial de devolución de solicitud
**NOTA**: Los cambios en el historial de solicitud son provisorios para ajustarse al requerimiento a la espera de la nueva implementación del historial
=> TOP: nueva operación devolver en PATCH de prestaciones

modules/prestamosCarpetas/controller/prestamosController.ts
Fecha equivocada en los filtros de prestamos de carpeta
=> fix(prestamos):  wrong date

core/mpi/routes/paciente.ts
https://glpisalud.neuquen.gov.ar/front/ticket.form.php?id=5354
1. Se elimina la condición de que el pacientebuscado tenga documento, ya que se verifica en el getObraSocial donde se retorna un arreglo vació en el caso que esto no se cumpla. De esta forma el campo financiador del paciente queda seteado con el array vació y funciona correctamente la dación de sobreturnos.
Dentro del controller obraSocial ( /modules/obraSocial/controller/obraSocial.ts)
```
export async function getObraSocial(paciente) {
if (!paciente.documento) { return []; } //Aca hace la comprobacion
let arrayOSPuco: any = await pacientePuco(paciente.documento);
if (arrayOSPuco.length > 0) {
return arrayOSPuco;
} else {
let arrayOSSumar = await getPacienteSumar(paciente.documento);
if (arrayOSSumar.length > 0) {
return [{ …
```
=> MPI: Fix paciente sin documento

core/mpi/schemas/paciente.ts, package-lock.json, package.json
https://proyectos.andes.gob.ar/browse/MPI-193
1. Actualiza paquete fuentes-autenticas
2. Agrega fecha de fallecimiento al esquema de relaciones
=> MPI - Paciente fallecido

core/term/controller/snomed.controller.ts, core/term/controller/snomed.snowstorm.ts, core/term/routes/snomed.ts
Poder buscar por expresion Snomed y termino más eficientemente. 
[RUP-144](https://proyectos.andes.gob.ar/browse/RUP-144)
1. Aplica las API de snomed de búsqueda de concepto 
APP: https://github.com/andes/app/pull/1810
=> MITOS: Busqueda por expresion más eficiente

auth/permisos.ts
Se necesita separar permiso para crear cama y editar cama de internación.
1. Agrega permiso explicitamente para editar cama de internación.
2. 
3.
=> INTERNACION - Agrega permiso para editar cama de internacion

core/tm/controller/organizacion.ts, core/tm/routes/organizacion.ts, modules/rup/internacion/cama-estados.controller.ts, modules/rup/internacion/camas.controller.ts
Se requiere controlar que los sectores en las camas se actualicen al modificar un sector y al eliminar se debe controlar que no hayan camas siendo utilizadas en el mismo. https://proyectos.andes.gob.ar/browse/IN-155
1. Separa las rutas de sectores para la organizacion
2. Al actualizar un sector ejecuta un método para actualizar todas las camas que pertenecen al mismo
3. Antes de eliminar un sector revisa si hay alguna cama que no esté inactiva en ese sector, de ser así no se podrá eliminar el sector.
=> INTERNACION - Controlar las camas al editar/eliminar sector

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/TOP-71
1.  Registra observaciones al referir solicitud
2. 
3.
=> TOP: observaciones en referir solicitud

auth/routes/routes.ts, auth/schemas/authUsers.ts
https://proyectos.andes.gob.ar/browse/MISC-79
1. authUser ordena organizaciones en pre save
2. Query para ordenar organizaciones de registros de `authUser` preexistentes.
3. Sort en GET de organizaciones de usuario.
```
var users = db.getCollection('authUsers').find({}).toArray();
users.forEach(u => {
u.organizaciones = u.organizaciones.sort(
(a, b) => {
if (a.nombre > b.nombre) {
return 1;
}
if (a.nombre < b.nombre) {
return -1;
}
// a must be equal to b
return 0;
}
);
db.getCollection('authUsers').update({ "_id":u._id }, u, { upsert:true });   
});
```
=> GDU: ordenar organizaciones de usuario.

modules/rup/routes/prestacion.ts
Filtrar por valores null antes de generar el grafico.
1. si es para graficar se filtran los null 
2. 
3.
=> fix(RUP): filtrar los valores null de los graficos

core/mpi/schemas/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-219
1. Agrega campo 'titulo' en atributo 'nota' del esquema del paciente
=> MPI - Guarda titulo de la nota de un paciente

modules/rup/schemas/prestacion.ts
Vamos a aplicar https://github.com/andes/api/pull/1082 en dos etapas.
1. Primeros pusheamos el generador del datos
2. Actualizamos los datos viejos
3. Creamos Indices
4. Cambiamos la query.
=> feat(rup): registro inicio de prestacion

.github/labeler.yml, .github/workflows/labeler.yml, core/term/schemas/cie10.ts, core/tm/schemas/direccion.ts, modules/matriculaciones/schemas/turnoSolicitado.ts, modules/obraSocial/schemas/obraSocial.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.ts, scripts/index.ts, scripts/rup-174.ts, shared/schemas/direccion.ts
https://proyectos.andes.gob.ar/browse/RUP-174
1. Registra `inicio` de prestación.
```bash
node scripts rup-174
```
```javascript
schema.index({
createdAt: 1,
'solicitud.organizacion.id': 1,
'solicitud.organizacionOrigen.id': 1
}, { name: 'TOP-ENTRADA', partialFilterExpression: { inicio: 'top' } });
schema.index({
createdAt: 1,
'solicitud.organizacionOrigen.id': 1,
'solicitud.organizacion.id': 1,
}, { name: 'TOP-SALIDA', partialFilterExpression: { inicio: 'top' } });
``` 
**Query**: dos meses de solicitudes Castro Rendon.
Antes:
```json
{
"executionStats" : {
"executionSuccess" : true,
"nReturned" : 1249,
"executionTimeMillis" : 1270,
"totalKeysExamined" : 173663,
"totalDocsExamined" : 173663
}
}
```
Ahora:
```json
{
"executionStats" : {
"executionSuccess" : true,
"nReturned" : 1249, …
```
=> RUP: registra inicio prestación 

modules/rup/schemas/elementoRUP.ts, seed.sh
1. Filtros de requeridos según sexo del paciente (PR SanJuan). 
2. Elimina el populate de requeridos.
https://github.com/andes/app/pull/1828
=> elementos-rup: filtro por sexo y remove populate

modules/rup/routes/prestacion.ts, modules/turnos/controller/turnosController.ts
Al ejecutar prestación cargar la obra social del paciente
1. Si la prestación tiene turno asociado, buscar el turno y cargar la obra social.
Si no tiene turno asociado, usar el getObrasocial (usado en MPI) y cargar el dato.
2. 
3.
=> feat(RUP): asociar la obra social a la prestacion

modules/descargas/informe-rup/informe-header.ts, modules/descargas/model/informe.class.ts, templates/rup/informes/sass/main.scss
informe-pdf: agregar obra social de paciente.(RUP-141)
1. se agrega la obra social del paciente a informe pdf.
2. 
3.
=> fix(RUP): agregar obra Social a informe-pdf

modules/rup/controllers/prestacion.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.solicitud.historial.ts, scripts/TOP-41.ts
https://proyectos.andes.gob.ar/browse/TOP-41
1. Cada vez que se hace POST o PATCH a una prestación, si la misma proviene de TOP o planes de RUP, se registra la acción en el historia de solicitud.
2. Incluye datos de turno, prestación y observaciones al registro de historial.
3. Si no se logra identificar la acción, se registra cómo modificación genérica
Script que actualiza keys de registros y genera registros de historial retroactivamente a partir de la fecha del primer histórico de prestación regristrado.
```bash
node scripts top-41
```
=> TOP: Registrar historial de solicitud en POST y PATCH de prestaciones

scripts/TOP-41.ts
Fix en script correspondiente al refactor en el historial de solicitudes
=> fix(script top): agrega control en datos de asignacion de turno

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/RUP-177
1. Modifica el get de solicitudes para que traiga el estadoActual
=> RUP: get solicitudes trae estadoActual

.gitignore, core/mpi/controller/mpiCorrector.ts, core/mpi/mpi.log.ts
Actualizar mpi con nueva version de log de andes
1. Instala version 2.0.0 de log
2. Reemplaza logs viejos
=> Mpi - Actualiza log en mpi-corrector

modules/mobileApp/routes/categoria.ts, modules/mobileApp/schemas/categoria.ts
https://proyectos.andes.gob.ar/browse/AM-50
1. Se define el schema de Categoría
2. Se definen las rutas de categorías con ResourceBase
=> APP-MOBILE: Nuevo schema y rutas de categoría

modules/estadistica/controller/procesarAgendas.ts, modules/estadistica/controller/procesarFueraDeAgenda.ts, modules/prestamosCarpetas/controller/prestamosController.ts, modules/rup/routes/prestacion.ts, modules/turnos/controller/reportesDiariosController.ts, modules/turnos/routes/agenda.ts
https://proyectos.andes.gob.ar/browse/RUP-165
1. Cambiar en la api todas las búsquedas que se realizan por tipoPrestacion.id y reemplazarlas por conceptId
=> CORE: tipoPrestacion.id por conceptId

core/tm/schemas/direccion.ts, initialize.ts, modules/rup/index.ts, modules/rup/internacion/index.ts, modules/rup/internacion/internacion.controller.ts, modules/rup/internacion/internacion.routes.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.ts
Permitir filtrar por fecha de egreso en el listado de internación.
1. Al buscar las prestaciones relacionadas con una internacion, si vienen los filtros por fecha de ingreso y/o egreso, se filtran según corresponda.
2. 
3. 
```
createIndex({
'solicitud.organizacion.id': 1,
'solicitud.ambitoOrigen': 1,
'solicitud.tipoPrestacion.conceptId': 1,
'ejecucion.registros.valor.informeIngreso.fechaIngreso': 1,
}, { sparce: true });
```
=> PRESTACIONES - Para internacion filtra por fecha ingreso y/o egreso

core/term/routes/snomed.ts, package-lock.json, package.json
Al buscar conceptos snomed nos devuelve los que son del tipo FSN (los terminos con el semantic tag entre parentesis)
Filtrar los items que sean fsn === term. 
1. se filtran los conceptos duplicados
2. 
3.
=> fix(RUP):buscador, filtrar FSN === TERM para sacar los conceptos duplicados .

.github/workflows/release.yml, modules/rup/internacion/cama-estados.schema.ts, modules/rup/internacion/camas.controller.ts
Se necesita guardar una nota en los movimientos de las camas y que persista hasta que se realiza el egreso del paciente.
1. Agrega la nota en los estados de las camas y permite la edicion de la misma.
2. 
3.
=> INTERNACION - Agrega nota en los estados de camas

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
Se agregan controles entre pacientes similares para poder incluir comparación con temporales
Necesario para: https://github.com/andes/app/pull/1831
1. Se agregan opción de incluir temporales al querer obtener pacientes similares
=> MPI: se agregan controles entre pacientes similares para temporales

core/tm/schemas/profesion.ts
https://proyectos.andes.gob.ar/browse/MISC-87
1. Se suma a profesión el atributo 'identificadores' para hacer mapeos con bases externas
=> MICROSERVICIOS: se suma 'identificadores' a profesion

core/tm/routes/profesional.ts, modules/matriculaciones/routes/turno.ts
Refactor de función de turno solicitado. 
1. Agrega try catch en post de profesionales
2. 
3.
=> fix(profesionales): Agrega control de errores

core/mpi/controller/mpiCorrector.ts, core/mpi/jobs/nacimientosProcess.ts, core/mpi/mpi.log.ts
https://proyectos.andes.gob.ar/browse/MPI-236
1. Se modificó la carga del bebe y su relación con el tutor teniendo en cuenta la posibilidad de que el primero podría estar ya registrado como paciente temporal e incluso existir la relación con el tutor.
=> MPI - Modificaciones en importación de nacidos vivos

modules/rup/internacion/cama-estados.schema.ts, modules/rup/internacion/camas.controller.test.ts
Se requiere guardar la unidad organizativa original en un extra del estado de cama
1. Cambia el esquema de estado de cama para agregar una unidad organizativa en los extras.
2. 
3.
=> INTERNACION - Agrega Unidad Organizativa en los extras del schema del estado de cama

auth/permisos.ts, modules/gestor-usuarios/perfil.routes.ts, modules/rup/internacion/estados.routes.ts, scripts/gdu-22.ts
https://proyectos.andes.gob.ar/browse/GDU-22
1. perfiles:write visibility restricted
2. 
3. 
Script:
Script que reemplaza el permiso `*` por todos y cada uno de los permisos de gestor de usuario.
```
node scripts gdu-22
```
=> GDU: perfiles:write visibility restricted

Dockerfile, core/tm/routes/profesional.ts, core/tm/routes/profesionalImagen.ts, core/tm/schemas/firmaAdmin.ts, core/tm/schemas/firmaProf.ts, core/tm/schemas/imagenes.ts, modules/cda/controller/CDAPatient.ts, modules/cda/routes/cda.ts, modules/cda/schemas/CDAFiles.ts, modules/descargas/informe-rup/informe-firma.ts, modules/descargas/informe-rup/informe-footer.ts, modules/descargas/informe-rup/informe-header.ts, modules/registro-novedades/images/controller/imageStore.ts, modules/registro-novedades/images/schemas/imageStore.ts, modules/rup/controllers/rupStore.ts, modules/rup/schemas/rupStore.ts, package-lock.json, package.json
Actualiza la versión de mongoose-gridfs, por errores de desconexión en las operaciones con GridFs
Error: Mongoose is not connected
at new GridFSStorage (/var/www/andes/api/source/node_modules/mongoose-gridfs/lib/storage.js:32:11)
at Object.makeFs (/var/www/andes/api/source/modules/cda/schemas/CDAFiles.ts:9:28)
at Object.<anonymous> (/var/www/andes/api/source/modules/cda/controller/CDAPatient.ts:497:26)
....
Error: Mongoose is not connected
at new GridFSStorage (/var/www/andes/api/source/node_modules/mongoose-gridfs/lib/storage.js:32:11)
at module.exports (/var/www/andes/api/source/node_modules/mongoose-gridfs/lib/storage.js:335:18)
at Object.makeFs (/var/www/andes/api/source/core/tm/schemas/imagenes.ts:6:38)
1. Actualización de carga de foto y firma en profesionales
2. Actualización de …
=> chore(gridfs): update mongoose-gridfs

modules/cda/controller/CDAPatient.ts
Los CDA se generan con el _id como String.
1. Cambia los métodos store de los CDA
2. Modifica la forma de leer de los CDA Files para el caso de los xml
3.
=> fix(cda): cambia string por objectId

core/mpi/controller/paciente.ts
Utilizar busqueda multimatch con filtros en auditoria
1. Agrega un atributo 'cadenaInput' para búsqueda de texto por comparación con tokens de paciente.
=> MPI - Modifica busqueda 'search'

modules/cda/routes/cda.ts
=> fix(cda): convert to ObjectId

index.ts
=> chore(promise): recover unhandledRejection

modules/turnos/controller/agenda.ts
https://proyectos.andes.gob.ar/browse/CIT-71
1. Se agrega bloque try-catch para capturar errores en log
2. Se modifica la consulta que busca el turno para que incluya sobreturnos
=> CITAS - Fix validar prestacion de paciente con sobreturno

modules/descargas/informe-rup/utils/registro-to-html.ts, modules/turnos/citasLog.ts, package-lock.json, package.json
Soluciona el error 
> document size limit: consider an smaller bucket
1. Actualiza version de @andes/logs
=> chore(logs): fix bucket size

modules/descargas/informe-censo/censo-header.ts, modules/descargas/informe-rup/elementos-rup/adjuntar-documento.component.ts
Error al descargar el PDF de la prestación con documentos adjuntos
1. 
2. 
3.
=> fix(rup): modifica parámetro de readFile

initialize.ts, modules/centroOperativoMedico/controllers/comStore.ts, modules/centroOperativoMedico/derivaciones.routes.ts, modules/centroOperativoMedico/index.ts, modules/centroOperativoMedico/schemas/comStore.schema.ts, modules/centroOperativoMedico/schemas/derivaciones.schema.ts
https://proyectos.andes.gob.ar/browse/COM-1
https://proyectos.andes.gob.ar/browse/COM-2
1. Se agrega el esquema para las derivaciones del COM
2. Se crean las rutas correspondientes con ResouceBase
=> COM: esquema y rutas de derivaciones

modules/rup/controllers/estadisticas.ts, modules/rup/controllers/prestacion.ts, modules/rup/controllers/rup.ts, modules/rup/routes/prestacion.ts, modules/turnos/controller/agenda.ts
https://proyectos.andes.gob.ar/browse/RUP-175
1. reemplaza filtros de ultimo estado de prestaciones
Indice propuesto:
```
{
"solicitud.estadoActual.tipo" : 1
}  
```
=> RUP: reemplaza filtros de ultimo estado de prestaciones

modules/rup/internacion/cama-estados.controller.ts, modules/rup/internacion/cama-estados.schema.ts
Agregar al esquema la propiedad deletedAt y deletedBy. No tener en cuenta estos estados para el snapshots ni los movimientos (filtrarlos en la API). 
1. Agrega los atributos deletedAt y deletedBy al esquema de estados de cama.
2. Excluye aquellos estados que tienen la propiedad "deletedAt" al momento de buscar snapshots o movimientos
3.
=> INTERNACION - Agrega borrado lógico en los estados de cama

auth/permisos.ts
Se requiere un permiso particular para poder bloquear camas.
1. Agrega el permiso de internacion para bloquear camas.
2. 
3.
=> INTERNACION - Agrega permiso para bloquear camas

initialize.ts, modules/centroOperativoMedico/controllers/comStore.ts, modules/centroOperativoMedico/derivaciones.routes.ts, modules/centroOperativoMedico/index.ts, modules/centroOperativoMedico/reglasDerivacion.routes.ts, modules/centroOperativoMedico/schemas/comStore.schema.ts, modules/centroOperativoMedico/schemas/derivaciones.schema.ts, modules/centroOperativoMedico/schemas/reglasDerivacion.schema.ts
https://proyectos.andes.gob.ar/browse/COM-9
1. Esquema y rutas para reglasDerivacion
=> COM: esquema y rutas de reglasDerivacion

modules/rup/schemas/elementoRUP.ts
https://proyectos.andes.gob.ar/browse/RUP-179
1. Se agrega a elementoRUP el atributo permiteRepetidos, que por defecto devuelve false
=> RUP: posibilidad de registrar conceptos repetidos en una prestación

auth/permisos.ts
https://proyectos.andes.gob.ar/projects/BI/issues/BI-56?filter=allopenissues
1. Se agrega _type queries_ para seleccionar dentro del gestor de usuarios las _query_ a las que tendrá ingreso el usuario.
Insertar en la colección _queries_ los siguientes documentos:
[Queries.zip](https://github.com/andes/api/files/5261464/Queries.zip)
=> Permisos: Permisos por consultas en BI-Queries

modules/obraSocial/routes/obraSocial.ts
=> feat(obra-social): protege puco

auth/permisos.ts
https://proyectos.andes.gob.ar/browse/COM-16
1. Nuevo permiso para COM
=> COM: permisos

modules/centroOperativoMedico/schemas/derivaciones.schema.ts, modules/centroOperativoMedico/schemas/reglasDerivacion.schema.ts
https://proyectos.andes.gob.ar/browse/COM-18
1. Se modifica la constante ESTADOS_DERIVACION para los nuevos estados
=> COM: cambios en nombres de estado

modules/descargas/informe-rup/informe-body.ts, modules/descargas/informe-rup/informe-header.ts, templates/rup/informes/sass/main.scss
https://proyectos.andes.gob.ar/browse/RUP-133
1.Se agrega una variable para determinar el origen y poder mostrar los  parámetros si una solicitud o una prestación 
2. Se retira la fecha de solicitud del body.
3.
=> fix(RUP): Datos de la solicitud en informe-PDF .Rup 133

apm.ts, index.ts, package-lock.json, package.json
Se agrega APM server desde el código, configurable desde variables de entorno. 
1. 
2. 
3.
=> chore(apm): add support for apm server

core/tm/routes/organizacion.ts
https://proyectos.andes.gob.ar/browse/GDU-18
1. Agrega permisos unidad organizativa para internación
2. GET de unidad organizativas en Organización
3.
=> GDU: permisos unidad organizativa para internación

core/tm/conceptos-turneables.routes.ts, modules/descargas/informe-rup/informe-rup.ts, modules/descargas/routes/descargas.ts, modules/mobileApp/auth_routes/rup-adjuntos.ts, modules/rup/controllers/estadisticas.ts, modules/rup/controllers/prestacion.ts, modules/rup/controllers/rup.ts, modules/rup/controllers/solicitudes.controller.ts, modules/rup/internacion/camas.controller.test.ts, modules/rup/internacion/camas.controller.ts, modules/rup/internacion/censo.controller.test.ts, modules/rup/internacion/censo.controller.ts, modules/rup/internacion/internacion.controller.test.ts, modules/rup/internacion/internacion.controller.ts, modules/rup/prestaciones.interface.ts, modules/rup/routes/codificacion.ts, modules/rup/routes/prestacion.ts, modules/rup/schemas/prestacion.ts, modules/rup/schemas/snomed-concept.ts, modules/top/controller/reglas.ts, modules/top/routes/reglas.ts, modules/top/schemas/reglas.ts, modules/turnos/controller/agenda.ts, modules/turnos/controller/reportesDiariosController.ts, scripts/TOP-41.ts, scripts/rup-174.ts
Mueve la logica de crear solicitudes a la API.
1. Se agregan algunas interfaces y acondiciona los scemas a los nuevos registros. 
2. Se contenpla este PR https://github.com/andes/api/pull/1076
https://github.com/andes/app/pull/1942
No requiere script, pero como modifique algunos archivos me lo marca automaticamente.
=> refactor(rup): crear solicitudes en background

modules/rup/internacion/internacion.routes.ts
Corrige el acceso al historial de la internación en la capa de enfermería
1. Agrega middleware para interceptar el filtro por capas al obtener el historial
2. 
3.
=> fix(INTERNACION): Obtener historial de la internacion en la capa de enfermeria

modules/turnos/controller/agenda.ts
Pequeña mejora en el GET de diagnosticos
=> fix(reportes): optimiza mejoras consulta diagnistico

core/mpi/controller/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-260
1. Se eliminan caracteres que no sean alfanuméricos antes de realizar la búsqueda
=> MPI - Filtro de caracteres en busquedas multimatch y search

modules/mobileApp/auth_routes/autenticacionApp.ts
Corrige bug:
```
ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 5f887548241e5ff796aafe18
at ParallelSaveError.MongooseError [as constructor] (/var/www/andes/api/source/node_modules/mongoose/lib/error/mongooseError.js:14:11)
TypeError: doc.$__reset is not a function
at model.reset [as $__reset] (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:2193:6)
at $__handleSave (/var/www/andes/api/source/node_modules/mongoose/lib/model.js:338:10)
at new ParallelSaveError (/var/www/andes/api/source/node_modules/mongoose/lib/error/parallelSave.js:18:17)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Array.forEach (<anonymous>)
at model.Model.save (/var/www/andes/api/source/node_modules/mongoose/lib/model.js:444:20)
at …
```
=> fix(mobile): fix parallel save error

modules/turnos/routes/turno.ts
https://proyectos.andes.gob.ar/browse/CIT-69
1. Permite dar turno a agendas del dia configuradas **solo con turnos de gestion**
=> CITAS - Habilita turnos de gestion en agendas del dia

config.ts, core-v2/mpi/paciente/paciente.routes.ts, core-v2/mpi/paciente/paciente.schema.ts, core-v2/mpi/validacion/validacion.controller.ts, core/mpi/controller/paciente.ts, core/mpi/controller/updateValidados.ts, core/mpi/jobs/updateValidadosJob.ts, core/mpi/mpi.log.ts, core/mpi/schemas/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-137
1. Tarea que busca 500 pacientes que no hayan sido actualizados en los ultimos 2 meses y actualiza su foto, dirección legal y fecha de fallecimiento contra renaper.
2. Corrección de logs en mpi corrector job.
=> MPI - Job para actualización de datos en pacientes validados

auth/auth.class.ts, modules/rup/internacion/cama-estados.controller.ts, modules/rup/internacion/camas.routes.ts, modules/rup/internacion/internacion.controller.test.ts, modules/rup/internacion/internacion.controller.ts, modules/rup/internacion/internacion.routes.ts
Cuando se elige mal al paciente a internar, por error y se inicia la internación, no hay manera de corregir esta situación al menos que se lo egrese, pero el registro en el historial sigue quedando.
1. Agrega endpoint para poder deshacer una internacion.
2. 
3.
=> INTERNACION - Agrega metodo para deshacer internaciones

modules/turnos/controller/turnosController.ts
https://proyectos.andes.gob.ar/browse/RUP-201
1. Se fuerza error borrando agenda cuando al turno se le inicio la prestación. 
2. desestructurar un turno si es null o indefinido nos devuelve un error.
3. si no existe el turno se retorna {} para descartar error.
=> fix(RUP):error en prestaciones al desestructurar turno

modules/turnos/controller/diagnosticosC2Controller.ts
Agrega filtros de búsqueda a la colección codificaciones.
=> fix(codificaciones): cambia de posición los filtros de busqueda

core/mpi/controller/updateFoto.ts, core/mpi/jobs/updateFotoJob.ts, core/mpi/schemas/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-259
1. Inserta atributo fotoId a pacientes que posean foto.
2. Actualiza foto de pacientes reemplazando el string de la imagen por el id de la foto del paciente relacionado.
Ejecutar job node jobs/manual.js core/mpi/jobs/updateFotoJob.js
**NOTA**: Relacionado con PR https://github.com/andes/api/pull/1143
=> MPI - script para actualizar foto/fotoId de pacientes

modules/obraSocial/obraSocialLog.ts, modules/obraSocial/routes/obraSocial.ts, modules/obraSocial/schemas/obraSocial.ts, modules/obraSocial/schemas/puco.ts
Se loguea codigo de la obra social que viene de puco, no existente en la colección de obras sociales.
https://proyectos.andes.gob.ar/browse/MISC-100
1. Se handlea el error de obras sociales que se traen de Puco y que no están en la colección de obra social, y se loggea el código para identificar los faltantes.
=> ObraSocial: se loguea codigoPuco de obra social no existente

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/RUP-124
1. Nueva operación en ruta de prestaciones que desasocia una prestación de un turno, y la pone en estado 'anulada'
=> RUP - Invalidar prestación

core/log/routes/log.ts, core/log/system.log.ts, modules/turnos/citasLog.ts, package-lock.json, package.json
Logguear los errores de la consola de angular.
Se busca tener una respuesta rápida a los errores por consola del navegador. 
Hay que borrar los indices:
```
use andesLogs;
db.getCollection('citas').dropIndex('type_1_start_1_end_1_level_1_bucketNumber_1');
db.getCollection('mpi').dropIndex('type_1_start_1_end_1_level_1_bucketNumber_1');
db.getCollection('obraSocial').dropIndex('type_1_start_1_end_1_level_1_bucketNumber_1');
```
Depsués el sistema los vuelve a regenerar.
=> CORE: angular handler error

package-lock.json, package.json
Actualiza la version del logger, estaba tomando mal el campo expiredAt.
=> chore(logs): logs 2.2.2

core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts, core/mpi/schemas/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-258
1. Nuevo esquema para la foto de pacientes
2. Modifica get de paciente por id para que cargue el contenido de la foto. Solo el id en caso de existir.
=> MPI - nuevo esquema para foto de paciente

modules/rup/internacion/censo.controller.ts
En los censos existían dos errores en situaciones extremas. El primer caso fallaba por no poder encontrar una internación dentro de los movimientos y el segundo caso, cuando se crea una cama y en el mismo momento se realiza la internación de un paciente, el censo falla por no encontrar la cama.
1. Arregla los errores que producen esas situaciones en los censos.
2. 
3.
=> INTERNACION - Corrige dos errores en los censos

modules/rup/internacion/camas.routes.ts
https://proyectos.andes.gob.ar/browse/IN-219
Visualizar un item de la sala común como disponible para que se puede buscar y hacer click en el +.
=> feat(mapa-camas): sala comun debe aparecer como disponible

modules/matriculaciones/schemas/turnoSolicitado.ts
Incidente reportado: error al asignar un sobreturno a profesionales con formación de posgrado o con nota asignada
1. Se actualizan los tipos de datos en el esquema de turnos solicitado ya que están replicados del profesional
2. 
3.
=> fix(turnoSolcitado): actualiza tipo de datos en esquema

jobs/especialidadExport.ts, jobs/jobEspecialidadExport.ts
https://proyectos.andes.gob.ar/browse/BI-32
1. Se agrega job para exportar a sql los profesionales con su especialidad
=> JOBS: exportar especialidades

core-v2/mpi/paciente/paciente.routes.ts, modules/rup/controllers/estadisticas.ts, modules/rup/routes/hudsExtras.ts, modules/rup/routes/prestacion.ts, modules/vacunas/controller/VacunaController.ts, modules/vacunas/routes/vacunas.ts, utils/utils.ts
https://proyectos.andes.gob.ar/browse/MPI-229
1. migración recursos paciente a core v2
2. 
3.
=> RUP: migración recursos paciente a core v2

core-v2/mpi/paciente/paciente.routes.ts, modules/cda/controller/CDAPatient.ts, modules/cda/routes/cda.ts
https://proyectos.andes.gob.ar/browse/MPI-227
1. migracion de CDAs a core_v2 
2. 
3.
=> MPI: migracion de CDAs a core_v2 

config.private.ts.example, core-v2/mpi/paciente/paciente.interface.ts, core-v2/mpi/paciente/paciente.routes.ts, core-v2/mpi/paciente/paciente.schema.ts, core/mpi/jobs/nacimientosProcess.ts, jobs/importarNacimientosJob.ts
Se agrega en el job de nacidos actualización de bebés sin dni y obtener modificaciones por fecha
https://proyectos.andes.gob.ar/browse/MPI-251
Se agrega en el job de nacidos:
1.  actualización de bebés sin dni que contendan el número de certificado Renaper obtenido de la importación de los nacidos,
2.  una importación de todos los pacientes que fueron modificados en la fecha actual y se los actualiza de acuerdo al dato de cetificado renaper.
=> MPI:Job para actualizar bebes sin dni y obtener modificaciones

modules/rup/internacion/index.ts, modules/rup/internacion/internacion.controller.ts, modules/rup/internacion/resumen/internacion-resumen.hook.ts, modules/rup/internacion/resumen/internacion-resumen.schema.ts, modules/rup/schemas/prestacion.ts
[IN-176](https://proyectos.andes.gob.ar/browse/IN-176)
Enlace entre el ID de internación y las prestaciones creadas.
También empiezo a crear una colleccion con el resumen de la internación. 
https://github.com/andes/app/pull/2010
=> feat(mapa-camas): trackId en prestaciones

modules/centroOperativoMedico/schemas/derivaciones.schema.ts
Guardar obra social del paciente en derivación
1. Cambio en schema de derivaciones para sumar obra social
=> COM: guardar obra social del paciente

modules/centroOperativoMedico/derivaciones.routes.ts, modules/centroOperativoMedico/schemas/derivaciones.schema.ts
https://proyectos.andes.gob.ar/browse/COM-29
1.Indice para derivaciones
=> COM: indices y corrección en routes

modules/centroOperativoMedico/schemas/derivaciones.schema.ts
https://proyectos.andes.gob.ar/browse/COM-24
1. Se suma el flag eliminado a HistorialDerivacionSchema
=> COM: eliminado en historial derivaciones

modules/rup/prestaciones.interface.ts, modules/rup/routes/codificacion.ts, modules/rup/schemas/prestacion.ts, scripts/MISC-85.ts
https://proyectos.andes.gob.ar/browse/MISC-85
**DEPENDE DE:**
https://proyectos.andes.gob.ar/browse/MISC-83
https://proyectos.andes.gob.ar/browse/MISC-84
1. Se remueve `estadoFacturacion` del schema de Codificación
2. Se remueve PATCH de `/codificacion/estadoFacturacion` del routes de codificaciones
3. Se agrega operación `estadoFacturacion` a PATCH de prestaciones.
```
var codificaciones = db.getCollection('codificacion').find({'estadoFacturacion':{ $exists: true } }).toArray()
codificaciones.forEach( c => {
var prestacion = db.getCollection('prestaciones').find({'_id': c.idPrestacion}).toArray()[0];
if (prestacion) {
prestacion.estadoFacturacion = c.estadoFacturacion;
delete c.estadoFacturacion;
db.getCollection('prestaciones').update({ "_id":prestacion._id }, prestacion, { upsert:true …
```
=> RUP: mueve estadoFacturacion de codificación a prestación

scripts/deleteFotoId.ts
https://proyectos.andes.gob.ar/browse/MPI-281
1. Borra campo fotoId de los pacientes que lo posean pero no tengan foto
node scripts deleteFotoId
=> MPI - Script para pacientes con fotoId pero sin foto

modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/RUP-193
1. Verifica que no exista una prestación asociada al turno. De ser asi devuelve error.
=> RUP - Inicio de prestación para turno con múltiples profesionales

modules/rup/routes/prestacion.ts
Bugfix al romper validacion, no deber hacer los controles.
=> fix(rup): romper validacion check

modules/webhook/webhook.routes.ts
Agrega formato a la fecha de nacimiento
1. 
2. 
3.
=> fix(webhook): fix fecha de nacimiento

core/log/schemas/logPaciente.ts, core/mpi/controller/paciente.ts, utils/loggerPaciente.ts
https://proyectos.andes.gob.ar/browse/MPI-279
1. Se crea nuevo evento donde se verifica si hubo cambio en el campo 'reportarError' de paciente
2. Se traslada actualización de georreferencia a este nuevo evento
=> MPI - Logueo de reporte de errores en datos de pacientes

modules/descargas/informe-rup/elementos-rup/index.ts, modules/descargas/informe-rup/elementos-rup/receta-medica.component.ts
Impresión de la receta médica
1. Se suma el template receta-medica para exportar a pdf
=> RUP: impresión receta médica

core-v2/mpi/validacion/validacion.controller.ts, core/mpi/controller/paciente.ts, core/mpi/jobs/nacimientosProcess.ts
Agrega el campo fotoId en validación de paciente, cuando existe foto
1. 
2. 
3.
=> refactor(mpi): agrega fotoId en validación

modules/rup/controllers/prestacion.ts, modules/turnos/controller/historialCitasController/historialCitasController.ts, modules/turnos/routes/turno.ts
https://proyectos.andes.gob.ar/browse/CIT-76
1. incluye fuera de agendas a historial de citas
=> CIT: incluye fuera de agendas a historial de citas

modules/centroOperativoMedico/derivaciones.routes.ts, modules/centroOperativoMedico/schemas/derivaciones.schema.ts, modules/centroOperativoMedico/schemas/reglasDerivacion.schema.ts, package-lock.json, package.json
https://proyectos.andes.gob.ar/browse/COM-25
1. Se actualiza paquete api-tool
2. Se suma un atributo gravedad a las derivaciones para que se indique el estado del paciente
=> COM: sumar gravedad al habilitar una derivación desde el COM

modules/descargas/com/derivacion-body.ts, modules/descargas/com/derivacion-firma.ts, modules/descargas/com/derivacion-header.ts, modules/descargas/com/derivacion.ts, modules/descargas/routes/descargas.ts, templates/com/comprobante.scss
https://proyectos.andes.gob.ar/browse/COM-31
1. Se suma a descargar el comprobante de derivaciones
2. 
3.
=> COM: impresión de comprobante

core/mpi/controller/updateFoto.ts, scripts/deleteFoto.ts
https://proyectos.andes.gob.ar/browse/MPI-282
1. Script que elimina el atributo 'foto' de las relaciones de los pacientes, en caso de exisitir
=> MPI - Script para eliminar foto de relaciones del paciente

package-lock.json, package.json
Actualización de andes/core 
1.  actualización de @andes/core a versión 1.8.0
=> CORE: actualización de andes/core

utils/roboSender/roboSender.ts
No se estaban marcando como success.
=> fix(robosender): no se estan marcando como succes

modules/obraSocial/controller/obraSocial.ts, modules/obraSocial/controller/puco.ts, modules/obraSocial/routes/obraSocial.ts, modules/obraSocial/schemas/obraSocial.ts, modules/obraSocial/schemas/puco.ts
https://proyectos.andes.gob.ar/browse/MISC-104
Se crea un nuevo servicio a Sisa para consultar la obra social de un paciente, según los datos que obtienen de Puco 
1. Se unifican consultas a la colección de puco.
2. Se agrega servicio para obtener datos de Puco con Sisa.
3. Se inserta una nueva obra social, para aquellas obras sociales obtenidas del servicio a Puco que no estén en la colección de obraSocial.
=> Obras Sociales: nuevo servicio a Puco para consultar la obra social de un paciente

modules/centroOperativoMedico/derivaciones.routes.ts, modules/centroOperativoMedico/schemas/derivaciones.schema.ts
https://proyectos.andes.gob.ar/browse/COM-38
1. Cambio de gravedad por prioridad
=> COM: cambio de palabra gravedad por prioridad

modules/descargas/informe-censo/censo-mensual-header.ts
Ajuste del logo del censo mensual.
=> fix(mapa-camas): informe censo logo

core/mpi/controller/paciente.ts
1. verifica que exista 'image/jpg' en el string de la foto
=> MPI - Verifica que la foto traida de renaper sea una imagen

modules/centroOperativoMedico/derivaciones.routes.ts
https://proyectos.andes.gob.ar/browse/COM-40
1. Permitir buscar derivaciones por id del paciente
2. Permitir buscar derivaciones por id del profesional
=> COM: permitir busqueda por id de paciente/profesional

modules/rup/schemas/elementoRUP.ts
Agregas reglas dinámicas a los elementos RUP.
https://github.com/andes/app/pull/2061
=> feat(elementos-rup): add rules

core-v2/mpi/index.ts, core-v2/mpi/paciente/paciente.controller.ts, core-v2/mpi/paciente/paciente.events.ts, core-v2/mpi/paciente/paciente.interface.ts, core-v2/mpi/paciente/paciente.routes.ts
https://proyectos.andes.gob.ar/browse/MPI-289
1. Agrega funcion de georeferencia en core-v2/mpi
2. Agrega archivo para webhoocks
=> MPI - Actualización de georeferencia y eventos

core-v2/mpi/paciente/paciente.interface.ts, core-v2/mpi/validacion/validacion.routes.ts, modules/mobileApp/routes/paciente.ts, modules/mobileApp/routes/turnos.ts, modules/mobileApp/routes/vacunas.ts
https://proyectos.andes.gob.ar/browse/MPI-288
https://proyectos.andes.gob.ar/browse/MPI-292
1. Reemplaza controller viejo de pacientes en api de mobileApp
=> MPI - Actualiza controller de paciente en rutas mobile

core/mpi/controller/paciente.ts, package-lock.json, package.json
Agrega servicio de Renaper por Federador
1. Actualiza fuentes-autenticas
2. 
3.
=> feat(mpi): servicio de renaper por federador

core-v2/mpi/paciente/paciente.routes.ts, modules/prestamosCarpetas/controller/prestamosController.ts, modules/prestamosCarpetas/schemas/solicitudCarpetaManual.ts, modules/turnos/controller/estadisticas.ts
https://proyectos.andes.gob.ar/browse/MPI-300
1. Reemplaza controller viejo de pacientes
=> MPI - Actualiza controller de paciente en prestamos de carpetas

core-v2/mpi/paciente/paciente.interface.ts, core/mpi/controller/mpiCorrector.ts, core/mpi/controller/regexChecker.ts, core/mpi/controller/updateFuzzy.ts, scripts/deleteFotoId.ts
https://proyectos.andes.gob.ar/browse/MPI-299
1. Reemplaza uso de controller viejo de paciente
=> MPI - Actualiza controller de paciente en jobs

core-v2/mpi/validacion/validacion.error.ts, modules/mobileApp/routes/paciente.ts
https://proyectos.andes.gob.ar/browse/MPI-302
1. Modifica estado de respuesta cuando no se encuentra un ciudadano en FA
Actualizacion en Testing de Integración:  https://github.com/andes/andes-test-integracion/pull/304
=> MPI - Modifica response en validación por FA

modules/descargas/informe-rup/informe-body.ts
Corregir los parametros para obtener los datos del profesional y cargar la firma en los informes PDF de las prestaciones y registros
=> fix(RUP): Corrige los parámetros para obtener la firma

modules/centroOperativoMedico/derivaciones.routes.ts, packages/drive/adapters/SeaweedAdapter.ts, packages/drive/drive.ts, packages/drive/file-descriptor/controller.ts, packages/drive/file-descriptor/schemas.ts, packages/drive/package.json
https://proyectos.andes.gob.ar/browse/COM-45
https://proyectos.andes.gob.ar/browse/COM-42
1. Poder eliminar archivos de andesDrive
2. Guardar archivos del COM en andesDrive
3. Leer archivos del COM de andesDrive
=> COM: refactor de adjuntar archivos

core/log/schemas/logPaciente.ts, modules/turnos/routes/agenda.ts, utils/loggerPaciente.ts
https://proyectos.andes.gob.ar/browse/CIT-67
https://proyectos.andes.gob.ar/browse/TOP-100
1.  Registra motivo liberación turno
=> CIT: registra motivo liberación turno

modules/facturacionAutomatica/controller/facturacionAutomaticaController.ts
hotfix descarga arancelamiento
https://glpi.andes.gob.ar/front/ticket.form.php?id=429
1. hotfix descarga arancelamiento
2. 
3.
=> CIT: hotfix descarga arancelamiento

modules/huds/export-huds/exportHuds.controller.ts, modules/huds/export-huds/exportHuds.routes.ts, modules/huds/export-huds/exportHuds.schema.ts, utils/roboSender/index.ts
https://proyectos.andes.gob.ar/browse/BI-65
1. Se modifica `exportHudsController` para que acepte un `array` de `ObjectId` de las prestaciones seleccionadas para exportar.
2. Se agrega al `exportHudsSchemma` el `array` de prestaciones.
=> TURNOS-PRESTACIONES: Descarga de prestaciones desde el buscador de turnos y prestaciones

modules/centroOperativoMedico/schemas/derivaciones.schema.ts
Se agrega la prioridad especial a derivaciones
1. Se suma prioridad especial a schema de derivaciones
=> COM: nuevo valor de prioridad especial a schema de derivaciones

auth/permisos.ts
Agrega permisos en monitoreo para rupers
=> feat(monitoreo): agrega permiso rupers

core-v2/mpi/validacion/validacion.routes.ts, package-lock.json, package.json
https://proyectos.andes.gob.ar/browse/MONIT-37
1. Se crean rutas para verificacion de estado de servicios renaper y sisa
=> MPI - rutas para verificar estado de FA

modules/facturacionAutomatica/routes/configFacturacionAutomatica.ts
Se reestablece ruta para obtener el mapeo de la prestación y el nomenclador de recupero
1. 
2. 
3.
=> fix(arancelamiento): reestablece ruta

config.private.ts.example, modules/centroOperativoMedico/derivaciones.routes.ts, package-lock.json, packages/drive/drive.ts, packages/drive/package.json, scripts/COM-46.ts, scripts/migrarArchivosCom.ts
https://proyectos.andes.gob.ar/browse/COM-46
1. Script para migrar archivos viejos del COM a AndesDrive
=> COM: migrar archivos viejos al drive

modules/descargas/arancelamiento/arancelamiento-body.ts, modules/descargas/arancelamiento/arancelamiento.ts
https://glpi.andes.gob.ar/front/ticket.form.php?id=446
1. En caso de no existir ninguna firma, muestra unicamente el nombre del profesional
2. 
3.
=> CIT: fix firma arancelamiento

modules/gestor-usuarios/usuarios.routes.ts
https://proyectos.andes.gob.ar/browse/GDU-27
1. Envía mensaje de error si no hay respuesta de LDAP
=> GDU: mejorar feedback al usuario al cargar un usuario

modules/estadistica/controller/procesarAgendas.ts, modules/estadistica/controller/procesarFueraDeAgenda.ts, modules/estadistica/routes/turnos_prestaciones.ts
https://proyectos.andes.gob.ar/browse/MISC-115
1. Se agrega el filtro ambito en la query que devuelve las prestaciones en el buscador de turnos y prestaciones
2. Se modifica el routes de turnos y prestaciones, para el caso en el que se pide un ámbito no devuelva los turnos, sino solo las prestaciones.
=>  TURNOS-PRESTACIONES: Agregar virtual scroll y filtro ambito

initialize.ts, modules/vacunas/index.ts, modules/vacunas/nomivacCategoria.route.ts, modules/vacunas/nomivacCondicion.route.ts, modules/vacunas/nomivacDosis.route.ts, modules/vacunas/nomivacEsquema.route.ts, modules/vacunas/nomivacLaboratorio.route.ts, modules/vacunas/nomivacVacuna.route.ts, modules/vacunas/schemas/nomivacCategoria.schema.ts, modules/vacunas/schemas/nomivacCondicion.schema.ts, modules/vacunas/schemas/nomivacDosis.schema.ts, modules/vacunas/schemas/nomivacEsquema.schema.ts, modules/vacunas/schemas/nomivacLaboratorios.schema.ts, modules/vacunas/schemas/nomivacVacuna.schema.ts, modules/vacunas/schemas/vacunasApi.ts
Crear las rutas para consumir datos para el registro de la vacuna
https://proyectos.andes.gob.ar/browse/RUP-230
1. Se crean rutas para el acceso a datos necesarios para el registro de una vacuna. Los datos provienen de nomivac
2. 
3. 
Cargar en elementosRUP el siguiente documento:
```
{
"componente" : "VacunasComponent",
"tipo" : "atomo",
"style" : {
"columnas" : 12.0,
"cssClass" : null
},
"params" : {
"required" : true
},
"conceptos" : [
{
"conceptId" : "840534001",
"term" : "vacunación contra COVID-19",
"fsn" : "vacunación contra coronavirus del síndrome respiratorio agudo severo 2 (procedimiento)",
"semanticTag" : "procedimiento"
}
],
"requeridos" : [],
"frecuentes" : []
}
```
=> feat(RUP): rutas de datos paramétricos  para registros de vacuna

core/tm/routes/profesional.ts
https://proyectos.andes.gob.ar/browse/MAT-23
1. Corrige filtros de guía de profesional
=> fix(MAT): corrige filtros guia paciente

modules/rup/routes/rupStore.ts
https://proyectos.andes.gob.ar/browse/TOP-102
1. Se modifica el get de rupStore para podes traer los archivos que se encuentren en AndesDrive
=> TOP: subir archivos a andesDrive

modules/descargas/routes/descargas.ts
https://proyectos.andes.gob.ar/browse/RUP-152
1. Si se reciben adjuntos al llamar a send/pdf , se suman como attachments al correo
=> RUP: Adjuntar archivos adjuntos al email

jobs/exportCovid19.ts
=> fix(nomivac): modificamos el campo que orden

core-v2/mpi/paciente/paciente.interface.ts, core-v2/mpi/paciente/paciente.routes.ts, core/mpi/controller/paciente.ts, core/mpi/routes/paciente.ts
Se agrega el número de trámite en el paciente que se obtiene de la validación del paciente o del scan del dni
https://proyectos.andes.gob.ar/browse/MPI-310
Se agrega el numero de tramite en el paciente el número de trámite se obtiene de
1.  la validacion del paciente 
2. o del scan del dni
3. Se agrega el campo de "identificadores" en validacion por Sisa rutas "viejas"
=> MPI: Se agrega el numero de tramite en el paciente

jobs/exportCovid19.ts
Agregar dato de idSniAplicacion en el log de informacion exportada de vacunas
1. Se obtiene dato de la respuesta de nomivac y se impacta en el log
=> feat(Job Vacunas): Agrega idSniAplicacion 

modules/rup/schemas/plantillasRUP.ts
Permite cargar plantillas desde una molecula
1. 
2. 
3.
=> feat(rup): plantillas moleculas

core/tm/controller/profesional.ts, core/tm/routes/profesional.ts, core/tm/schemas/profesional.ts
https://proyectos.andes.gob.ar/browse/MAT-32
1. Incluye rutas para POST y GET de títulos de formación de profesional.
2. 
3.
=> TM: rutas adjuntar titulo profesional

modules/centroOperativoMedico/schemas/derivaciones.schema.ts
https://proyectos.andes.gob.ar/browse/COM-49
1. Se agrega la prioridad a de DerivacionHistorialSchema
=> COM: sumar prioridad a DerivacionHistorialSchema

modules/centroOperativoMedico/derivaciones.routes.ts
https://proyectos.andes.gob.ar/browse/COM-50
1. Nueva ruta para actualizar historial
=> COM: nueva ruta para actualizar historial

core-v2/mpi/validacion/validacion.controller.ts, core-v2/mpi/validacion/validacion.routes.ts, core/mpi/controller/updateValidados.ts
https://proyectos.andes.gob.ar/browse/MPI-317
1- Actualiza validación de pacientes a renaperV3
2- Agrega actualización de georeferencia
https://github.com/andes/andes-test-integracion/pull/313
=> MPI - Actualiza job 'updateValidados'

config.private.ts.example, jobs/exportCovid19.ts
- Agregamos las credenciales en el header.
=> feat(vacuna): Agregamos las credenciales en el header en lugar de enviarlas en el body

auth/auth.controller.ts, auth/ldap.controller.ts, auth/routes/routes.ts, auth/schemas/authUsers.ts, config.private.ts.example, initialize.ts, templates/emails/email-informe.html, templates/emails/layout.html, templates/emails/recover-password.html, utils/roboSender/sendEmail.ts
- Setea un token de validación para los usuarios que sean externos al sistema oneLogin.
- Realiza el reset de la contraseña para los usuario externos al sistema oneLogin.
- Realiza modificaciones en authUsers, de manera de poder continuar utilizando este esquema para los permisos de usuario.
- Agrega template para la notificación realizada por robosender vía email.
Permitir el login y actualización de password de más de 200 usuarios externos para el proceso de vacunación.
=> feat(login): Permite realizar el cambio de contraseña para usuarios externos a oneLogin

core/tm/routes/organizacion.ts
https://proyectos.andes.gob.ar/browse/MISC-109
1. Arregla la sincronización de organizaciones  con SISA
2. 
3.
=> fix(TM): fix error en sincro organizacion con sisa

core-v2/mpi/index.ts, core-v2/mpi/paciente/index.ts, core-v2/mpi/paciente/paciente.schema.ts, core/mpi/controller/paciente.ts, core/mpi/schemas/paciente.ts, modules/mobileApp/routes/turnos.ts, scripts/updateToken.ts
https://proyectos.andes.gob.ar/browse/MPI-294
1. Elimina tildes, 'ñ's y dieresis de cadenas para búsqueda multimatch
2. Script para actualizar tokens de pacientes en DB
=> MPI - Tokens de paciente para búsqueda
