andes/api

auth/permisos.ts
modules/rup/index.ts
modules/rup/internacion/cama-estados.controller.ts
modules/rup/internacion/camas.controller.ts
modules/rup/internacion/camas.routes.ts
modules/rup/internacion/estados.schema.ts
modules/rup/internacion/index.ts
modules/rup/internacion/resumen/internacion-resumen.hook.ts
modules/rup/internacion/resumen/internacion-resumen.routes.ts
modules/rup/internacion/resumen/internacion-resumen.schema.ts
modules/rup/internacion/sala-comun/sala-comun-snapshot.ts
modules/rup/internacion/sala-comun/sala-comun.controller.ts
modules/rup/routes/prestacion.ts
modules/turnero/routes/configuracionPantalla.ts

Colleccion resumen de internacion y configuraciones de schemas

Guardia: primeros pasos

---

core-v2/mpi/validacion/validacion.controller.ts
core/mpi/controller/updateValidados.ts

Se agregan varios controles
1. Se agrega try-catch en validar para handlear error de cuando el servicio no está disponible
2. Se agregan controles en job updateValidados
3.

MPI: se agregan controles varios

---

config.private.ts.example
core/log/schemas/logExportaInformacion.ts
jobs/exportNexosSisa.ts
jobs/jobExportNexosSisa.ts

Exportar casos covid registrados en Andes como confirmados por nexos o confirmados por test rapido de antigenos

feat(JOB): Exportación a sisa de casos covid

---

modules/rup/internacion/camas.routes.ts

Al filtrar por ID de Cama se estaba buscando en la salas tambien.

fix(mapa-camas): historial camas trae salas

---

jobs/exportCovid19.ts

Se modifica la consulta para evitar que el proceso omita registros para los casos que crean la solicitud y se tarde en registrar la prestación.

fix(exportCovid): se modifica la fecha para que toma la de la creció del registro y no de la solicitud para evitar gaps

---

modules/mobileApp/auth_routes/noticias.ts

https://proyectos.andes.gob.ar/browse/AM-92
1. Se suman parámetros count y max_id a la ruta _modules/mobileApp/noticias/:name_

AM: se suma max_id y count a parametros para traer tweets

---

modules/rup/internacion/estados.schema.ts
modules/rup/internacion/resumen/internacion-resumen.routes.ts
modules/rup/internacion/resumen/internacion-resumen.schema.ts

Se agrega a la capa estadística, un listado de movimientos de la capa medica.

mapa-camas: historial movimientos capa medica

---

core-v2/mpi/paciente/paciente.controller.ts
core-v2/mpi/paciente/paciente.events.ts
core-v2/mpi/paciente/paciente.routes.ts
core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-308
1. Actualiza funciones y rutas

MPI - Actualiza funciones y rutas

---

core-v2/mpi/paciente/paciente.routes.ts
core-v2/mpi/paciente/paciente.schema.ts

Cambia permisos al get de paciente
Quita foto del esquema de relaciones
1. 
2. 
3.

fix(mpi): cambia permisos de get

---

jobs/manual.ts
modules/cda/controller/CDAPatient.ts
modules/cda/routes/cda.ts
modules/huds/export-huds/exportHuds.controller.ts

https://proyectos.andes.gob.ar/browse/PRIV-62
1. Se realiza un refactor en el modulo cda pasando al controller la lógica que se encontraba en el archivo route.
2. Se agrega a exportHuds la búsqueda de los registros de un paciente en CDAFiles.

PRIV-62:  CDA al exportar HUDS

---

core/tm/routes/profesion.ts

https://proyectos.andes.gob.ar/browse/MAT-42
1. Incluye filtro por código en búsqueda de profesión
2. 
3.

TM: busca profesión por código

---

modules/webhook/webhook.routes.ts

Agrega control de contacto para notificación de pacientes
1. 
2. 
3.

fix(mpi): control de contacto en notificación

---

jobs/exportNexosSisa.ts
jobs/jobExportNexosSisa.ts

Cambia la frecuencia para exportar los casos por nexo de Sisa
1. 
2. 
3.

fix(job): cambia frecuencia

---

modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/CIT-104
1. Se eliminaron funciones en desuso
2. Se reemplazó $set por $push mas $set en caso necesario.
3. Se reemplazo retorno de endpoint agenda por turno dado

CITAS - Fix solapamiento de turnos en agendas dinámicas

---

modules/vacunas/index.ts
modules/vacunas/nomivacLote.route.ts
modules/vacunas/schemas/nomivacLote.schema.ts

Se agrega la api con resource base de lotes de vacunas.
https://proyectos.andes.gob.ar/browse/MISC-118
- [] No
Se agregó a la BD los siguientes lotes de vacunas:
Collection: nomivacLotes
[
{
"codigo" : "486081120R",
"descripcion" : "Pertenece a primera dosis",
"habilitado" : true,
"vacuna" : {
"_id" : ObjectId("5fd90f2fd4ef41746d79fe06"),
"codigo" : 198.0,
"nombre" : "Sputnik V COVID19 Instituto Gamaleya"
}
},
{
"codigo" : "ZB01720",
"descripcion" : "Pertenece a segunda dosis",
"habilitado" : true,
"vacuna" : {
"_id" : ObjectId("5fd90f2fd4ef41746d79fe06"),
"codigo" : 198.0,
"nombre" : "Sputnik V COVID19 Instituto Gamaleya"
}
},
{
"codigo" : "ZA00121",
"descripcion" : "Pertenece a primera dosis",
"habilitado" : true,
"vacuna" : {
"_id" : ObjectId("5fd90f2fd4ef41746d79fe06"),
"codigo" : …

feat(vacunas): Agregamos lote de vacunas

---

core/tm/routes/organizacion.ts
core/tm/schemas/organizacion.ts
initialize.ts
modules/centroOperativoMedico/derivaciones.routes.ts
modules/centroOperativoMedico/index.ts
modules/centroOperativoMedico/schemas/derivaciones.schema.ts
modules/centroOperativoMedico/schemas/tipoTraslado.schema.ts
modules/centroOperativoMedico/tipoTraslado.routes.ts
modules/descargas/com/derivacion-body.ts

https://proyectos.andes.gob.ar/browse/COM-53
https://proyectos.andes.gob.ar/browse/COM-57
1. Agrega schema y routes de `tipoTraslado`
2. Incluye filtro de tipoTraslado al search de derivaciones
3. Incluye flag `trasladosEspeciales` a schema de organizacion
4. Incluye datos de traslado en comprobante
1.Crear colección `tipoTraslado` e insertar registros:
```
{
"_id" : ObjectId("6011a1d85d7b650c40bc12a4"),
"nombre" : "VUELO SANITARIO"
},
{
"_id" : ObjectId("601ac9d1a9431a5262d582c5"),
"nombre" : "AMBULANCIA EXTERNA"
}
```
1.Agregar atributo `trasladosEspeciales` con valor de array conteniendo los registros de tipo traslado al registro de organización correspondiente al SIEN
o

feat(COM): incluye traslados especiales

---

modules/rup/internacion/estados.schema.ts

Se necesita poder configurar los pases de unidad organizativa en el mapa de camas.
1. Agrega la configuracion de los pases de unidad organizativa para las maquinas de estado.
2. 
3.

INTERNACION - Agrega configPases al schema de la maquina de estados

---

modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-106
1. Se elimina control de profesional origen al crear solicitud

TOP: permitir cargar solicitudes sin profesional origen

---

core-v2/mpi/paciente/paciente.routes.ts
core-v2/mpi/validacion/validacion.controller.ts
core/log/schemas/logPaciente.ts
modules/webhook/webhook.routes.ts

Agrega control de verificación de foto de Renaper. Índice en logPaciente y control de contactos en la ruta de notificación de contactos
1. 
2. 
3.

fix(mpi): control de fotos

---

modules/descargas/informe-rup/elementos-rup/index.ts
modules/descargas/informe-rup/elementos-rup/vacuna.component.ts

https://proyectos.andes.gob.ar/browse/RUP-239
1. se implementa vacunasComponent  para generar su informe-pdf.
2. 
3.

Refactor(RUP): informe-pdf se agrega implementación de VacunasComponent

---

modules/descargas/informe-rup/elementos-rup/checklist.component.ts
modules/descargas/informe-rup/elementos-rup/index.ts

…nent
https://proyectos.andes.gob.ar/browse/RUP-238
1. se implementa CheckListComponent para  informe-pdf
2. 
3.

Refactor(RUP): informe-pdf se agrega implementación de CheckListComponent

---

auth/permisos.ts
scripts/cit-103.ts

https://proyectos.andes.gob.ar/browse/CIT-103
1. se agrega permiso soloLectura en punto de inicio y gestor de agendas
2. 
3. 
Cambiar los permisos del modulo de citas de `turnos:planificarAgenda:?` a `turnos:agenda:?`

feat(CITAS): se agrega permiso soloLectura

---

core/tm/interfaces/IOrganizacion.ts
modules/centroOperativoMedico/derivaciones.routes.ts

https://proyectos.andes.gob.ar/browse/COM-51
https://proyectos.andes.gob.ar/browse/COM-55
1. Verifica en el POST de derivaciones, que la organización que cambia de estado es la misma que la organización destino
2. 
3.

feat(COM): verifica organizacion destino en POST derivaciones

---

modules/descargas/informe-rup/informe-footer.ts

https://proyectos.andes.gob.ar/browse/RUP-241

feat(rup): nota al pie configurable

---

modules/mobileApp/auth_routes/rup-adjuntos.ts
package-lock.json
package.json
packages/drive/drive.ts

https://proyectos.andes.gob.ar/browse/AM-122
1. Se actualiza la subida de archivos para que los almacene en el servidor de archivos.

AM: Actualizar subida de archivos para almacenar en AndesDrive

---

auth/permisos.ts
core-v2/mpi/paciente/paciente.schema.ts
core/mpi/schemas/paciente.ts

https://proyectos.andes.gob.ar/browse/MPI-312
1. se agrega pestaña para visualizar documentos adjuntos 
2. se agrega lista de documentos adjuntos en paciente detalle
3. 
- [] No

feat(mpi): documentos paciente

---

auth/permisos.ts
initialize.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
modules/forms/forms-resources/forms-resources-routes.ts
modules/forms/forms-resources/forms-resources-schema.ts
modules/forms/forms.routes.ts
modules/forms/forms.schema.ts
modules/forms/index.ts

https://proyectos.andes.gob.ar/browse/EP-3
https://proyectos.andes.gob.ar/browse/EP-16
1. Se crean esquemas y rutas para formBuilder y formEpidemiologia
2. Se crean permisos para formBuilder
- [] Si
- [] Si

EPIDEMIOLOGIA: Form buillder y punto de inicio de ficha epidemiologica 

---

auth/permisos.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

https://proyectos.andes.gob.ar/browse/EP-19
1. Se actualiza resourceBase y permisos para el correcto funcionamiento de la ficha epidemiológica.

FICHA EPIDEMIOLÓGICA: Fix para busqueda de fichas

---

core/mpi/jobs/nacimientosProcess.ts

Se corrigen bugs en el job de importarNacimientos
1.se corrige  bug al guardar progenitor/a sin campo fotoId
2. se corrige bug al guardar el tipo de relación en progenitor e hijo
3. se agregan controles en pacientes que tengan relaciones en null
4. se cambia búsqueda de pacientes bebés en Andes por los pacientes que tenga la madre entre sus relaciones asignadas

Se corrigen bugs al guardar pacientes obtenidos del Registro Civil

---

config.private.ts.example
modules/vacunas/inscripcion-vacunas.routes.ts

Poder habilitar/deshabilitar el control del captcha al inscribirse para vacunación
1. Se suma variable enabled en config.private

VAC: variable para deshabilitar control de captcha

---

modules/vacunas/schemas/inscripcion-vacunas.schema.ts

Agregar el campo de riesgos/morbilidades a las inscripción
1. 
2. 
3.

fix(VAC): Agregar el campo de riesgos/morbilidades a las inscripción

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/CORE-67
Se controla parametros para que no se genere una query muy demandante.

fix(matriculaciones): protección de rutas

---

jobs/fueraDeAgendaJob.ts
modules/estadistica/pecas/controller/fueraDeAgenda.ts
modules/rup/schemas/codificacion.ts

- Agregar parámetros a job fuera de agenda para poder correrlo en un rango de fechas
- Agregar indices en la colección codificacion
1. Se agregan argumentos a fueraDeAgendaJob.ts
2. Se agregan indices

feat(pecas): Agrega parametros a job de fuera de agenda

---

auth/auth.class.ts
auth/auth.controller.ts
core/tm/routes/profesional.ts
modules/gestor-usuarios/usuarios.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-3
1. Ruta de validación de profesional
2. POST de creación de profesional 
3. PUT `/usuarios/:usuario/organizaciones/permisos`
4. Incluye en el `auth.check` validación de permisos de token de aplicación

feat(VAC): rutas para certificado de vacunacion covid

---

modules/vacunas/controller/inscripcion-vacunas.events.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts
scripts/validar-inscriptos.ts

Script para validar los inscriptos exportados con fuentes autenticas
1. 
2. 
3.

feat(script): validación de inscriptos

---

scripts/VAC-9.ts

https://proyectos.andes.gob.ar/browse/VAC-9
1. Script para actualizar la fecha de vacunación y el id de prestación en las inscripciones a vacunas.

VAC: script para actualizar estado de vacunación en inscripciones

---

modules/webhook/webhook.schema.ts
modules/webhook/webhook.ts

Poder filtrar webhooks de forma dinamica.
https://proyectos.andes.gob.ar/browse/CORE-60
1.  Aplica json-engine-rules para agregar reglas en la DB en forma de JSON.
Ejemplo de uso (el gact data depende de cada webhook):
```
{
"event" : "mpi:pacientes:update",
"url" : "http://127.0.0.1:3000/cda/ejecutar",
"method" : "POST",
"active" : true,
"nombre" : "CDA solo validados",
"rules" : {
"all" : [ 
{
"fact" : "data",
"operator" : "equal",
"value" : "validado",
"path" : "$.estado"
}
]
}
}
```

feat(webhook): aplicas filtros por base de datos

---

core/tm/interfaces/IOrganizacion.ts
modules/centroOperativoMedico/controllers/com.controller.ts
modules/centroOperativoMedico/derivaciones.routes.ts

https://proyectos.andes.gob.ar/browse/COM-61
1. Cuando se finaliza una derivación con organización destino, se envía un mail con el comprobante de derivación
2. 
3. 
Antes de mergear, crear configuración en CENTRO OPERATIVO MEDIDO:
`{
"emails" : [ 
{
"nombre" : "recupero",
"email" : "auditoriamedica.subsesalud@gmail.com"
}
]
}` 
TABLAS MAESTRAS / ORGANIZACIONES / CENTRO OPERATIVO MEDIDO / CONFIGURACIONES

COM: Envío comprobante derivación por mail

---

modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-17
1. Control para por si viene null en el arreglo de morbilidades

fix(VAC):control para elemento null en array de morbilidades

---

modules/forms/forms.schema.ts

Remueve unique index de `form.section.field.key` que impide usar el mismo key de field en dos formularios distintos
1. Remueve unique index de `form.section.field.key` que impide usar el mismo key de field en dos formularios distintos
2. 
3.

fix(MISC): formbuilder remove fieldkey unique

---

modules/centroOperativoMedico/derivaciones.routes.ts

https://proyectos.andes.gob.ar/browse/COM-68
1. Se elimina ruta de store en modulo COM

COM: se elimina ruta /store de derivaciones

---

core/tm/schemas/grupo-poblacional.schema.ts
modules/vacunas/controller/inscripcion.vacunas.controller.ts
modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-8
1. Devuelve un objeto vacío si no encuentra una inscripción
[ {
"_id" : ObjectId("603da3bdf00dd3d711253fa6"),
"nombre" : "mayores60",
"descripcion" : "Mayores de 60",
"validaciones" : [ 
{
"type" : "domicilio",
"mensajeError" : {
"titulo" : "Mayores de 60",
"subtitulo" : "Su inscripción como ciudadano mayor de 60 años no ha sido posible ",
"body" : "Según nuestros registros, su domicilio legal (DNI) se encuentra fuera de la Provincia del Neuquén. Si usted se encuentra radicado en la Provincia del Neuquén, puede dirigirse al Centro de salud mas cercano a su domicilio y solicitar la actualización de sus datos de domicilio en Andes.",
"status" : "warning"
}
}
]
},
{
"_id" : ObjectId("603e019056865e7f35afe979"),
"nombre" : …

VAC: consulta de estado de inscripción para vacunación

---

core/tm/routes/profesional.ts

Se ajusta las restricciones de la api de guía profesional.

fix(profesionales): permite buscar por dni y profesion

---

auth/permisos.ts
modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-1
1. Agrega campos para búsqueda 'search'

Vac -Búsqueda por filtros para listado de inscriptos

---

modules/descargas/agenda/agenda-body.ts
modules/descargas/agenda/agenda-header.ts
modules/descargas/agenda/agenda.ts
modules/descargas/routes/descargas.ts
modules/turnos/controller/agenda.ts
templates/agenda/agenda.scss

https://proyectos.andes.gob.ar/browse/CIT-107
1. Se crea carpeta agenda, con body y header para el informe de la agenda

feat(CITAS):Imprimir agenda

---

modules/vacunas/controller/inscripcion.vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/VAC-22
1. Se suman los datos del inscripto a la respuesta en la consulta

VAC: mostrar los datos del inscripto al consulta por la inscripción

---

core-v2/mpi/paciente/paciente.controller.ts

https://proyectos.andes.gob.ar/browse/MPI-339
1. Se modifica funcion 'set' del controller de paciente para poder actualizar la fecha.

MPI - Fix revalidación de paciente

---

modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-18
1. Se modifica el mensaje de error si ya encuentra una inscripción

VAC: cambio en el mensaje de inscripción registrada

---

modules/cda/controller/CDAPatient.ts

https://proyectos.andes.gob.ar/browse/CORE-80
Hay un permiso especial para aplicaciones pero que se estaba tomando para un usuario general de andes. Provocando una query terrible.

fix(cda): ajuste de permisos al crear CDA

---

modules/descargas/recupero-costo/recupero-costo-body.ts
modules/descargas/recupero-costo/recupero-costo-header.ts
templates/recupero-costo/formulario.scss

https://proyectos.andes.gob.ar/browse/ASJ-8
1. Se mejoró el layout para dar un poco más de orden

Mejora visualización de anexo-2 recupero (SJ)

---

core-v2/mpi/paciente/paciente.controller.ts
core-v2/mpi/paciente/paciente.routes.ts
core/mpi/controller/updateValidados.ts
core/mpi/jobs/nacimientosProcess.ts
modules/vacunas/controller/inscripcion-vacunas.events.ts
scripts/deleteFotoPaciente.ts
scripts/validar-inscriptos.ts

https://proyectos.andes.gob.ar/browse/MPI-338

feat(mpi): quita foto del schema paciente. 

---

core-v2/mpi/validacion/validacion.controller.ts

https://proyectos.andes.gob.ar/browse/MPI-332
1. Verifica que el paciente traiga la foto desde renaper

MPI -  FIX error validando paciente

---

modules/mobileApp/routes/prestacion.routes.ts
modules/rup/controllers/prestacion.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/RUP-243
1. Pasa logica de busqueda de huds desde ruta a controller
2. Nueva ruta para obtener huds de paciente desde mobile-app

RUP - Refactor de búsquedas de conceptos de la Huds

---

packages/drive/adapters/MongoAdapter.ts

https://proyectos.andes.gob.ar/browse/CORE-81

feat(drive): adaptador mongo

---

modules/webhook/webhook.routes.ts

Cambia el nombre del evento para las notificaciones de laboratorios
1. Agrega emitAsync con nuevo evento desde la ruta de webhook
2. 
3.

feat(webhook): cambia nombre de evento

---

modules/mobileApp/routes/paciente.ts

https://proyectos.andes.gob.ar/browse/AM-89
1. Permitir que un familiar pueda actualizar datos del paciente

AM: permitir que familiar actualice datos del paciente

---

modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

Poder filtrar por fecha de registro en el listado
Poder filtrar segun pacientes vacunados
1. 
2. 
3.

VAC - Agrega filtro por fecha de registro

---

modules/cda/routes/cda.ts
modules/mobileApp/routes/paciente.ts

https://proyectos.andes.gob.ar/browse/AM-52
1. Habilita la consulta de laboratorios de familiares

AM: permitir consultar laboratorios de familiares

---

modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

https://proyectos.andes.gob.ar/browse/BI-75
1.  Cambia schema de formEpidemiologia.type a `{ id, name }`
2. 
3.

EP: formEpidemiologia.type.id

---

core/tm/index.ts
core/tm/schemas/organizacion.ts
core/tm/schemas/zonaSanitarias.ts
core/tm/zonaSanitaria.routes.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

https://proyectos.andes.gob.ar/browse/EP-15
https://proyectos.andes.gob.ar/browse/EP-26
1. Se agregan los campos de búsqueda para el buscador de fichas epidemiologicas.
2. Se agrega el esquema ZonaSanitaria y el ResourceBase correspondiente.
Para probar el filtro de zonas sanitarias, en demo se encuentra la colección zonasSanitarias y ademas las organizaciones deben tener seteadas la zona sanitaria en el documento que corresponde.

EPIDEMIOLOGÍA: Buscador de fichas epidemiologicas

---

modules/cda/routes/cda.ts

No se pueden visualizar los CDA desde la HUDS.

fix(cda): visualizar cda desde andes

---

modules/vacunas/controller/inscripcion-vacunas.events.ts
modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-33
1. Se agrega el AuditPlugin a schema inscripcion-vacunas
- [Z] Si

VAC: audit plugin en inscripcion-vacunas

---

auth/permisos.ts

Sumar restricted a permisos de vacunación
1. Se suma restricted a permisos de vacunación

VAC: restringir permisos de vacunación

---

core-v2/mpi/jobs/importarNacimientosJob.ts
core-v2/mpi/jobs/nacimientosProcess.ts

Fix en el job importarnacimientos, ya que finaliza antes de lo esperado y no se ejecutaba la segunda parte.
1. 
2. 
3.

MPI: Fix en job importarNacimientos

---

modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

Poder agregar una nota a las inscripciones
1. Agrega atributo 'nota' al esquema de inscripciones

VAC - Agregar nota a una inscripción

---

modules/centroOperativoMedico/schemas/derivaciones.schema.ts

https://proyectos.andes.gob.ar/browse/COM-52
1. Se incluye prestación al schema de derivación
2. 
3.

feat(COM): crear derivación como una prestación

---

modules/descargas/informe-rup/elementos-rup/checklist.component.ts
modules/descargas/informe-rup/utils/registro-to-html.ts

https://proyectos.andes.gob.ar/browse/RUP-248
https://proyectos.andes.gob.ar/browse/RUP-247

feat(rup): ajuste en informe PDF

---

auth/auth.class.ts
modules/mobileApp/auth_routes/autenticacionApp.ts
modules/mobileApp/pacienteApp.routes.ts
modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/AM-129
1. Se suma ruta para registro de pacientes desde la app
2. Se eliminan imports sin uso
3. Se crea middleware para el control del captcha y se aplica tanto en la ruta de registro como en la de inscripción a vacunas

AM: permitir el registro de nuevos paciente desde la app

---

modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-28
1. Cambio de nombre de ruta post para registro público
2. Se habilita el post de ResourceBase

VAC: Nueva inscripción

---

modules/vacunas/inscripcion-vacunas.interface.ts
modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts
package.json
scripts/vac-41.ts

https://proyectos.andes.gob.ar/browse/VAC-41
1. Agrega búsqueda por nombre y apellido a través de tokens
**OBSERVACION: Se debe correr el script primero**

VAC - Filtro por nombre y apellido

---

modules/vacunas/controller/vacunas.controller.ts

1. Se agrega a la consulta el filtro por desde y hasta, porque no lo estaba agregando ya que solo preguntaba por horas.
2. Se agrega un try catch porque el proceso se rompe y deja de funcionar cuando hay errores en la prestación.

fix(jobVacunas): Fix varios en job vacunas a sisa

---

modules/estadistica/controller/procesarFueraDeAgenda.ts

https://proyectos.andes.gob.ar/browse/MISC-146
1. Se modifica if en procesarFueraDeAgenda para corregir la búsqueda por financiador.

TURNOS-PRESTACIONES: Fix en el fltro financiador

---

modules/mobileApp/auth_routes/autenticacionApp.ts
modules/mobileApp/pacienteApp.routes.ts

Al registrar nuevo usuario en app mobile no permitir que un mismo usuario(documento, sexo) se registre con otro email. 
1. Se agrega control en ruta de registro

fix(AM): Control de único email por usuario app

---

modules/forms/forms-epidemiologia/forms-epidemiologia.events.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
modules/forms/index.ts
modules/webhook/webhook.routes.ts

https://proyectos.andes.gob.ar/browse/EP-31
1. Se crea evento desde notifications para handlear actualizaciones para ficha.
2. Cada evento permitirá realizar una actualización automática en la ficha epidemiológica con resultados de PCR
Agregar en la colección "forms", dentro de clasificación final los fields:
{
"key" : "pcrM",
"label" : "Muestra tomada de PCR",
"type" : "dependencia",
"description" : "",
"required" : false,
"subfilter" : false,
"resources" : "",
"preload" : false
}
{
"_id" : ObjectId("601016027406db28e08b0d3a"),
"key" : "pcr",
"label" : "PCR",
"type" : "dependencia",
"description" : "",
"required" : false,
"subfilter" : false,
"resources" : "",
"preload" : false
}

Events ficha epidemio

---

modules/centroOperativoMedico/derivaciones.routes.ts
modules/centroOperativoMedico/schemas/derivaciones.schema.ts
modules/descargas/com/derivacion-body.ts

https://proyectos.andes.gob.ar/browse/COM-70
1. Incluye unidad destino en derivación
2. 
3.

COM: unidad destino derivación

---

core-v2/mpi/paciente/paciente.controller.ts
modules/vacunas/controller/inscripcion-vacunas.events.ts
modules/vacunas/controller/inscripcion.vacunas.controller.ts
modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/interfaces/inscripcion-vacunas.interface.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

Refactor de las funciones de validación de los datos de inscripción
1. Permite inscribirse cuando la inscripción no fue validada
2. Cambia el mensaje al paciente, cuando la inscripción fue inhabilitada
3. Actualiza datos de contacto en paciente, a partir de la inscripción

refactor(inscripcion): cambios en validación de inscripción

---

modules/vacunas/controller/vacunas.controller.ts

fix(jobVacunas): Se restaura el filtro de horas

---

modules/descargas/routes/descargas.ts

Try catch en descarga de comprobante
1. 
2. 
3.

COM: try catch en descarga de comprobante derivación

---

modules/centroOperativoMedico/derivaciones.routes.ts

1. Se realiza control por si el COM no tiene email asociado.

feat(COM): se verifica si tiene un email asociado para auditoria de com

---

modules/rup/schemas/plantillasRUP.ts

https://proyectos.andes.gob.ar/browse/RUP-231
1. Se agregan dos atributos a PlantillasRUPSchema
2. 
3. 
- [] No

feat(RUP): se agregan atributos a PlantillasRUPSchema

---

auth/permisos.ts
initialize.ts
modules/perinatal/carnet-perinatal.routes.ts
modules/perinatal/controller/carnet-perinatal.events.ts
modules/perinatal/index.ts
modules/perinatal/schemas/carnet-perinatal.schema.ts

https://proyectos.andes.gob.ar/browse/PER-19
https://proyectos.andes.gob.ar/browse/PER-16
1. Nuevo recurso carnet-perinatal
2. Eventos para carnet-perinatal
En el elementoRUP para el conceptId 366321006 (consulta de control de embarazo), hay que agregar:
_"dispatch" : [ 
{
"event" : "perinatal:control:validacion",
"method" : "validar-prestacion"
}, 
{
"event" : "perinatal:control:cancelar-validacion",
"method" : "romper-validacion"
}
]_
Para sumar el icono del módulo al inicio, agregar a la colección módulos:
{
"permisos" : [ 
"perinatal:?"
],
"nombre" : "PERINATAL",
"subtitulo" : "Salud perinatal",
"descripcion" : "Módulo de control perinatal",
"color" : "#44A756",
"linkAcceso" : "/perinatal",
"icono" : "circulo-madre-hijo",
"orden" : 18.0,
"__v" : 0.0
}

PER: recurso de carnet perinatal

---

modules/centroOperativoMedico/derivaciones.routes.ts

https://proyectos.andes.gob.ar/browse/COM-73
1. asigna habilitadas al COM
2. 
3.

COM: asigna habilitadas al COM

---

modules/vacunas/controller/inscripcion.vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/VAC-56
1. Cuando se carga un nueva inscripción, si existe una prestación validada con CERTIFICACIÓN DE PACIENTE CON RIESGO AUMENTADO DE COVID-19 se completan los campos fechaCertificado e idPrestacionCertificado.

VAC: certificado al momento de la inscripción

---

modules/descargas/com/derivacion-body.ts
modules/descargas/com/derivacion.ts
modules/descargas/routes/descargas.ts

https://proyectos.andes.gob.ar/browse/COM-69
1. Modifica el download de reporte de derivación para incluir información de historial
2. 
3.

COM: incluye historial en reporte derivación

---

modules/mobileApp/controller/AuthController.ts
templates/emails/active-app-code.html
templates/emails/reset-password.html

https://proyectos.andes.gob.ar/browse/AM-150
La idea es que sean menos los usuarios que hagan consultas a Andes porque no pueden registrarse o ingresar a la app móvil.
1. Se mejora template/texto de email para activar cuenta de app móvil
2. Se mejora template/texto de email para reestablecer contraseña
3. Para poder testear hay que hacer 4 cosas:
1. Conectar la API **a la base local** en `master` y tener la config de emails
2. Limpiar/vaciar la collection sendMessageCache
3. Insertar el registro (setear un email donde dice TU EMAIL) que hay al final de este PR **en la base local**, collection sendMessageCache
4. Correr el job de Robosender con `node jobs/manual.js jobs/roboSenderJob.js`
```
db.sendMessageCache.insert({
"status": "pending",
"device_id": [],
"message": "Hola BOC-HO, ANDRES, …
```

feat(email-verificacion-app): se mejora texto de email

---

modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

https://proyectos.andes.gob.ar/browse/EP-47
1. Filtrar por codificacion SISA
2. 
3.

EP: codigo SISA en ficha epidemio

---

auth/permisos.ts
modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-58
https://proyectos.andes.gob.ar/browse/VAC-59
1. Se modificó el schema de inscripcion-vacunacion para guardar datos de usuario asignano y turno
2. Nueva ruta post para asignar usuario a próxima inscripción
3. Nuevo permiso en vacunación 'dacion-turnos'

VAC: monitoreo de inscriptos y gestión de turnos

---

core-v2/mpi/paciente/paciente.controller.ts
modules/turnos/controller/turnosController.ts
modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/MPI-343
1. Reemplaza usos del viejo controller de paciente por el actual

MPI - Reemplaza controller de paciente en turnos

---

modules/vacunas/inscripcion-vacunas.routes.ts

Bug en edicion de inscriptos: No habilita el botón guardar cuando el formato del mail es incorrecto. Tampoco se visualiza el error hasta modificar este campo.
1. Formatea el mail correctamente en post y patch de inscripción.

VAC - Fix, convierte mail a minuscula y elimina espacios

---

config.private.ts.example
core/tm/routes/profesional.ts
core/tm/schemas/profesional.ts
initialize.ts
package-lock.json
package.json
services.ts
utils/roboSender/sendEmail.ts

Implementa AndesServices. 
AndesServices es un paquete que permite configurar servicios desde la Base de datos y ser consumido en el código. 
Hay diferentes tipos de servicios:
- HTTP.
- Mongo (find/findOne).
- Static (valor definido).
- Dinamica (se enlaza un código con el servicio).
De esta formo podemos definir HTTP request a diferentes servidores desde la DB, sin que el programador se preocupe de la cominicación.
A demás, en materia de testing  un mismo servicio puede cambiar de implementación rápidamente. A la hora de testear podemos definir el servicio como un valor estático así no se realiza el llamado al servicio externo. 
En esta primera versión,  se refacotoriza la inscripción de profesionales para que el llamado a renaper pase por andes Services. Se ajusta el PR …

Andes Services

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/EP-64
1. Se agrega el permiso para seguimiento de casos.
2. Se agrega a la base de datos el submodulo "Seguimiento de casos" de acuerdo al Mockup.
En la colección módulos editar el de EPIDEMILOGIA con el siguiente submodulo:
```
{
"permisos" : [ 
"epidemiologia:seguimiento:?"
],
"_id" : ObjectId("609e702d0fb8e228a00bb361"),
"nombre" : "Seguimiento<br><b>de casos</b>",
"linkAcceso" : "/epidemiologia/seguimiento",
"color" : "#669933",
"icono" : "nodos",
"orden" : 3
}
```

PERMISOS: Seguimiento de casos epidemiológicos

---

modules/descargas/informe-rup/informe-rup.ts

https://proyectos.andes.gob.ar/browse/MPI-344
1. Reemplaza controller de paciente

MPI - Actualiza controller de paciente en descarga de informe RUP

---

modules/mobileApp/auth_routes/autenticacionApp.ts
templates/emails/active-app-code.html

Al verificar si la cuenta ya existe, si el usuario existia como profesional en pacienteApp no dejaba registrarse
1. Se agrega control 
2. 
3.

fix(AM): Agrega control al verificar si ya existe la cuenta

---

core/tm/grupo-poblacional.routes.ts
core/tm/schemas/grupo-poblacional.schema.ts
modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-66
1. Agrega propiedad 'factorRiesgoEdad' (boolean) al esquema de inscripcion-vacunas
Modificar el grupo poblacional agregando.. 
"excepciones" : {
"any" : [ 
{
"all" : [ 
{
"fact" : "paciente",
"operator" : "greaterThan",
"value" : 56.0,
"path" : "$.edad"
}, 
{
"fact" : "paciente",
"operator" : "lessThan",
"value" : 60.0,
"path" : "$.edad"
}
]
}
]
}

VAC - Inscripción de nuevo grupo 57 a 59 años

---

scripts/VAC-9.ts

Modifica script para actualizar la fecha de vacunación de las inscripciones de vacunas, para incluir las prestaciones de los pacientes vinculados
1. 
2. 
3.

fix(script): busca pacientes por vínculos

---

modules/vacunas/controller/inscripcion.vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/VAC-67
1. Para inscriptos en factores de riesgo entre 57 y 59 años no deberá figurar el mensaje que requiere certificado con la prescripción correspondiente

VAC: Consultas de grupo 57 a 59 años

---

modules/mobileApp/auth_routes/autenticacionApp.ts

1. Fix en registro de paciente que también

fix(registro-mobile): validar email y documento

---

modules/mobileApp/auth_routes/autenticacionApp.ts

fix en chequeo de cuenta existente
1. 
2. 
3.

fix(AM): Agrega control faltante en registro

---

modules/centroOperativoMedico/controllers/com.controller.ts
modules/descargas/com/derivacion-body.ts
modules/descargas/com/derivacion.ts

fix(COM): fix send mail comprobante

---

modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-71
1. Permitir buscar inscripciones por usuario asignado

VAC: ver listado de inscripciones asignadas

---

core/mpi/controller/paciente.ts
modules/mobileApp/routes/paciente.ts

https://proyectos.andes.gob.ar/browse/AM-153
1. Nueva ruta para registrar un hijo menos a 11 años a un paciente

AM: registro de familiares desde la app

---

modules/rup/controllers/prestacion.ts

Se modifica hudsPaciente para realizar la búsqueda por vinculados, en vez de por idPaciente.
1. 
2. 
3.

Huds: búsqueda de conceptos por pacientes vinculados

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/IN-279
1.  Se agregar la modificación del paciente para editar la obra social de la prestación.

feat(rup): patch paciente para obra social

---

core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-347
1. 
2. 
3.

MPI: Mayúscula al guardar alias del paciente

---

modules/centroOperativoMedico/controllers/com.controller.ts
modules/centroOperativoMedico/derivaciones.routes.ts

https://proyectos.andes.gob.ar/browse/COM-77
1. https://proyectos.andes.gob.ar/browse/COM-77
2. 
3. 
**RECORDATORIO**: Cambiar el TAG de recupero a comDerivacionesRecupero

COM: envio mail a org destino

---

modules/rup/prestaciones.interface.ts
modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/RUP-252
1. se agrega unidad organizativa a prestación.
2. 
3.

feat(RUP):agregar unidad organizativa a la prestación

---

core-v2/mpi/paciente/paciente.controller.ts

Se detectó un error al crear relaciones desde app móvil para familiares menores de 11 años, cuando el usuario principal no tenía ninguna relación previa (en lugar de haber un array, hay un valor null).
**Importante para probar:** considerar 2 situaciones, un usuario con relaciones (algún familiar previamente vinculado) y sin relaciones (ningún familiar previamente vinculado).
1. Se agregó un control para ver que las relaciones no estén en null antes de intentar comprobar que el familiar ya existe.

fix(relaciones): control array vacío/null

---

auth/permisos.ts

Restringir la visibilidad de permisos del formBuilder para no poder ser asignados desde el gestor.
1. 
2. 
3. 
- [] No

FORMS: restrict formBuilder visibility

---

core/tm/routes/localidad.ts
core/tm/schemas/localidad.ts

Agregar un campo "activo" para diferenciar entre localidades y barrios en la colección "localidad"
1. Se agrega el Schema "localidades" el campo activo donde los que estén en true serán localidades y los que estén en false barrios. 
2. Se agrega el campo activo en routes.
3. Se modifica la colección "localidad" seteando el campo en cada uno de los documentos.
[localidad.bson.zip](https://github.com/andes/api/files/6571068/localidad.bson.zip)

Localidades: field activo

---

jobs/exportNexosFichaSisa.ts
jobs/jobExportFichasSnvsSisa.ts

- Nuevo job para abrir casos por nexo y antígeno desde la ficha de epidemiología.
- Está completamente separado del proceso de prestaciones existente debido a que van a tener que convivir un tiempo hasta que finalmente el otro JOB se desactive.
https://proyectos.andes.gob.ar/browse/EP-68

feat(fichaEpidemiologica): Apertura de casos por nexo y antigeno desde la ficha epidemiológica

---

modules/descargas/informe-censo/censo-body.ts
modules/rup/internacion/censo.controller.ts

https://proyectos.andes.gob.ar/browse/IN-297
1. 
2. 
3.

IN - Agrega fecha de ingreso en censo diario

---

modules/rup/internacion/camas.controller.ts
modules/rup/internacion/internacion.controller.ts
scripts/IN-274.ts

https://proyectos.andes.gob.ar/browse/IN-274
1. Agrega unidad organizativa al esquema de prestaciones
2. Agrega evento que actualiza la unidad organizativa de la prestación al momento de un cambio

INT - Agregar columna 'unidad organizativa'

---

modules/descargas/recupero-costo/recupero-costo-body.ts
modules/descargas/recupero-costo/recupero-costo.interface.ts
modules/descargas/recupero-costo/recupero-costo.ts
templates/recupero-costo/formulario.scss

Problemas en la visualización de la información y diseño del pdf a descargar

DESCARGAS - Recupero de costo (anexo 2)

---

modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

1. Cambia búsqueda de localidades dentro del form (nombre por id)

FORMS: Fix localidades

---

index.ts

https://proyectos.andes.gob.ar/browse/CORE-87
1. Se detecta la señal de apagado que manda PM2 y se cortan las conexiones. Deja un tiempito de cortesía para que terminen bien todos los procesos en background.

feat(core): graceful shutdown

---

modules/cda/controller/CDAPatient.ts

https://proyectos.andes.gob.ar/browse/MISC-167

fix(cda): crear cda a extranjeros

---

modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-69
1. Permitir eliminar paciente de inscripción

VAC: poder desvincular paciente en el patch de inscripciones

---

modules/descargas/routes/descargas.ts
modules/mobileApp/schemas/categoria.ts
modules/rup/controllers/rup.ts
modules/rup/routes/prestacion.ts

Agregar ruta get para descarga de prestación/registro 
1. Se agrega get de descarga
2. Se agrega parametro idPrestacion en funcion buscarEnHuds
3. En el get de prestaciones extiende filtro por tipo de prestaciones para aceptar expresiones

feat(descargas): Agrega get para descarga de prestaciones

---

initialize.ts
modules/centroOperativoMedico/derivaciones.routes.ts
modules/centroOperativoMedico/schemas/derivaciones.schema.ts
modules/descargas/com/derivacion-body.ts
modules/dispositivo/dispositivo.routes.ts
modules/dispositivo/dispositivo.schema.ts
modules/dispositivo/index.ts

1. Nuevo recurso dispositivo reusable.
2. Se agrega los dispositivos de tipo: oxigeno para poder agregar la información solicitada al COM
3. Se agrega en el informe si se utilizó un dispositivo de oxigeno en la derivación.
https://proyectos.andes.gob.ar/browse/COM-83
1. Se deberá crear la colección dispositivo
2. Se deberán cargar los datos necesarios en la colección:
[
{
"nombre" : "HELMET",
"tipo" : "oxigeno",
"descripcion" : "Casco de oxigeno",
"icono" : "helmet"
},
{
"nombre" : "ARM",
"tipo" : "oxigeno",
"descripcion" : "Asistencia respiratoria móvil",
"icono" : "arm"
},
{
"nombre" : "CNAF",
"tipo" : "oxigeno",
"descripcion" : "Cánula nasal de alto flujo",
"icono" : "cnaf"
},
{
"nombre" : "MR",
"tipo" : "oxigeno", …

feat(com): Posibilidad de asociar dispospositivos de oxigeno a la derivación

---

config.private.ts.example
jobs/perinatalFechaFinEmbarazo.ts
jobs/perinatalUpdateJob.ts
modules/perinatal/perinatal.log.ts
modules/perinatal/schemas/carnet-perinatal.schema.ts
utils/servicioSipPlus.ts

Perinatal: se crea job para actualizar fecha fin de embarazo desde sip+
https://proyectos.andes.gob.ar/browse/PER-26
1. se actualiza dato fechaFinEmbarazo de la coleccion carnet-perinatal cuando no existe.
2. 
3.

Perinatal: se crea job para actualizar fecha fin de embarazo

---

core/tm/routes/organizacion.ts

https://proyectos.andes.gob.ar/browse/COM-90
1. 
2. 
3.

COM: filtro esCOM false

---

modules/rup/controllers/prestacion.ts
modules/rup/dinamic-context.controller.ts
modules/rup/elementos-rup.controller.ts
modules/rup/index.ts
modules/rup/routes/prestacion.ts
modules/rup/schemas/elementos-rup-requeridos.schema.ts
package-lock.json
package.json
services.ts

https://proyectos.andes.gob.ar/browse/RUP-255
1. 
2. 
3. 
(no es real)
```
{
"_id" : ObjectId("60ba377fb5387ac0894776fb"),
"nombre" : "control fractura",
"active" : true,
"conceptos" : [ 
{
"conceptId" : "391000013108",
"term" : "consulta de medicina general",
"fsn" : "consulta de medicina general",
"semanticTag" : "procedimiento",
"id" : ObjectId("598ca8375adc68e2a0c121b8")
}
],
"contexto" : [ 
{
"name" : "fractura",
"service" : "paciente-huds-registros",
"params" : {
"paciente" : "$.prestacion.paciente.id",
"expression" : "<<15574005",
"first" : true
},
"dependsOn" : []
}
],
"rules" : {
"all" : [ 
{
"fact" : "prestacion",
"operator" : "equal",
"value" : "34934522",
"path" : "$.paciente.documento"
}, 
{
"fact" : "prestacion",
"operator" : "equal",
"value" : "BOTTA",
"path" : …
```

rup: conceptos requeridos dinámicos

---

package-lock.json
package.json

Quedo un console.log es el build de una de las librerías

chore(package): update librerias

---

modules/centroOperativoMedico/schemas/derivaciones.schema.ts

- Se agrega la posibilidad de un nuevo color para identificar prioridades intermedias.
-

feat(COM): Se le agrega color naranja para identificar gravedades intermedias

---

jobs/manual.ts

fix(robosernder): error import

---

utils/roboSender/roboSender.ts

Cambiar el foreach que recorre los envíos pendientes por un for, para que el await actúe como se espera
1. reemplaza foreach

feat(robosender): reemplaza forEach x for

---

core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-349
1. Se suma lugarNacimiento a Schema de paciente

MPI: se suma lugarNacimiento a schema de paciente

---

modules/forms/forms-epidemiologia/forms-epidemiologia.events.ts

https://proyectos.andes.gob.ar/browse/MISC-175
1. Corrige match de resultados en notification event de laboratorio central
2. 
3.

MISC: notificacion lab fix match resultado

---

modules/rup/internacion/cama-estados.controller.ts
modules/rup/internacion/cama-estados.schema.ts
modules/rup/internacion/internacion.controller.test.ts
modules/rup/internacion/internacion.controller.ts
modules/rup/internacion/internacion.routes.ts

https://proyectos.andes.gob.ar/browse/IN-259
1. Agrega identificador de movimiento al esquema de 'cama-estados'.
2. Rastrea los cambios de estado de camas como consecuencia de los movimientos del paciente y realiza un borrado lógico.

IN - Anular internación con varios movimientos

---

modules/webhook/logger/laboratorioCentralLog.ts
modules/webhook/webhook.routes.ts

https://proyectos.andes.gob.ar/browse/MISC-172
1. Logs de notificaciones de laboratorio cental

MISC: logs laboratorio central

---

auth/permisos.ts
modules/descargas/informe-rup/informe-body.ts
modules/descargas/informe-rup/informe-firma.ts

Permisos especiales para validar prestaciones no creadas por mí. Ejemplos de uso:
1. Residentes-Medicos a cargo.
2. Edición de vacunas cuando la carga un NN.
https://github.com/andes/app/pull/2322

feat(rup): permisos especiales para validar otras prestaciones

---

modules/vacunas/interfaces/inscripcion-vacunas.interface.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

Eliminar de schema las dos opciones del listado de Precauciones relacionadas con la seguridad de la inmunización

fix(VAC):sacar dos precauciones de la inscripción de vacunación

---

modules/vacunas/schemas/nomivacLote.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-77
1. Se modifico, dentro del objeto de vacuna, su id agregando un tipo y referencia.

refactor(VAC): Modificacion del id de la vacuna

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/CORE-63
Obliga a mongo a usar indices
1. 
2. 
3.

fix(top): indices

---

modules/rup/routes/prestacion.ts

Quito indice cuando tiene ID paciente. 
1. 
2. 
3.

fix(top): saco indice si tiene paciente

---

modules/vacunas/interfaces/inscripcion-vacunas.interface.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-85
1. Se agrega en schema e interface el arreglo de llamados

feat(VAC):agrega llamados a schema e interface

---

core/tm/routes/organizacion.ts

Poder filtrar en get de organizaciones por el campo showMapa
1. Se agrega filtro por campo showMapa

feat(organizaciones): Agrega parametro showMapa

---

modules/rup/internacion/cama-estados.controller.ts
modules/rup/internacion/cama-estados.schema.ts
modules/rup/internacion/camas.controller.ts
modules/rup/internacion/camas.routes.ts
modules/rup/routes/prestacion.ts
scripts/IN-287.ts

https://proyectos.andes.gob.ar/browse/IN-287
1. Agrega fecha de ingreso al esquema de cama-estado
2. Elimina fecha de ingreso del paciente en cama que se desocupa por movimiento

Mapa-camas - Días de estada en el listado

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/RUP-262
Permite romper validación si tengo el permisos de validar extras

feat(rup): romper validacion si tengo permisoss

---

modules/georeferencia/controller/areasPrograma.ts

Corrección de key de sisa en import de areas.
1. 
2. 
3.

EP: fix referencia de sisa en area programa

---

modules/mobileApp/routes/agendas.ts
modules/turnos/condicionPaciente/condicionPaciente.controller.ts
modules/turnos/condicionPaciente/condicionPaciente.routes.ts
services.ts

https://proyectos.andes.gob.ar/browse/AM-156
1. Modifica get de agendas disponibles
2. mueve método **verificarCondicionPaciente** a controller
Ejemplo:    
`{
"_id" : ObjectId("60da049c4757463cf70c6c3d"),
"tipoPrestacion" : {
"conceptId" : "1821000246103",
"term" : "campaña de vacunación contra COVID-19",
"fsn" : "campaña de vacunación contra COVID-19 (procedimiento)",
"semanticTag" : "procedimiento"
},
"contexto" : [ 
{
"name" : "paciente",
"service" : "obtener-paciente",
"params" : {
"id" : "$.id"
},
"dependsOn" : []
}, 
{
"name" : "organizacion",
"service" : "obtener-organizacion",
"params" : {
"organizacion" : "$.organizacion"
},
"dependsOn" : []
}
],
"rules" : {
"any" : [ 
{
"all" : [ 
{
"fact" : "paciente",
"operator" : "lessThan",
"value" : 40.0,
"path" : "$.edad"
}, 
{
"fact" : …

feat(AM): Permitir acceder a turnos mediante reglas

---

modules/seguimiento-paciente/seguimiento-pacientes.events.ts

fix referencia geolocation
1. 
2. 
3.

EP: fix referencia geolocation

---

modules/forms/forms-epidemiologia/controller/forms-epidemiologia.controller.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

1. patch de fields de ficha epidemiologica
2. 
3.

EP: patch de fields de ficha epidemiologica

---

jobs/LAMPResultsImport.ts
jobs/index.ts
jobs/jobLAMP.ts
jobs/manual.ts
jobs/scheduler.ts
modules/forms/forms-epidemiologia/controller/forms-epidemiologia.controller.ts
modules/forms/index.ts
modules/webhook/webhook.ts

Job importartor de LAMP
1. Job que llama a microservicio importador de LAMP
2. Patch de fields para ficha epidemiológica
3. 
*NOTA*: Agregar a config.private: 
```
export const jobs = [
...
{
when: '* * */12 * * * ',
action: './jobs/LAMPReesultsImport'
}
];
```
https://proyectos.andes.gob.ar/browse/EP-50 https://proyectos.andes.gob.ar/browse/EP-44
[webhook_ Resultados LAMP Import.txt](https://github.com/andes/api/files/6478443/webhook_.Resultados.LAMP.Import.txt)

EP: Job importartor de LAMP

---

modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

Se agrega el search por id de clasificación en resourceBase
https://proyectos.andes.gob.ar/browse/EP-91

feat(ficha): Se agrega la búsqueda por clasificación

---

core/tm/schemas/profesional.ts
modules/rup/schemas/prestacion.solicitud.historial.ts

https://proyectos.andes.gob.ar/browse/CORE-84
1. Crea subschema con datos básicos, sin índices

Profesional - Nuevo subesquema con datos basicos

---

modules/rup/controllers/prestacion.ts
modules/rup/routes/prestacion.ts
modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/RUP-257
1. Nuevo modelo a partir de clon de esquema de prestacion
2. Modifica patch de prestacion para los casos de romper validacion y anular

RUP - Guarda prestaciones modificadas y anuladas en nueva colección

---

core/tm/controller/profesional.ts
core/tm/routes/profesional.ts
modules/rup/routes/prestacion.ts
modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/TM-15
1. Refactor de endpoint para guardar firma de profesional

TM - Cargar firma de profesional fuera de matriculaciones

---

core-v2/mpi/paciente/paciente.events.ts
modules/rup/controllers/rup.ts
modules/rup/routes/prestacion.ts
modules/vacunas/controller/vacunas.events.ts
modules/vacunas/index.ts
modules/vacunas/schemas/vacunas-pacientes.schema.ts
modules/vacunas/schemas/vacunasApi.ts
services.ts
utils/roboSender/roboSchema.ts
utils/roboSender/roboSender.ts

https://proyectos.andes.gob.ar/browse/VAC-93
1. Evento disparado por dispatch para asociar la prestacion de vacunacion con el registro de la vacuna e inscripcion 
En _elementosRUP_, agregar al concepto **1821000246103** (`conceptos.conceptId`)   los siguientes campos: 
```
"dispatch" : [ 
{
"event" : "rup:prestaciones:vacunacion",
"method" : "validar-prestacion"
},
{
"event" : "rup:prestaciones:vacunacion",
"method" : "romper-validacion"
}
]
```
Agregar en `andes-services`:
```
{
"_id" : ObjectId("60f6e0561728352a8ab16e79"),
"name" : "paciente-vacunacion-registrar",
"type" : "dinamic-client",
"configuration" : {
"name" : "paciente-vacunacion-registrar"
}
}
```

Vac - event para asociar prestacion con vacunacion covid

---

core/tm/controller/profesional.ts

Chequeo de que exista la matricula

fix(tm): ajuste matricula profesional

---

core/log/routes/log.ts
modules/vacunas/controller/vacunas.events.ts

Controla correctamente si la localidad existe.

fix(vacunas): error en localidades

---

jobs/actualizar-inscriptosJob.ts
modules/vacunas/controller/inscripcion.vacunas.controller.ts

Se cambia script VAC-9 por job para actualizar los datos de los inscriptos de la vacunación, con la fecha de vacunación.
Este proceso  es para los casos que realizan modificaciones posteriores al registro de las vacunas
1. 
2. 
3.

feat(job): actualiza datos de vacunación en inscriptos

---

modules/vacunas/controller/inscripcion-vacunas.events.ts
modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/interfaces/inscripcion-vacunas.interface.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-91
https://proyectos.andes.gob.ar/browse/VAC-92
1. Si el paciente es extranjero no se realiza la validación
2. Se agrega numeroIdentificación

feat(VAC):inscripcion para extranjeros

---

modules/vacunas/controller/vacunas.events.ts

https://proyectos.andes.gob.ar/browse/AM-173
1. se agrega el llamado al método exportCovid19

feat(AM): agrega POST a sisa en el login a la app mobile

---

modules/mobileApp/pacienteApp.routes.ts
modules/mobileApp/schemas/pacienteApp.ts

https://proyectos.andes.gob.ar/browse/MONIT-41
1. Se modifico que la busqueda no sea solamente por documento sino tambien por email.

(MONIT-41): buscar usuario por email

---

core-v2/mpi/paciente/paciente.routes.ts
index.ts
modules/top/controller/reglas.ts
modules/turnos/routes/agenda.ts
package-lock.json
package.json

Por alguna razón, la foto del paciente  no se guarda en seaweed como corresponde y al obtenerla se explota todo.

mpi: handler correcto si no existe la foto 

---

index.ts
modules/perinatal/controller/carnet-perinatal.events.ts
modules/rup/schemas/semantic-tag.ts
package.json

Handleamos los errores para que no se cuelgue nada.

feat(core): handler bugs

---

modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/interfaces/inscripcion-vacunas.interface.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-86
1. Nuevo parámtro de búsqueda 'fechaProximoLlamado'
2. Al asignar una fecha se elimina el atributo 'asignado' para que la inscripción pueda ser cargada mas adelante
3. Agrega filtro para que las inscripciones con fecha de próximo llamado solo puedan volver a cargarse a partir de dicha fecha

Vacunación -  Registrar fecha de próximo llamado

---

modules/perinatal/carnet-perinatal.routes.ts

https://proyectos.andes.gob.ar/browse/PER-32
1. Se agregaron dos nuevos filtros para buscar a un paciente por organizacion y/o por profesional

feat(PER-32): agregar nuevos filtros al modulo perinatal

---

auth/permisos.ts
modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-84
1. Nuevo permiso especial para desasignar permisos

feat(VAC): agrega permiso especial para desasignar inscriptos

---

jobs/perinatalFechaFinEmbarazo.ts
utils/servicioSipPlus.ts

https://proyectos.andes.gob.ar/browse/PER-33
En job perinatal se agrega la actualizacion fecha prox control embarazo en la coleccion carnet-perinatal, solo en aquellos documentos que no contengan fecha fin de embarazo, y que la fecha de la proxima cita no exista o sea menor a la que existe en sip-plus.
1. En job perinatal se agrega la actualizacion fecha prox control embarazo en la coleccion carnet-perinatal
2. 
3.

PER: en job perinatal actualizacion fecha prox control embarazo

---

jobs/exportCovid19.ts
jobs/jobExportVacunaCovid19.ts
modules/vacunas/controller/vacunas.controller.ts
modules/vacunas/controller/vacunas.events.ts

Controla argumentos en función exportCovid19 y vuelve a enlazar

feat(vacunas): ajuste de proceso covid

---

core/tm/areaProgramaProvincial.ts
core/tm/schemas/areaProgramaProvincial.ts
modules/vacunas/controller/vacunas.events.ts
modules/vacunas/schemas/vacunas-pacientes.schema.ts

Agrega el área programa a paciente-vacunas
1. 
2. 
3.

feat(vacunas). agrega area programa

---

core-v2/mpi/paciente/paciente.events.ts

https://proyectos.andes.gob.ar/browse/MPI-356
1. Verifica modificación de dirección del paciente para actualizar georeferencia

MPI - Fix actualización de georeferencia

---

scripts/VAC-94.ts

https://proyectos.andes.gob.ar/browse/VAC-94
1. Script para migrar prestaciones de campaña de vacunación de covid-19 a colección paciente-vacunas

VAC - Script para migración de vacunas

---

modules/mobileApp/auth_routes/autenticacionApp.ts
modules/mobileApp/controller/PushClientFCM.ts

1. no envía push si es una versión de app anterior a esta funcionalidad

fix(registro): no enviar push en versiones legacy

---

modules/vacunas/controller/vacunas.events.ts

Chequea que existas el area programa

feat(vacunas): no todas las localidades tienen area programa

---

modules/mobileApp/auth_routes/autenticacionApp.ts
modules/mobileApp/controller/AuthController.ts

1. Arregla un bug en control de envío de notificaciones (push, email)
2. 
3.

fix: control push

---

modules/perinatal/controller/carnet-perinatal.events.ts
modules/rup/controllers/elementos-rup.controller.ts

https://proyectos.andes.gob.ar/browse/PER-36
Corrige error al disparar evento en la validacion de prestacion por embarazo
1. Corrige error al disparar evento en la validacion de prestacion por embarazo
2. Se modifica el concepto de próxima cita utilizado
3. 
Insertar nuevo elemento Rup:
```
{
_id:ObjectId("60ef3c3afd17465ada66c178"),
"componente" : "ValorFechaComponent",
"tipo" : "atomo",
"style" : {
"columnas" : 6.0,
"cssClass" : null
},
"conceptos" : [
{
"conceptId" : "2471000246107",
"term" : "fecha sugerida de la próxima visita",
"fsn" : "fecha sugerida de la próxima visita (entidad observable) ",
"semanticTag" : "entidad observable"
}
],
"requeridos" : [],
"frecuentes" : [],
"params" : {
"title" : "Fecha próxima visita",
"type" : "date"
}
}
```

PER: Corrige error al disparar evento en la validacion de prestacion por embarazo

---

modules/mobileApp/controller/NotificationService.ts

Activa el envío de push notifications para el paciente al reasignar turnos y suspender agendas

Fix push turnos

---

modules/descargas/informe-rup/elementos-rup/adjuntar-documento.component.ts

https://proyectos.andes.gob.ar/browse/RUP-269
1. Que en el informe PDF se vean varias imágenes por hoja.
2. se modifico salto de linea.
3.

fix(RUP): informe-pdf, imagenes adjuntas

---

scripts/index.ts

Para utilizar los servicios definidos en AndesService en la ejecución de los scripts, se agrega la inicialización de los mismos en el index. 
1. 
2. 
3.

fix(scripts): setup de servicios

---

modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts

https://proyectos.andes.gob.ar/browse/EP-104
1. 
2. 
3.

EP: identificador PCR único

---

modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/seguimiento-paciente/seguimiento-pacientes.events.ts

reutilizar funcion de calculr edad
1. 
2. 
3.

EP: chore calcular edad

---

scripts/RUP-265.ts

https://proyectos.andes.gob.ar/browse/RUP-265
1. Script que busca todas las prestaciones en estado 'modificadas' y 'anuladas' (Exceptuando las de top) y las almacena en la colección prestacion-historial
**Alternativa en mongo:**
```
db.getCollection('prestaciones').find({ $and: [{ 'estados.tipo': { $in: ['modificada', 'anulada'] } }, { inicio: { $ne: 'top' } }]}).forEach(function(docs) {
db.getCollection('prestacion-historial').insert(docs);
})
```

RUP - Script para migrar prestaciones modificadas-anuladas

---

modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-history.routes.ts
modules/forms/forms-epidemiologia/forms-history.schema.ts

Refactor de historial de ficha: Se cambia el schema a el mismo de la Ficha y se guarda el registro en middleware post save
1. 
2. 
3. 
[script.update.fichaHistorial (1).txt](https://github.com/andes/api/files/6939810/script.update.fichaHistorial.1.txt)

EP: guardar history post save

---

templates/emails/active-app-code.html

https://proyectos.andes.gob.ar/browse/AM-184

feat(MOBILE): agregar texto en email de codigo de activacón

---

config.private.ts.example
jobs/actualizar-inscriptos-fallecidos.ts
modules/vacunas/controller/inscripcion.vacunas.controller.ts

Actualiza los datos de los pacientes inscriptos con el web services de pacientes fallecidos por covid.  Se cambia el estado de las inscripciones 
1. 
2. 
3. 
{
"_id" : ObjectId("610d24e5e8b3eae47c9de487"),
"name" : "xroad-fallecidos",
"type" : "http-client",
"configuration" : {
"url" : "http://10.1.72.6:5000/r1/roksnet/GOV/70000101/GP-SALUD/WS_Fallecidos_Covid",
"headers" : {
"X-Road-Client" : "roksnet/GOV/70000101/SALUD-TICS",
"Accept" : "application/json"
},
"method" : "GET",
"form" : false,
"json" : true
}
}

feat(jobs): consulta a web services de fallecidos

---

modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

https://proyectos.andes.gob.ar/browse/EP-114
1. Se agrega un nuevo filtro por clasificación final.

Forms : Nuevo filtro clasificacionFinal

---

modules/vacunas/inscripcion-vacunas.routes.ts
modules/vacunas/interfaces/inscripcion-vacunas.interface.ts

https://proyectos.andes.gob.ar/browse/VAC-83
1. Agrega datos del turno al esquema de inscripción a vacunación

VAC - Dación de turno desde la inscripción

---

scripts/updateRelacionesNacidos.ts

Script que actualiza las relaciones en pacientes que no tengan el dato del tipo "relacion"
https://proyectos.andes.gob.ar/browse/MPI-354
1. 
2. 
3.

MPI: script actualizar relaciones

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/VAC-88
1. Se agrego un nuevo permiso para poder visualizar el contenido de las vacunas con las dosis y esquemas correspondientes

feat(VAC-88): mostrar esquemas y condiciones de una dosis

---

initialize.ts
modules/semaforo/index.ts
modules/semaforo/semaforo.routes.ts
modules/semaforo/semaforo.schema.ts

https://proyectos.andes.gob.ar/browse/MISC-171
1.  https://proyectos.andes.gob.ar/browse/MISC-171
2. 
3. 
[semaforo com.txt](https://github.com/andes/api/files/6717867/semaforo.com.txt)
*andesTestIntegracion*: https://github.com/andes/andes-test-integracion/pull/373

MISC: semaforo priorizacion

---

index.ts

Parámetros del servidor de Express para evitar fallós de conexión. Error 504.

chore(express): keepalive

---

core-v2/mpi/mpi.log.ts
modules/rup/internacion/censo.controller.ts
modules/rup/internacion/internacion.controller.ts
modules/rup/internacion/internacion.log.ts

https://proyectos.andes.gob.ar/browse/IN-319
1. Nuevo log para internacion
2. Se agrega bloque try-catch en deshacer internación para loguear prestaciones anuladas

INT - Error en datos con internaciones anuladas

---

modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
scripts/EP-111.ts

https://proyectos.andes.gob.ar/browse/EP-89
https://proyectos.andes.gob.ar/browse/EP-111
1. Se crean indices para la colección formsEpidemiologia
2. Se agrega script para actualizar las fichas ya guardadas para que queden con el tipo organizacion:{id, nombre}
[fichaLaboratorio.txt](https://github.com/andes/api/files/6879325/fichaLaboratorio.txt)
Ejecutar script `node scripts EP-111`

Epidemiología: Save organización e index formsEpidemiolgia

---

core/tm/routes/organizacion.ts

https://proyectos.andes.gob.ar/browse/MISC-189
1. Se obtienen los ids de las organizaciones del usuario en lugar de recibirlos en la query

TM - Control de permisos cargando organizaciones del usuario

---

config.private.ts.example
modules/vacunas/controller/vacunas.events.ts

https://proyectos.andes.gob.ar/browse/VAC-73
1. Al romper validacion de prestación de vacunación, consulta si existe el registro de la vacuna en sisa y de ser así lo de de baja.

VAC - Elimina registro de nomivac al romper validación de vacuna

---

modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
scripts/update-pacientes-ficha.ts

https://proyectos.andes.gob.ar/browse/EP-128
1. Elimina type del schema y agrega script para actualizar el type del id del paciente.

Form -  Fix para id de paciente

---

core/tm/schemas/profesional.ts
scripts/eliminarProfesionalesDuplicados.ts

https://proyectos.andes.gob.ar/browse/MAT-54
1. Agrega propiedad 'activo' al esquema de profesional
2. Script para inactivar profesionales duplicados y asignar sus turnos y prestaciones al profesional que queda activo

MAT - Inactiva profesionales duplicados

---

modules/matriculaciones/routes/turno.ts

https://proyectos.andes.gob.ar/browse/MAT-52
1. antes de guardar un turno nuevo, verificar que no existe otro turno con mismo día/horario

MAT: antes de guardar un turno nuevo, verificar que no existe otro turno con mismo dia/horario

---

auth/auth.class.ts
core/tm/routes/organizacion.ts

https://proyectos.andes.gob.ar/browse/MISC-190
1. Verifica si el usuario tiene permiso global antes de filtrar la query. 
2. Agrega skip y limit.

TM organizaciones: Agregar permiso global

---

modules/mobileApp/auth_routes/autenticacionApp.ts
modules/mobileApp/pacienteApp.routes.ts

https://proyectos.andes.gob.ar/browse/AM-197
1. Al momento del registro de usuario en la app mobile, si ya existe una cuenta asociada al paciente pero está sin activar permite avanzar con el registro. 
2. Modifica la búsqueda en pacienteApp para que solo busque cuentas de pacientes y no de profesionales.

feat(AM): Permitir el registro de usuarios que tienen cuenta sin activar 

---

core/tm/schemas/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-55
1. Se agrego un atributo 'fecha de vencimiento' para poder almacenar las fechas de vencimiento de la especialidad postgrado

refactor(MAT-55): fecha de vencimiento de las especialidades

---

modules/vacunas/schemas/inscripcion-vacunas.schema.ts

https://proyectos.andes.gob.ar/browse/VAC-103
1. Nuevo estado "no completa esquema"

VAC - Agrega nuevo estado de inscripción

---

core/tm/routes/profesional.ts
core/tm/schemas/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-60
1.

MAT - Filtro por profesión

---

auth/auth.class.ts

https://proyectos.andes.gob.ar/browse/CORE-95
Tambien afecta a adjuntar archivos de RUP. Gracias APM!!!

fix(tm): no se puede acceder a organizaciones

---

core/tm/schemas/profesional.ts

MAT (Fix) - Elimina indice de posgrado

---

modules/rup/controllers/estadisticas.ts

https://proyectos.andes.gob.ar/browse/CORE-71
1.  Cambia busqueda de fecha de solicitud por creación de la prestación
2. 
3.

CORE: filtro solicitudes dashboard

---

modules/seguimiento-paciente/schemas/seguimiento-paciente.schema.ts
modules/seguimiento-paciente/seguimiento-paciente.route.ts

https://proyectos.andes.gob.ar/browse/EP-123
1. Se agrega asiganciones a schema de seguiiemento
2. filtro por profesional asignado a seguimiento
3.

EP: asignar seguimiento a profesional

---

modules/turnos/controller/diagnosticosC2Controller.ts
modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/MISC-188
1. Visualizador: filtrar reportes c2 x organización
2. 
3.

MISC: filtrar c2 x organización

---

modules/vacunas/controller/vacunas.events.ts
modules/vacunas/schemas/vacunas-pacientes.schema.ts
scripts/VAC-104.ts

https://proyectos.andes.gob.ar/browse/VAC-104
1. Nuevo campo enDomicilio para paciente-vacunas
2. Script para actualizar la coleccion a partir de las prestaciones de campañas de vacunación covid

VAC: nuevo campo enDomicilio para vacunas-paciente

---

modules/seguimiento-paciente/seguimiento-paciente.route.ts

https://proyectos.andes.gob.ar/browse/EP-140
1. 
2. 
3.

EP: filtrar seguimientos activos

---

modules/seguimiento-paciente/seguimiento-pacientes.events.ts

Reemplazar las coordenadas por defecto, por organización por defecto, de manera que se puedan asignar por defecto al CAM.
https://proyectos.andes.gob.ar/browse/EP-118
1. 
2. 
3.

EP: organización x defecto seguimiento

---

modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-117
1. Corrige indicé para obtener datos de la agenda buscada

CIT - Fix solapamiento de agendas con varios profesionales

---

core/log/routes/logPaciente.ts
core/log/schemas/logPaciente.ts

https://proyectos.andes.gob.ar/browse/PDP-73
1. Extiende esquema de logPaciente para guardar reporte de error de PDP

PDP - Guardar reporte de error

---

modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-114
1. Controla que hayan turnos al momento de realizar operaciones de comparación

CITAS - Fix error al liberar turno

---

modules/turnos/routes/turno.ts
modules/turnos/schemas/agenda.ts
modules/turnos/schemas/turno.ts

https://proyectos.andes.gob.ar/browse/CIT-113
1. se agrega la propiedad link
2. 
3.

feat(CIT): se agrega la propiedad link

---

config.private.ts.example
modules/ips/controller/autenticacion.ts
modules/ips/routes/ips.ts

https://proyectos.andes.gob.ar/browse/IO-17
Primera versión del flujo de IPS.

IPS: primera versión 

---

scripts/VAC-104.ts

Verificar porque el script VAC-104 no actualiza el campo enDomicilio en pacientes-vacunas cuando hay más de una aplicación
1. Se arregla el script VAC-104 para que actualice todas las aplicaciones

VAC: arreglo de script para actualizar enDomicilio

---

.eslintrc.js
core/log/routes/logPaciente.ts
core/tm/routes/organizacion.ts
modules/cda/controller/CDAPatient.ts

Reglas para formatear el código, espacios y demás.

chore(lint): reglas de espaciados

---

core/tm/controller/organizacion.ts
modules/turnos/controller/diagnosticosC2Controller.ts

https://proyectos.andes.gob.ar/browse/BI-87
1. Al recibir param de zonaSanitaria, recupera los ids de organizaciones pertenecientes a la zona y filtra por esas organizaciones
2. 
3.

BI: filtro de zona para reportes

---

package-lock.json
package.json

https://proyectos.andes.gob.ar/browse/CORE-96

andes-services: correcto loggueo de error HTTP

---

auth/permisos.ts
scripts/IN-323.ts

https://proyectos.andes.gob.ar/browse/IN-323
1. Se agrega permiso "regitros"  
2. 
3.

feat(mapa-camsa): se agrega permiso para ver registros

---

core/tm/controller/profesional.ts
modules/perinatal/carnet-perinatal.routes.ts

https://proyectos.andes.gob.ar/browse/PER-49
1. Dentro de la api se agrego el atributo fechaControl para poder machear desde la parte de matriculaciones y hacer el filtro por fechas de controles.

PER - 49: filtros por fechas de control 

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-62
1. Se agrego una condición para que se pueda insertar un nuevo posgrado cuando se registra un nuevo profesional.

refactor(MAT-62): Reestructuracion de la solapa de especialidades

---

modules/seguimiento-paciente/interfaces/seguimiento-paciente.interface.ts
modules/seguimiento-paciente/seguimiento-paciente.route.ts

https://proyectos.andes.gob.ar/browse/EP-131
1. Se agrega el campo ultimaAsignacion para guardar el profesional actual encargado del seguimiento y el array para tener el historial de asignaciones.

Epidemiología - Crear filtro en seguimientos para pacientes asignados

---

core-v2/mpi/paciente/paciente.events.ts

https://proyectos.andes.gob.ar/browse/MPI-359
1. Agrega función que verifica cambies en dirección, localidad y provincia

MPI Fix - Georeferencia con cambio de localidad/provincia

---

modules/rup/controllers/elementos-rup.controller.ts
modules/seguimiento-paciente/seguimiento-pacientes.events.ts

Registrar alta y fallecimiento en seguimiento epidemiologico
1. Se agrega un nuevo evento rup:paciente:fallecido para poder registrar el fallecimiento de un paciente en el modulo de seguimiento epidemiologico. Cuando se registre algunos de los conceptos agregados en el nuevo elementoRUP (ver actualizaciones de base de datos), se dispara dicho evento.
2. Se agrego un elementoRup con el concepto "muerto" y sus descendientes.
3. Se agrega el evento que registra los seguimientos, la opción para registrar el alta de un paciente.
[elementoRupFallecido.txt](https://github.com/andes/api/files/7117544/elementoRupFallecido.txt)
```
{
"_id" : ObjectId("613634a10e7ed0fb9ee336e8"),
"defaultFor" : [],
"componente" : "EvolucionProblemaDefaultComponent",
"conceptos" : [ 
{ …
```

Epidemiología - Registrar alta y fallecimiento en seguimiento epidemiologico

---

modules/turnos/controller/historialCitasController/historialCitasController.ts

https://proyectos.andes.gob.ar/browse/CIT-118
1. Se agregó un nuevo parámetro para poder traerme todo el historial fuera de agendas. También se agrego un condicional por si el paciente no esta vinculado con nadie y no devuelva un arreglo vacío innecesario.

fix(CIT-118): Error al mostrar datos de pacientes unificados

---

modules/rup/internacion/censo.controller.test.ts
modules/rup/internacion/censo.controller.ts
modules/rup/internacion/test-utils/index.ts

Se corrige error en el cálculo de los días de estada de el censo diario: se está reiniciando por cada movimiento de cama, sin importar si es el mismo servicio o uno nuevo.
https://proyectos.andes.gob.ar/browse/IN-322
1. Se debe contabilizar la cantidad de días de estada desde el ingreso al servicio, hasta el día que se consulta.
2. Los días de estada se visualizan y se suman sólo cuando se egresa el paciente de la internación o de un servicio.
3.

INT: censo diario se corrige calculo en los días de estada

---

modules/rup/routes/codificacion.ts

https://proyectos.andes.gob.ar/browse/CIT-128
1. Refactor visual, actualiza uso de componentes plex

CITAS (Fix) - Auditar fuera de Agenda: trae registros de internación

---

modules/vacunas/controller/inscripcion-vacunas.events.ts

https://proyectos.andes.gob.ar/browse/VAC-98
1. No se pudo reproducir el error pero se agregó la sincronización de vacunas al validar/domper-validación del concepto como registro

VAC - Sincronizacion de vacunas

---

modules/vacunas/controller/vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/VAC-78
1. Se busca el paciente por id, y si no está activo y tiene paciente asociado se traen los datos del paciente principal

VAC: modificación de proceso para exportar vacunas

---

modules/top/routes/reglas.ts
modules/top/schemas/reglas.ts

https://proyectos.andes.gob.ar/browse/PACS-29
https://github.com/andes/app/pull/2430

TOP: abm reglas servicio intermedio

---

auth/auth.class.ts

https://proyectos.andes.gob.ar/browse/PRIV-34
1. Se reduce la sesión a 8hs 
2. 
3. 
https://github.com/andes/app/pull/2485

feat(auth): session de 8hs

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/BI-108
1. Se lleva el permiso de zonas sanitarias de dashboard a visualización

BI: permiso por zonas sanitarias

---

modules/vacunas/controller/vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/MPI-364
El problema de las direcciones vacías ocurre al momento de exportar un alta a sisa. Por lo tanto se resuelve fixear el campo que da error en lugar de agregar contenido sin información a la colección 'paciente'.

VAC (Fix) - Evita enviar calle sin contenido en alta de vacuna

---

modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts

https://proyectos.andes.gob.ar/browse/EP-162
1. agrega filtro para fichas sin clasificación final.
2. 
3.

EP: filtro sin clasificación final

---

modules/forms/forms-epidemiologia/constantes.ts
modules/forms/forms-epidemiologia/controller/forms-epidemiologia.controller.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
modules/sisa/controller/sisa.controller.ts
modules/sisa/logger/sisaLog.ts

https://proyectos.andes.gob.ar/browse/EP-143
1.  Andes services para sisa ws400, ws75 y ws76 (alta de evento, muestra y determinación, respectivamente).
2. Controller para interoperar con sisa:
- https://sisa.msal.gov.ar/sisadoc/docs/050216/snvs_ws_400.jsp
- https://sisa.msal.gov.ar/sisadoc/docs/050216/snvs_api75_muestralaboratorio.jsp
- https://sisa.msal.gov.ar/sisadoc/docs/050216/snvs_api76_determinacioneslaboratorio.jsp 
[andes_services-SISA.txt](https://github.com/andes/api/files/7338711/andes_services-SISA.txt)

EP: export LAMP SISA

---

modules/sisa/controller/sisa.controller.ts

EP: log sisa params

---

modules/vacunas/inscripcion-vacunas.routes.ts

https://proyectos.andes.gob.ar/browse/VAC-113
1. Se elimina el control del número de trámite

VAC: se elimina el control de número de trámite en la inscripción.

---

jobs/exportNexosFichaSisa.ts
modules/forms/forms-epidemiologia/constantes.ts
modules/forms/forms-epidemiologia/controller/forms-epidemiologia.controller.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.events.ts
modules/seguimiento-paciente/seguimiento-pacientes.events.ts

https://proyectos.andes.gob.ar/browse/EP-163
1. Parametrización de nombre de sección clasificación final
2. 
3.

EP: parametrización clasificación final

---

core-v2/mpi/paciente/paciente.routes.ts

https://proyectos.andes.gob.ar/browse/CIT-130
1. Se filtran las obras sociales en caso de que vengan repetidas y se controlo que en la base de datos de puco solamente se almacene un elemento ya que anteriormente se almacenaban elementos duplicados.

Obras sociales duplicadas

---

auth/permisos.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
package-lock.json
package.json
scripts/EP-167.ts

https://proyectos.andes.gob.ar/browse/EP-167
1. eliminar ficha con permiso restrictivo
2. 
3.

EP: eliminar ficha

---

modules/turnos/controller/historialCitasController/historialCitasController.ts

https://proyectos.andes.gob.ar/browse/CIT-143
1. Filtra prestaciones por ámbito ambulatorio al momento de consultar por el historial fuera de agenda del paciente

CITAS (Fix) - Se muestran prestaciones de registro de internación fuera de agendas en ventanilla citas

---

modules/rup/controllers/estadisticas.ts

https://proyectos.andes.gob.ar/browse/BI-110
1. Filtra solicitudes con turno en caso de aplicar un filtro con estado únicamente 'pendiente'

BI (Fix) - Filtra solicitudes pendientes con turno

---

modules/descargas/informe-rup/elementos-rup/solicitud-default.component.ts
modules/top/schemas/reglas.ts

Campos especificos para diferentes tipos de solicitudes. Queda un ejemplo en DEMO (no real). Concepto a solicitar (prueba de laboratorio).
1.  Se crea un modulo de formuladrios dinámicos.
2.  Se agrega a las reglas de solicitudes templates dinamicos de formularios.
3.  Se adapta la molécula de solicitudes para renderizar estos formularios.
4.  Se modifica la impresión de solicitudes.
https://github.com/andes/app/pull/2478

rup: campos dinámicos para solicitudes

---

core/tm/routes/profesional.ts
core/tm/schemas/profesional.ts

https://proyectos.andes.gob.ar/browse/TM-18
1. Nuevo campo observaciones en el schema de profesional

TM: nuevo campo observaciones en profesional

---

modules/perinatal/controller/carnet-perinatal.events.ts

https://proyectos.andes.gob.ar/browse/PER-59
1. Al romper validacion de un único control de embarazo registrado para un embarazo y paciente se eliminar el registro de la colección carnet-perinatal
2.  Al romper validación actualiza fecha próximo control y último control.
3.

PER: fix actualiza/elimina datos al romper validación

---

core/tm/controller/profesional.ts
core/tm/routes/profesional.ts
core/tm/schemas/profesional.ts
jobs/verificaMatriculasPosgrado.ts
packages/drive/drive.ts

https://proyectos.andes.gob.ar/browse/MAT-31
1. Se agregaron nuevas funcionalidades para guardar y eliminar los archivos necesarios de cada profesional dentro de matriculaciones.

Adjuntar y eliminar archivos relacionados con el profesional 

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-86
1. Se agrego una condicion para evitar que se pushee a una variable null.

MAT: Error al cargar posgrado a profesional recién cargado

---

modules/mobileApp/auth_routes/autenticacionApp.ts
modules/mobileApp/registroMobile.log.ts
modules/mobileApp/routes/paciente.ts

https://proyectos.andes.gob.ar/browse/AM-210
1. Se registra log cuando falla la validación del paciente al registrar nueva cuenta/familiar

AM: registrar log en registros fallidos

---

jobs/exportNexosFichaSisa.ts
modules/forms/forms-epidemiologia/controller/forms-epidemiologia.controller.ts

https://proyectos.andes.gob.ar/browse/EP-171
1. 
2. 
3.

EP: remove update SISA

---

modules/mobileApp/routes/paciente.ts

https://proyectos.andes.gob.ar/browse/AM-209
1. Obtener los datos del familiar a asociar del scan en /registro-familiar

AM: permitir registro de familiar con scan del dni

---

modules/rup/internacion/resumen/internacion-resumen.hook.ts
modules/rup/internacion/resumen/internacion-resumen.routes.ts
modules/rup/internacion/resumen/internacion-resumen.schema.ts

https://proyectos.andes.gob.ar/browse/IN-355
1. se agrega un método al dispatch , cuando se valida la prestación de evaluación inicial medica se guardan conceptos en 
2. la colección internacionResumenPaciente
3. se agrega paciente_id como parámetro de búsqueda en get  internacion-resumen

feat(IN): mostrar registro de diagnostico al ingreso

---

core/log/schemas/logExportaInformacion.ts
modules/vacunas/controller/vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/VAC-117
1. Se agrega en el esquema de informacion exportada el campo idPrestacion, para obtener mas informacion de aquellas vacunas que fueron o no exportadas.
2. Se corrige el proceso exportCovid19 ya que habían vacunas que no migraban, sobre todos las que se registraban en alguna otra prestacion que no era campaña de vacunación y dentro de la prestacion se registraba la campaña como concepto.

Vacunas - Corregir proceso de migración a nomivac de vacunas covid

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MISC-203
1. Se refactorizó el endpoint de profesionales.

MISC - visualización de las matriculas de un profesional

---

modules/descargas/informe-rup/informe-rup.ts
modules/descargas/informe-rup/utils/registro-to-html.ts
modules/rup/controllers/elementos-rup.controller.ts

https://proyectos.andes.gob.ar/browse/RUP-300
1. Se asocia un elementoRUP por default durante la impresión a los registros que no lo posean

fix(rup): descarga de Ecografías tira error 500

---

scripts/VAC-120.ts

https://proyectos.andes.gob.ar/browse/VAC-120
1. Se crea un script que actualiza cada docuemento de la coleccion nomivacInformacionExportada que haya dado OK como resultado, con el id de la prestacion correspondiente para un mejor seguimiento y a futuro no enviar de forma repetida las vacunas a nomivac
- Se hizo una prueba con exito en la base clon de produccion entre feechas: `node scripts VAC-120 2020-12-28 2020-12-31`

Vacunacion - Crear Script para agregar IdPrestacion a informacion exportada

---

modules/rup/internacion/resumen/internacion-resumen.hook.ts
modules/rup/internacion/resumen/internacion-resumen.schema.ts

https://proyectos.andes.gob.ar/browse/IN-337
1. se agrega método  a dispatch para guardar los conceptos cargados en el registro de epicrisis del paciente
2. al momento del egreso del mismo .
3.

feat(IN): se guarda en resumen paciente conceptos al egreso

---

modules/rup/controllers/prestacion.ts
modules/turnos/routes/agenda.ts
modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/TOP-26
1. Desvincula la solicitud del turno suspendido y agrega el registro en el historial

TOP - Suspensión de turno dado a solicitud

---

core/log/schemas/logExportaInformacion.ts
modules/vacunas/controller/vacunas.controller.ts

https://proyectos.andes.gob.ar/browse/VAC-118
1. Se agrega un control para no intentar enviar nuevamente las vacunas  ya enviadas (Si tienen idPrestacion).
- Este PR debe subir luego de que se haya actualizado la coleccion nomivacInformacionExportada con todos los idPrestaciones correspondientes. Script VAC-120

Vacunas - Mejora del proceso de migración de vacunas a nomivac

---

modules/mobileApp/controller/NotificationService.ts
modules/turnos/controller/agenda.ts
modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/AM-189
1. Actualización texto al suspender y reasignar turnos de agendas
2. Agregar notificación cuando se suspende turno individual. 
3. Control al momento de suspender la agenda para que se les envié la notificación solo a los turnos que tengan paciente

MOBILE - Actualizaciones de datos en push

---

modules/rup/routes/codificacion.ts

https://proyectos.andes.gob.ar/browse/CIT-141
1. Nuevo match para id de profesional

CITAS - Filtro por profesional en auditoría de fuera de agenda

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/CIT-148
1. permiso turnos:puntoinicio:darSobreturnos
2. 
3.

CIT: permiso punto inicio dar sobreturno

---

modules/vacunas/controller/vacunas.events.ts

https://proyectos.andes.gob.ar/browse/VAC-119
1. Al romper la validación de una prestacion de vacunación, se modifica el resultado del log para que pueda ser enviada nuevamente.

Vacunas - Modificar estado de vacuna en vacunasInformacionExportada al romper validación

---

core/tm/routes/profesional.ts
modules/matriculaciones/routes/turno.ts
modules/matriculaciones/schemas/turno.ts
modules/matriculaciones/schemas/turnoSolicitado.ts

https://proyectos.andes.gob.ar/browse/MAT-81
1. Se agrega endpoint para búsqueda de profesionales en proceso de renovacion de matrícula.
2. Modifica esquema de turno agregando atribudo con datos del usuario y organización que edita.
3. Agrega filtros por estado en generación de reporte.

MAT - Filtros para renovación de matrículas

---

modules/rup/routes/codificacion.ts
modules/rup/schemas/codificacion.ts

https://proyectos.andes.gob.ar/browse/RUP-304
1. Se agrego el idProfesional a la colección de codificación

RUP - Guardar idProfesional en la coleccion codificacion

---

core/tm/schemas/tipoPrestacion.ts
modules/rup/routes/prestacion.ts
modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/RUP-276
1. se modifica codificación del turno para que acepte multiprestacion
2. se modifica control de prestación  sobre un turno.
3.

RUP: turno Multipretacion

---

core/tm/controller/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-71
1. Se modifico el job vencimientoMatriculaGrado optimizando la consulta que se realiza en el find.

refactor(MAT-71): verificación de vencimiento de formación de grado

---

modules/rup/schemas/codificacion.ts
scripts/BI-112.ts
scripts/update-codificacion.ts

https://proyectos.andes.gob.ar/browse/BI-112
1. Se creo un script para actualizar la coleccion "codificacion" agregando dentro de la misma el id del profesional correspondiente
Es necesario actualizar la query con lo siguiente: 
[query.txt](https://github.com/andes/api/files/7780957/query.txt)

BI - Agregar id del profesional a la colección codificación

---

modules/rup/internacion/cama-estados.controller.ts
modules/rup/internacion/camas.controller.ts

https://proyectos.andes.gob.ar/browse/IN-347
1.  ámbito, paso de requerido a ser opcional .
2. 
3.

refactor(IN): Desacoplar ámbito de las queries

---

modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/CIT-157
1. Actualiza los audit de updated en los casos que la agenda se actualiza por query a la base
2. 
3.

CIT: actualizar updatedAt agenda

---

modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-160
1. 
2. 
3.

CIT: audit created agendda clonada

---

modules/seguimiento-paciente/seguimiento-pacientes.events.ts

https://proyectos.andes.gob.ar/browse/EP-176
1. 
2. 
3.

EP: ignorar seguimiento en apertura ficha

---

modules/descargas/informe-rup/elementos-rup/formula-base.component.ts
modules/rup/schemas/prestacion.registro.ts

ademas edita informe para registros de formulaBase sin valor
https://proyectos.andes.gob.ar/browse/PER-65
1. Agrega atributo booleano 'valorManual'
2. Modifica la generación del informe de rup para que los conceptos que posean el atributo valorManual en true no incluya los registros (requeridos de la formula para el calculo del valor final) en el informe.
Registro de coleccion ElementosRUP con id **ObjectId("6081bc9484ff50fdf474f062")** (FormulaBaseComponent con concepto 'edad gestacional') agregar param 'valorEditable' en true.

RUP (Fix) - Poder editar valor de edad gestacional

---

auth/permisos.ts
core/tm/conceptos-turneables.routes.ts
core/tm/schemas/tipoPrestacion.ts

1. Se agrego la nueva capa interconsultores en auth/permisos.ts
2. Se agrego un arr 'ambitos' a coleccion 'conceptoTurneable' y un boolean 'checkRupTiposPrestacion' en 'internacionEstados' al estado 'Ocupada' para la nueva capa 'interconsultores'
3. Se modifico el shema de tipoPrestacionShema para devolver los ambitos

feat(IN): nueva capa interconsultores

---

modules/vacunas/index.ts
modules/vacunas/routes/vacunas-pacientes.routes.ts

https://proyectos.andes.gob.ar/browse/EP-180
1. Se agrega resourceBase del schema pacientesVacunas para obtener las aplicaciones de las vacunas de los pacientes

Epidemiología - Mostrar en la ficha el estado de vacunacion del paciente

---

modules/rup/routes/prestacion.ts
modules/turnos/controller/agenda.ts
modules/turnos/schemas/turno.ts

https://proyectos.andes.gob.ar/browse/BI-117
1. Al validar una prestación,  en el turno de la misma (si tiene) se guarda el id del profesional validador
2. 
3.

BI: profesional validador turno

---

modules/turnos/schemas/listaEspera.ts

https://proyectos.andes.gob.ar/browse/PDP-76
1. Agrega atributo 'origen' al esquema de lista de espera

PDP - Demanda insastifecha

---

modules/perinatal/controller/carnet-perinatal.events.ts

https://proyectos.andes.gob.ar/browse/PER-66
1. Si el carnet perinatal ya existe y su fecha es mayor a la fecha existente entonces se actualizan los datos de peso previo, fecha de parto, fecha ultima menstruación y talla.

PER - Visualización de datos en carnet-perinatal

---

modules/seguimiento-paciente/seguimiento-paciente.route.ts
modules/seguimiento-paciente/seguimiento-pacientes.events.ts

https://proyectos.andes.gob.ar/browse/EP-175
1. Bloquea para actualización los seguimientos de paciente, una vez q fueron cerrados por fallecimiento.
2. 
3.

EP: bloquear ultimo estado fallecido

---

modules/facturacionAutomatica/routes/configFacturacionAutomatica.ts

Se agrega facturacion prepagas y OS desde buscaordor de turnos
https://proyectos.andes.gob.ar/browse/CIT-149
1. Se agrega evento para facturar a recupero 
2. 
3.

Facturacion:  se agrega facturacion prepagas y OS desde buscador de turnos

---

scripts/BI-115.ts

https://proyectos.andes.gob.ar/browse/BI-114
https://proyectos.andes.gob.ar/browse/BI-115
1. Profesional en scheame de turno
2. Script para incluir profesional en turno de agenda
3. Query de agendas-consolidado incluye date de id de profesional de turno
[query_agenda-consolidado.txt](https://github.com/andes/api/files/7808528/query_agenda-consolidado.txt)

BI: incluir profesional en turno de agenda

---

.eslintrc.js
core/tm/routes/especialidad.ts
core/tm/routes/profesional.ts
modules/turnos/controller/agenda.ts
modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-158
1. Verificamos si al momento de clonar una agenda ya existe una con el mismo profesional o espacio físico para que, en caso afirmativo, se imprima un mensaje de error. En caso contrario se clona la agenda con éxito.

CIT - verificar solapamiento al clonar agendas

---

modules/estadistica/controller/turnos_prestacionesController.ts
modules/estadistica/routes/turnos_prestaciones.ts

https://proyectos.andes.gob.ar/browse/CIT-147
1. Se genera una nueva ruta donde se arma el csv previo a ser descargado. Se implementa una nueva función "obtenerProfesionales" para obtener todos los profesionales de forma ordenada en un string.

CIT - Descarga del csv del listado en turnos y prestaciones

---

config.ts
modules/validar-certificado/routes/validar-certificado.ts

https://proyectos.andes.gob.ar/browse/EP-183
1. Se agrega ruta que consulta si existe un certificado de aislamiento para un paciente.

 Epidemiologia - Pantalla de consulta para certificados de aislamiento

---

modules/validar-certificado/routes/validar-certificado.ts

https://proyectos.andes.gob.ar/browse/EP-188
1. Se agregan nuevos conceptos a la búsqueda de registros para validar certificados. Estos son los mismos que se muestran en la app mobile.

Epidemiología - Agregar conceptos a la validacion de certificados

---

modules/seguimiento-paciente/seguimiento-pacientes.events.ts

https://proyectos.andes.gob.ar/browse/EP-191
1. Se modifica la comprobación para evitar que la prestacion que se registra al confirmar la ficha, se guarde como un seguimiento. Actualmente se estaba comprobando que la prestacion no tenga alguno de los conceptos de confirmación, pero puede ser que en el seguimiento se evolucione alguno de estos seguimientos, entonces se deben guardar. 
2. Se opta por comprobar que la fecha de validación de la prestacion sea mayor a 1 hora que la fecha de actualización/creación de la ficha, para guardar el seguimiento. ( Se buscara mejorar esto )

Seguimiento - Modificar control en epidemiologia:prestaciones:validate (primer seguimiento)

---

auth/permisos.ts
core/tm/schemas/tipoPrestacion.ts

https://proyectos.andes.gob.ar/browse/CIT-153
1. array de ids de queries en `agenda.tipoPrestaciones`
2.  Crear Permiso para carga de pacientes masivos en una agenda
3.

CIT: queries en prestación de agenda

---

core-v2/mpi/paciente/paciente.routes.ts
modules/gestor-usuarios/usuarios.routes.ts

Se redefine post en Gestor de Usuarios para evitar crear duplicados
1. Hay usuarios creados con el campo documento como número, lo que no permite que aparezcan en las búsquedas.
2. 
3. 
db.getCollection('authUsers').update(
{ documento:{$type:'number'}  },
[{  $set: { documento: { $toString:"$documento" }} } ]
)

fix(GDU): se redefine post para evitar crear duplicados

---

modules/rup/internacion/cama-estados.controller.ts
modules/rup/internacion/censo.controller.test.ts
package-lock.json
package.json
packages/unit-testing/index.ts

https://proyectos.andes.gob.ar/browse/IN-392
Si el paciente esta resperidaro, muestra la R de respirador en verde.

feat(mapa-camas): mostrar uso del respirador

---

modules/rup/controllers/prestacion.ts
modules/rup/schemas/prestacion.solicitud.historial.ts
modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/TOP-122
1. Se agrego el id del turno suspendido para obtener la prestacion y reasignarle el turno correspondiente y generar un nuevo historial.

TOP - Agenda suspendida

---

core-v2/mpi/paciente/paciente.controller.ts

Corrige error por variable mal nombrada.
1. 
2. 
3.

Georeferencia: corrige error al georeferenciar

---

modules/seguimiento-paciente/seguimiento-paciente.route.ts

https://proyectos.andes.gob.ar/browse/EP-190
1. 
2. 
3.

EP: filtro score

---

package-lock.json
package.json

https://proyectos.andes.gob.ar/browse/MPI-371
1. 
2. 
3.

chore(package): api-tools 2.3.0

---

jobs/exportNexosFichaSisa.ts

https://proyectos.andes.gob.ar/browse/EP-200
1. Existen fichas que se crean en un momento y al tiempo se confirman / descartan. El job filtra por fecha createdAt y en el caso que se confirme un tiempo después, estas fichas no se van a exportar, por lo que se agrega el match por el campo updatedAT.

JOB - Casos de fichas confirmadas no exportadas a SISA

---

modules/rup/controllers/estadisticas.ts

https://proyectos.andes.gob.ar/browse/TOP-123
1. Se modificaron los estados de la operacion aggregate para que la informacion que se ve en el listado de top figure exactamente igual que el dashboard.

TOP - No mostrar como pendientes las solicitudes con turnos dados en el dadshboard

---

jobs/exportNexosFichaSisa.ts

fix(job-sisa): elimina update temporal

---

modules/descargas/informe-rup/informe-firma.ts

https://proyectos.andes.gob.ar/browse/MAT-80
1. Las firmas de los profesionales no figuraba cuando se descargaban desde el modulo de citas. Entonces se agrego una ternaria para verificar si existe el id del profesional del cual se manda tanto de RUP como de CITAS.

fix(MAT-80): Falta firma del profesional

---

core/term/controller/snomed.snowstorm.ts

https://proyectos.andes.gob.ar/browse/BI-109
1.  Se modifico los datos que se almacenan en el arreglo result dentro de la funcion filterRelationships

BI - Proximos padres

---

modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-165
1. Se modifican las instancias de logueo para guardar solo datos principales de la operación

CIT - Refactor logs de agendas

---

core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-375
1. Se modifico el schema de paciente para que se almacene de forma correcta la variable tipoIdentificacion

MPI - fix en el campo tipo de identificacion en pacientes extranjeros

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-398
1. Se corrige nombre de la colección en el esquema y se elimina código comentado

IN (Plan indicaciones) - Permitir cambiar de secciones

---

package-lock.json
package.json

https://proyectos.andes.gob.ar/browse/MPI-380
1. Se actualiza paquete de fuentes autenticas con la versión  1.0.9
2. 
3.

Fuentes-autenticas: se actualiza fuentes autenticas

---

core-v2/mpi/jobs/updateRelacionesPacientes.ts
core-v2/mpi/jobs/updateRelacionesPacientesJob.ts
core-v2/mpi/mpi.log.ts
core-v2/mpi/paciente/paciente.events.ts
core-v2/mpi/paciente/paciente.interface.ts
core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-374
1. Se agregan atributos de fechaNacimiento y activo en las relaciones de un paciente.
2. Script para actualizar las relaciones de un paciente (se actualizan varios campos).
3. Fix al actualizar un paciente con direccion:null.

MPI: atributos fechaNacimiento y activo en las relaciones de un paciente

---

modules/pacs/dicom/prestacion-encode.ts

Pacs - Se revierten cambios temporalmente

---

core-v2/mpi/jobs/updateRelacionesPacientes.ts

Se filtran pacientes que no se contiene el id en la relacion (referencia)
1. 
2. 
3.

fix(mpi): actualiza job relaciones

---

modules/rup/internacion/censo.routes.ts

https://proyectos.andes.gob.ar/browse/IN-342
1. Nuevas rutas para daescarga de los censos en csv

IN - Descarga de censos en csv

---

modules/seguimiento-paciente/seguimiento-paciente.route.ts

https://proyectos.andes.gob.ar/browse/EP-193
1. Nueva ruta en recurso de seguimiento de pacientes para descargar listado por csv
- [X ] No

EP - Permitir descarga de un csv con reporte de seguimientos

---

modules/huds/export-huds/exportHuds.routes.ts

https://proyectos.andes.gob.ar/browse/MISC-227
1. En buscador de prestaciones, ordena descargas de más reciente a más antigua
2. 
3.

MISC: en buscador ordenar descargas

---

modules/forms/forms.schema.ts

https://proyectos.andes.gob.ar/browse/EP-204
1. Se agrega el array de items al schema field para agregar los elementos del select-static.

Epidemiología - Select static para ficha covid 19

---

modules/descargas/informe-rup/informe-body.ts

https://proyectos.andes.gob.ar/browse/IN-404
1. Se crea un nuevo arreglo en donde se filtran los registros que no están vacíos.

IN - secciones vacias dentro del pdf de evaluacion inicial

---

modules/descargas/informe-rup/informe-body.ts

Epicrisis - No se muestra al descargar el resumen de internacion

---

modules/pacs/dicom/prestacion-encode.ts

fix(pacs): reverse tags

---

modules/pacs/dicom/prestacion-encode.ts

Revert "fix(pacs): reverse tags"

---

core-v2/mpi/paciente/paciente.events.ts

https://proyectos.andes.gob.ar/browse/MPI-378
1. se agrego una nueva funcionalidad dentro del evento de modificar un paciente para que actualice todas sus relaciones.

MPI - Relaciones de un paciente

---

modules/descargas/informe-censo/censo-mensual-body.ts
modules/descargas/informe-censo/censo-mensual-header.ts
modules/descargas/informe-censo/informe-censo.ts
modules/descargas/routes/descargas.ts

https://proyectos.andes.gob.ar/browse/IN-410
1. Se modifican estilos del pdf de los censos. 
2. Se setea orientacion horizontal de pagina para censo mensual. 
3. Se quita el footer de todas las paginas.

IN - Censos - Descarga PDF CSV

---

modules/forms/forms.schema.ts

https://proyectos.andes.gob.ar/browse/EP-107
1. Se agregan las dependencias al esquema.
2. 
3.

Form - Dependencias

---

core/tm/controller/authUser.ts
jobs/desactivarUsuarios.ts

https://proyectos.andes.gob.ar/browse/GDU-42
1. Se creo un job para desactivar a los usuarios cuya variable lastLogin sea mayor a 3 meses

feat(GDU-42): desactivar usuarios no logueados

---

initialize.ts
modules/forms/forms-resources/forms-preset-resources-routes.ts
modules/forms/forms-resources/forms-preset-resources-schema.ts
modules/forms/index.ts

https://proyectos.andes.gob.ar/browse/EP-206
1. Secciones pre cargadas para creación de template de formulario
2. 
3. 
Colección nueva `formPresetResources`
[formPresetResources.txt](https://github.com/andes/api/files/8621252/formPresetResources.txt)

EP: secciones precargadas 

---

core-v2/mpi/paciente/paciente.events.ts

https://proyectos.andes.gob.ar/browse/IN-393
1. Agrega funcion en evento update de paciente, para actualizar los datos basicos en los estados de la internacion actual (si la tuviera), resumen de internacion y prestación que contiene el informe de ingreso.

IN (Fix) - Actualiza internación al modificar datos básicos del paciente en MPI

---

modules/cda/routes/cda.ts

fix(MISC): cda duplicados

---

package-lock.json
package.json

Agregar al package las nuevas versiones de api-tool y core
1. Se actualizan las versiones para usar la paginacion en el buscador de seguimientos epidemiologicos.

Api tool - Nuevas versiones de core y api tool

---

modules/rup/internacion/censo.controller.ts

https://proyectos.andes.gob.ar/browse/IN-409
1. En la función realizarConteo verificamos si las prestaciones son censables o no para sumarlas a la variable 'disponible'.

IN - Camas censables y no censables

---

modules/cda/routes/cda.ts
modules/forms/forms-epidemiologia/controller/forms-epidemiologia.controller.ts

https://proyectos.andes.gob.ar/browse/EP-195
1.  Route para post de cda de sisa
2. 
3.

CDA: route para cda sisa

---

modules/pacs/dicom/prestacion-encode.ts
package-lock.json
package.json

PACS - fix tags

---

jobs/exportNexosFichaSisa.ts
jobs/exportNexosSisa.ts

Se corrige el id de clasificación para la apertura de casos en el job de prestaciones y el control. del ámbito para. el job que busca por fichas.
- [] No

FIX(EPI): se corrige clasificación para  apertura de casos covid

---

auth/permisos.ts

[GDU-49](https://proyectos.andes.gob.ar/browse/GDU-49) - Filtrar por ámbito ambulatorio al dar permisos para el gestor de agendas
1. Se agrego en el archivos permisos.ts un subtipo que contiene el ambito de las prestaciones para las citas con turno
2. 
3.

feat(GDU-49): se agrega subtipo ambulatorio

---

.github/workflows/build.yml
package-lock.json
package.json

Bajar dependencias dev para que no rompa el build de la api en condorpiedra.
1. Se baja dependencias dev (eslint) para que buildee correctamente la api.
2. Se baja la versión de node en build.yml para que el action configurado no de error.

Fix package

---

core-v2/mpi/paciente/paciente.events.ts

Corregir error por paciente no internado
1. Realiza control sobre internacion existente de un paciente
2. 
3.

fix(mpi): event paciente

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-358
1. Registrar motivo de suspensión de indicaciones
2. 
3.

IN: motivo suspensión indicación

---

modules/turnos/controller/diagnosticosC2Controller.ts

https://proyectos.andes.gob.ar/browse/MISC-225
1. Se modificaron los aggregate para que se puedan traer las agendas filtradas mediante el código.

MISC - Agregar filtro por conceptos en el reporte c2

---

core/tm/schemas/organizacion.ts
jobs/exportNexosFichaSisa.ts
modules/sisa/controller/sisa.controller.ts

https://proyectos.andes.gob.ar/browse/EP-210
1. En job `exportSisaFicha`, luego de dar de alta caso en ws400, se sa de alta muestra (ws75) y determinación (ws76)
2. 
3. 
[andes-services.txt](https://github.com/andes/api/files/8961155/andes-services.txt)

EP: confirmacion SISA

---

modules/matriculaciones/routes/turnoSolicitado.ts

https://proyectos.andes.gob.ar/browse/CIT-181
1. 
2. 
3.

fix(CIT): Cannot set headers..

---

jobs/perinatalFechaFinEmbarazo.ts

Se agrega control por error detectado en logs: "Cannot read properties of null (reading 'toString')" del job de perinatal cuando se traen datos desde sip-plus.
1. 
2. 
3.

fix(PER):corrige error por número embarazo inexistente

---

jobs/exportNexosFichaSisa.ts

Corregir el JOB que carga eventos en sisa desde las fichas epidemiológicas. No se estaba registrando la fecha de resultado de la determinación. 
1. 
2. 
3.

fix(JOB): Se Agrega fecha de  emisión de resultado

---

modules/rup/controllers/prestacion.ts
modules/rup/routes/prestacion.ts

…nomed
https://proyectos.andes.gob.ar/browse/RUP-317
1. Se modifica función de snomed agregando parámetros para refinar la búsqueda por expresión

RUP - Componente para visualización de alergias

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/GDU-50
1. Se elimino el permiso de punto de inicio que se encuentra dentro del modulo de internacion para que no se den dichos permisos desde el gestor de usuarios.

GDU - eliminar permiso del punto de inicio en internacion

---

auth/permisos.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.hook.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/IN-475
1. Nuevo method en dispatch de elemento rup para ejecutar mas rapidamente los hooks de plan de indicaciones
dispatch del elementoRUP **ObjectId("5ea76e3cc4baa64a68b04390")**  _(Concepto plan de indicaciones médicas)_ debe quedar asi: 
[
{
"event" : "mapa-camas:plan-indicacion:create",
"method" : "plan-indicaciones-validar-prestacion"
}
]

IN - Plan indiaciones: Actualizar vista al validar indicaciones pendientes

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-469
1. Nuevos atributos en el esquema de plan de indicaciones para almacenar la verificacion

IN - Perfil interconsultor para farmacia

---

shared/constantes.ts

Reportan que no se puede registrar extranjeros
1. Correccion de constante en api

MPI (Fix) - Registro extranjeros

---

core/tm/routes/profesional.ts
core/tm/schemas/profesional.ts
modules/matriculaciones/routes/turnoSolicitado.ts
scripts/fix-sexo-profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-93
1. Se modifica la ruta matching para comparar tambien por sexo del profesional y además comparar con no matriculados en andes

MAT(Fix) - Se crean profesionales duplicados

---

modules/rup/internacion/internacion.controller.ts

https://github.com/andes/api/compare/IN-477
1. Se quita el control de filtro para rango de ingreso obligatorio
2. Se ajustan las fechas de filtros para cubrir el día entero
3.

INT: Se cambia filtros en el GET de prestaciones de internacion

---

modules/turnos/routes/turno.ts

- Al momento de reasignar un turno, se agrega filtro en la búsqueda de solicitudes que pudieran estar asociadas al tunos que se esta reasignado. Esto porque la consulta original no esta utilizando ningún indice.
1. Agrega filtro a la consulta de prestaciones (solicitudes) en reasignación de turno.
2. 
3.

FIX(CITAS): Agregar filtros en  reasignación de turno

---

core/tm/routes/organizacion.ts
core/tm/schemas/organizacion.ts

https://proyectos.andes.gob.ar/browse/IN-349
1. Nuevo parámetro de búsqueda de organizaciones

TM - ABM para configuración de internación

---

core-v2/mpi/paciente/paciente.routes.ts

Se inhabilita el acceso a foto del paciente, temporalmente
Se agrega control de parámetros vacíos en el acceso a datos de pacientes.
1. 
2. 
3.

fix(MPI): Se quita acceso a foto del paciente

---

core-v2/mpi/paciente/paciente.routes.ts

Cambia el control de parámetros vacíos en el get de pacientes
1. 
2. 
3.

fix(MPI): Cambia el control de parámetros para búsqueda de pacientes

---

modules/rup/internacion/camas.controller.test.ts
modules/rup/internacion/camas.controller.ts
modules/rup/internacion/camas.routes.ts
modules/rup/internacion/camas.schema.ts
modules/rup/internacion/censo.controller.test.ts
modules/rup/internacion/internacion.controller.test.ts

https://proyectos.andes.gob.ar/browse/IN-491
1. Nueva ruta para edicion de camas
2. Refactor de ruta para edicion de una cama y sus respectivos estados. En lugar de esto, ahora solo edita estados correspondientes a un id de cama.
3. Desacoplamiento de guardado y edicion de camas-estados en controller.

IN - Error al editar camas

---

modules/descargas/informe-rup/informe-body.ts
modules/descargas/informe-rup/informe-firma.ts

https://proyectos.andes.gob.ar/browse/HUDS-56
1. Evita buscar la firma (Para agregarla en el informe) en caso que la prestación la haya validado un profesional

HUDS - Error en la descarga PDF

---

modules/descargas/informe-rup/informe-firma.ts

Soluciona el acceso a los datos del profesional por usuario que valida la prestación
1. 
2. 
3.

FIX(RUP): cambia búsqueda de profesional para la  firma

---

modules/pacs/dicom/paciente-encode.ts
modules/pacs/dicom/prestacion-encode.ts

FIX(PACS): Cambia configuración de charset

---

modules/turnos/controller/agenda.ts
modules/turnos/schemas/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-185
1. En el esquema de Agenda se agrego el campo motivoDeSuspension para que después se pueda editar con el motivo de suspensión que se carga desde la app

CIT - Guardar motivo de suspension de agenda

---

modules/top/routes/reglas.ts

https://proyectos.andes.gob.ar/browse/TOP-134

TOP - Listado reglas

---

modules/top/routes/reglas.ts

1. Agrega sort por prestacion destino a la query

Fix en listado de reglas TOP/RUP

---

modules/rup/controllers/solicitudes.controller.ts

https://proyectos.andes.gob.ar/browse/TOP-144
1. Al crear una nueva prestación desde RUP, con fecha previa a la actual, las solicitudes creadas a partir de la misma obtienen la fecha seleccionada para la prestación de origen.

feat(TOP): nueva solicitud con misma fecha que prestacion

---

modules/rup/internacion/cama-estados.schema.ts

[](https://proyectos.andes.gob.ar/browse/IN-517)
1. Se extiende el esquema de camaEstados agregando un extra

IN (Fix) - Desbloqueo de cama duplicado

---

modules/rup/routes/codificacion.ts

https://proyectos.andes.gob.ar/browse/CIT-199
1. Se modifico el aggregate para que ahora pueda filtrar por el id de prestacion
2. 
3.

feat(CIT-199): Agregar filtro de prestacion en el sidebar

---

modules/descargas/informe-rup/utils/registro-to-html.ts
modules/rup/schemas/prestacion.registro.ts

https://proyectos.andes.gob.ar/browse/RUP-329
1. Agrega atributo 'params' a esquema de registros de prestacion.

RUP - Nueva molecula ACV

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-147
1. Se agrego una condición nueva para que pueda filtrar por fechas de actualización de las solicitudes y que se puedan ordenar de forma descendente.

TOP - filtros fecha de actualizacion

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/IN-330
1. Permisos para plan de indicaciones
2. 
3.

IN: permisos plan indicaciones

---

core/tm/schemas/profesional.ts
modules/descargas/matriculaciones/credencial-profesional-body.ts

https://proyectos.andes.gob.ar/browse/MAT-126
https://proyectos.andes.gob.ar/browse/AM-236
1. Agrega atributo 'renovacionOnline' a esquema de profesional
2. Modifica pdf de credencial digital de profesional

MAT - Detalles en descarga de pdf

---

auth/auth.controller.ts
auth/routes/routes.ts
auth/schemas/authUsers.ts

https://proyectos.andes.gob.ar/browse/GDU-55
1. Se agregó el atributo lastLogin para cada organización.
2. Nota: para probar si funciona para más de un efector tener habilitado más de uno.

GDU- Agregar atributo lastLogin por efector

---

core/tm/schemas/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-132
1. Se agrega el objeto rechazarOnline dentro de una formacion de grado de un profesional.

MAT - Agregar rechazo de una renovacion online

---

modules/cda/controller/CDAPatient.ts

fix(CDA): se corrige error al generar CDA de paciente con sexo otro

---

modules/estadistica/controller/procesarAgendas.ts
modules/estadistica/controller/procesarFueraDeAgenda.ts
modules/estadistica/controller/turnos_prestacionesController.ts

https://proyectos.andes.gob.ar/browse/MISC-266
1. se modifican los aggregates de las funciones "procesar" para que permitan filtrar por nombre, apellido y documento de un paciente.

MISC - refactor de los filtros

---

modules/rup/internacion/estados.schema.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.hook.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-511
1. Se agrega una condición para verificar si el elemento rup que viene es una indicación de un medicamento y no una indicación de hidratación.

IN - balance hidrico en el plan de indicaciones

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/RUP-344
1. Se agrega permiso para acceder al link de plantillas: https://demo.andes.gob.ar/rup/plantillas
2. Se agrega permiso _plantilla_ para el módulo de _RUP_. Colección authUsers->organizaciones->permisos->rup:plantilla

RUP - Agrear permiso para abm de plantillas

---

scripts/MAT-134.ts

https://proyectos.andes.gob.ar/browse/MAT-134
1.  Se creó un script para actualizar la colección de profesionales desde la colección especialidad.
NOTA: Se buscan los profesionales que tengan formacionPosgrado.especialidad y que formacionPosgrado.especialidad._id sea null o 'formacionPosgrado.especialidad.codigo.sisa' sea null o 'formacionPosgrado.especialidad.habilitado' sea null.

MAT - Script p/actualizar especialidades de Profesionales

---

package-lock.json
package.json
utils/roboSender/sendEmail.ts

fix(send-mail): corrige error envío mail

---

modules/huds/export-huds/exportHuds.routes.ts

[MISC-228](https://proyectos.andes.gob.ar/browse/MISC-228) - Agregar filtro a la pantalla de descargas pendientes
1. Se modifico la búsqueda en huds para que se puede filtrar por fechas
2. 
3.

feat(HUDS): Agregar filtro de descargas pendientes

---

modules/descargas/informe-rup/informe-body.ts

https://proyectos.andes.gob.ar/browse/HUDS-55
**GLPI (Solucionar al mergear este PR)**
https://glpi.andes.gob.ar/front/ticket.form.php?id=3157
1. Corrige el origen de la fecha de ejecucion y se reemplaza este titulo por 'fecha de consulta'.

HUDS - Fecha de registros medicos no coinciden

---

core-v2/mpi/paciente/paciente.events.ts
core-v2/mpi/paciente/paciente.schema.ts
modules/centroOperativoMedico/schemas/derivaciones.schema.ts
modules/descargas/informe-censo/censo-body.ts
modules/descargas/informe-rup/informe-header.ts
modules/perinatal/schemas/carnet-perinatal.schema.ts
modules/prestamosCarpetas/schemas/prestamo.ts
modules/rup/internacion/cama-estados.schema.ts
modules/rup/internacion/censo.routes.ts
modules/rup/internacion/internacion.controller.test.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts
modules/rup/internacion/resumen/internacion-resumen.schema.ts
modules/rup/internacion/sala-comun/sala-comun-movimientos.schema.ts
modules/rup/internacion/sala-comun/sala-comun.schema.ts
modules/rup/internacion/test-utils/index.ts
modules/rup/schemas/prestacion.ts
modules/seguimiento-paciente/interfaces/seguimiento-paciente.interface.ts
modules/seguimiento-paciente/schemas/seguimiento-paciente.schema.ts
modules/seguimiento-paciente/seguimiento-pacientes.events.ts
modules/turnos/schemas/listaEspera.ts
modules/turnos/schemas/turno.ts
modules/vacunas/interfaces/inscripcion-vacunas.interface.ts
modules/vacunas/schemas/inscripcion-vacunas.schema.ts
modules/vacunas/schemas/vacunas-pacientes.schema.ts

https://proyectos.andes.gob.ar/browse/MISC-226
1. Se completa subesquema de paciente preexistente para su reutilización en esquemas que guardan un set de datos reducidos del paciente. De manera que cada recurso nuevo que lo requiera, utilice este subesquema y de ser necesario le agregue atributos en la seccion 'extras'. 
Todo esto a modo de no perder información del alias, genero y numero de identificacion extranjera que por lo general no se tienen en cuenta.

MISC - Agregar alias y documento extranjero a datos de paciente

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/IN-525
1.  Se agrega un nuevo permiso llamado aceptarRechazar

IN - se agrega nuevo permiso al plan de indicaciones

---

utils/roboSender/sendEmail.ts

Se agrega el campo "from" a la configuración del emailClient para una configuración particular por organización. 
1. 
2. 
3.

fix(MISC): Agrega 'from' al EmailClient

---

modules/turnos/controller/agenda.ts

[https://proyectos.andes.gob.ar/browse/CIT-213](https://proyectos.andes.gob.ar/browse/CIT-213)
1. Se agrega la codificación del turno en el evento de validar prestación
2. 
3.

fix(CITAS): agrega codificación en evento de  validar prestación

---

modules/rup/controllers/prestacion.ts
modules/rup/routes/prestacion.ts
modules/rup/schemas/prestacion.solicitud.historial.ts

https://proyectos.andes.gob.ar/browse/TOP-131
1. Se modifica esquema y controller y router para poder almacenar las notificaciones provenientes de la app agregando las condiciones necesarias cuando solamente se quiere agregar una notificación. 
2. 
3.

TOP - Seguimiento de llamados telefonicos a pacientes

---

core-v2/mpi/validacion/validacion.controller.ts

Se agrega control por posible error al validar con Renaper 
1. 
2. 
3.

MPI: controles en la validación con Renaper

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/CIT-211
1. Se agrega permiso para visualizar solicitudes.

CITAS - Separar permiso de creación de solicitudes

---

modules/pacs/pacs.ts

[almacenar Scheduled Procedure Step ID](https://proyectos.andes.gob.ar/projects/PACS/issues/PACS-38?)
1. Al momento de programar un estudio se almacena el ID de la órden de trabajo en el PACS. Este dato se requerirá en otra user [Cancelar orden de trabajo](https://proyectos.andes.gob.ar/projects/PACS/issues/PACS-37) 
- [ x] Si
- [ x] No
n/a

PACS-38 - PACS - Store of Scheduled Procedure Step ID in Prestacion

---

modules/turnos/schemas/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-218
1. Se agrega nuevo atributo en el schema de Agenda.

(feat) CIT - Agregar configuracion de multiprofesional

---

modules/rup/internacion/estados.schema.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.hook.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-538
1. Se agrega un atributo booleano requiereAceptacion para verificar si una indicacion necesita la aceptacion de un farmaceutico o pasa directo a estar aceptada. 
2. 
3. 
En la coleccion internacionEstados es necesario agregar el atributo booleano requiereAceptacion true en caso de ser una indicacion de medicacion, en caso contrario se agrega dicho atributo en false.

IN - Plan indicaciones: dar opción para validar o no una indicación

---

modules/rup/internacion/estados.schema.ts

https://proyectos.andes.gob.ar/browse/TM-25
1. Nuevo atributo 'checkRupTiposPrestacion' en esquema de estados

TM - Configuracion de internacion por conceptos turnuables

---

core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-406
Enlace a PR APP
https://github.com/andes/app/pull/2887
1. Se agrega columna con dato "Creado por" que muestra el usuario que creó ese paciente. Cuando no existe el usuario se autocompleta con "S/D" (sin dato).
2. Se crea interfaz ICreatedBy

MPI- Auditoria de pacientes- Creado por

---

core/tm/routes/profesional.ts

Agregar cuit de profesional al GET de la guía profesional

feat(MAT):  Agrega cuit a salida de guía profesional

---

modules/rup/routes/prestacion.ts

[TOP-113](https://proyectos.andes.gob.ar/browse/TOP-113) - Error solicitud anulada con turno dado
1. Se agrego un control para verificar si la prestación ya esta anulada, entonces no puede cambiar el estado
2. Se agrego un control para verificar si la prestación ya tiene un turno dado, entonces no se puede anular
3.

TOP - Error solicitud anulada con turno dado

---

auth/ldap.controller.ts

Agrega un "unbind" para cerrar la conexión al server ldap
1. 
2. 
3.

fix(AUTH): Cierra la conexion al server ldap

---

jobs/perinatalFechaFinEmbarazo.ts

[PER-75](https://proyectos.andes.gob.ar/browse/PER-75) - Actualizar job perinatal
1. Se modifica el jobs para contemplar cuando la cantidad de embarazos son superiores a 10
2. 
3.

PER-75 - Actualizar job perinatal

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-131
1. Cuando desde matriculaciones se selecciona una renovacion online, en la api se capta el dato y busca el profesional con ese estado en su matricula. 
2. En caso de que "no aplicar", se devuelve todos los presionales que no tengan un estado en  la matricula.
3. Lineas relevantes: todas menos la 1217 (por correcion de linteo).

MAT: Agregar condiciones para filtrar renovacion online

---

modules/pacs/pacs-network.ts
modules/pacs/pacs.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/PACS-37
1.  Se agrega funcionalidad para anular el pacs al momento de anular la prestacion asociada.
2.  Ademas se contempla el metodo que contabiliza los pacs que se encuntran en el servicio.
3. Se sugiere cargar un paciente fuera de agenda en el modulo de RUP, con las prestaciones configuradas en la coleccion de   PACS-CONFIG (radiografía simple (procedimiento), ecografía diagnóstica (procedimiento), fibrobroncoscopia (procedimiento), etc).

(FEAT) PACS - Cancelar orden de trabajo

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-140
https://github.com/andes/matriculaciones/pull/210
1. Corregido bug de listado nulo al tener una formación de grado sin matrícula
2. Corregido vencimiento de matrícula, ahora se verifica con "fecha fin"

MAT - Filtros en guía profesional

---

modules/pacs/pacs-network.ts

corrige error en url al cambiar estado
1. 
2. 
3.

PACS: se corrige error en url al cambiar estado

---

core/tm/routes/profesional.ts

1. Agrega chequeo de profesional en el user para permitir el acceso.

MAT - Permiso para profesionales

---

core/tm/routes/profesional.ts

MAT - Habilita permisos para firma desde mobile

---

modules/centroOperativoMedico/derivaciones.routes.ts
modules/descargas/agenda/agenda-body.ts
modules/descargas/informe-rup/informe-header.ts
modules/estadistica/controller/procesarAgendas.ts
modules/perinatal/carnet-perinatal.routes.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/MPI-407
1. Se agrega acciones para filtrar por numero de identificacion y/o alias

MPI: Identidad autopercibida

---

modules/huds/export-huds/exportHuds.controller.ts
modules/huds/export-huds/exportHuds.schema.ts
utils/roboSender/index.ts
utils/roboSender/roboSchema.ts
utils/roboSender/roboSender.ts

https://proyectos.andes.gob.ar/browse/MISC-275
1. Se agrega fecha de expiración -expiredAt- a esquemas de roboSender (elementos de sendMessageCache) para envío de mails y exportación de HUDS
2. Al correr el job de roboSender, se comparan fechas de creación con fecha de expiración para verificar que se encuentran en un periodo de tiempo aceptable
3. La ejecución es normal si la fecha actual no es mayor que la fecha de expiración y en caso contrario se actualizan los estados con status Error
4. Se reemplaza el uso de Date por Moment

MISC - Control de fechas para cache de robosender

---

modules/perinatal/controller/carnet-perinatal.events.ts

https://proyectos.andes.gob.ar/browse/PER-80
1. Se corrige actualizar  FechaProximoControl.
2. Nota:  Fijarse que solo se hizo esta modificación: se sacó las líneas 51 y 53. Y se dejó la 52:            
carnetExistente.fechaProximoControl = fechaProximoControl;

PERINATAL - No se actualiza la fecha de próximo control 

---

modules/matriculaciones/routes/turnoSolicitado.ts
modules/matriculaciones/schemas/turnoSolicitado.ts

https://proyectos.andes.gob.ar/browse/MAT-110
1. Se agrego el plugin AuditPlugin y se agrego el .audit(...) para que se pueda crear en la BD el createdAt y el createdBy que va a contener los datos basicos de la persona que lo creo.

MAT - Agregar campo created en BD

---

modules/rup/routes/prestacion.ts

En las bandejas de entrada o salida de top, Se corrige un error en el filtro de búsqueda por pacientes que no tenían identificación extranjera o el dato de identidad autopercibida.
1. 
2. 
3.

TOP: agrega control en búsqueda por paciente

---

auth/auth.controller.ts
core/tm/controller/profesional.ts
core/tm/routes/profesional.ts
modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-169
1. Al recibir en la query del get parametros de prestaciones, se filtra adicionalmente que los profesionales estén habilitados para registrar dichas prestaciones
2. Al guardar o modificar una agenda, se valida que los profesionales posean permiso para registrar al menos un de las prestaciones de la agenda
3.  *Nota: se realizó cambio en la línea 303 del archivo modules/turnos/routes/agenda.ts.

CIT - Control de permisos de prestaciones en profesionales

---

scripts/eliminarProfesionalesDuplicados.ts

https://proyectos.andes.gob.ar/browse/MAT-141
1.  Se modifico el script de eliminarProfesionalesDuplicados donde se inactiva el profesional viejo, si este tiene un grado que el duplicado no tenga entonces se le asocia dicho grado pero si las profesiones son iguales aunque los numeros de matriculas no entonces se ignoran dichos casos. Si el profesional viejo tiene foto y firma y el duplicado no entonces se le asocian tanto la firma como la foto. 
GLPI  asociado: https://glpi.andes.gob.ar/front/ticket.form.php?id=3801
NOTA: No son necesarios los cambios en la BD pero si una ves que se ejecute este script va a ser necesario tener que armar otro para que elimine aquellos profesionales cuyo atributo en la base sea activo:false.
NOTA 2: Para probar dicho script pegar en la colección de …

MAT - script de profesionales duplicados

---

core/tm/controller/profesional.ts

Se agregar un control al buscar un profesional con permiso por prestación por error recurrente en api detectado en APM:
_Cannot read properties of null (reading 'map')_
1. 
2. 
3.

CITAS: control al buscar un profesional con permiso por prestación

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/TM-27
1.  Se agrega nueva condición de filtro para profesionales no matriculados.
2. 
3.

TABLAS MAESTRAS - Nuevo filtro tm/profesional

---

modules/huds/export-huds/exportHuds.controller.ts
modules/huds/export-huds/exportHuds.schema.ts
utils/roboSender/index.ts

https://proyectos.andes.gob.ar/browse/HUDS-83
1. Obtiene filtros desde la prop -excluye-.
2. Aplica filtros para no incluir los CDAs cuyo concepto SNOMED coincida con los que contiene -excluye-

HUDS - Agrega filtro de CDAs al exportar HUDS

---

auth/permisos.ts
modules/cda/controller/CDAPatient.ts
modules/cda/routes/cda.ts
modules/huds/hudsAccesos.controller.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/PRIV-66
1.  Se agrego un permiso mas al modulo HUDS que restringe las visualizaciones de los efectores.
2.  Se modifico el aggregate para que filtre, en caso de ser necesario, por los efectores en el cual el usuario esta logueado.

PRIV - Restricción por efector

---

initialize.ts
modules/huds/motivosHuds/index.ts
modules/huds/motivosHuds/motivosHuds.routes.ts
modules/huds/motivosHuds/motivosHuds.schema.ts

https://proyectos.andes.gob.ar/browse/PRIV-64
1. Se crea una nueva colección llamada motivosHuds.

HUDS - Cargar/obtener motivos de accesos desde la HUDS 

---

jobs/vencimientoPrestacion.ts
modules/rup/controllers/prestacion.ts
modules/rup/prestaciones.interface.ts
modules/rup/schemas/prestacion.estado.ts

https://proyectos.andes.gob.ar/browse/TOP-156
https://proyectos.andes.gob.ar/browse/TOP-157
link a PR app
https://github.com/andes/app/pull/2907
1.  Agregado al esquema nuevo estado de solicitud 'vencida'
2. Agregado Job 'vencimientoPrestacion' que cumple requisito TOP-157, pero acotando la revisión de las prestaciones hasta 3 años en el pasado para evitar prestaciones con datos incompletos.

TOP - Solicitudes: Nuevo estado vencido / Job estado vencido

---

modules/cda/controller/CDAPatient.ts

1. Corrige condición para mostrar cdas

HUDS (FIX) - Filtro por efector

---

scripts/MAT-152.ts

https://proyectos.andes.gob.ar/browse/MAT-152
1. Se agrega script para corregir dentro de los profesionales, el objeto de entidadFormadora,
2.  Se toma como referencia el código o nombre para despues realizar la busqueda en la coleccion EntidadFormadora.

MAT - Script para corregir entidadFormadora

---

modules/cda/routes/cda.ts

orrige respuesta al fallar la creación de un CDA
1. 
2. 
3.

CDA: corrige respuesta de error al crear un CDA

---

modules/descargas/matriculaciones/certificado-etica-body.ts

https://proyectos.andes.gob.ar/browse/MAT-160
1.  Por el momento se comentan la firma de Roberto Villar para que la misma no salga al momento de generar los certificados de ética hasta que  salga la norma legal de designación de cargo de la Dra. Dell'agnese.

MAT - Remover firma en certificado de etica

---

modules/rup/internacion/resumen/internacion-resumen.schema.ts

https://proyectos.andes.gob.ar/browse/IN-565
1. Se incorpora plugin Audit para generar las fechas createdAt y updatedBy en internaciones

IN - Agrega audit para updatedAt y createdBy en internaciones

---

modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-233
1. Verificar al momento de liberar un turno lo siguiente:
- pasar a turnos programados si esta entre las 48 y 24 hs del horario de la agenda.
- pasar turnos del día si es el mismo dia de la agenda.

(FIX) CIT - Agregar control para pasar turnos liberados segun corresponda

---

modules/estadistica/controller/procesarAgendas.ts

https://proyectos.andes.gob.ar/browse/TYP-9
1. Corrige error al filtrar pacientes cuando los campos de alias y numeroIdentificacion son nulos.

TYP - Error en buscador con filtros de pacientes

---

modules/rup/internacion/camas.controller.test.ts
modules/rup/internacion/camas.controller.ts
modules/rup/internacion/camas.routes.ts
modules/rup/internacion/estados.schema.ts
modules/rup/internacion/internacion.log.ts
packages/unit-testing/index.ts

https://proyectos.andes.gob.ar/browse/IN-568
1. Crea nuevo logger para internacion y agrega logs en endpoints y controllers de edición de estados.

INT - Agregar logs en api

---

core-v2/mpi/paciente/paciente.events.ts

Corrige error al recorrer un array de relaciones que es null, cuando se activa/inactiva un paciente.
1. 
2. 
3.

MPI: control en array de relaciones

---

modules/estadistica/routes/turnos_prestaciones.ts

https://proyectos.andes.gob.ar/browse/TYP-10
PR APP https://github.com/andes/app/pull/2964
1. Un usuario profesional que no tenga permisos para el módulo TYP podrá acceder al buscador a travéz de la dirección (...gob.ar/buscador)
2. Se visualizan las prestaciones en las que el profesional sea parte del equipo de salud.
3. Se deshabilita el campo "Equipo de salud" .

TYP - Corregir Acceso al buscador

---

scripts/corregir_os_prestaciones.ts
scripts/corregir_os_turnos.ts

Script que elimina corrige las OS de pacientes dentro de turnos de una agenda.
1. 
2. 
3.

CITAS: Script corrige OS en turnos de pacientes

---

modules/turnos/controller/agenda.ts
modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-198
1. Modulariza actualizacion de los turnos restantes y llama a esta nueva funcion cada vez que libera un turno de una agenda que inicia en menos de 48hs.

CIT - Liberar Turno: modificar tipo de turno

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/CIT-247
1. En API tm/routes/profesional.ts, get('/profesional') si recibe parámetro 'habilitado' filtra profesional.habilitado = habilitado (true o false).

CIT - Crear agenda con profesional habilitado.

---

modules/rup/internacion/resumen/internacion-resumen.routes.ts

https://proyectos.andes.gob.ar/browse/IN-553
1. Dentro del resourceBase de internacion-resumen se agrega una nueva ruta para traerme todas las internaciones junto con sus unidades organizativas.

IN - Mejorar consulta para listado medico

---

modules/rup/internacion/resumen/internacion-resumen.routes.ts

Se quita de la querie para el listado de internaciones histórico el lookup con movimientos y agrega filtro por deletedAt
1. 
2. 
3.

fix(INT): Corrige la consulta para listado de historial medico

---

modules/estadistica/controller/procesarAgendas.ts
modules/estadistica/controller/procesarFueraDeAgenda.ts
modules/estadistica/controller/turnos_prestacionesController.ts

https://proyectos.andes.gob.ar/browse/TYP-5
1. Agrega filtros para prestaciones no nominalizadas en turnos de agenda y fuera de agenda

TYP - Listado de prestaciones no nominalizadas

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-153
1. Se agrega el estado correspondiente en el caso de referir.

TOP: Continuidad a solicitud contrarreferida

---

modules/obraSocial/controller/puco.ts

https://proyectos.andes.gob.ar/browse/MPI-402
Asociado a https://glpi.andes.gob.ar/front/ticket.form.php?id=3650
1. Se determina un periodo de tres meses para la recuperación de una obra social de un paciente, basado en la versión del padrón proveniente de PUCO.
>

MPI: Condición trimestral para devolución de obra social de un paciente

---

modules/facturacionAutomatica/controller/facturacionAutomaticaController.ts

https://proyectos.andes.gob.ar/browse/TYP-7
1. Se reducen las condiciones.

TYP - Mejorar condiciones

---

modules/forms/forms.schema.ts

https://proyectos.andes.gob.ar/browse/EP-220
1. Agrega campo descripción en las fichas epidemiologicas
2. 
3.

fix(EPI): Agrega  campo descripción

---

core/tm/controller/authUser.ts

https://proyectos.andes.gob.ar/browse/GDU-56
1. Se desactiva el campo activo para cada organización donde el usuario no se loguea hace tres o más meses.
2.  Al comparar la fecha se prioriza en este orden: 1-organizaciones.lastLogin, 2-lastLogin, 3-updetedAt y 4-createdAt.

GDU - Revisar Job para inactivar usuarios

---

core/tm/controller/authUser.ts

Se agregan atributos de vinculacion en paciente que queda inactivo
1. 
2. 
3.

feat(GDU): se desactiva usuario por organizacion (#1789)

---

core/tm/routes/profesional.ts
package.json

https://proyectos.andes.gob.ar/browse/MAT-158
1.  Se agregó filtro de fechas desde / hasta en get('/profesionales'...) profesional.ts

MAT - Renovaciones Online

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts
modules/rup/prestaciones.interface.ts
modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/IN-561
1.  Se modifico el esquema de Prestaciones, atributo inicio, (string) : 'plan-indicaciones'
2.  inicio: {
type: String,
enum: ['top', 'agenda', 'fuera-agenda', 'internacion', 'servicio-intermedio', 'plan-indicaciones'],
},

IN - Cargar campo para diferenciar prestación de Plan de Indicaciones

---

modules/turnos/routes/agenda.ts

1. Modifica condicion en tipo de turno, para ser contemplado al momento de suspender la agenda.

CIT - Repara error al reasignar turnos asociados a solicitudes TOP

---

modules/rup/routes/prestacion.ts
modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/RUP-363
1.  En esquema '**schemas/prestacion.ts**' se agregaron 2 indices p/fecha actualización (**updatedAt**).
2.  Los indices son: '**TOP-ENTRADA-UPDATED**' y '**TOP-SALIDA-UPDATED**'.
3.  En 'routes/prestacion.ts' se agregó en caso de entradas indice = 'TOP-ENTRADA-UPDATED'
y para salidas indice = 'TOP-SALIDA-UPDATED'.

(RUP-363) Filtro por actualizacion de solicitudes

---

modules/cda/routes/cda.ts

https://proyectos.andes.gob.ar/browse/AM-259
1.  Se corrigue para encontrar el paciente dentro de la coleccion user requerida 
{
"_id" : ObjectId("65d4c6548b008efa8791d97a"),
"titulo" : "Pap",
"expresionSnomed" : "921000013107",
"descargaAdjuntos" : false,
"busquedaPor" : "cdas"
}
{
"_id" : ObjectId("65d4c68a8b008efa8791d9bd"),
"titulo" : "Mamografía",
"expresionSnomed" : "71651007",
"descargaAdjuntos" : false,
"busquedaPor" : "cdas"
}

Fix AM - Error de descargar pdf de CDA

---

core/tm/controller/profesional.ts
core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-87
1. En routes, el componente profesional, se agregó la ruta patch  y a su vez el endpoint post de profesional solamente se dejo para la creación de uno nuevo.
2. En el componente profesional de controllers se corrigió un linteo y condición.
3. Para chequear el agregado de domicilios, se sugiere realizar patch desde postman.

MAT - Agregar nueva ruta patch

---

auth/permisos.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts
modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-573
https://proyectos.andes.gob.ar/browse/IN-584
1. Se agregaron nuevos permisos para el nuevo rol de farmacéutico y un nuevo estado para el esquema del plan de indicaciones (sujeto a cambios en un futuro)
NOTA: en caso de que al momento de crear una indicación, si en la colección no se visualizan los siguientes atributos entonces agregarlos. Solamente agregarlos para indicaciones de medicación.
- requiereFrecuencia: true
- requiereAceptacion: true

IN - nuevo rol de internacion: farmacia

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-583
1. Se modificó el esquema del plan de indicación agregando los atributos deleteBy y deleteAt

IN - eliminar indicación en estado borrador

---

core/tm/routes/profesional.ts

Corrige error al momento de actualizar domicilios de profesionales, porque el orden de los tipos de domicilios no siempre es. igual.
1. 
2. 
3.

fix(MAT): Actualización de domicilios

---

modules/turnos/routes/listaEspera.ts
modules/turnos/schemas/listaEspera.ts

https://proyectos.andes.gob.ar/browse/CIT-256
https://proyectos.andes.gob.ar/browse/CIT-266
1. En .../turnos/**routes/listaEspera**.ts, se modificó get() para buscar por **paciente.id + tipoPrestacion.conceptId + estado**.
2. Se agregó método patch() para actualizar campos: **demandas** o **estado**
3. Se modificó esquema ../turnos/schemas/listaEspera.ts

CIT - Demada Insatisfecha

---

modules/mobileApp/routes/agendas.ts

Se cambia la distancia de turnos por mobile de 10 pasa a 4 km
1. 
2. 
3.

AM: se modifica la distancia para sacar turnos por mobile

---

jobs/exportNexosFichaSisa.ts
jobs/jobExportFichasSnvsSisa.ts

[https://proyectos.andes.gob.ar/browse/EP-223](https://proyectos.andes.gob.ar/browse/EP-223)
1. Agrega proceso para dar alta a evento nominal con el ws400 de las fichas generadas con forms dinamicos

feat(EPI): Agrega job interoperabilidad generico

---

core/tm/schemas/organizacion.ts
modules/constantes/constantes.schema.ts
modules/mobileApp/routes/agendas.ts
modules/turnos/condicionPaciente/condicionPaciente.controller.ts

https://proyectos.andes.gob.ar/browse/AM-261
1. Se establece el minimo y máximo para una circunferencia requerida
{
"_id" : ObjectId("65c4fa41f019edab2ec92b23"),
"key" : "1",
"nombre" : "minimo-km",
"source" : "organizacion:circunferenciaKmTurno",
"type" : "number"
},
{
"_id" : ObjectId("65c4fa65f019edab2ec92b53"),
"key" : "10",
"nombre" : "maximo-km",
"source" : "organizacion:circunferenciaKmTurno",
"type" : "number"
},
{
"_id" : ObjectId("663a12e3f1b15d16a728a1f7"),
"key" : "4",
"nombre" : "default-km",
"source" : "organizacion:circunferenciaKmTurno",
"type" : "number"
}

AM - Configuración distancia de turnos

---

modules/top/routes/reglas.ts

https://proyectos.andes.gob.ar/browse/RUP-348
1.  Se agrega nuevo atributo (search) a los parametros que ingresan como filtros

CIT - Agregar filtro buscar a los parametros ingresados

---

modules/cda/controller/CDAPatient.ts
modules/mobileApp/routes/agendas.ts

Corrige error al buscar configuración de radio para turnos mobile
Agrega al try al generar CDAs

fix(CITAS): Corrige error al calcular radio para turnos mobile

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.schema.ts

https://proyectos.andes.gob.ar/browse/IN-575
1.  Se modificó **esquema**: PlanIndicacionesEstadoSchema, nuevo atributo: verificacion.**key**: String,

IN: Plan de indicaciones - motivo de rechazo

---

modules/cda/controller/CDAPatient.ts
modules/cda/routes/cda.ts
modules/descargas/informe-cda/informe-body-cda.ts
modules/descargas/informe-cda/informe-cda.ts
modules/descargas/informe-cda/informe-footer-cda.ts
modules/descargas/informe-cda/informe-header-cda.ts
modules/huds/export-huds/exportHuds.controller.ts

https://proyectos.andes.gob.ar/browse/HUDS-97
1. Se genera un nuevo informeCDA con sus correspondientes HTML para generar los PDFs correspondientes a los CDAs que no se podian descargar ni visualizar al momento de ver la HUDS del paciente o exportar la misma.

HUDS - Exportacion de HUDS

---

config.private.ts.example
modules/turnos/controller/agenda.ts

Se actualiza ruta para obtener días feriados
1. Se actualiza ruta para obtener días feriados (https)
2. Se pasa url a archivo de configuración
3.

CITAS: cambia url feriados en actualizarAgendasJobs

---

modules/mobileApp/auth_routes/rup-adjuntos.ts
modules/mobileApp/controller/NotificationService.ts

https://proyectos.andes.gob.ar/browse/AM-237
1. Agrega función para aviso de cancelacion de solicitud de adjuntar archivo

RUP - Error en Adjuntos RUP

---

modules/cda/controller/CDAPatient.ts
modules/mobileApp/routes/paciente.ts

Agregar una captura de error al crear bucket por un adjunto de CDAs

fix(CDAs): Agrega control al crear bucket

---

core-v2/mpi/paciente/paciente.events.ts
core-v2/mpi/paciente/paciente.routes.ts
shared/interfaces/direccion.interface.ts
shared/schemas/direccion.ts

https://proyectos.andes.gob.ar/browse/MPI-424
1. Se agregan condiciones para resetear a null la georeferencia en caso de que el paciente se encuentra en situación de calle.
2. Se modifican interfaces y esquemas para agregar la situación de calle del paciente
3.

MPI - Pacientes sin domicilio real

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/AM-262
1. Al momento de verificar un profesional se deja de hacer comparación por 
[documento, sexo, fechaNacimiento, nombre , apellido] 
y ahora sólo se hace por  
[documento, sexo, fechaNacimiento]

AM - Corregir matching profesional

---

modules/descargas/informe-rup/informe-body.ts

https://proyectos.andes.gob.ar/browse/HUDS-93
1. Obtiene fecha de inicio de prestación desde el primer estado de tipo "ejecución"
2. Imprime fecha de inicio de prestación en el template del PDF

HUDS - Agregar fecha de creación de la consulta en PDF

---

core/tm/routes/profesional.ts

AM (Fix) - corrige comparacion de fechas en matching profesional

---

.github/workflows/has_conflic.yml

cambiar label para marcar conflictos

fix(LIB): cambia label para marcar conflictos

---

core/tm/routes/profesional.ts

Cambiar formato de fechas para validar profesional

fix(MAT): Cambia el formato de fecha para validar profesional

---

core/tm/routes/profesional.ts

Saca el control de fecha de nacimiento para validar

fix(MAT): Saca el control de fecha de nacimiento para validar

---

modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-254
1.  Se agregaron condiciones para evitar que se de una asistencia a un turno que no presenta paciente o un sobreturno suspendido.

CIT - Error en auditoria de agendas en turnos disponibles

---

modules/turnos/routes/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-274
1. Se controla si el profesional está o no habilitado para el/los tipos de prestaciones ingresados.

CIT - Edición de profesional en agenda

---

modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/AM-276
1. Se agrega un control para la cantidad de turnos programados virtuales

AM - Evitar errores por asignación simultáneas de turnos virtuales

---

core-v2/mpi/paciente/paciente.schema.ts
modules/rup/internacion/censos.schema.ts
modules/rup/schemas/prestacion.ts

https://proyectos.andes.gob.ar/browse/MISC-259
Agregados índices a los siguientes esquemas:
1. PacienteSchema
2. CensoSchema
3. PrestacionSchema

MISC - API agregar índices a mongo

---

jobs/demanda-insatisfecha-corregir.ts
modules/turnos/citasLog.ts
modules/turnos/schemas/listaEspera.ts

con pacientes registrados por demanda insatisfecha.
https://proyectos.andes.gob.ar/browse/CIT-263
1. El script recorre listaEspera en estado 'pendiente'
2. Luego buscar turnos dados al paciente posteriores a la demanda para la prestación
3. La demanda queda en estado 'resuelto'
4. Si el paciente tiene varias demandas para la misma prestación, y alguna es posterior a la fecha del turno, genera una nueva demanda.

(FEAT) Script para asociar turnos dados c/Demanda Insatisfecha

---

modules/cda/routes/cda.ts

Corrige control de permisos en ruta de cda de un paciente, ya que no es accesible desde la app-mobile en Historia de Salud
1. 
2. 
3.

MOBILE: actualiza permisos ruta CDA de un paciente

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts

https://proyectos.andes.gob.ar/browse/HUDS-74
1. Implementa filtro "excluyeEstado" para obtener todas las indicaciones a excepción de las que contienen "estadoActual.tipo" con el valor especificado.

HUDS - Implementa filtro para estado de indicaciones

---

jobs/demanda-insatisfecha-corregir.ts

Corrige detalles en job que cierra demandas de turnos
1. 
2. 
3.

CITAS: corrige errores en job cerrar demanda insatisfecha

---

core/tm/routes/sms.ts
modules/turnos/citasLog.ts
modules/turnos/controller/turnosController.ts

[https://proyectos.andes.gob.ar/browse/MISC-354](https://proyectos.andes.gob.ar/browse/MISC-354)
1. Se agrega evento para envío de notificaciones para nuevo turno de gestión y para cancelar turno

fix(Notificacion): Se agregan eventos para envío de notificaciones

---

modules/huds/motivosHuds/motivosHuds.routes.ts
modules/huds/motivosHuds/motivosHuds.schema.ts

https://proyectos.andes.gob.ar/browse/PRIV-65
1. Cambios en el esquema realizados en base a los comentarios en el PR de app. https://github.com/andes/app/pull/2958

PRIV -  Visualizar motivos de acceso a la HUDS

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/GDU-64
1. Se modifica la condición de buscar por documento para que solamente traiga el profesional correcto.

GDU - Controlar datos del profesional asociado al usuario

---

modules/turnos/controller/agenda.ts
modules/turnos/routes/agenda.ts

https://glpi.andes.gob.ar/front/ticket.form.php?id=4860
El problema reportado surge en agendas con varios bloques con diferente cantidad de turnos
1. Se cambia la forma de controlar si el turno esta disponible al momento de dar un turno.

fix(CITAS):  Corrige control por turno liberado  al dar asistencia

---

auth/auth.controller.ts
modules/gestor-usuarios/usuarios.routes.ts

[https://proyectos.andes.gob.ar/browse/MISC-346](https://proyectos.andes.gob.ar/browse/MISC-346)
1. Se agrega control, para buscar al potencial usuario en one login

fix(AUTH): agrega control para usuarios one login

---

modules/turnos/routes/listaEspera.ts
modules/turnos/schemas/listaEspera.ts

https://proyectos.andes.gob.ar/browse/CIT-277
https://proyectos.andes.gob.ar/browse/CIT-278
1. Crea opciones para aplicar filtros en consulta de lista de espera

CIT - Implementa casos de demanda insatisfecha

---

modules/turnos/controller/turnosController.ts

Agrega control por id en el evento citas:asignar y notificaciones:turno:suspender

fix(CITAS): Agrega control por id en el evento citas:asignar

---

modules/turnos/controller/turnosController.ts

Agrega control de turno en null

fix(CITAS): Control de turno null

---

modules/turnos/controller/turnosController.ts

Cambia el logs del evento de asignar turno, para sacar el log de error cuando no son turnos de gestión

fix(CITAS): Cambio de logs en  notificaciones

---

modules/rup/internacion/censo.controller.ts
modules/rup/internacion/censo.routes.ts

https://proyectos.andes.gob.ar/browse/IN-608
1. Se muestra cama correcta al existir dos internaciones en un mismo día.
2. Se muestra nombre autopercibido (alias) en caso que corresponda si el paciente cambia del mismo.

IN - Censo diario:  error datos de cama y paciente de internacion duplicada

---

modules/mobileApp/auth_routes/rup-adjuntos.ts
modules/mobileApp/controller/NotificationService.ts

Corregir error de tipeo para enviar a la app mobile la notificación de que se ha cancelado la acción de adjuntar

fix(AM): Corrige error de tipeo en notificación al cancelar adjunto

---

modules/mobileApp/routes/paciente.ts

https://proyectos.andes.gob.ar/browse/AM-256
1.  Se aumenta la edad para permitir registrar hijos en la app mobile, hasta 13 años.

AM - Cambiar edad para registrar paciente hijo

---

jobs/CIT-219.ts
scripts/CIT-219.ts

https://proyectos.andes.gob.ar/browse/CIT-219
1.  Recorre prestaciones de las ultimas 24 Hs. 
2.  Si la codificación de agenda.turno o agenda.sobreturno está vacia le agrega la codificación.
3.  Si turno.horaAsistencia está vacia le asigna turno.horaInicio.

Feat-Script p/corregir prestaciones no codificadas

---

modules/rup/internacion/censo.controller.ts
modules/rup/internacion/internacion.log.ts

https://proyectos.andes.gob.ar/browse/IN-610
1. Se corrigen movimientos de cama huerfanos (tras anulación de internación) que producía un error al calcular censos diarios
2. Agrega logs para manejar casos de error y asegurar la continuidad del job ante un error.

IN (Fix) - Censo mensual: ejecutar job

---

modules/rup/internacion/plan-indicaciones/plan-indicaciones.hook.ts

https://proyectos.andes.gob.ar/browse/IN-606
1. fix creacion de eventos al verificar indicacion
2. fix duplicacion de eventos al continuar indicacion (api)
3. correccion de horario de ultima toma (se estaba excluyendo) (api)

INT - Plan indicaciones: creacion de eventos innecesarios

---

modules/turnos/routes/listaEspera.ts

https://proyectos.andes.gob.ar/browse/CIT-310
1. Crea filtro basado en param para aplicar a la descarga de la lista de espera (demandas insatisfechas).

CIT - Implementa filtro para efector en demanda insatisfecha

---

core/tm/routes/profesional.ts

https://proyectos.andes.gob.ar/browse/MAT-164
https://github.com/andes/matriculaciones/pull/216
1. Se agrega atributo 'habilitado' para el get de guiaProfesional

MAT - Implementar mockup guia profesional

---

modules/descargas/informe-rup/elementos-rup/index.ts
modules/descargas/informe-rup/elementos-rup/odontograma.component.ts
modules/huds/export-huds/exportHuds.routes.ts

https://proyectos.andes.gob.ar/browse/HUDS-103
1. Se crea componente de odontograma
2. Se agregan controles para evitar error al exportar

HUDS -  Error al exportar la HUDS

---

modules/estadistica/controller/procesarFueraDeAgenda.ts
modules/rup/schemas/prestacion.ts

agrega indices buscador para fuera de agendas
1. 
2. 
3.

TYP: agrega indices buscador para fuera de agendas

---

modules/turnos/routes/listaEspera.ts

https://proyectos.andes.gob.ar/browse/CIT-293
https://proyectos.andes.gob.ar/browse/CIT-276
1. Se agregan nuevos controles para poder almacenar el cierre de las demandas insatisfechas. 
2. 
3.

CIT - Cerrar demanda insatisfecha

---

modules/turnos/controller/agenda.ts
modules/turnos/controller/turnosController.ts
modules/turnos/routes/turno.ts
modules/turnos/schemas/turno.ts

https://proyectos.andes.gob.ar/browse/CIT-304
1.  Se modificó evento '**citas:turno:asignar**' para que notifique si: turno.reasignado.**anterior** && turno.**notificar**.
2.  Se agregó campo **notificar**: boolean al **esquema turno**.
3.  Si es turno reasignado utiliza la contante: **'turno-reasignar'** para el cuerpo del mensaje.
3.  Nueva constante '**telefonoUnico**' para **local, demo y test**, esto evita enviar notificación p/error.
{
"key" : "telefonoUnico",
"nombre" : "2996318193", (este es mi nro, puede ser otro)
"source" : "notificaciones:sendMessage",
"type" : "text"
}

(FEAT) CIT - Reasignación turno: notificar al paciente

---

modules/rup/internacion/resumen/internacion-resumen.routes.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/MPI-436
1. Modifica recurso _internacion-resumen_ para incluir búsquedas por id de paciente de tipo array
2. Modifica endpoint de _prestacion_ para incluir al filtro de 'paciente' a sus vinculados

IN (Fix) - HUDS de pacientes no incluye prestaciones de pacientes unificados

---

core/tm/farmacia.routes.ts
core/tm/index.ts
core/tm/interfaces/IFarmacia.ts
core/tm/schemas/farmacia.ts

https://proyectos.andes.gob.ar/browse/TM-36
1. Se creo una ABM con Resourse Base para nuevo modulo de farmacias.
NOTA: En demo hay una colección llamada farmacias de la cual se puede utilizar para hacer una copia en el local y ejecutar, desde postman, los comandos necesarios para probarla!

TM - API para ABM de Farmacias

---

config.ts
modules/turnos/citasLog.ts
modules/turnos/controller/agenda.ts

Se agregan y actualizan logs de errores en el controlador de turnos utilizado por job que actualiza agendas.
https://glpi.andes.gob.ar/front/ticket.form.php?id=4569
https://glpi.andes.gob.ar/front/ticket.form.php?id=4969
1. Agregar try-catch para error en job que actualiza agendas
2. Actualiza logs: cambiar log por logger
3. Se agrega atributo expiredAt para los logs de citas existentes

CITAS: Logs en job que actualiza turnos y agendas

---

modules/turnos/controller/turnosController.ts
modules/turnos/routes/turno.ts

- Agrega control de turno reasignado al enviar notificaciones
- Cambia orden en consulta de prestaciones de top para uso de indice

fix(CITAS): Agrega control en notificación

---

modules/rup/internacion/resumen/internacion-resumen.routes.ts
modules/rup/routes/prestacion.ts

IN (Fix) - busqueda por array de pacientes

---

jobs/recordatorioTurnos.ts

ref(CIT): Reubica archivo recordatorioTurnos

---

modules/mobileApp/routes/turnos.ts
modules/rup/controllers/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-182

Eliminar referencia de solicitud al cancelar un turno desde mobile

---

core-v2/mpi/financiador/financiador.interface.ts
core-v2/mpi/financiador/financiador.schema.ts
core-v2/mpi/paciente/paciente.controller.ts
modules/turnos/controller/agenda.ts
modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/MPI-403
Se requieren los cambios realizados en la tarea de CIT-214:
https://proyectos.andes.gob.ar/browse/CIT-214
1. Se agrega la siguiente información al esquema de pacientes: origen (PUCO, ANDES o SUMAR) y fechaDeActualización
2. Cada vez que se guarda un turno, o se guarda desde MPI la información del paciente, se agrega fechaDeActualización a la obra social o al prestador modificado .
3. Cuando se obtienen datos de la obra social o prestador, tanto de padrones PUCO o SUMAR en MPI, como del selector de prestadores en CIT-214, se determina el origen para completar el cambio en el esquema del paciente.

MPI - Agrega detalles al esquema de pacientes

---

modules/rup/internacion/resumen/internacion-resumen.routes.ts
modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/HUDS-123
1.Modifica recurso internacion-resumen para incluir búsquedas por id de paciente de tipo array
2.Modifica endpoint de prestacion para incluir al filtro de 'paciente' a sus vinculados

HUDS (Fix) - Ambito internación: huds de pacientes unificados

---

jobs/exportNexosFichaSisa.ts
jobs/jobExportFichasSnvsSisa.ts
modules/sisa/controller/sisa.controller.ts
modules/sisa/logger/sisaLog.ts

Quitamos funcionalidad especifica de covid. 
Agregamos Logger  para casos de éxito

EPI: Corrige logs en el JOB. de exportar a SNVS

---

jobs/recordatorioTurnos.ts

https://proyectos.andes.gob.ar/browse/MISC-367
1. Script recordatorioTurnos.ts se separó en bloques de 50 msg. con un tiempo de espera entre bloques de 10 seg.

(Fix) Separar por bloques envio de notificaciones

---

auth/auth.controller.ts

Al obtener un profesional filtra por atributo habilitado
https://proyectos.andes.gob.ar/browse/RUP-416
1. 
2. 
3.

fix(auth): filtro profesional habilitado en login

---

jobs/recordatorioTurnos.ts

https://proyectos.andes.gob.ar/browse/MISC-370
1.  Se implementa tiempo de espera entre mensajes de 7.5 seg.

(FEAT) Recordatorio Turnos: Tiempo de espera

---

auth/schemas/authUsers.ts
auth/schemas/permisos-organizaciones.ts

https://proyectos.andes.gob.ar/browse/GDU-69
PR APP
https://github.com/andes/app/pull/3078
1. Se agrega un subesquema de organización y permisos para agregar plugin Audit

GDU - Agregar auditoría en permisos por organización

---

modules/turnos/controller/agenda.ts
modules/turnos/controller/turnosController.ts

https://proyectos.andes.gob.ar/browse/CIT-329
1. En los eventos citas:turno:asignar y notificaciones:turno:suspender, se agrega restricción para que solamente se envie notificaciones en aquellas agendas que tienen HABILITADO el "Enviar Notificaciones"
2. En el tercer requerimiento de la tarea, tener en cuenta de chequear en la colección webhookLog si "dispara" o "no dispara" el evento, por ejemplo: 
{
"_id" : ObjectId("667ecb3c4bba864d0ebdb33d"),
"event" : "notificaciones:enviar",
"url" : "http://localhost:3000/notificaciones/sendMessage",
"method" : "POST",
"active" : true
}

CIT - Mejoras visuales en notificaciones de turnos

---

modules/turnos/routes/listaEspera.ts
modules/turnos/schemas/listaEspera.ts

https://proyectos.andes.gob.ar/browse/CIT-323
1. Crea recuperación de demandas completando datos del paciente y aplicando los filtros solicitados en request
2. Modifica esquema de listaEspera para guardar únicamente el id del paciente

CIT - Modifica recuperacion de pacientes en lista de espera

---

modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-267
1.  Se eliminan datos residuales en la agenda clonada
2. Queda activo por defecto el envío de notificaciones al clonar una agenda.

CIT - Error al clonar agendas

---

modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/CIT-343
1. Modifica patch de recurso 'turno' para actualizar los números de carpeta de un paciente

CITAS (Fix) - Gestor de agendas: Nuevo número de carpata

---

auth/permisos.ts

https://proyectos.andes.gob.ar/browse/TM-34
1.  Se agregan nuevos permisos para poder crear, editar y eliminar una farmacia.
NOTA: Para probar este PR debe estar mergeada la tarea TM-36 que tiene todo el esquema e interfaz de una farmacia.

TM - Nuevo modulo de farmacias

---

config.private.ts.example
jobs/encuestaSatisfaccion.ts
modules/turnos/citasLog.ts

https://proyectos.andes.gob.ar/browse/RUP-420
1. Script (job diario) que recorre una tabla de SQL para enviar link a encuesta de satisfación.
2. En principio Gervacio va a definir a que Nro. y el Link de la encuesta.
3. Una vez enviado el msg se marca en la tabla de la DB como enviado.
4. EL cuerpo del mensaje está en 'constantes', key: 'encuesta-envio'

RUP - Script (Job) Encuesta Satisfacción.

---

modules/descargas/matriculaciones/credencial-profesional-body.ts
modules/mobileApp/auth_routes/autenticacionApp.ts
utils/utils.ts

https://proyectos.andes.gob.ar/browse/AM-307
https://proyectos.andes.gob.ar/browse/AM-317
1. Para verificar que el paciente tenga una o mas cuentas, filtrando por dni.
2. Esto sirve para chequear para el momento de login.
3. Corrige visualización de fecha de primera matriculación y fecha de nacimiento.

AM - Se agrega busqueda de pacienteaApp por dni

---

modules/turnos/routes/agenda.ts

https://glpi.andes.gob.ar/front/ticket.form.php?id=4949
1. Modifica el objeto error que se retorna a la app
**GLPI asociado:** https://glpi.andes.gob.ar/front/ticket.form.php?id=4949

CIT (Fix) - Manejo de errores editando agenda

---

core-v2/mpi/paciente/paciente.events.ts
core-v2/mpi/paciente/paciente.routes.ts

https://proyectos.andes.gob.ar/browse/MPI-431
1. Se agrega verificacion para pacientes con domicilio incompleto

MPI: Controles al actualizar pacientes

---

modules/descargas/laboratorio/laboratorio-body.ts

Corrige visualización PDFs en laboratorios
1. 
2. 
3.

fix(HUDS): corrige descarga PDF laboratorios

---

jobs/exportNexosFichaSisa.ts
modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
modules/forms/forms.schema.ts

[EP-234](https://proyectos.andes.gob.ar/browse/EP-234)
[EP-239](https://proyectos.andes.gob.ar/browse/EP-239)
[EP-241](https://proyectos.andes.gob.ar/browse/EP-241)
1. Se guardara el id_code generado por SNVN al exportar la ficha
2. No se exportaran las fichas que tengan el codigo generado por SNVN
3. Actualizacion de schema de forms y de forms-epidemiologia con el objeto de configuracion de iteroperabilidad con laboratorio
4. Generar un identificador aleatorio para interoperar con laboratorio
5. Agregar numero identificación laboratorio como parametro de busqueda en la ruta de fichas

EP - Registro de id_caso al dar de alta una ficha

---

core-v2/mpi/paciente/paciente.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-438
1.  Se agregan los atributos nombreCorrecto y apellidoCorrecto, y se elimina el de notaError dentro del schema de paciente

MPI - Reporte de errores de Renaper

---

jobs/recordatorioTurnos.ts
modules/turnos/citasLog.ts
modules/turnos/controller/turnosController.ts

https://proyectos.andes.gob.ar/browse/CIT-325
1. Se agregan nuevos "loggers" para clasificar los logs de notificaciones de turnos en 
recordatorio/ asignación/ suspención

CIT- Notificación log whatsapp

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-190
1. Borrar prioridad en solicitud que vuelve a auditoría
GLPI ASOCIADO: https://glpi.andes.gob.ar/front/ticket.form.php?id=5083

TOP - Borrar prioridad

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-187
1. Recupera el diagnóstico asociado de cada solicitud desde la prestación de origen

TOP - Agrega filtros para diagnósticos asociados

---

jobs/exportNexosFichaSisa.ts

- Cambia el filtro de  búsqueda de  fichas para exportar a Sisa.
- Agrega el campo de  Nro de caso en  la query  en sisa  para  controles posteriores

fix(JOB): Cambia filtro para exportar fichas a SNVS

---

.github/workflows/build.yml
modules/rup/internacion/censo.controller.test.ts
packages/unit-testing/index.ts

1. Modifica inicio de conexion de mongoserver en tests

MISC - Fix CI?

---

.github/workflows/build.yml
docker-compose.yml
package.json

Fija versión de ubuntu, ya que la "ubuntu-lastest" no contiene algunas dependencias para mongo 5
1. Fija versión de ubuntu a 20.04
2. Mongo 5 en docker de test unitarios
3. actualiza node 16
4. Habilita debugger en los test unitarios

chore(test): actualiza ubuntu version para test unitarios

---

jobs/encuestaSatisfaccion.ts
jobs/recordatorioTurnos.ts

https://proyectos.andes.gob.ar/browse/CIT-361
1. Se redujo el tiempo a la mitad (5000 ms)
2. en: RecordatorioTurnos.ts
3. en: EncuestaSatisfaccion.ts

CIT - Instancias Notificaciones

---

modules/turnos/routes/turno.ts

https://proyectos.andes.gob.ar/browse/CIT-360
1. Agrega control para saber si la agenda tiene bloques solo con turnos para profesional disponibles

CIT - Turnos autocitados del dia

---

modules/turnos/controller/agenda.ts
modules/turnos/schemas/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-271
1. Se implementa el método actualizarHistorial para agregar un nuevo cambio de estado con audit.
2. Se permite acceso al método desde el guardado de agendas en Citas y desde el job de actualización.

CIT - Implementa historial de estados en agendas

---

jobs/actualizarAgendasJob.ts

https://proyectos.andes.gob.ar/browse/CIT-334
1.  Se modificó fecha (end) fin del día anterior a la fecha actual.

CIT - Modificar fechas en job citas

---

modules/descargas/informe-rup/elementos-rup/receta-medica.component.ts
modules/rup/controllers/rup.events.ts
modules/rup/schemas/receta-schema.ts

Se agrega conceptos snomed en esquema de receta  y se corrige informe PDF para receta

FIX(RUP): Se corrigen el informe y algunos esquemas de receta 

---

modules/descargas/laboratorio/laboratorio-body.ts
modules/descargas/routes/descargas.ts
modules/rup/laboratorios.controller.ts

Se cambia la estructura  recibida del ws de protocolos del SIL para mejorar la visualización y no repetir codigo

refactor(HUDS): modifica estructura de un protocolo

---

auth/auth.class.ts
initialize.ts
modules/recetas/index.ts
modules/recetas/receta-schema.ts
modules/recetas/recetas.error.ts
modules/recetas/recetas.routes.ts
modules/recetas/recetasController.ts
modules/rup/controllers/rup.events.ts
utils/utils.ts

https://proyectos.andes.gob.ar/browse/REC-31
1. Se generan las rutas para consumir receta mediante resourceBase.
2. Se implementan GET customizados.
3. El PATCH vía resourceBase.

REC - Rutas Receta

---

modules/rup/controllers/prestacion.ts

https://proyectos.andes.gob.ar/browse/TOP-191
1. Corrige datos de audit para que guarde el efector desde donde se liberó el turno
GLPI ASOCIADO: https://glpi.andes.gob.ar/front/ticket.form.php?id=5128

TOP (Fix) - Historial: No se guarda usuario correctamente

---

modules/turnos/controller/turnosController.ts

https://proyectos.andes.gob.ar/browse/MISC-361
1. Se agrega en el log del microservicio de notificaciones el ID de turno y el ID de paciente.
PR andesMicroservices https://github.com/andes/andesMicroservices/pull/229

MISC - Agregar data en el log info de notificaciones

---

auth/auth.class.ts
modules/recetas/receta-schema.ts
modules/recetas/recetas.routes.ts
modules/recetas/recetasController.ts
modules/rup/controllers/rup.events.ts

https://proyectos.andes.gob.ar/browse/RUP-451
1. Permitir la suspensión de un medicamento solo si está en estado "Vigente No dispensada" o "Vigente Dispensa parcial". 
2. Solo Médicos, Odontólogos y Obstetras pueden suspenderlo. 
3. Registrar motivo de suspensión desde una nueva colección en la base, junto con el profesional y la fecha.
4. Realiza pre-save para guardar el estado actual de la receta a partir de la ultima actualización de estados.
Coleccion motivosReceta:
```
motivosRecetaSchema = {
label: {
type: String,
required: true
},
descripcion: {
type: String,
required: false
}
}
Próximo vencimiento
Intolerancia
Cambio de tratamiento
Efecto adverso
Fin de tratamiento
Error de prescripción
Otro
```

RUP - Implementa suspension de recetas

---

modules/estadistica/controller/procesarFueraDeAgenda.ts

Que no se rompa el listado de turnos y prestaciones cuando una internación no tiene registros. Plan de indicaciones por ejemplo.
1. Chequea que si la prestacion no tiene registros, no busca atributos dentro de ellos

TYP (Fix) - Prestacion sin registros

---

modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/CIT-358
1. En job de actualización de turnos, se incorpora un registro de los de los bloques de la agenda, para guardar dentro de agendaLog la comparación del estado de turnos antes y despues de la actualización.

CIT - Implementa logs de bloques en job de actualizacion

---

core-v2/mpi/paciente/paciente.controller.ts

https://proyectos.andes.gob.ar/browse/MPI-399
1. Se obtiene por defecto el financiador en pacientes, sin esperar filtro por URL.

MPI - Recupera financiador en paciente sin params

---

core/tm/farmacia.routes.ts

Agregar el campo de Nro de disposición en para filtran  en la API de farmacias
1. Agrega  campo "disposicionHabilitacion" en ruta "search"

FIX(REC): Agregar filtro de búsqueda por Nro de disposición

---

modules/rup/internacion/camas.routes.ts

1. Consulta por existencia de atributo "extras" y agrega bloque de codigo reciente dentro del try

IN (Fix) - Cambio de estado de camas

---

auth/auth.class.ts
modules/huds/hudsAccesos.routes.ts

https://proyectos.andes.gob.ar/browse/IN-612
PR APP https://github.com/andes/app/pull/3115
1. Se agrega ruta de tiempo restante de un token huds

IN -  cambiar periodos de registros de internacion

---

modules/recetas/receta-schema.ts
modules/recetas/recetas.error.ts
modules/recetas/recetas.routes.ts
modules/recetas/recetasController.ts

https://proyectos.andes.gob.ar/browse/HUDS-149
Se agregan multiples controles en request api de receta sobre patch y cambios en esquema
1. Se agregan modificaciones varias en el esquema de una receta: 
- array de medicamentos para la dispensa, 
- subesquema de profesionales, 
- nuevo estado de receta "pendiente",
- idDispensa del medicamento provisto por Sifaho o recetar
- fecha de dispensa
2. Se agregan controles en el patch, tales como:
- solo dispensar recetas "vigentes",
- agrega descripción
- completan operaciones de dispensa y sin-dispensar (limpia appNotificada)
- Dato del sistema se obtiene del usuario
- cambios de respuesta con el recurso modificado si fue exitoso o mensaje de error cuando no es posible

Receta: cambios esquema y dispensa

---

modules/matriculaciones/controller/matriculaciones.ts
modules/matriculaciones/routes/numeracionMatriculas.ts

https://proyectos.andes.gob.ar/browse/MAT-180
1. matriculaciones/controller método: ultimoPosgrado(...)
2. numeracionMatriculas: GET y PATCH '/ultimoPosgrado'
3. En todos los métodos de numeracionMatriculas se incorporó Auth.authenticate()

MAT - Posgrados: Numeración automática

---

modules/turnos/controller/historialCitasController/historialCitasController.ts

En el historial de turnos de un paciente, se amplia periodo de 6 meses a 1 año para atenciones fuera de agendas 
1. amplia periodo para fuera de agendas a un año.
2. modifica query para utilizar índice  por paciente y estadoActual.tipo.

fix(CITAS): amplia periodo de fuera de agendas en historial de turnos

---

core/tm/controller/profesional.ts
modules/recetas/recetasController.ts
modules/rup/controllers/rup.events.ts

https://proyectos.andes.gob.ar/browse/RUP-471
1. Se recupera informacion de la profesion de grado, matricula y post grado para adjuntar a la receta

RUP - Actualiza datos de profesional en recetas

---

core/tm/eclqueries.routes.ts
core/tm/index.ts
core/tm/schemas/eclqueries.schema.ts

https://proyectos.andes.gob.ar/browse/RUP-466
1. Agrega esquema para nueva colección "ECLQueries"
2. Agrega API con Resource Base para las ECLQueries
Generar  nueva  colección 'eclqueries' con los siguientes documentos: 
```
[{
"_id" : ObjectId("67cf91001a4680432fe3e5c1"),
"key" : "receta:genericos",
"nombre" : "medicamentosGenericos",
"valor" : "<763158003:732943007=*,[0..0] 774159003=*, 763032000=*",
"descripcion" : "Representar todos los medicamentos genéricos con unidad de presentación"
},
{
"_id" : ObjectId("67cf91971a4680432fe3e5db"),
"key" : "receta:presentacionescomerciales",
"nombre" : "presentacionesComerciales",
"valor" : "#MG#.763032000",
"descripcion" : "Representar todas las presentaciones comerciales asociadas a un medicamento genérico con unidad de presentación"
},
{
"_id" …
```

feat(RUP): Agrega API para ECLs

---

modules/recetas/receta-schema.ts
modules/recetas/recetaLogs.ts
modules/recetas/recetas.routes.ts
modules/recetas/recetasController.ts
modules/recetas/services/receta.ts

https://proyectos.andes.gob.ar/browse/RUP-472
https://proyectos.andes.gob.ar/browse/RUP-478
1. Patch:
- Cancelar dispensa: nuevo método que permite volver a "sin-dispensar" una receta ya dispensada
3. Get: 
- Cambios en las condiciones y controles para registro de dispensa o no- dispensa
- Agrega get a Sifaho o Recetar con andes-services, respuesta intermedia para app no dispensada, pero que se sigue usando por la app
4. Logs de errores
Insertar en la colección andes-services
```
{
"name" : "obtener-receta-sifaho",
"type" : "http-client",
"configuration" : {
"url" : { 
"$apply" : {
"fn" : "concat",
"args" : [ 
"http://localhost:4000", 
"/api/andes-prescriptions"
]
}
},
"headers" : {
"Content-Type" : "application/json",
"Authorization" : "Bearer token"
},
"method" : "GET",
"params" : { …
```

Receta: Cambios en api patch y get

---

core/term/controller/snomed.controller.ts
core/term/controller/snomed.snowstorm.ts
core/term/routes/snomedv2.ts

https://proyectos.andes.gob.ar/browse/RUP-482
1. Se agrega ruta en SNOMED  para consultar valores concretos definidos por una relación de conceptos. Esto  era necesario para obtener la cantidades disponibles en  presentaciones comerciales  de  un medicamento genérico
Agregar  a la coleccion eclqueries dos documentos:
[
{
"_id" : ObjectId("680689dc8b63d7f51cf96a53"),
"key" : "receta:medicamentoscomercialesporgenerico",
"nombre" : "medicamentoscomercialesporgenerico",
"valor" : "^331101000221109:774160008=<#MG#",
"descripcion" : "Representar todas las unidades de las presentaciones comerciales asociadas a un medicamento genérico"
},
{
"_id" : ObjectId("6807cd388b63d7f51c03321e"),
"key" : "receta:filtroUnidades",
"nombre" : "filtroUnidadesPorAtributo",
"valor" : "1142142004",
"descripcion" : …

Se agrega ruta en snomed para devolver listado de valores

---

modules/recetas/receta-schema.ts
modules/rup/controllers/rup.events.ts

https://proyectos.andes.gob.ar/browse/RUP-477
1. Agrega los campos "serie" (una letra) y "numero" al esquema de recetas para medicamentos con triplicado
2. Guarda datos desde eventos de RUP
3. Si el medicamento es por triplicado, ya no se podrá marcar la receta como tratamiento prolongado.

RUP - Nuevos datos para medicamentos con triplicado

---

modules/recetas/receta-schema.ts
modules/recetas/recetaLogs.ts
modules/recetas/recetas.routes.ts
modules/recetas/recetasController.ts

https://proyectos.andes.gob.ar/browse/RUP-484
1. Nuevo método cearReceta() en recetasController.ts
2. Agrego post en recetas.routes.ts
3. Modifico receta.schema, datos requeridos.

RUP - Modificar POST generar recetas

---

modules/turnos/routes/listaEspera.ts

1. Corrección de error al filtrar demandas por fecha

fix(CIT): corrección de errores varios

---

core-v2/mpi/paciente/paciente.controller.ts
core-v2/mpi/paciente/paciente.routes.ts

https://proyectos.andes.gob.ar/browse/TOP-195
1. Se realiza la búsqueda de internacion de un paciente para detectar sus resoectivos estados.

TOP - Buscar internacion

---

core-v2/mpi/paciente/paciente.controller.ts

https://proyectos.andes.gob.ar/browse/CIT-371
1. Se realizan cambios para poder guardar mas de un financiador con origen ANDES en el paciente

CIT - Guarda multiples financadores en paciente

---

core-v2/mpi/parentesco/parentesco.interface.ts
core-v2/mpi/parentesco/parentesco.schema.ts

https://proyectos.andes.gob.ar/browse/MPI-443
1. Se modifica esquema e interfaz de la relación de un paciente, agregando el nuevo atributo "esConviviente"

MPI - Convivientes

---

modules/recetas/receta-schema.ts
modules/rup/controllers/rup.events.ts

Cambia campo dosis como no obligatorio en esquema de receta
1. 
2. 
3.

Receta: cambia campo dosis obligatorio a false

---

modules/recetas/recetasController.ts

Corrige patch de dispensa
1. Quita restricción de dispensar, para receta de medicamentos no vigentes
2. devuelve receta modificada al dispensar
3. Get: corrige error no trae receta

fix(receta): corrige respuesta al dispensar u obtener recetas

---

modules/descargas/laboratorio/laboratorio-body.ts

https://proyectos.andes.gob.ar/browse/HUDS-147
https://proyectos.andes.gob.ar/browse/HUDS-148
https://proyectos.andes.gob.ar/browse/HUDS-155
1. Se agrega en el encabezado del pdf los datos mencionados  de laboratorio.

HUDS - Agregar estado, tipo de muestra y prácticas

---

core-v2/mpi/paciente/paciente.controller.ts
modules/obraSocial/controller/obraSocial.ts
modules/obraSocial/controller/puco.ts
modules/obraSocial/routes/obraSocial.ts

https://proyectos.andes.gob.ar/browse/MPI-445
1. Se modifica la ruta de la obra social permitiendo buscar por documento y sexo
2. Se remplaza el evento de crear/insertar obra social por una función y de esta forma poder mostrar en el primer intento la misma en los datos del paciente
3. Se actualizan los datos del campo financiador del paciente cada un mes.

MPI - Obra social PUCO

---

core-v2/mpi/paciente/paciente.controller.ts

https://glpi.andes.gob.ar/front/ticket.form.php?id=5508
1. Se agrega bloque de codigo provisorio para ir depurando datos erroneos de financiador en [null]

MPI (Fix) - Obra Social en array null

---

auth/auth.class.ts
modules/recetas/recetas.routes.ts
modules/recetas/recetasController.ts
modules/recetas/services/receta.ts

Agrega permisos para acceder  como usuario de mobile y demás detalles aclarados a continuación
1. Agrega permisos a rutas de api receta para usaurio de mobile
2. Control de no registro de doble dispensa, sólo cuando es la misma dispensa
3. Modifica get por receta, para evaluar estado de dispensa en otros sistemas (sifaho, recetar)
4. Control en get de recetas para que se envíe por parámetro el id de paciente o documento y sexo del paciente
5. Corrige audit en el post de recetas.

Receta: cambio en permisos para usuario mobile

---

modules/turnos/controller/agenda.ts

https://proyectos.andes.gob.ar/browse/RUP-489
1. Se realiza modificación para que la expresión consultada sea obtenida de la bd ECLQueries.
colección : 'eclqueries'
{
"_id" : ObjectId("682cc82df1b15d16a7040d33"),
"key" : "turnos:noasistio",
"nombre" : "conceptos-noasitio",
"valor" : "<<281399006 OR 2031000013104 OR 21541000119102 OR 275694009",
"descripcion" : "Asistencia del turno al validar prestacion"
}

RUP -  Pasar a eclqueries los conceptos de NO Asistio

---

modules/rup/routes/prestacion.ts

https://proyectos.andes.gob.ar/browse/CIT-375
1.  Se eliminan los atributos asistencia y hora de asistencia cuando se anula una prestación tanto para un turno como un sobreturno.

CIT - Gestor de Agendas-Botón de suspender agenda

---

packages/drive/drive.ts
packages/drive/file-descriptor/schemas.ts
packages/drive/middleware/multer.ts

https://proyectos.andes.gob.ar/browse/MPI-442
1. Control de extensiones
2. Control de tamaño máximo 2mb
3. Control de caracteres especiales
GLPI: https://glpi.andes.gob.ar/front/ticket.form.php?id=5501

MPI-442: Documentos Adjuntos: Agregar control

---

modules/rup/laboratorios.controller.ts
modules/rup/routes/protocolosLab.ts

https://proyectos.andes.gob.ar/browse/LAB-95
1. Se modificó protocolosLab.ts para que resuleva la API que parámetros enviar al request de laboratorio de acuerdo al id de  paciente.
2. Mantiene compatibilidad con parámetros anteriores, estado, dni, apellido, fechaNac.

LAB - Actualizar solicitud para pacientes temporales

---

modules/rup/controllers/rup.events.ts

https://proyectos.andes.gob.ar/browse/RUP-496
1. Agregado corrección para visaulizar todos los medicamentos dentro del listado Receta del paciente
2. Se agrega try catch para especificar errores (si lo hubieran) sobre medicamento.

RUP - No se visualizan algunos medicamentos en el historial del paciente

---

modules/recetas/receta-schema.ts
modules/recetas/recetasController.ts

se agrega idDispensaApp y fecha de dispensa en estados de dispensa
1. se agrega idDispensaApp en estados de dispensa
2. se corrige fecha en estados de dispensa
3.

Receta: se agrega idDispensaApp en estados de dispensa

---

core-v2/mpi/paciente/paciente.schema.ts
core-v2/mpi/paciente/pacienteFallecimiento.schema.ts

[MPI-454](https://proyectos.andes.gob.ar/browse/MPI-454)
1. Generar un audit del usuario que lo cargó
2. Se agrega un label más con un hint que muestre los datos de quien lo cargo y cuando
3. Agregar botón slide que diga "Paciente fallecido".

MPI-454: Registrar paciente fallecido

---

jobs/vencimientoRecetas.ts
modules/recetas/parametros.schema.ts
modules/recetas/recetaLogs.ts
modules/recetas/recetasController.ts

https://proyectos.andes.gob.ar/browse/RUP-465
1. Implementa job que actualiza recetas: venciendo aquellas con más de 30 días en estados "vigente" + "sin dispensa" o "vigente" + "dispensa-parcial" y activando como "vigente" las "pendientes" dentro de su fecha de vigencia.
Requiere agregar el siguiente documento a la coleccion recetasParametros:
`{
"key": "fechaLimite",
"value": "30",
"type": "number",
"nombre": "Fecha limite para verificar vencimiento"
}`

RUP - Implementa job para actualizar estado de recetas

---

modules/descargas/routes/descargas.ts

Agrega control de parametro documento al descargar labo
1. 
2. 
3.

fix: Agrega control de documento en descarga de labo

---

modules/recetas/recetasController.ts

https://proyectos.andes.gob.ar/browse/REC-119
1. Se modifica el suspender receta con tratamiento prolongado, se suspende la siguiente receta con estado 'pendiente'/ 'sin-dispensa' y luego se eliminan el resto de las recetas en esa condición

REC - Suspención de receta con tratamiento prolongado
