andes/api

- modules/rup/controllers/rup.ts
- modules/rup/schemas/prestacion.ts
- package-lock.json
- package.json
- Implementar debugging con colores
- Implementar controller para código compartido rup
> Rup linting

- core/mpi/routes/paciente.ts
- Verificamos si al hacer el post el paciente tiene documento. Si no tiene debe modificarse el dto y no realizar la validación de match.
> fix verificacion de paciente sin documento no guardaba

- modules/turnos/routes/agenda.ts
- Fix: se nullean los diagnosticos principal y secundario cuando clonamos la agenda.
> Fix en clonar

- core/mpi/controller/mpiUpdater.ts
- core/mpi/controller/paciente.ts
- MPIUpdater no actualizaba los datos modificados de un paciente al CORE por cuestiones relacionadas al modelo y  a la conexión, se crea un método específico para este tratamiento.
> fix en actualizar paciente que tiene una conexion diferente

- auth/routes/routes.ts
- auth/schemas/organizacion.ts
- auth/schemas/permisos.ts
- Unificación de Organizaciones y AuthOrganizaciones.
La idea es dejar de usar la colección AuthOrganizaciones. Ojo: En caso de tener estas colecciones con organizaciones que difieran es los Object Ids hay que realizar una actualización por mongodb.
> unificación organizaciones con authOrganizaciones

- modules/turnos/controller/agenda.ts
Se cambia el parámetro de cantidad de días previos que se realiza la actualización de las agendas
> Actualizar jobs de cambio de cantidad de turnos

- core/term/routes/cie10.ts
- normalizamos el searchterm para evitar errores al entrar paréntesis u otros 
- Es necesario correr este script sobre la col. CIE10 para crear un array de words correspondiente al sinónimo.
>  db.cie10.find({}).forEach( function(myDoc) {
myDoc.words = myDoc.sinonimo.trim().split(" ");
//print(myDoc ); 
db.cie10.save(myDoc);
} );
> normalización del término de búsqueda para cie10

- config.private.ts.example
- modules/cda/controller/CDAPatient.ts
- modules/cda/controller/import-labs.ts
- modules/cda/controller/import-prestacionesHPN.ts
- modules/cda/routes/cda.ts
- modules/cda/routes/cdaLaboratory.ts
- modules/cda/routes/cdaPrestacionesHPN.ts
- Generador de CDA
- Control de CDA repetido
- Codificación a SNOMED (queda para revisar)
- Queda para confirmar que otras prestaciones se quieren generar
> Cda imagenes

- modules/turnos/controller/turnosController.ts
- modules/turnos/routes/turno.ts
- La operación que devuelve todos los turnos de un paciente, en cada turno devuelve ahora el id de bloque (junto con el id de agenda que ya devolvía) para facilitar los patchs de esos turnos.
- Se agrega la etiqueta de motivo suspensión al patch del turno.
> fix Issue app#460

- modules/obraSocial/routes/obraSocial.ts
- modules/turnos/routes/carpetaPaciente.ts
agregamos dos fixes para querys a la API con pacientes sin dni
en la ruta de obras sociales y en la ruta de carpetaPaciente (quedaba en pending)
> Fix pacientes sin dni

- modules/cda/routes/cda.ts
- modules/turnos/controller/operationsCacheController/operationsAgenda.ts
Agrega control para marcar las agendas cerradas como codificadas y que el proceso de IntegracionAndes no las vuelva a verificar
> Verificación de estado de agenda integradas

- modules/rup/schemas/prestacion.registro.ts
Se cambia la variable esPrimeraVez en el esquema de Registro. Se quita el valor por defecto. En app se valida que se elija SI o NO
> issue #576  indicar primera vez de c2

- modules/turnos/controller/agendasHPNCacheController.ts
Agregamos un setRequestTimeout de msssql, para que no falle el insert en sql de HPN. Esto se debe a que hay muchos datos en la tabla y el insert tarda en terminar.
Se agregó el parámetro  requestTimeout: 30000 en el objeto de la conexión.
> Integración HPN: Request Timeout

- modules/turnos/controller/pacienteHPNController.ts
- modules/turnos/controller/turnoHPNCacheController.ts
INTEGRACION HPN: Solucionamos el bug por tipo de documento y el update de los turnos existentes.
1. Quitamos de la consulta SQL el filtro por tipo de documento, ya que daba conflicto con pacientes extranjeros.
2. Bug en el update, el id es de tipo string y en sql debe ir entre comillas simples.
> Integracion HPN: tipo de documento

- modules/turnos/controller/operationsCacheHPNController.ts
- modules/turnos/controller/pacienteHPNController.ts
- modules/turnos/controller/turnoHPNCacheController.ts
INTEGRACION HPN: 
1) Verificación del documento del paciente. Si le dieron un turno a un paciente temporal sin dni, se le asigna el objectId del paciente para guardarlo en la bd del HPN.
2) Si es una agenda 100% autocitada, se pone con estado publicada en Prestaciones 2.0
3) Se creo retry and fail. Si por algún motivo la transacción falla, prueba 2 veces más y cambia el estado a estadoIntegracion = Fail para evitar que se acumulen las agendas.
Bug encontrado durante el uso en producción.
> verificación de paciente sin dni

- config.ts
- package-lock.json
- package.json
* Publicar la ruta de padrones para que se pueda acceder desde diferentes efectores de la provincia
1. Se quita la autenticación a la ruta de puco.
> Publicar la ruta de padrones de obra social

- swagger/static/index.html
- swagger/swagger.class.ts
1. Cambiar la URL del archivo swagger.json. Se mueve a '/api/swagger.json'.
> Documentación: cambia ubicación de swagger.json

- modules/descargas/controller/descargas.ts
Se agrega un if para la impresión. 
Se repara el problema con las impresiones de los registros.
El problema esta actualmente en le impresión en producción. Cuando imprimen el informe del examen medico del adulto les imprime la hoja en blanco. Ahora quedo reparado.
> Fix en la impresion

- modules/cda/controller/CDAPatient.ts
CDA: Se crea una prestación genérica cuando no matchea con ninguna prestación de la colección configuración prestaciones. Para evitar que falle por falta de codificación.
> Se agrega prestacion generica de consulta

- modules/turnos/routes/turno.ts
* Se revierte cambios en el commit https://github.com/andes/api/commit/b137c939f6305494658203b71af8958d3952f779
1. Se quita la búsqueda de carpetas en el patch de turnos
> Revierte el cambio de búsqueda de carpetas

- core/mpi/controller/paciente.ts
1. Adapta consulta a Google maps al paquete 'request' porque utiliza internamente el proxy.
> mpi: implementa paquete request en google maps

- modules/mobileApp/auth_routes/noticias.ts
* Resuelve incidente en las noticias de punto saludable. Las fechas de las noticias se visualizaban diferentes a las fechas de las publicaciones realizadas en el sitio de twitter.
1. Se especifica un argumento más en la conversión de las fechas con moment, ya que el lenguaje es "en", y estaba tomando el lenguaje por defecto.
> Formatea las fechas en noticias de punto saludable

- jobs/actualizarAgendasJob.ts
- jobs/actualizarEstadosAgenda.ts
- modules/rup/routes/codificacion.ts
- modules/turnos/controller/agenda.ts
Se requiere corregir estados de las agendas hacia atrás verificando los siguientes casos:
- Agendas sin pacientes asignados -> que pasen a auditadas
- Agendas no nominalizadas -> que pasen a auditadas
- Agendas que hayan quedado con todos los turnos auditados y por algún motivo no hayan pasado a auditadas.
> CITAS - verificar estados en agendas pasadas

- modules/turnos/routes/agenda.ts
* Cuando fallaba la integración (muy de vez en cuando) se envíaba dos veces una respuesta al cliente, generando un fallo.
`Can't set headers after they are sent.`
1.  Se acomodan las lineas de código para evitar este problema.
> citas: corrige error de envío de datos dos veces.

- modules/prestamosCarpetas/controller/prestamosController.ts
Corregir: 
`Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.`
1. Se agrega opción allowDiskUse.
> prestamos: corrige error 'Exceeded memory limit for $group'

- core/term/controller/mapping.ts
1. Corrige un bug en el mappeo de snomed a cie10. Quedaban undefined en el array. 
```
TypeError: Cannot read property 'codigo' of undefined
at SnomedCIE10Mapping.<anonymous> (/var/www/andes/api/core/term/controller/mapping.ts:105:53)
```
> mapping: soluciona bugs de mappeo a CIE10.

- core/mpi/routes/paciente.ts
MPI - Quitamos la sincronización con elastic search para la actualización de campos que no son de búsqueda.
* No pertenece a US, es un fix por bug recurrente.
> mpi: Quita update de elastic para campos no importantes

- modules/mobileApp/routes/agendas.ts
* Corrige bug que ocurría cuando el efector no estaba georeferenciado y tenía agendas con cupo para turnos mobile.
> TurnosMobile - Fix bug consulta georeferencia

- config.ts
- core/log/schemas/log.ts
- jobs/actualizarTurnosMobile.ts
- modules/turnos/controller/agenda.ts
* Implementar job que setee a 0 los turnos disponibles para la aplicación mobile el día anterior a la ejecución de la agenda a las 12 hs
Requiere agregar en el array de jobs del config.private lo siguiente
{
when: '0 12 * * *',
action: './jobs/actualizarTurnosMobile'
}
> Job turnos mobile

- modules/rup/controllers/codificacionController.ts
- modules/rup/routes/codificacion.ts
- modules/rup/routes/prestacion.ts
Soluciona el problema de la duplicación en la auditoría cuando se rompe la validación y se vuelve a validar la prestación.
> RUP/CITAS: Soluciona la duplicación de auditoría: Fix1110

- modules/estadistica/controller/procesarAgendas.ts
* Corrige detalle en el filtro del buscador de turnos y prestaciones con las agendas que tienen mas de un bloque. comentario de @palita1991  en v4.4.7
Agrega condición en match de turnos
> Agrega control por prestación en el turno

- core/mpi/controller/paciente.ts
El try catch no utilizaba el handler de la API (next()) por lo tanto el status del response no era correcto
Errores en el pacienteUpdate respondidos con status 200 a la app.
1. Se quita un catch que atrapaba el error imposibilitando que handler de la API lo maneje correctamente.
> Update paciente error handler

- modules/turnos/routes/turno.ts
```
CastError: Cast to ObjectID failed for value "-1" at path "dataTurno.idBloque"
at new CastError (/var/www/andes/api/source/node_modules/mongoose/lib/error/cast.js:29:11)
at model.$set (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:1030:7)
at model._handleIndex (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:806:14)
at model.$set (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:756:22)
at model._handleIndex (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:786:12)
at model.$set (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:756:22)
```
> fix(citas): loggin reasignar sobreturnos

- modules/rup/controllers/rup.ts
Se reemplaza la fecha de cada registro por la de ejecucion de la consulta, en lugar de la de creacion.
fixed #611
Issue #611 
1. En HUDS de un paciente, muestra la fecha de ejecución de la prestación en lugar de la de carga.
> RUP - Coorrige issue 611 (Visualización de fecha de prestaciones)

- modules/descargas/controller/descargas.ts
- templates/rup/informes/html/includes/adjunto.html
- templates/rup/informes/sass/main.scss
Si no existe descripción de un archivo adjunto, la descarga falla
1. Se agregó un control para verificar que la descripción exista, caso contrario no se muestra nada (string vacío)
> RUP: fix de informes en adjuntos sin descripción

- core/tm/schemas/tipoPrestacion.ts
- modules/turnos/controller/agenda.ts
- modules/turnos/schemas/turno.ts
U.S. https://pm.andes.gob.ar/projects/citas/work_packages/803/activity
Se agrega el atributo "auditable: false" en DB a los conceptos turneables de "consulta de enfermeria/odontología". El mismo atributo queda agregado en el esquema de tipoPrestaciones (por defecto en true) y de turno (se asigna el valor correspondiente al tipoPrestacion). 
Al momento de actualizar el estado de las agendas (job) si alguna contiene al menos un bloque con una de estas dos prestaciones, automáticamente pasara al estado "auditada" cuando corre el job que actualiza agendas.
Coleccion "conceptoTurneable": Agregar el atributo "auditable: false" a los documentos con conceptId: 34043003 y 861000013109
> Audita automáticamente agendas de prestaciones no auditables

- modules/turnos/controller/agenda.ts
fix en cambios de estados de agenda
1. se vuelve funcionalidad que falla para agendas no auditables
> fix (citas): hotfix en job de cambio de estado de agendas

- config.private.ts.example
- modules/estadistica/pecas/controller/agenda.ts
- modules/estadistica/pecas/controller/fueraDeAgenda.ts
Separa las constantes de conexión a sql para que el consolidado se conecte a un server y fuera de agenda a otro.
> pecas: separa constantes de conexión

- modules/webhook/schemas/webhookSchema.ts
Se resuelve error de tipeo en el esquema de webhook. Lo que no permitía devolver los datos y filtrar por los que tenían activado fhir como método de transformación.
> fix(webhook): Error de tipeo en el esquema

- modules/gestor-usuarios/perfil.routes.ts
https://github.com/andes/app/issues/1465
Se cambia el string del permiso a `usuarios:perfiles:read` porque el Auth.authorize no toma los caracteres especiales de shiro porque usa internamente la función `check` y no `permissions`.
> fix(gestor-usuarios): ajuste get perfiles permisos

- modules/estadistica/pecas/controller/agenda.ts
Corregir campo SnomedTerm3 en tabla consolidado (pecas) que se estaba insertando siempre como undefined.
> Corrige error de tipeo que provocaba campo null en tabla consolidado

- modules/carpetas/controller/carpetaPacienteController.ts
La ruta getCarpetasPAciente estaba devolviendo null cuando el paciente no tenía documento. Debe devolver array vacío como si no encontro carpetas. 
1.  Se agrego un else necesario
> fix(carpetas): ruta de carpeta devolvia null

- modules/rup/schemas/elementoRUP.ts
- modules/rup/schemas/prestacion.registro.ts
- modules/rup/schemas/prestacion.ts
Poder mantener un versionado de los elementosRUP. Para poder visualizar los registros viejos como fueron observados. 
1. Agrega el ID del elementoRUP en el array de registros de una prestación.
https://gist.github.com/liquid36/c300d16ff035c136fa90322c66d206d7
> feat(rup): versionado elementos rup

- modules/turnos/controller/agenda.ts
- modules/turnos/routes/agenda.ts
- modules/turnos/routes/turno.ts
* https://proyectos.andes.gob.ar/browse/TOT-1
* https://proyectos.andes.gob.ar/browse/TOT-4
* https://proyectos.andes.gob.ar/browse/TOT-5
* https://proyectos.andes.gob.ar/browse/TOT-14
1. Muestra la agenda que tiene el turno con la fecha más reciente
2. Se modificaron los nombres de las rutas
3. Se movió la definición del aggregate del router de agenda al controlador
4. Muestra solo prestaciones/agendas con turnos mobile disponibles
5. Al dar un turno, resta uno del cupo mobile (restantesMobile)
> TOTEM: Refactor de rutas

- modules/descargas/controller/descargas.ts
Requerimiento
Al mergear el PR #752 se perdió parte del código, este PR lo devuelve.
1. Se reinserta el código, no se llegó a ninguna conclusión luego de revisar este tema con @liquid36 :joy_cat: 
```
if (!registro) {
let registros = prestacion.ejecucion.registros[0].registros.length ? prestacion.ejecucion.registros[0].registros : prestacion.ejecucion.registros;
// SE ARMA TODO EL HTML PARA GENERAR EL PDF:
await this.generarInforme(registros);
} else {
await this.generarInforme([registro]);
}
```
> fix(descarga procedimientos): se devuelve if desaparecido

- config.private.ts.example
- core/term/controller/snomed.controller.ts
- core/term/controller/snomed.mongo.ts
- core/term/controller/snomed.snowstorm.ts
- core/term/routes/snomed.ts
- core/term/routes/snomedv2.ts
- core/term/schemas/snomed.ts
- modules/descargas/controller/descargas.ts
- modules/rup/controllers/estadisticas.ts
- modules/rup/controllers/plantillasRUP.ts
- modules/rup/routes/elementosRUP.ts
- modules/rup/routes/prestacion.ts
- utils/requestHandler.ts
Actualizar a las nuevas APIs y bases de SNOMED. Soportar Snowstorm.
1. Se generan las mismas consultas que se hacían en mongo, vía snowstorm.
2. Se mantienen las interfaces para evitar cambios.
3. Mantiene las dos implementaciones para hacer una prueba incremental.
4. Agrega nueva configuraciones al config.private.
- Requiere una nueva base de datos: [snowstorm](https://github.com/IHTSDO/snowstorm)
> feat(snomed): implementa api snowstorm

- modules/rup/routes/prestacion.ts
Agrega la opción de allow Disk en el get de solicitudes para solucionar el problema incidente del limite de uso de memoria ocasionado por el sort
1. Agrega allowDisk true en Pipeline
> fix(rup): allowDisk en solicitudes

- modules/rup/routes/prestacion.ts
BUG: en el modulo TOP cuando un usuario tiene permisos para visualizar solicitudes de algunos tipos de prestaciones se están filtrando aquella que tenga algún tipo de prestación permitida en origen **Y** en destino (debería ser en origen **O** en destino)
1. Corrige el filtro en el aggregate que ejecuta la api de solicitudes
2. 
3. 
- [] Si
- [] No
> fix(TOP): cambia el filtro de solicitudes por tipo de prestaciones

- auth/permisos.ts
Poder setear distintos niveles de visibilidad en el gestor de usuarios:
- _public_: cualquier puede asignar ese permiso.
- _restricted_: Solo si tenes ese permiso podes asignarlo a otros usuarios.
- _hidden_: Invisible para todos, se gestiona desde base de datos.
Con esta funcionalidad, solo los que tienen permiso de matriculaciones pueden dar permisos para matriculaciones. Si no tenes permisos y estás editando un usuarios, no se lo pisas como pasaba antes.
Del lado de la API solo se determino que permisos van en restricted. Por el momento, se descomento auditoría y matriculaciones. Y agrego el permiso de analytics para próximo uso.
PR APP: https://github.com/andes/app/pull/1497
> feat(gestor-usuario): add visibility attribute

- auth/auth.class.ts
- modules/turnero/routes/configuracionPantalla.ts
- modules/turnero/schemas/turneroPantalla.ts
Permitir configurar los totems de la misma forma que las pantallas del turnero. Se deberá especificar al cargar una nueva de qué tipo es (totem/turnero).
1. Se sumó al schema de pantallaTurnero el campo tipo
2. Se modificó la ruta '/pantalla/activate' para recibir el tipo por parámetro
> TURNERO: sumado tipo a turneroPantalla

- core/mpi/controller/paciente.ts
Antes de este commit no se guardaba el cambio de tipo de relacion en una relacion preexistente
Cuando se modificaba el tipo de relación de un paciente, al pariente no se le actualizaba con la nueva relación como se indica en el issue andes/app#1487
1. 
2. 
3.
> MPI - fix modificar relaciones pacientes

- modules/turnos/routes/listaEspera.ts
- modules/turnos/schemas/listaEspera.ts
1.  Al rechazar una demanda en el punto de inicio, se guarda la organización logueada.
2.  Al rechazar una demanda en el punto de inicio, la prestacion seleccionada se guarda con el concepto snomed correspondiente
3.  Al rechazar una demanda en el punto de inicio, se crea una nueva prestacion en la BD con el Concepto Snomed  turno no disponible (hallazgo) SCTID: 419069000
> CITAS: Se guarda organizacion y concepto snomed en prestacion

- modules/turnos/controller/agenda.ts
- modules/turnos/routes/turno.ts
- modules/turnos/schemas/turno.ts
[https://proyectos.andes.gob.ar/browse/CIT-25](url)
1. Se agregó al esquema turno los campos: fechaHoraDacion y UsuarioDacion para registrar la fecha/hora y el usuario que dio el turno.
2. Al crear el turno se guardan los nuevos campos.
> CITAS: Agregar fecha, hora y usuario de dación de turno

- modules/turnos/controller/agenda.ts
https://proyectos.andes.gob.ar/browse/AM-34
1. Al cancelar un turno programado se verifica si fue emitido por la App-mobile, en caso de serlo se aumenta la cantidad de restantesMobile. Luego se setea a vacio _emitidoPor_
> APP-MOBILE: No actualiza el cupo al liberar turno cuando es el último disponible

- modules/turnos/routes/turno.ts
https://proyectos.andes.gob.ar/browse/AM-35
1. Antes de confirmar un turno, verifica que el estado de la agenda no haya cambiado en el transcurso de la solicitud a 'suspendida' o 'pausada'. Si esto pasa retorna un error.
> APP-MOBILE: Fix confirmar turno luego de que una agenda se pausa

- core/mpi/controller/paciente.ts
- core/mpi/jobs/elasticFix.ts
- core/mpi/routes/paciente.ts
- utils/elasticSync.ts
- Linkea paciente validado con los temporales con un match igual o superior a la cota estipulada, que indica que son pacientes iguales
- Cambia el método update de Elastic, implementado con un delete y create, por la opción correspondiente (index). 
1. Refactor del la ruta de identificadores de pacientes
2.  Resuelve los incidentes de conflictos de versiones actuales de Elastic (version conflict, document already exists)
3. La función de linkeo de pacientes temporales se realiza en el evento de creación de un paciente
> MPI: Link temporales

- auth/auth.controller.ts
Como algunos datos del token no están más en el "token", se obtienen de la base de datos. Los IDs se estaban guardando como ObjectId.
1. Castea a String datos del token.
> fix(auth): payload token parse to string

- modules/turnos/controller/reportesDiariosController.ts
Se reporto que habían días que mostraban mal el reporte, y este se debió a que existe un desface en la zona horaria que hace la consulta en la base de datos.
1. Se agrego el time zone _"America/Argentina/Buenos_Aires"_ en la consulta
> Reportes diarios: Arreglo en los timezones de la consulta

- modules/turnos/controller/agenda.ts
https://proyectos.andes.gob.ar/browse/RUP-39
1. Al registrar una asistencia se verifica en primer lugar si tiene registro de asistencia, en caso de no tenerlo y que el turno sea de un día anterior al actual, se le asigna como horario de asistencia, la hora de inicio de la agenda
> RUP:Fecha de ejecución en agendas anteriores

- modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/RUP-130
1. En el patch de solicitudes, al momento de ejecutar una solicitud sin profesional, se lo setea por defecto con el usuario de sesión (el que ejecutó la prestación).
> RUP: setea x defecto profesional a solicitud rup sin profesional

- modules/descargas/informe-rup/informe-rup.ts
Hay prestaciones de internacion que no se cargan desde el mapa de camas, por ende no tienen cama asociada. 
1. Control de camas
> fix(internacion): internaciones sin camas informe pdf

- core/term/controller/snomed.snowstorm.ts
- modules/rup/controllers/codificacionController.ts
- modules/rup/internacion/camas.controller.test.ts
- modules/rup/internacion/censo.controller.test.ts
- modules/rup/routes/frecuentesProfesional.ts
- modules/rup/schemas/prestacion.ts
- modules/rup/schemas/snomed-concept.ts
- modules/top/schemas/reglas.ts
- modules/turnos/controller/agenda.ts
1. Borra el schema de snomed  el campo refsetids que esta en desuso. Así no se genera un array vacío en la DB.
> refactor(rup): remove refsetids from snomed schema

- config.private.ts.example
- core/term/controller/snomed.snowstorm.ts
La última versión de Snowstorm agregó un filtro por varios semanticTags, así que ya no es necesario consumir directamente desde elasticsearch.
> refactor(snomed): snowstorm soporta multiple semanticTags

- core/term/controller/snomed.snowstorm.ts
Ajusta parámetro de búsqueda en snowsotrm así no aparecen términos en ingles
> fix(mitos): evita buscar en ingles

- modules/turnos/controller/reportesDiariosController.ts
En el Reporte Diario Mensual, al dividir el turno por horarios, estos se desfasan.
En la Planilla C1, no cuenta los sobreturnos y fuera de agenda .
1.  Corrección en los timezones al momento de hacer la consulta en la BD
2.  En planilla C1, consultar la tabla prestaciones y luego cruzar los datos con la tabla agenda para obtener la Obra Social.
3.  Filtrar por profesional en la planilla C1
> Reporte diarios: Timezones en division de turnos & Sobreturnos y fuera de agenda en Planilla C1

- auth/permisos.ts
- modules/gestor-usuarios/perfil.routes.ts
https://proyectos.andes.gob.ar/browse/GDU-1
1. Se borra el permiso usuarios:perfiles:read
2. Se verifica el permiso usuarios:read para las rutas get/search de perfiles
> GDU: se borra permiso de lectura de perfiles

- core/mpi/controller/paciente.ts
- core/mpi/routes/paciente.ts
- core/mpi/schemas/paciente.ts
Elimina la foto del paciente desde el esquema
1. En los find se fuerza traer el campo foto, solo cuando es necesario 
2. 
3.
> fix(mpi): quita la foto desde schema paciente

- modules/rup/schemas/elementoRUP.ts
https://proyectos.andes.gob.ar/browse/RUP-99
1. Agrega a schema elementoRUP atributo bool requiereDiagnosticoPrincipal
2. Remueve `motivoConsultaOpcional` en desuso
Se aplica un cambio en el requerimiento de diagnostico principal. Anteriormente las prestaciones no nominalizadas y las prestaciones de internación no requerían un diagnostico principal.
A partir de ahora se configura dinámicamente desde elementos-rup, individualizado por tipo prestación.
Se sugiere agregar el campo `requiereDiagnosticoPrincipal` en false en las prestaciones de internación y las no nominalizadas, para mantener la funcionalidad. 
```
db.getCollection('internacionEstados').aggregate([
{ $unwind: '$estados' },
{ $unwind: '$estados.acciones' },
{ $match: { 'estados.acciones.tipo': 'nuevo-registro'  } },
{ $group: …
```
> RUP: agrega a schema elementoRUP atributo bool requiereDiagnosticoPrincipal

- auth/auth.class.ts
- modules/turnos/controller/agenda.ts
- modules/version/routes/routes.ts
https://proyectos.andes.gob.ar/browse/RUP-136
1. Al captar el evento  'rup:prestacion:validate', desde el controlador de agenda se audita la agenda correspondiente a la prestación si es no nominalizada.
> RUP: al validar prestación auditar agenda para no nominalizadas

- core/tm/interfaces/IContacto.ts
- core/tm/interfaces/IDireccion.ts
- core/tm/interfaces/IOrganizacion.ts
- core/tm/interfaces/ISectores.ts
- core/tm/interfaces/ITipoEstablecimiento.ts
- core/tm/interfaces/IUbicacion.ts
- core/tm/routes/tipoPrestacion.ts
- core/tm/schemas/organizacion.ts
- core/tm/schemas/tipoPrestacion.ts
ServSalud necesita generar automáticamente un reporte basado en reportes diario mensual, es por eso que se agregó los códigos para realizar el correcto mapeo.
1. Interfaces de Organización, Tipo de Prestación & Ubicación
2. Actualización de los Schemas para los modelos correspondiente a las interfaces anteriores
3. Métodos PATCH que modifica solamente el código de ServSalud para Organización y Tipo de Prestación
> Organizaciones - Códigos para mapeo de ServSalud

- modules/rup/internacion/estados.schema.ts
La prestación de atención domiciliaria COVID, solo debe aparecer en la unidad organizativa de COVID. 
1. Se crea un filtro de registro por unidad organizativa. 
APP:  https://github.com/andes/app/pull/1814
> feat(mapa-camas): registros filtros por unidad organizativa

- modules/estadistica/pecas/controller/agenda.ts
Corregir bug que se produce cuando el domicilio tiene mas de una comilla (Ej: PARCELA 'A' 11 )
> fix(pecas): corrige todas las apariciones de comillas en el domicilio del paciente

- jobs/fueraDeAgendaJob.ts
- modules/estadistica/pecas/controller/fueraDeAgenda.ts
Agregar el idprofesional en los registros de las prestaciones fuera de agenda
1. se agrega campo idProfesional
> feat(pecas): agrega idprofesional a la tabla de fuera de agenda

- core/tm/routes/profesional.ts
- modules/matriculaciones/routes/turno.ts
Al buscar la firma del profesional, devolver un json vacío en lugar de un null.
Al buscar turnos por documento, devolver un arreglo vacío en lugar de un null
> MATRICULACIONES: arreglo de error al devolver firma

- modules/turnos/controller/agenda.ts
https://proyectos.andes.gob.ar/browse/RUP-135
1. Se guarda la asistencia del paciente a un turno mediante EventCore 'rup:prestacion:validate'
> RUP: Marcar asistencia del turno en background

- modules/rup/controllers/prestacion.ts
Cuando el profesional cita un paciente y agrega observaciones, ese dato no se está almacenando en el historial
1. Se agrega control en updateRegistroHistorialSolicitud
> fix(historial TOP): guarda observaciones al citar paciente

- auth/permisos.ts
- modules/turnos/routes/agenda.ts
- scripts/visualizacion-informacion.ts
https://proyectos.andes.gob.ar/browse/BI-53
1. Se agregan como hijos del permiso visualizacionInformacion reportes  y dashboards con sus descendientes
2. Se agrega el permiso biQueries como hijo del permiso visualizacionInformacion.
3. Se crea Script para actualizar los permisos existentes dada la nueva organización.
1. Ejecutar Script 
El script elimina los modulos _Reportes_ y Dashboard e inserta el nuevo _Visualización de información_. Luego realiza una búsqueda por toda la colección AuthUsers y verifica si en cada organización que tenga el usuario posee permisos para reportes o dashboard, en caso de que así sea modifica el permiso agregándole la palabra "visualizacionInformacion:" por delante para que funcione de manera correcta con la modificación actual. 
```bash
node scripts …
```
> Permisos: nuevos permisos para modulo visualizacion de informacion

- core/term/controller/snomed.snowstorm.ts
Hay request que snowstorm devuelve un mensaje de error porque es una request muy HEAVY. Por ejemplo cuando se busca por una sola letra. (No todos los plex-select tiene un minimo de caracteres).
Por eso en ves de devolver null, la API devuelve array vacío así no genera un fallo en la app.
> fix(snowstorm): too heavy request

- modules/cda/routes/cda.ts
- modules/descargas/informe-rup/elementos-rup/adjuntar-documento.component.ts
- modules/registro-novedades/images/controller/imageStore.ts
- modules/rup/controllers/rupStore.ts
Error al abrir imágenes o pdf adjuntos
1. Se agrega conversión explicita a ObjectId en RupStore e ImageStore
2. 
3.
> fix(rup): conversión explícita a objectId

- core/tm/routes/organizacion.ts
- core/tm/schemas/organizacion.ts
https://proyectos.andes.gob.ar/browse/COM-7
1. Se suma a organización el campo _aceptaDerivacion_
1. Se suma a organización el campo _esCOM_
2. Se modifica la ruta de GET /organizaciones para que permita filtrar por aceptaDerivacion y esCOM
Parte de https://github.com/andes/api/pull/1108
> COM: Campo derivable y esCOM en efectores

- modules/rup/internacion/cama-estados.controller.ts
- modules/rup/internacion/sala-comun/sala-comun.controller.ts
La query searchEstados pisaba los atributos createdAt y createdBy del estado con el de la cama
1. Cambia el lookup que busca la cama y agrega un project para que no traiga dichos atributos.
2. 
3.
> INTERNACION - Arregla search estados que pisaba createdBy y createdAt del estado

- modules/turnos/routes/agenda.ts
https://proyectos.andes.gob.ar/browse/MPI-248
```
ValidationError: logPaciente validation failed: dataTurno.idBloque: Cast to ObjectID failed for value "-1" at path "dataTurno.idBloque"
at new ValidationError (/var/www/andes/api/source/node_modules/mongoose/lib/error/validation.js:30:11)
at model.Document.invalidate (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:2080:32)
at model.$set (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:1029:10)
at model._handleIndex (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:806:14)
at model.$set (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:756:22)
at model._handleIndex (/var/www/andes/api/source/node_modules/mongoose/lib/document.js:786:12)
at model.$set …
```
> fix(citas): log suspender sobreturno

- modules/turnos/routes/turno.ts
Por error en la lógica de un nuevo método que se agregó para permitir dar turnos de gestión hasta el mismo día de la agenda, no se están pudiendo dar turnos del día en algunos casos específicos. 
1. Se corrigen operadores lógicos
> fix(turnos): corrige lógica en bloques de solo gestión

- core-v2/mpi/paciente/paciente.controller.ts
- core-v2/mpi/paciente/paciente.routes.ts
- modules/webhook/api-doc.yml
- modules/webhook/webhook.routes.ts
- swagger/swagger.class.ts
Agrega ruta para permitir realizar notificaciones a pacientes
TODO: queda pendiente utilizar los subrecursos de pacientes, en la ruta implementada a fin de desacoplar la asignación del dato de contacto, ya que la lógica de estas operaciones no deberían estar en este recurso, sino que se deberían resolver del lado del paciente
1. 
2. 
3.
> feat(webhook): agrega ruta para notificación

- core-v2/mpi/validacion/validacion.controller.ts
- core/mpi/routes/paciente.ts
- core/tm/controller/localidad.ts
Agrega match de ubicación en los nuevos controladores de validación.  Actualmente utilizada en el proceso de importar pacientes recién nacidos.  
1.  Agrega match de localidad y provincia
2. Agrega control para la foto del paciente
3.
> fix(mpi): agrega match de localidades en validación

- modules/estadistica/controller/procesarAgendas.ts
- modules/estadistica/controller/procesarFueraDeAgenda.ts
https://proyectos.andes.gob.ar/browse/BI-59
1. Agrego al aggregate el campo ámbito tanto para los turnos como para las prestaciones fuera de agendas.
> Turnos y prestaciones: se agrega el campo ambito

- utils/roboSender/sendSms.ts
Quita momentáneamente los envios de sms debido a que el servicio no se encuentra actualmente operativo
1. 
2. 
3.
> refactor(sms): quita servicio de sms

- connections.ts
- modules/rup/controllers/frecuentesProfesional.ts
- modules/rup/routes/frecuentesProfesional.ts
- modules/rup/schemas/profesionalMeta.ts
En algunos casos el calculo de frecuentes se hace muy demandante, todo el tiempo y ya son larga listas de conceptos. 
Como primer medida vamos a aplicar Cache mediante de REDIS cuando la lista es más 20 conceptos, así mantenemos la actualización real time cuando arranca una prestación o profesional a registrar. 
La idea es empezar a experimentar con algo no tan crítico como los frecuentes, antes de llegar a otras secciones. 
https://github.com/andes/app/pull/2019
> feat(rup): agrega cache redis para frecuentes

- config.private.ts.example
- modules/obraSocial/controller/obraSocial.ts
- modules/obraSocial/controller/puco.ts
- modules/obraSocial/routes/obraSocial.ts
Utiliza el servicio del federador para actualizar las obras sociales
1. Quita el uso del servicio de Sisa en obras sociales
2. 
3.
> fix(puco): cambia uso de sisa por federador

- modules/rup/controllers/elementos-rup.controller.ts
- modules/rup/elementos-rup.controller.ts
- modules/rup/prestaciones.interface.ts
- modules/rup/routes/elementosRUP.ts
- modules/rup/routes/prestacion.ts
- modules/rup/schemas/elementoRUP.ts
- modules/rup/schemas/prestacion.ts
Permite configurar un HOOK en un elemento RUP. Al validar prestación si el elemento rup registrado tiene un hook configurado este se dispara mediante el EventCore. De esta forma se puede disparar un evento a un Microservicio o resolver internamente ne la API mediante código.
Caso de usos: Recetar, COM, otros.
> feat(rup): elementos rup hooks

- config.private.ts.example
- core/log/schemas/logExportaInformacion.ts
- jobs/exportCovid19.ts
- jobs/jobExportVacunaCovid19.ts
- Permite realizar el envío a nomivac en función de los datos cargados en la prestación de vacunación covid19
- Se almacena los datos en los logs sobre lo que se envió y las respuestas de nomivac.
- Cuando se invoque desde un job en forma automática, se deberá enviar una varible de entorno HORAS con la cantidad de horas que se quiera tomar hacia atrás.
- Se realiza control (filtro) en authUser para el login. Ya que debería tomar los usuarios activos.
> feat(nomivac): registro de aplicaciones de vacunas

- packages/drive/adapters/FileAdapter.ts
Pequeño ajuste para que funcione Andes Drive con el adaptador de archivos directo al disco rígido. Útil para probar los test o si no se quiere Seaweed en alguna versión de prueba.
> fix(drive): ajustes file adapter

- modules/descargas/informe-rup/elementos-rup/adjuntar-documento.component.ts
- modules/descargas/routes/descargas.ts
- modules/rup/controllers/rup.ts
Los nuevos adjuntos de RUP están dirigidos a Andes Drive pero faltaban porciones de código por editar.
> fix(rup): adjuntos desde andes drive

- core-v2/mpi/paciente/paciente.controller.ts
- core-v2/mpi/validacion/validacion.controller.ts
Agrega try catch para controlar error de resize de la foto que viene desde renaper
1. 
2. 
3.
> fix(mpi): controla error de tamaño de la foto

- modules/mobileApp/routes/agendas.ts
El get de agendas disponibles que devuelve las agendas para la app mobile no estaba filtrando correctamente por prestación.
1. Se cambia el nombre del parámetro por el que corresponde (el que llega es el conceptId)
> fix(AM): Corrige parametro en get de agendas disponibles

- modules/rup/routes/prestacion.ts
- modules/rup/schemas/elementoRUP.ts
- modules/vacunas/controller/inscripcion-vacunas.events.ts
- modules/vacunas/inscripcion-vacunas.routes.ts
- modules/vacunas/schemas/inscripcion-vacunas.schema.ts
- En el momento que se valida la prestación de vacunación de un inscripto, agregar el campo fechaVacunacion a la inscripcion para poder realizar consultas de manera eficiente.
- Si rompen una validación que ya impacto la fecha de vacunación en la inscripcion, limpiar dicho campo
1. Se agregaron los eventos correspondientes en inscripcion-vacunas
En el elementoRup de vacunasComponent, agregar el siguiente campo:
"dispatch" : [ 
{
"event" : "vacunas:inscripcion:vacunado",
"method" : "validar-prestacion"
}, 
{
"event" : "vacunas:inscripcion:cancelar-vacunado",
"method" : "romper-validacion"
}
],
> feat(inscripcion-vacunacion): Agrega eventos para actualizar inscripción

- modules/estadistica/controller/procesarFueraDeAgenda.ts
- modules/estadistica/pecas/controller/fueraDeAgenda.ts
Revisar porque no se están pasando a Pecas las prestaciones fuera de agenda
1. Se elimina segundo parámetro del método eachAsync de mongoose ya que devolvía un indice y no un error (a partir de actualización en versión de mongoose)
> fix(pecas): quita control de segundo parametro de eachAsync

- modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/RUP-244
1. Se agrega a la ruta `/prestaciones/huds/:idPaciente` la búsqueda por vinculados.
- Si bien la US marca que se agregue la búsqueda por vinculados en la ruta de vacunas, no se pudo realizar porque en la colección nomivac no se registra el id del paciente sino que se hace por documento.
> HUDS:  Búsqueda por pacientes vinculados

- core/tm/schemas/tipoPrestacion.ts
Problema al guardar codificaciones por semanticTags
codificacion validation failed: tipoPrestacion.semanticTag: `elemento de registro` is not a valid enum value for path `semanticTag`., tipoPrestacion: Validation failed: semanticTag: `elemento de registro` is not a valid enum value for path `semanticTag`.
> fix(codificacion): validacion de tipoPrestacion

- core-v2/mpi/validacion/validacion.controller.ts
- modules/vacunas/controller/inscripcion.vacunas.controller.ts
Para los casos en que la validación por Renaper, devuelve caracteres inválidos en nombre y apellido, no se estaba guardando el número de trámite, debido a que Sisa no posee este número.  Para estos casos, no se estaba pudiendo verificar el número de trámite del documento.
1. 
2. 
3.
> fix(validacion): agrega idTramite en validación por Sisa

- core/tm/routes/profesional.ts
Fix para profesionales duplicados en la base de datos.
1. Se agrega el campo _profesionalMatriculado: true_ en la búsqueda de profesionales para que esta solo traiga los profesionales que se encuentren registrado en matriculaciones.
> INSCRIPCION-PROFESIONALES: Campo solo profesionales matriculados

- jobs/exportCovid19.ts
- jobs/jobExportVacunaCovid19.ts
Permitir hacer la exportación por fecha desde y hasta en el job _exportCovid19_
1. Se agregan las constantes desde y hasta para enviar en caso que se desee a la funcion _exportCovid19_
2. Dentro de la función _exportCovid19_ se agrega ternaria para chequear en caso que venga por parámetro una fecha "desde" se setea la constanste `start` con dicha fecha, caso contrario se setean las horas enviadas o 1 hora en el caso que es el caso default.
3. Dentro de la funcion _exportCovid19_ se agrega ternaria para chequear en caso que venga por parámetro una fecha "hasta" se setea la constante `end` con dicha fecha, caso contrario se setea la constante con la fecha y hora actual.
> VACUNACION: Agrega parametros fecha desde y hasta al exportVacuna

- scripts/VAC-9.ts
Corregir error en script que inserta fecha de vacunación e id en inscriptos
1. se reemplazó save por updateOne
> fix(script VAC-9): reemplaza save por updateOne

- modules/rup/prestaciones.interface.ts
- modules/rup/routes/prestacion.ts
- modules/rup/schemas/elementoRUP.ts
- modules/rup/schemas/prestacion.ts
- scripts/tag-vacunas.ts
- Script para tagear las prestaciones correspondientes a vacunación covid
- Agrega tags del elementoRUP en la prestación al momento de su validación
1. Script
2. Campo nuevo en prestaciones
> feat(vacunas): TAG vacunasCovid en prestaciones

- modules/vacunas/controller/inscripcion-vacunas.events.ts
- modules/vacunas/schemas/inscripcion-vacunas.schema.ts
https://proyectos.andes.gob.ar/browse/VAC-16
1. Cuando se valida o se rompe la validación de la prestación **certificación de paciente con riesgo aumentado de COVID-19**, se actualizan los campos fechaCertificado e idPrestacionCertificado en inscripcion-vacunas
En el elementoRup de certificación de paciente con riesgo aumentado de COVID-19, agregar el siguiente campo:
"dispatch" : [ 
{
"event" : "vacunas:inscripcion:certificado",
"method" : "validar-prestacion"
}, 
{
"event" : "vacunas:inscripcion:cancelar-certificado",
"method" : "romper-validacion"
}
]
> VAC: nuevos eventos al validar o romper validación de certificación

- modules/vacunas/controller/inscripcion.vacunas.controller.ts
Cambia condición para que se visualice el mensaje de que el paciente recibió una dosis antes que los mensajes default configurados por grupo
1. 
2. 
3.
> fix(inscripcion): cambia control para el mensaje de consulta

- modules/vacunas/inscripcion-vacunas.routes.ts
https://proyectos.andes.gob.ar/browse/VAC-36
1. Nuevo filtro por tieneCertificado
> VAC: filtro por certificado en listado de inscripciones

- modules/vacunas/controller/inscripcion.vacunas.controller.ts
- modules/vacunas/inscripcion-vacunas.routes.ts
Modifica el momento en que se realiza el control de número de trámite
Si los datos ingresados del inscripto, son inferiores a la cota máxima establecida se verifica el número de trámite.  Caso contrario deja al inscripto continuar
1. Agrega controles en la verificación del domicilio para la consulta
2. Permite ingresar un paciente si, existe algun registro previo no validado
3.
> fix(inscripcion): control de nro de trámite

- modules/vacunas/controller/inscripcion.vacunas.controller.ts
- modules/vacunas/inscripcion-vacunas.routes.ts
Se quita la emisión del evento create de inscripción, ya que lo dispara a través del uso del controlador del resource base
1. 
2. 
3.
> fix(inscripcion): quita doble llamado al evento create

- auth/permisos.ts
- initialize.ts
- modules/forms/forms-epidemiologia/forms-history.routes.ts
- modules/forms/forms-epidemiologia/forms-history.schema.ts
- modules/forms/index.ts
https://proyectos.andes.gob.ar/browse/EP-42
1. Se agrega el nuevo permiso al modulo "Epidemiología" para ver el historial de una ficha.
2. Se agrega Schema y ResourceBase correspondiente a la nueva colección formsEpidemiologiaHistory donde se guardarán entradas del historial de fichas.
>  BUSCADOR-EPIDEMIO: Historial de fichas

- modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
1. Agregamos el campo sexo el objeto paciente dentro del esquema de la ficha de epidemio porque lo necesitamos para interoperar con Lab central.
> feat(epidemio): Agregamos el campo sexo al objeto paciente de la ficha

- modules/vacunas/controller/inscripcion.vacunas.controller.ts
- scripts/validar-inscriptos.ts
Al validar desde el listado, si el paciente no existe se asigna sin el id a la inscripción
1. Corregir la asignación del id al validar inscripción
> VAC: arreglo al asignar id de paciente en validación

- auth/auth.class.ts
https://proyectos.andes.gob.ar/browse/AM-154
1. No validar captcha si es un scan de dni
> AM: no validar trámite o captcha si es scan

- core-v2/mpi/paciente/paciente.controller.ts
- core/tm/controller/localidad.ts
- core/tm/schemas/localidad.ts
- core/tm/schemas/zonaSanitarias.ts
- modules/webhook/webhook.routes.ts
Poder configurar y filtrar por zonas sanitarias pacientes que reciben el mensaje de que esta listo su resultado de PCR
1. Agregar la configuracion a la zona sanitaria
2. Agrega control en las notificaciones de si debe enviar o no el msn
> feat(WEBHOOK): Agrega control por zona sanitaria para los sms de resultados covid

- modules/vacunas/inscripcion-vacunas.routes.ts
Se quita el control para el grupo de adultos mayores, que permitía ingresar una inscripción sin validar los datos debido a que muchas personas con más de 70 años no habían realizado el cambio de documentación y no existía en Renaper.  Debido a la etapa actual de vacunación se quita dicho control debido a que ingresaba una gran cantidad de datos erróneos en ese grupo.
1. 
2. 
3.
> fix(inscripcion): quita excepción para mayores de 60

- modules/matriculaciones/routes/turnoSolicitado.ts
Verifica si el profesional existe como no matriculado, cuando saca un turno para matricularse, así utiliza el mismo objectId que tenía previamente a matricularse.
1. 
2. 
3.
> fix(matriculaciones): verifica profesional duplicado al cargar un turno

- core/tm/controller/localidad.ts
- modules/webhook/webhook.routes.ts
Se agrega control en la función getZona, ya que al no controlarlo repercute el error en webhook notification.
1. 
2. 
3.
> fix(tm): Se agrega control en la función getZona

- jobs/exportNexosFichaSisa.ts
- Se quita el control de casos confirmados, ya que no es necesario.
- Se filtran las fichas de control de alta.
https://proyectos.andes.gob.ar/browse/EP-87
> Job de envío de test rápidos y contactos estrechos a SNVS

- modules/rup/controllers/prestacion.ts
En Registros del paciente no se visualizaban los gráficos de seguimiento de peso, monitorización de la talla, etc, debido a que la búsqueda en la huds de dichos conceptos no arroja ningún resultado
1. Se quita el mapeo de las prestaciones a objetos
2. 
3.
> fix(huds): quita mapeo a objetos de prestaciones

- modules/forms/forms-epidemiologia/forms-epidemiologia.routes.ts
En el buscador de fichas, realizar la busqueda identificador PCR por expresion regular ya que cuando se escanea el codigo puede venir con una leyenda antes del numero.
1. Se modifica la busqueda del identificador pcr por el operador $regex
> Epidemiología: Búsqueda id pcr

- modules/rup/internacion/censo.controller.ts
- modules/rup/routes/prestacion.ts
- modules/rup/schemas/prestacion.registro.ts
- modules/rup/schemas/prestacion.ts
permite que las internaciones censables se tengan en cuenta durante los censos
https://proyectos.andes.gob.ar/browse/IN-301
1. Agrega atributo 'esCensable' al esquema de prestacion
2. Tiene en cuenta internaciones censables al momento de calcular los censos
> Mapa-camas - Marcar una internación como censable aunque la cama no lo sea

- modules/seguimiento-paciente/seguimiento-pacientes.events.ts
https://proyectos.andes.gob.ar/browse/EP-113
1. Con el control anterior, si el array es vació entra al if, se modifica a findeOne para obtener el ultimo seguimiento y funcione correctamente el if.
> Seguimiento: Fix al guardar llamados

- jobs/exportNexosSisa.ts
Elimina control de confirmados de covid, en el job de exportar casos por nexos, ya que no corresponde realizar este control debido a las reinfecciones reportadas.
1. 
2. 
3.
> fix(job): elimina control confirmados en casos por nexos

- modules/cda/controller/CDAPatient.ts
Cambio un `{ $exists: false }` por un `null`, para ver si se optimizan algunas consultas. El resutlado obtenido es el mismo. 
https://proyectos.andes.gob.ar/browse/CORE-90
> feat(cda): "optimiza" find de CDA

- scripts/add-sumar-turnos.ts
En la ultima actualización de SUMAR hubo un problema con el script y no se renombro la colección, quedo con el nombre sumarOld. Entre el rango de fechas (15/07 -  04/8) los pacientes que están en SUMAR aparecían sin obra social por lo que no se podían enviar a faccionario.
1. Se agrega Script que actualiza los registros en la coleccion agenda agregandole a los pacientes SUMAR la obra social.
> SCRIPT: Actualizar turnos con Sumar

- modules/vacunas/controller/vacunas.events.ts
Corregir bug en evento que elimina vacunas de nomivac
1. Casteo de tipo en dosis de la vacuna que viene de nomivac para comparar con la dosis registrada en la prestación.
> fix(VAC): Corrige error de tipos en evento que elimina vacunas de nomivac

- modules/forms/forms-epidemiologia/forms-epidemiologia-schema.ts
https://proyectos.andes.gob.ar/browse/EP-115
1. En el pre save del `FormsEpidemiologiaSchema` si la ficha viene como confirmada, se guarda el nombre completo del usuario que hizo esta confirmación y en el caso que se haya pedido un hisopado, se guarda también el usuario correspondiente.
> Epidemiología - Agregar el profesional que confirmo y el que hisopo en la ficha covid 19

- modules/turnos/controller/diagnosticosC2Controller.ts
Los turnos y sobreturnos codificados no se visualizaban porque el match accedía a la posición 0 de un objeto
1. 
2. 
3.
> fix(reporteC2): cambio en match de turnos y sobreturnos

- modules/turnos/controller/estadisticas.ts
https://proyectos.andes.gob.ar/browse/BI-94
1. Se modifica query para que tenga en cuenta los turnos que quedaron disponibles.
> fix(Dashboards): Agrega al gráfico de tipos de turnos los que están sin clasificar

- core/tm/routes/profesional.ts
En reportes, permitir filtrar por fechaDesde y fechaHasta aisladas, no solo por rango completo.
1. Se modifica la ruta /profesionales/matricula para buscar por fechaHasta y fechaDesde
> MAT: filtrar matricula por fechas aisladas

- modules/rup/internacion/cama-estados.controller.ts
- modules/rup/internacion/resumen/internacion-resumen.hook.ts
- modules/rup/internacion/resumen/internacion-resumen.schema.ts
- modules/rup/routes/prestacion.ts
https://proyectos.andes.gob.ar/browse/IN-353
https://proyectos.andes.gob.ar/browse/IN-354
1. Agrega atributo 'registros' para guardar datos del respirador usado
2. Nuevos eventos para actualizar resumen de internación del paciente al validar/romper-validación usando conceptos de respiración asistida
Tres nuevos registros en colección ElementosRUP:
```
{
"_id" : ObjectId("618d225591b3d014186132fd"),
"componente" : "SelectStaticoComponent",
"tipo" : "atomo",
"conceptos" : [ 
{
"conceptId" : "266700009",
"term" : "respiración asistida",
"fsn" : "respiración asistida (procedimiento)",
"semanticTag" : "procedimiento"
}
],
"style" : {
"columns" : 12.0,
"cssClass" : null
},
"requeridos" : [],
"params" : {
"titulo" : "Dispositivo",
"items" : [ 
{
"id" : …
```
> IN - Registro de uso de respirador en colección internacionPacienteResumen

- modules/seguimiento-paciente/interfaces/seguimiento-paciente.interface.ts
- modules/seguimiento-paciente/seguimiento-pacientes.events.ts
- modules/vacunas/controller/vacunas.controller.ts
https://proyectos.andes.gob.ar/browse/EP-182
1. Se agregan dos eventos en seguimiento para que al validar/romper una prestacion con el hallazgo Paciente Internado(266938001), se refleje en seguimiento en el caso de que el paciente tenga uno activo.
[ElementoRup.txt](https://github.com/andes/api/files/7959029/ElementoRup.txt)
> Epidemiología - Agregar dispatch al hallazgo Paciente Internado

- core/tm/routes/profesional.ts
Permitir busqueda por email para corroborar informacion de nuevos usuarios para recetAR
1. Se agrega la posibilidad de enviar al get de la guiá de profesionales, el email como param para verificar que el ingresado en el nuevo formulario de usuarios de recetAR sea el mismo que el registrado en la base de Andes.
> Profesional - Param email

- modules/rup/internacion/plan-indicaciones/plan-indicaciones.hook.ts
- modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts
https://proyectos.andes.gob.ar/browse/IN-471
1. Se agrega la posibilidad de obtener el horario de inicio del plan de indicaciones dada una organización.
2. Se agrega posibilidad de filtrar por el rango de fechas en el plan de indicaciones.
3. 
En cada organización que quiera usar el plan, agregar en el objeto configuraciones , un objeto plan de indicaciones con un campo llamado horaInicio con un horario ej:
```
"configuraciones" :{
"planIndicaciones" : {
"horaInicio" : 6
}
}
```
Quedan configurados en la base de demo el castro rendon y el hospital de centenario.
> Plan Indicaciones - Modificar grilla horaria del plan

- modules/perinatal/controller/carnet-perinatal.events.ts
- modules/perinatal/schemas/carnet-perinatal.schema.ts
https://proyectos.andes.gob.ar/browse/PER-77
1. Se modifico el esquema de carnet-perinatal para poder agregar la cantidad de embarazos en caso de que se seleccione el term "mas de 10 embarazos".
En la colección elementos rup con este id: ObjectId("5b057eaf623ded31ac70ed94") se agrego dentro de params un booleano
"required:true" para que sea obligatorio el campo de ingresar el numero de embarazos en caso de seleccionar la opción del select "mas de 10 embarazos". Tambien se elimino la variable max que tiene la cantidad maxima de embarazos ya que se lo considera innecesario a la hora de escribir el numero y se modifico la variable min dejandola en 1.
> Cantidad de embarazos

- modules/rup/internacion/plan-indicaciones/plan-indicaciones-eventos.routes.ts
- modules/rup/internacion/plan-indicaciones/plan-indicaciones.hook.ts
https://proyectos.andes.gob.ar/browse/IN-508
1. Nuevo event que se dispara al crear registrar un evento nuevo, para replanificar los el horario de los eventos posteriores.
2. Se edita funcion de borrado de eventos, agregando un parametro opcional fechaDesde.
> Plan de indicaciones - Control de hs (frecuencia) para ejecución de una indicación

- scripts/fix-domicilio-profesional.ts
Corregir domicilios de profesionales que ..
1. Tienen valor o codigo postal nulo
2. No tienen datos de provincia o localidad
3. Datos de provincia y/o localidad son inconsistentes con las colecciones de la DB
4. Corrige atributos _matriculado_ y _papelesVerificados_ que estaban en 'false' por error de migración
1. Script que setea valores de domicilio segun error
> MAT - Corrige domicilios y matricula suspendida de profesional

- modules/huds/hudsAccesos.controller.ts
- modules/huds/hudsAccesos.routes.ts
- modules/huds/hudsAccesos.schema.ts
- modules/huds/hudsAccesos.ts
https://proyectos.andes.gob.ar/browse/PRIV-70
pr app https://github.com/andes/app/pull/3010
1. Se agrega al esquema atributo 'detalleMotivo'
3. Se agrega 'detalleMotivo' a la proyeccion del get
> PRIV - Agregar campo observación en motivos

- modules/turnos/routes/listaEspera.ts
- modules/turnos/schemas/listaEspera.ts
1. En ../routes/listaEspera.ts se modificó método post(...) para que decida si agrega un doc a la colección o una demanda al un doc. existente.
2. en ../schemas/listaEspera.ts se agregó: 'export const demanda' para poder auditar (Auth.audit) el elemento.
> (FEAT) Demanda Insatisfecha: pasar funcionalidad a API

- modules/rup/internacion/internacion.routes.ts
- modules/rup/internacion/plan-indicaciones/plan-indicaciones.routes.ts
https://proyectos.andes.gob.ar/browse/IN-574
1.  Reporte de los pedidos de medicamentos de un sector para realizar el control de entrega de medicación 
2.  Extraccion de una planilla con la siguiente información: DNI paciente / sector / unidad org./ cama actual/ los datos del medicamento, filtros por sector, unidad organizativa y por nombre de medicamento para un efector.
3. Descarga en csv
> IN - Reporte indicaciones de medicamentos

- modules/perinatal/carnet-perinatal.routes.ts
https://proyectos.andes.gob.ar/browse/CORE-105
1. En la clase CarnetPerinatalResource, el campo fechaControl se arma mediante una función.
2. Se divide el parámetro de fechas en fechas[0][1]
3 Se utiliza $elemMatch: { fechaControl: { $gte: fechas[0], $lte: fechas[1] }}} para la busqueda entre fechas.
> CORE - ResourceBase: consulta periodos de fechas en array

- modules/rup/routes/protocolosLab.ts
https://proyectos.andes.gob.ar/browse/HUDS-99
1. Nuevo archivo modules\rup\routes\protocolosLab.ts
2. Se implementa una ruta: get('/protocolosLab/:id?, ...
3. Utiliza andesServices
> HUDS - Api consultas laboratorios

- modules/rup/internacion/camas.routes.ts
https://proyectos.andes.gob.ar/browse/IN-619
1. Se agrega una condición  de tal forma que si viene un ingreso con obra social se modifique.
> IN - Modificar carga de OS en alta de internación capa estadística

- auth/permisos.ts
- modules/recetas/recetas.routes.ts
https://proyectos.andes.gob.ar/browse/HUDS-127
1. Se agregaron nuevos permisos al módulo HUDS para poder ver solamente los laboratorios, las vacunas, las recetas o ambas.
> HUDS - Habilitacion parcial de la HUDS

- modules/pacs/pacs.logs.ts
- modules/pacs/pacs.ts
- modules/rup/routes/prestacion.ts
Agrega logs en coneccion a pacs para generar el worklist
> fix(PACS): Agrega logs en pacs
